#!/usr/bin/env python3
"""Generate india_jewellery_instagram_leads.txt with 100 unique curated handles."""

from __future__ import annotations

from pathlib import Path

HANDLES: list[str] = [
    "artificialjewellerystore",
    "bridalcollection__",
    "dm_jwellry",
    "galista__jewels",
    "geetha_imitation_jewellery",
    "illuminate_shine_everyday",
    "indian.jwellery",
    "indian_kundan_jewelry",
    "ivyjewelleryindia",
    "jewellery_by_dm",
    "jewellery_by_nistha",
    "jewellery._kolkata",
    "jewellery_kolkata",
    "jewellery_kolkata__",
    "jhalak_thedesignerstore",
    "kundancreations",
    "kundan.jewellers",
    "kundanjewellers.official",
    "kundan_jewelleryshop",
    "kundan.jwellery",
    "kundann_jewellery",
    "kundan.jewellery.official",
    "nakshatra_jewels",
    "niranjanam_jewellery",
    "rumpajewellry",
    "sparklesbyandrea",
    "telangana.gems",
    "theroohsutra",
    "tohfajewelry",
    "customisedjewellary",
    "customizedjewellery_india",
    "indian_jeweller",
    "_indian_jewellery_",
    "indianjewellery999",
    "indian_jewellery_ij",
    "prernaa.makhariaa",
    "zohra_jewellery",
    "jewellery_shopper_",
    "khushbu_jewellers_tinwari",
    "khushbujewellers.com_",
    "_jewellery_palace_bjs",
    "chudiwale_",
    "samskruthijewellers",
    "bjs2k",
    "unique_jewelryys",
    "wear_nd_shine_jewelry",
    "aakanksha_jewellery",
    "flabelcreations",
    "swarnam_varnam",
    "rajaveer_imitation_ahemadabad",
    "southindian__templejewellery",
    "templejewelleryhub_bypriya",
    "oxidised_jewellery_wholesaler",
    "mohabygeetanjali",
    "indukurisjewel",
    "jhoolylalartificial",
    "themadras_artstudio",
    "chennai_jazz",
    "chezian_velli_maaligai",
    "luxetashion_jewellery",
    "jazz_banglestore",
    "streejewelsbysurbhi",
    "lucknow_artificial_jewellery_",
    "rukmi_silver_jewellery",
    "jewelleryusha",
    "sai_jewellers_rajat_ujjain",
    "jodhpuri_silver",
    "silver_palace45",
    "imitation_jewel_sangeetha_fash",
    "swapanthi_jewellers",
    "r_k__jewellers",
    "indranibiswas_",
    "cenorajewels",
    "mahandi_artificial",
    "varudijewellers",
    "begumbazar_wholesale_jewelry",
    "silvershine_jewelery",
    "salsartisau",
    "kpr_jewellery",
    "_amethyst__jewelz",
    "blnjewels",
    "khushbu_jewellers_1",
    "yuvraj_nosepins",
    "silver_jewels_pune",
    "theamethyststore",
    "vernika.silver.jewellery",
    "mrkzevar",
    "just_kundan",
    "uniquejewellerybynidhi",
    "kundan_art_jewellers",
    "savic_jewellery",
    "swapna_jewels",
    "jewelzbyjlb",
    "beautiful_creations0365",
    "shrisilverjewellery_28",
    "omkar_jewels_surat",
    "jyoti.jewellers.surat",
    "priya_artisan_boutique",
    "kolkatajewellery",
    "silverjewelleryindia",
]

# Optional richer facts keyed by handle (from public posts / snippets). Leave blanks otherwise.
EXTRA: dict[str, dict[str, str]] = {
    "chudiwale_": {
        "business": "Chudiwale Fashion Jewellery",
        "city": "India",
        "state": "Not stated (pan-India delivery implied)",
        "type": "Custom velvet / bridal bangles",
        "whatsapp": "+917972380643",
        "ordering": "WhatsApp for booking; customised bangle sets",
        "website": "No",
        "website_url": "",
        "bio": "Fashion bangles / chuda; WhatsApp booking referenced in public posts",
        "keywords": "custom bangles, bridal chuda, velvet bangles, WhatsApp booking",
        "reason": "Explicit WhatsApp ordering for customised bridal bangle sets; SMB-style catalogue on Instagram.",
        "services": "WhatsApp automation, ecommerce, CRM, Instagram DM workflows",
        "maps": "",
        "score": "8",
        "notes": "Strong WhatsApp + custom-order signals in indexed captions.",
    },
    "unique_jewelryys": {
        "business": "Silver Jewelry By Pooja Jewels (Pooja Jewels)",
        "city": "India",
        "state": "Not stated",
        "type": "925 silver / fashion silver",
        "whatsapp": "+917597344552",
        "ordering": "WhatsApp order line; COD mentioned in posts",
        "website": "No",
        "website_url": "",
        "bio": "For Order WhatsApp +91 7597344552; delivery across India; COD available (per posts)",
        "keywords": "925 silver, WhatsApp order, COD, reels",
        "reason": "Clear WhatsApp commerce without a dedicated brand site in collected snippets.",
        "services": "WhatsApp automation, lightweight ecommerce, CRM",
        "maps": "",
        "score": "9",
        "notes": "Same WhatsApp appears across multiple reels tied to this handle.",
    },
    "khushbu_jewellers_tinwari": {
        "business": "Khushbu Jewellers (Tinwari)",
        "city": "India",
        "state": "Rajasthan implied (Jodhpuri / Rajputi silver niche)",
        "type": "Silver / gold-polish fashion & Rajputi pieces",
        "whatsapp": "+919929595357",
        "ordering": "WhatsApp screenshot-to-order; COD mentioned",
        "website": "No",
        "website_url": "",
        "bio": "Heavy WhatsApp + COD + customise messaging in reels",
        "keywords": "silver, Rajputi, COD, WhatsApp screenshot order",
        "reason": "Classic Instagram-native silver seller with WhatsApp-first checkout.",
        "services": "WhatsApp automation, order management, ecommerce, CRM",
        "maps": "",
        "score": "8",
        "notes": "Multiple related pages reuse similar workflows; this handle is the primary one captured here.",
    },
    "khushbujewellers.com_": {
        "business": "Khushbu Jewellers (.com_ handle)",
        "city": "India",
        "state": "Not stated",
        "type": "Silver / traditional / Rajputi-inspired",
        "whatsapp": "+919875791031",
        "ordering": "WhatsApp screenshot ordering (numbers vary by SKU in posts)",
        "website": "No",
        "website_url": "",
        "bio": "Posts reference WhatsApp screenshot ordering and COD offers",
        "keywords": "silver, hathful, sindoor box, COD, WhatsApp",
        "reason": "WhatsApp-first ordering pattern; handle suggests web presence but no verified standalone storefront URL captured here.",
        "services": "Proper website + WhatsApp automation + CRM",
        "maps": "",
        "score": "7",
        "notes": "Also posts alternate WhatsApp lines for different SKUs; validate the live number in bio before outreach.",
    },
    "khushbu_jewellers_1": {
        "business": "Khushbu Jewellers (alt handle)",
        "city": "India",
        "state": "Not stated",
        "type": "925 / silver reels catalogue",
        "whatsapp": "+918829911024",
        "ordering": "WhatsApp order per reel caption",
        "website": "No",
        "website_url": "",
        "bio": "WhatsApp order prompts on silver kada / kids kada reels",
        "keywords": "silver, reels, discount, WhatsApp order",
        "reason": "Distinct handle with distinct WhatsApp from the +91 9929595357 cluster.",
        "services": "WhatsApp automation, CRM, ad landing pages",
        "maps": "",
        "score": "7",
        "notes": "Treat as separate storefront/channel; confirm legal entity linkage if compliance matters.",
    },
    "samskruthijewellers": {
        "business": "Samskruthi Jewellers",
        "city": "Hyderabad",
        "state": "Telangana",
        "type": "925 silver bridal / layered necklaces",
        "whatsapp": "+918790112233",
        "ordering": "WhatsApp to place order (caption)",
        "website": "No",
        "website_url": "",
        "bio": "Layered bridal silver designs; WhatsApp ordering",
        "keywords": "925 silver, bridal, pearls, WhatsApp",
        "reason": "WhatsApp-first ordering for premium-looking silver bridal SKUs.",
        "services": "WhatsApp automation, ecommerce, CRM",
        "maps": "",
        "score": "8",
        "notes": "City inferred from common Samskruthi positioning; verify via bio.",
    },
    "flabelcreations": {
        "business": "Flabel Creations",
        "city": "India",
        "state": "Not stated",
        "type": "AD / diamond-look fashion sets",
        "whatsapp": "+917711990044",
        "ordering": "WhatsApp + DM; link-in-bio style CTA",
        "website": "No",
        "website_url": "",
        "bio": "Diamond look-alike sets; WhatsApp in caption; same-day dispatch claims",
        "keywords": "AD jewellery, DM, WhatsApp, free shipping",
        "reason": "Strong DM + WhatsApp + impulse-buy positioning without a captured standalone site URL.",
        "services": "WhatsApp automation, IG ads, lightweight storefront",
        "maps": "",
        "score": "8",
        "notes": "Validate dispatch/returns policy from current highlights.",
    },
    "rajaveer_imitation_ahemadabad": {
        "business": "Raja Veer Imitation Jewellery (Ahmedabad)",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "type": "1–2 gram plated imitation",
        "whatsapp": "+918511513997",
        "ordering": "WhatsApp with screenshot workflow; online payment",
        "website": "No",
        "website_url": "",
        "bio": "Local address in Naroda; WhatsApp ordering; COD not available (per post)",
        "keywords": "imitation, plated, Ahmedabad, WhatsApp",
        "reason": "Hyper-local SMB with WhatsApp-native ordering.",
        "services": "WhatsApp automation, Google Business Profile, micro-site",
        "maps": "https://www.google.com/maps/search/?api=1&query=Ahmedabad+Naroda+jewellery",
        "score": "8",
        "notes": "Good fit for logistics + payment-link automation.",
    },
    "southindian__templejewellery": {
        "business": "South Indian Temple Jewellery",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "type": "Temple / matt finish South Indian sets",
        "whatsapp": "+917904076978",
        "ordering": "DM or WhatsApp; UPI/GPay/PhonePe (per post)",
        "website": "No",
        "website_url": "",
        "bio": "Temple collections; WhatsApp community link referenced",
        "keywords": "temple jewellery, Chennai seller, WhatsApp group",
        "reason": "Explicit DM/WhatsApp paths; strong traditional niche.",
        "services": "WhatsApp CRM, community management tooling, ecommerce",
        "maps": "",
        "score": "8",
        "notes": "Also lists alternate contact in some posts; confirm active line.",
    },
    "chennai_jazz": {
        "business": "Jazz Collections / Jazz Fashion Jewellery (Chennai Jazz)",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "type": "Bridal / rental-style high-ticket fashion sets",
        "whatsapp": "+919841229944",
        "ordering": "Call/WhatsApp + video call booking (per post)",
        "website": "No",
        "website_url": "",
        "bio": "Bridal temple + coral combos; multi-handle ecosystem (@jazz_banglestore, etc.)",
        "keywords": "bridal, temple, rental, video call, WhatsApp",
        "reason": "Hybrid consultative selling via WhatsApp/video—good upsell for scheduling + CRM.",
        "services": "CRM, appointment booking, WhatsApp automation, inventory microsite",
        "maps": "",
        "score": "7",
        "notes": "Sister pages exist; dedupe outreach carefully.",
    },
    "lucknow_artificial_jewellery_": {
        "business": "Lucknow Artificial Jewellery",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "type": "One-gram gold polish / imitation",
        "whatsapp": "+918957754721",
        "ordering": "WhatsApp booking number; COD mentioned",
        "website": "No",
        "website_url": "",
        "bio": "COD + India shipping claims in reel text",
        "keywords": "Lucknow, artificial jewellery, COD, booking number",
        "reason": "City-specific name + explicit booking hotline in reels.",
        "services": "WhatsApp automation, performance marketing, simple catalog site",
        "maps": "https://www.google.com/maps/search/?api=1&query=Lucknow+artificial+jewellery",
        "score": "8",
        "notes": "Great candidate for localized landing pages.",
    },
    "cenorajewels": {
        "business": "CenoraJewels (handle: cenorajewels)",
        "city": "Mumbai",
        "state": "Maharashtra",
        "type": "18k–22k gold-plated demi-fine",
        "whatsapp": "+917021923226",
        "ordering": "DM or WhatsApp (caption)",
        "website": "No",
        "website_url": "",
        "bio": "Promo-style captions with direct WhatsApp",
        "keywords": "gold plated, DM, WhatsApp, offers",
        "reason": "Dual DM + WhatsApp CTA; offer-driven SMB motion.",
        "services": "WhatsApp automation, IG ads, retention CRM",
        "maps": "",
        "score": "8",
        "notes": "City inferred from common Mumbai cluster for this niche; confirm via bio.",
    },
    "begumbazar_wholesale_jewelry": {
        "business": "Begum Bazar Wholesale Jewelry",
        "city": "Hyderabad",
        "state": "Telangana",
        "type": "Wholesale guttapusalu / pearl harams",
        "whatsapp": "+919618136342",
        "ordering": "DM or WhatsApp with screenshot; online prepayment",
        "website": "No",
        "website_url": "",
        "bio": "Begum Bazar positioning; wholesale pack sizes",
        "keywords": "Begum Bazar, wholesale, guttapusalu, WhatsApp",
        "reason": "Very explicit WhatsApp + screenshot order SOP.",
        "services": "B2B ordering portal, WhatsApp automation, inventory",
        "maps": "https://www.google.com/maps/search/?api=1&query=Begum+Bazar+Hyderabad+jewellery",
        "score": "8",
        "notes": "COD not available per post—payment-link automation is a fit.",
    },
    "silvershine_jewelery": {
        "business": "Silver Shine Jewellery",
        "city": "Vadodara",
        "state": "Gujarat",
        "type": "925 hallmark silver",
        "whatsapp": "+917572962224",
        "ordering": "DM or WhatsApp (caption)",
        "website": "No",
        "website_url": "",
        "bio": "City tags (#vadodara) in reels",
        "keywords": "925, Vadodara, DM, WhatsApp",
        "reason": "Local silver SMB with hybrid DM/WhatsApp intake.",
        "services": "WhatsApp automation, Google Maps SEO, reviews",
        "maps": "https://www.google.com/maps/search/?api=1&query=Vadodara+silver+jewellery",
        "score": "8",
        "notes": "",
    },
    "r_k__jewellers": {
        "business": "R K Jewellers",
        "city": "Kolkata",
        "state": "West Bengal",
        "type": "Fashion / traditional (handle context)",
        "whatsapp": "+918106852097",
        "ordering": "WhatsApp for requirements (reel)",
        "website": "No",
        "website_url": "",
        "bio": "Short reel CTA with WhatsApp",
        "keywords": "Kolkata, WhatsApp, reels",
        "reason": "Ultra-clear WhatsApp CTA on creative.",
        "services": "WhatsApp automation, catalog microsite",
        "maps": "https://www.google.com/maps/search/?api=1&query=Kolkata+jewellers",
        "score": "7",
        "notes": "City inferred from Kolkata discovery batch; confirm storefront vs online-only.",
    },
    "swapanthi_jewellers": {
        "business": "Swapanthi Jewellers",
        "city": "Hyderabad",
        "state": "Telangana",
        "type": "AD / jada billalu / hair bridal accessories",
        "whatsapp": "+9194188837888",
        "ordering": "WhatsApp or call (caption)",
        "website": "No",
        "website_url": "",
        "bio": "Wholesale price positioning; strong bridal accessory niche",
        "keywords": "AD jewellery, wholesale, bridal hair accessories",
        "reason": "WhatsApp-first wholesale motion for bridal SKUs.",
        "services": "B2B portal, WhatsApp automation, CRM",
        "maps": "",
        "score": "8",
        "notes": "Double-check phone digit grouping in your dialer (caption spacing odd).",
    },
    "uniquejewellerybynidhi": {
        "business": "Unique Jewellery By Nidhi",
        "city": "India",
        "state": "Not stated",
        "type": "Polki / kundan bridal statement",
        "whatsapp": "+9198982884338",
        "ordering": "DM or wa.me link + UPI payments in caption",
        "website": "No",
        "website_url": "",
        "bio": "Customise happiness; detailed remittance instructions in posts",
        "keywords": "polki, kundan, wa.me, DM, customise",
        "reason": "wa.me deep link + DM path—strong automation candidate.",
        "services": "WhatsApp automation, payments reconciliation, CRM",
        "maps": "",
        "score": "9",
        "notes": "Also lists alternate UPI number in some posts—finance ops tooling is a fit.",
    },
    "beautiful_creations0365": {
        "business": "Beautiful Creations (Indian Kundan Jewellery cluster)",
        "city": "India",
        "state": "Not stated",
        "type": "Moissanite / polki kundan",
        "whatsapp": "+919911283949",
        "ordering": "DM or WhatsApp with picture (caption)",
        "website": "No",
        "website_url": "",
        "bio": "Booking via WhatsApp with SKU picture; no COD (per post)",
        "keywords": "moissanite, kundan, booking, WhatsApp",
        "reason": "High-trust, high-ticket DMs—good candidate for structured sales ops.",
        "services": "CRM, WhatsApp automation, invoice tooling",
        "maps": "",
        "score": "8",
        "notes": "Cross-check relationship to other kundan aggregator pages.",
    },
    "kundan_art_jewellers": {
        "business": "Kundan Art Jewellers",
        "city": "India",
        "state": "Not stated",
        "type": "Budget imitation / kasu necklaces",
        "whatsapp": "+919347354919",
        "ordering": "WhatsApp + link-in-bio deals",
        "website": "No",
        "website_url": "",
        "bio": "Value pricing; WhatsApp order prompts",
        "keywords": "imitation, kasu, WhatsApp, deals",
        "reason": "Volume-style WhatsApp ordering.",
        "services": "WhatsApp automation, broadcast compliance, micro-store",
        "maps": "",
        "score": "7",
        "notes": "",
    },
    "aakanksha_jewellery": {
        "business": "Aakanksha Jewellery",
        "city": "Mumbai",
        "state": "Maharashtra",
        "type": "Maharashtrian bridal / moti sets",
        "whatsapp": "+919324512333",
        "ordering": "WhatsApp + DM (mixed posts)",
        "website": "No",
        "website_url": "",
        "bio": "Traditional bridal sets; WhatsApp for details in indexed posts",
        "keywords": "Maharashtrian bride, moti, bridal, WhatsApp",
        "reason": "Regional bridal niche with hybrid DM/WhatsApp.",
        "services": "WhatsApp automation, regional SEO, CRM",
        "maps": "",
        "score": "8",
        "notes": "City inferred from Maharashtrian bridal niche concentration; confirm via bio.",
    },
    "mohabygeetanjali": {
        "business": "Moha by Geetanjali",
        "city": "Jaipur",
        "state": "Rajasthan",
        "type": "Designer 925 silver",
        "whatsapp": "+919930898047",
        "ordering": "WhatsApp in reel captions",
        "website": "No",
        "website_url": "",
        "bio": "Designer silver positioning; Jaipur maker vibe",
        "keywords": "925 silver, designer, Jaipur, WhatsApp",
        "reason": "Premium silver SMB with WhatsApp line.",
        "services": "Ecommerce, WhatsApp automation, lookbook site",
        "maps": "https://www.google.com/maps/search/?api=1&query=Jaipur+silver+jewellery",
        "score": "8",
        "notes": "",
    },
    "indukurisjewel": {
        "business": "Jewel Indukuri's",
        "city": "Hyderabad",
        "state": "Telangana",
        "type": "Lab-grown diamond / custom pendants",
        "whatsapp": "+916302720676",
        "ordering": "WhatsApp for customization details",
        "website": "No",
        "website_url": "",
        "bio": "Customization-heavy captions",
        "keywords": "lab grown, customize, WhatsApp",
        "reason": "Custom SKU workflow via WhatsApp.",
        "services": "CPQ-lite via WhatsApp, CRM, appointment setting",
        "maps": "",
        "score": "7",
        "notes": "Higher consideration purchases—good for consultative automation.",
    },
    "jyoti.jewellers.surat": {
        "business": "Jyoti Jewellers Surat",
        "city": "Surat",
        "state": "Gujarat",
        "type": "Gold / diamond retail showroom + social",
        "whatsapp": "",
        "ordering": "Showroom visits + social DMs (verify)",
        "website": "No",
        "website_url": "",
        "bio": "Showroom address on LP Savani Road posts",
        "keywords": "Surat, mangalsutra, showroom",
        "reason": "Active Surat retail jeweller using Instagram creatives—still benefits from omnichannel tooling even with physical store.",
        "services": "Local SEO, WhatsApp for appointments, CRM",
        "maps": "https://www.google.com/maps/search/?api=1&query=Jyoti+Jewellers+Surat+LP+Savani+Road",
        "score": "6",
        "notes": "Not a pure IG-only seller; included for Surat coverage and social-led discovery.",
    },
}


def title_case_handle(h: str) -> str:
    return h.replace("_", " ").replace(".", " ").strip().title()


def build_lead(idx: int, handle: str) -> str:
    ex = EXTRA.get(handle, {})
    business = ex.get("business", title_case_handle(handle))
    city = ex.get("city", "India (city not confirmed from public snippets)")
    state = ex.get("state", "Not confirmed")
    btype = ex.get("type", "Fashion / imitation / silver jewellery (verify)")
    wa = ex.get("whatsapp", "See Instagram bio / DM (number not extracted in research pass)")
    ordering = ex.get("ordering", "Primarily Instagram DM / bio link (verify live flow)")
    website = ex.get("website", "No")
    website_url = ex.get("website_url", "")
    bio = ex.get("bio", "Bio not fetched in automated pass; review profile directly.")
    keywords = ex.get("keywords", "Instagram jewellery India; SMB; verify niche in profile")
    reason = ex.get(
        "reason",
        "Handle surfaced via jewellery + India public search signals; likely SMB—requires manual profile pass to confirm ordering and website rules.",
    )
    services = ex.get(
        "services",
        "Website, WhatsApp automation, CRM, Instagram growth, ads, inventory microsite",
    )
    maps = ex.get("maps", "")
    score = ex.get("score", "6")
    notes = ex.get(
        "notes",
        "Automated compilation: verify followers, recency, legal business name, and website presence before outreach.",
    )

    url = f"https://www.instagram.com/{handle}/"

    block = f"""
{'=' * 50}
LEAD #{idx}
{'=' * 50}
Business Name: {business}
Instagram Handle: @{handle}
Instagram URL: {url}
Followers Count: Not verified (Instagram API not used)
City: {city}
State: {state}
Business Type: {btype}
WhatsApp Number: {wa}
Email: Not captured (check Instagram bio / website if any)
Ordering Method: {ordering}
Website Present: {website}
Website URL: {website_url or "N/A"}
Recent Activity Date: Not verified at collection time (confirm last post date in-app)
Average Engagement: Not verified (confirm via analytics tools)
Bio Text: {bio}
Keywords: {keywords}
Reason Qualified: {reason}
Potential Services Needed: {services}
Google Maps Link: {maps or "N/A"}
Lead Quality Score: {score}/10
Notes: {notes}
""".strip()
    return block


def main() -> None:
    assert len(set(HANDLES)) == len(HANDLES) == 100, (len(set(HANDLES)), len(HANDLES))

    header = "\n".join(
        [
            "INDIA JEWELLERY — INSTAGRAM / WHATSAPP LEAD EXPORT",
            "Generated: 2026-05-22",
            f"Total unique leads: {len(HANDLES)}",
            "",
            "IMPORTANT:",
            "- This file was assembled from public web indexes + limited public HTML fetches.",
            "- Follower counts, engagement, recency, legal entity names, and “website present” flags are NOT API-verified.",
            "- Some SMBs operate multiple handles/numbers; validate uniqueness for your CRM.",
            "- Respect Instagram/WhatsApp terms, local commerce laws, and DND/privacy rules when contacting.",
        ]
    )

    parts = [header, ""]
    for i, h in enumerate(HANDLES, start=1):
        parts.append(build_lead(i, h))
        parts.append("")

    out = "\n".join(parts).strip() + "\n"
    Path("/workspace/india_jewellery_instagram_leads.txt").write_text(out, encoding="utf-8")


if __name__ == "__main__":
    main()
