#!/usr/bin/env python3
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT = Path("/workspace")


@dataclass(frozen=True)
class Lead:
    business: str
    handle: str
    city: str
    state: str
    business_type: str
    whatsapp: str
    email: str
    ordering: str
    website_present: str
    website_url: str
    recent_activity: str
    avg_engagement: str
    bio_text: str
    keywords: str
    reason: str
    services: str
    maps: str
    score: int
    notes: str


NA = "Not publicly indexed (verify on Instagram / Google Maps)"
SERVICES = (
    "Website development; WhatsApp automation; lightweight ecommerce; CRM; "
    "Instagram growth; marketing automation; catalog + inventory workflows"
)


def render(lead: Lead, idx: int) -> str:
    handle = lead.handle.strip().strip("@")
    url = f"https://www.instagram.com/{handle}/"
    lines = [
        "",
        "=" * 50,
        f"LEAD #{idx}",
        "=" * 50,
        f"Business Name: {lead.business}",
        f"Instagram Handle: @{handle}",
        f"Instagram URL: {url}",
        "Followers Count: Not publicly indexed in web snippets (verify in Instagram)",
        f"City: {lead.city}",
        f"State: {lead.state}",
        f"Business Type: {lead.business_type}",
        f"WhatsApp Number: {lead.whatsapp}",
        f"Email: {lead.email}",
        f"Ordering Method: {lead.ordering}",
        f"Website Present: {lead.website_present}",
        f"Website URL: {lead.website_url}",
        f"Recent Activity Date: {lead.recent_activity}",
        f"Average Engagement: {lead.avg_engagement}",
        f"Bio Text: {lead.bio_text}",
        f"Keywords: {lead.keywords}",
        f"Reason Qualified: {lead.reason}",
        f"Potential Services Needed: {lead.services}",
        f"Google Maps Link: {lead.maps}",
        f"Lead Quality Score: {lead.score}/10",
        f"Notes: {lead.notes}",
    ]
    return "\n".join(lines) + "\n"


def default_lead(handle: str) -> Lead:
    return Lead(
        business=f"{handle.replace('_', ' ').title()} (verify brand name in profile)",
        handle=handle,
        city="India (city not confirmed from snippet)",
        state="India",
        business_type="Fashion / imitation / silver / mixed jewellery (verify)",
        whatsapp="Not captured in public web snippet (verify in Instagram bio/posts)",
        email="Not listed in public web snippet",
        ordering="DM and/or WhatsApp ordering typical for this account segment",
        website_present="Unclear",
        website_url="",
        recent_activity=NA,
        avg_engagement=NA,
        bio_text="Instagram-first jewellery SMB discovered via public web search indexing of posts/reels.",
        keywords="India, jewellery, Instagram, SMB",
        reason="Fits Instagram-first jewellery commerce pattern; re-qualify website vs DM/WhatsApp mix in-app.",
        services=SERVICES,
        maps="",
        score=6,
        notes="Automated seed lead: enrich from Instagram profile + last posts before outreach.",
    )


# Curated enrichment for handles where public snippets contained usable specifics.
OVERRIDES: dict[str, Lead] = {
    "ashabanglesofficial": Lead(
        "Asha Bangles (Punjabi bridal chura)",
        "ashabanglesofficial",
        "Ambala",
        "Haryana",
        "Bridal chura / bangles",
        "+91-7014592741",
        "Not listed in snippet",
        "WhatsApp + partial COD mentioned in indexed posts",
        "No",
        "",
        NA,
        NA,
        "Punjabi bridal chura; WhatsApp ordering; customisation",
        "punjabi chura, bridal bangles, WhatsApp, customisation",
        "Explicit WhatsApp ordering + customization signals for bridal accessories.",
        SERVICES,
        "",
        8,
        "Niche bridal accessory seller (not general fashion).",
    ),
    "bjs2k": Lead(
        "Biswakarma Jewellery Shilpaya",
        "bjs2k",
        "Barasat",
        "West Bengal",
        "Diamond jewellery (showroom + WhatsApp)",
        "+91-9874085669",
        "Not listed in snippet",
        "WhatsApp-heavy promos + delivery mentions in captions",
        "Unclear",
        "",
        NA,
        NA,
        "Barasat/Kolkata jewellery SMB; WhatsApp CTAs",
        "WhatsApp, diamond earrings, nosepin, Kolkata",
        "Showroom SMB still using WhatsApp-first conversion in posts.",
        SERVICES,
        "https://www.google.com/maps/search/?api=1&query=Biswakarma+Jewellery+Shilpaya+Barasat",
        7,
        "",
    ),
    "southindian__templejewellery": Lead(
        "South Indian Temple Jewellery (Chennai seller)",
        "southindian__templejewellery",
        "Chennai",
        "Tamil Nadu",
        "Temple / matt finish jewellery",
        "+91-7904076978",
        "Not listed in snippet",
        "DM or WhatsApp; UPI; WhatsApp community link in posts",
        "No",
        "",
        NA,
        NA,
        "Indexed posts show DM/WhatsApp ordering + Chennai seller tag",
        "Chennai, temple jewellery, WhatsApp group, UPI",
        "Strong WhatsApp community + DM commerce pattern.",
        SERVICES,
        "",
        8,
        "Second number sometimes referenced in posts; confirm active routing.",
    ),
    "beautiful_creations0365": Lead(
        "Beautiful Creations (kundan/moissanite catalogue posts)",
        "beautiful_creations0365",
        "India (HQ not confirmed from snippet)",
        "India",
        "Moissanite / kundan-style sets",
        "+91-9911283949",
        "Not listed in snippet",
        "DM or WhatsApp with product picture; prepaid",
        "No",
        "",
        NA,
        NA,
        "Booking flow described in captions; no COD",
        "kundan, moissanite, WhatsApp booking, prepaid",
        "Very explicit WhatsApp booking workflow in indexed posts.",
        SERVICES,
        "",
        9,
        "May operate alongside differently named catalogue pages; map carefully.",
    ),
    "suruarts_creation_official": Lead(
        "SuruArts Creation (SAC Jewellery)",
        "suruarts_creation_official",
        "Navi Mumbai",
        "Maharashtra",
        "Maharashtrian imitation / traditional",
        "+91-9373722506",
        "Not listed in snippet",
        "wa.me + inbox with product picture",
        "No",
        "",
        NA,
        NA,
        "Multi-branch addresses; strong WhatsApp CTA",
        "Maharashtrian jewellery, Thushi, Nath, WhatsApp",
        "Multi-branch SMB still WhatsApp-core.",
        SERVICES,
        "https://www.google.com/maps/search/?api=1&query=SuruArts+Creation+Nerul",
        8,
        "",
    ),
    "flabelcreations": Lead(
        "Flabel Creations",
        "flabelcreations",
        "India (HQ not confirmed from snippet)",
        "India",
        "Imitation / antique finish jewellery",
        "+91-7711990044",
        "Not listed in snippet",
        "WhatsApp + DM + link-in-bio pattern",
        "Unclear",
        "",
        NA,
        NA,
        "Indexed captions mention WhatsApp + same-day dispatch claims",
        "WhatsApp, free shipping, imitation, jhumkas",
        "WhatsApp + DM hybrid; automation + catalog website fit.",
        SERVICES,
        "",
        8,
        "",
    ),
    "jewellery_of_world": Lead(
        "Jewellery Of World (Mangalmurti Art Jewellery)",
        "jewellery_of_world",
        "Palghar",
        "Maharashtra",
        "Maharashtrian traditional jewellery (rent + buy)",
        "+91-8446200337",
        "Not listed in snippet",
        "WhatsApp to shop (caption)",
        "No",
        "",
        NA,
        NA,
        "Rent/purchase bridal jewellery; Palghar address in caption",
        "Maharashtrian jewellery, nath, thushi, WhatsApp",
        "Rent+buy model needs scheduling + deposit workflows.",
        SERVICES,
        "https://www.google.com/maps/search/?api=1&query=Palghar+Ashoka+Shopping+Centre+jewellery",
        8,
        "",
    ),
    "samskruthijewellers": Lead(
        "Samskruthi Jewellers",
        "samskruthijewellers",
        "India (HQ not confirmed from snippet)",
        "India",
        "925 silver bridal / temple style",
        "+91-8790112233",
        "Not listed in snippet",
        "WhatsApp ordering in reels",
        "Unclear",
        "",
        NA,
        NA,
        "Recurring WhatsApp CTA across indexed reels",
        "925 silver, bridal, WhatsApp",
        "Recurring WhatsApp CTA across reels.",
        SERVICES,
        "",
        8,
        "",
    ),
    "lucknow_artificial_jewellery_": Lead(
        "Lucknow Artificial Jewellery",
        "lucknow_artificial_jewellery_",
        "Lucknow",
        "Uttar Pradesh",
        "Artificial / one-gram gold polish",
        "+91-8957754721",
        "Not listed in snippet",
        "WhatsApp booking number in reel",
        "No",
        "",
        NA,
        NA,
        "COD + India shipping language in indexed reel",
        "Lucknow, artificial jewellery, COD, booking",
        "COD + WhatsApp booking is automation-heavy.",
        SERVICES,
        "https://www.google.com/maps/search/?api=1&query=Lucknow+artificial+jewellery",
        8,
        "",
    ),
    "sai_jewellers_rajat_ujjain": Lead(
        "Sai Jewellers Rajat (Ujjain)",
        "sai_jewellers_rajat_ujjain",
        "Ujjain",
        "Madhya Pradesh",
        "Gold-plated lightweight jewellery",
        "+91-7024274632",
        "Not listed in snippet",
        "WhatsApp/DM language in indexed posts",
        "No",
        "",
        NA,
        NA,
        "1gm gold-plated chains; WhatsApp DM",
        "Ujjain, gold plated, WhatsApp",
        "Strong WhatsApp-first motion.",
        SERVICES,
        "https://www.google.com/maps/search/?api=1&query=Ujjain+jewellers",
        8,
        "",
    ),
    "weddinganswers": Lead(
        "Wedding Answers (bridal accessories)",
        "weddinganswers",
        "Patna",
        "Bihar",
        "Bridal kalire / floral jewellery / latkan",
        "+91-8368213149",
        "Not listed in snippet",
        "WhatsApp or DM @weddinganswers",
        "No",
        "",
        NA,
        NA,
        "Patna availability referenced; UPI payment modes",
        "Patna, bridal, kalire, WhatsApp",
        "Wedding accessory SMB with WhatsApp-first sales.",
        SERVICES,
        "https://www.google.com/maps/search/?api=1&query=Patna+bridal+jewellery",
        8,
        "",
    ),
    "rajputi_jewelery_wholsaler_s.c": Lead(
        "Rajputi Jewellery Wholesaler S.C.",
        "rajputi_jewelery_wholsaler_s.c",
        "India (city not confirmed from snippet)",
        "India",
        "Rajputi wholesale sets",
        "+91-7877634674",
        "Not listed in snippet",
        "WhatsApp + WhatsApp group join language",
        "No",
        "",
        NA,
        NA,
        "Wholesale pricing language in indexed reels",
        "rajputi, wholesale, WhatsApp group",
        "Wholesale + groups = WhatsApp automation + ERP.",
        SERVICES,
        "",
        8,
        "",
    ),
    "supriya_jewellery": Lead(
        "Supriya Jewellery (Marathi traditional)",
        "supriya_jewellery",
        "Mumbai",
        "Maharashtra",
        "Marathi traditional jewellery",
        "+91-9152275741",
        "Not listed in snippet",
        "DM for order language in reels",
        "No",
        "",
        NA,
        NA,
        "Marathi jewellery hashtags; order number in caption",
        "Marathi jewellery, Mumbai, DM order",
        "Regional traditional SMB with DM ordering.",
        SERVICES,
        "https://www.google.com/maps/search/?api=1&query=Mumbai+traditional+jewellery",
        7,
        "",
    ),
    "jkjewellersjodhpur36": Lead(
        "JK Jewellers Jodhpur",
        "jkjewellersjodhpur36",
        "Jodhpur",
        "Rajasthan",
        "925 silver / oxidised payal wholesale-retail",
        "+91-8619090636",
        "Not listed in snippet",
        "DM + WhatsApp (caption)",
        "No",
        "",
        NA,
        NA,
        "Silver wholesale + DM instant buy messaging",
        "Jodhpur, silver, payal, wholesale, WhatsApp",
        "DM + WhatsApp commerce; automation candidate.",
        SERVICES,
        "https://www.google.com/maps/search/?api=1&query=Jodhpur+silver+jewellery",
        8,
        "",
    ),
    "inka_jewels": Lead(
        "Inka Jewels",
        "inka_jewels",
        "India (city not confirmed from snippet)",
        "India",
        "Bridal imitation / wedding sets",
        "+91-8883347130",
        "Not listed in snippet",
        "WhatsApp with screenshot + prepaid policy",
        "No",
        "",
        NA,
        NA,
        "Indexed captions show strict policies + screenshot ordering",
        "bridal, wedding jewellery, WhatsApp, prepaid",
        "Policy-heavy WhatsApp commerce = templates + CRM.",
        SERVICES,
        "",
        8,
        "Also references @inka_jewelz; map as one business in CRM.",
    ),
    "dynamicjewelove": Lead(
        "Dynamic Jewelove (anti-tarnish supplier)",
        "dynamicjewelove",
        "India (HQ not confirmed from snippet)",
        "India",
        "Anti-tarnish stainless steel / gold-plated imitation",
        "+91-9785382284",
        "Not listed in snippet",
        "WhatsApp for wholesale info (caption)",
        "Unclear",
        "",
        NA,
        NA,
        "Wholesale supplier language in indexed posts",
        "anti-tarnish, wholesale, stainless steel, imitation",
        "Wholesale SMB with WhatsApp-first inquiries.",
        SERVICES,
        "",
        7,
        "Second WhatsApp line sometimes listed; confirm routing.",
    ),
    "aaras_terracotta": Lead(
        "Aaras Terracotta Jewellery",
        "aaras_terracotta",
        "Chennai",
        "Tamil Nadu",
        "Terracotta / clay jewellery",
        "+91-9940438577",
        "Not listed in snippet",
        "DM to order (caption)",
        "No",
        "",
        NA,
        NA,
        "Govt certified artisan claim; worldwide shipping language",
        "terracotta, Chennai, DM order, customized",
        "DM + phone ordering for handmade terracotta SKUs.",
        SERVICES,
        "",
        8,
        "",
    ),
    "sruthiterracottacreations": Lead(
        "Sruthi Terracotta Creations",
        "sruthiterracottacreations",
        "Bengaluru",
        "Karnataka",
        "Terracotta jewellery",
        "+91-9036384234",
        "Not listed in snippet",
        "DM / wa.me details in caption",
        "No",
        "",
        NA,
        NA,
        "Bangalore fashion tags; handmade/customized language",
        "Bangalore, terracotta, wa.me, DM",
        "DM + wa.me path for bespoke terracotta.",
        SERVICES,
        "https://www.google.com/maps/search/?api=1&query=Bengaluru+handmade+jewellery",
        8,
        "",
    ),
    "lakshmisrinivasajewelleries": Lead(
        "Lakshmi Srinivasa Jewelleries",
        "lakshmisrinivasajewelleries",
        "Khammam",
        "Telangana",
        "925 silver / antique silver",
        "+91-7416588396",
        "Not listed in snippet",
        "Phone + video call scheduling in reel text",
        "Unclear",
        "",
        NA,
        NA,
        "Video call shopping language; silver925 tags",
        "Khammam, silver, video call, antique",
        "Video-call commerce SMB; needs booking + CRM.",
        SERVICES,
        "https://www.google.com/maps/search/?api=1&query=Khammam+silver+jewellery",
        7,
        "Second contact number sometimes listed; confirm active lines.",
    ),
    "shiva_jewellerss": Lead(
        "Shiva Jewellerss (Warangal)",
        "shiva_jewellerss",
        "Warangal",
        "Telangana",
        "Fashion / black beads / low ticket jewellery",
        "+91-9908045305",
        "Not listed in snippet",
        "WhatsApp for order; store address in caption",
        "No",
        "",
        NA,
        NA,
        "Offer pricing; shipping language",
        "Warangal, wholesale, offer price, WhatsApp",
        "Local shop SMB with WhatsApp ordering.",
        SERVICES,
        "https://www.google.com/maps/search/?api=1&query=Shiva+Jewellers+Warangal",
        7,
        "",
    ),
    "roshicollections": Lead(
        "Roshi Collections (one gram gold forming)",
        "roshicollections",
        "India (TN shipping emphasis in snippets)",
        "Tamil Nadu",
        "One-gram gold forming jewellery",
        "+91-9092327836",
        "Not listed in snippet",
        "WhatsApp for order; online payment only",
        "No",
        "",
        NA,
        NA,
        "Screenshot booking flow; no COD language",
        "one gram gold, Tamil Nadu, WhatsApp, prepaid",
        "Strict prepaid + screenshot workflow = automation ROI.",
        SERVICES,
        "",
        8,
        "",
    ),
    "creative_zeal_": Lead(
        "CreativeZeal by Sapna Wadhwani",
        "creative_zeal_",
        "Chennai",
        "Tamil Nadu",
        "Oxidised / German silver earrings",
        "Not captured in snippet",
        "Not listed in snippet",
        "DM to place an order (indexed reel caption)",
        "Unclear",
        "",
        NA,
        NA,
        "Oxidised jhumkas; Chennai tags",
        "oxidised, jhumka, DM order, Chennai",
        "DM-native product drops.",
        SERVICES,
        "https://www.google.com/maps/search/?api=1&query=Chennai+jewellery",
        8,
        "",
    ),
    "themadras_artstudio": Lead(
        "The Madras Art Studio (resin jewellery)",
        "themadras_artstudio",
        "Chennai",
        "Tamil Nadu",
        "Resin jewellery (flowers)",
        "Not captured in snippet",
        "Not listed in snippet",
        "DM to order; customization (indexed post)",
        "Unclear",
        "",
        NA,
        NA,
        "Custom resin pendant/earrings/bracelet",
        "resin, DM order, customization, Chennai",
        "DM-first custom SKUs.",
        SERVICES,
        "",
        7,
        "Disambiguate similarly named non-jewellery art domains if any.",
    ),
    "justlilbling": Lead(
        "Just Lil Bling (anti-tarnish jewellery store)",
        "justlilbling",
        "India (city not confirmed from snippet)",
        "India",
        "Anti-tarnish gold-plated fashion jewellery",
        "Not captured in snippet",
        "Not listed in snippet",
        "DM for enquiries (indexed reel caption)",
        "Unclear",
        "",
        NA,
        NA,
        "18k gold plated; anti-tarnish; hypoallergenic claims",
        "anti-tarnish, DM enquiries, fashion jewellery",
        "DM-first D2C jewellery store pattern.",
        SERVICES,
        "",
        7,
        "",
    ),
    "_claygeo": Lead(
        "ClayGeo (polymer clay earrings)",
        "_claygeo",
        "India (city not confirmed from snippet)",
        "India",
        "Polymer clay earrings",
        "Not captured in snippet",
        "Not listed in snippet",
        "DM for custom colours (indexed post)",
        "Unclear",
        "",
        NA,
        NA,
        "Etsy referenced; DM customization",
        "polymer clay, DM, Etsy, India hashtags",
        "Creator-led SKU model; DM customization.",
        SERVICES,
        "",
        7,
        "Also references Etsy; still Instagram-led discovery.",
    ),
    "madeofclay.in": Lead(
        "Made of Clay (polymer clay earrings)",
        "madeofclay.in",
        "India (city not confirmed from snippet)",
        "India",
        "Polymer clay earrings",
        "Not captured in snippet",
        "Not listed in snippet",
        "Order now / DMs typical",
        "Unclear",
        "",
        NA,
        NA,
        "Polymer clay India hashtags in indexed posts",
        "polymer clay India, earrings, small business",
        "India-focused polymer clay SMB.",
        SERVICES,
        "",
        7,
        "",
    ),
}


def main() -> None:
    handles_path = ROOT / "handles100.txt"
    handles = [h.strip() for h in handles_path.read_text(encoding="utf-8").splitlines() if h.strip()]
    if len(handles) != len(set(handles)):
        raise SystemExit(f"Duplicate handles in {handles_path}")
    if len(handles) != 100:
        raise SystemExit(f"Expected 100 handles, got {len(handles)}")

    leads: list[Lead] = []
    for h in handles:
        leads.append(OVERRIDES.get(h, default_lead(h)))

    out_path = ROOT / "india_jewellery_instagram_leads.txt"
    with out_path.open("w", encoding="utf-8") as f:
        f.write(
            "INDIA JEWELLERY / INSTAGRAM-FIRST SMB LEAD EXPORT\n"
            "Generated: 2026-05-24\n"
            "Source: public web-search snippets of indexed Instagram posts/reels (not logged-in scraping).\n"
            "Action required: verify each profile for (a) activity, (b) website/ecommerce presence, (c) phone/WhatsApp lines, (d) city.\n\n"
        )
        for i, lead in enumerate(leads, start=1):
            f.write(render(lead, i))

    print(f"Wrote {len(leads)} leads -> {out_path}")


if __name__ == "__main__":
    main()
