#!/usr/bin/env python3
"""Assemble india_jewellery_instagram_leads.txt from curated public-search snippets."""
from __future__ import annotations

import re
from pathlib import Path

# Each tuple: (handle, business_name, city, state, business_type, whatsapp, email, ordering, website_yn,
#             website_url, recent_activity, engagement_note, bio, keywords, reason, services, maps, score, notes)
LEADS: list[tuple[str, ...]] = [
("mohabygeetanjali", "Moha by Geetanjali", "Unknown", "India", "Designer 925 silver jewellery", "+919930898047", "Unknown", "WhatsApp + Instagram DM", "No", "None found in snippet", "2026 (verify)", "Unknown", "Handcrafted silver jewellery; posts include WhatsApp contact.", "silver,925,handcrafted,fashion", "Public reel captions advertise WhatsApp ordering for silver fashion jewellery.", "Ecommerce, WhatsApp automation, CRM", "Unknown", "8", "Indexed search shows active product reels with direct WhatsApp."),
("gahanejewellery", "Gahane Jewellery", "Kolkata", "West Bengal", "Handmade gold temple / bridal bangles", "Unknown", "Unknown", "DM / store enquiries (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Handcrafted gold bangles; strong bridal hashtags.", "gold,bangles,handmade,bengal,bridal", "Kolkata-linked handmade gold jewellery content.", "Website, appointment booking, CRM", "Unknown", "7", "Appears artisan/atelier-style; verify ordering flow on profile."),
("lakshmijewells", "Lakshmi Jewells (Sree Wholesale Jewellery)", "Unknown", "Telangana/India", "Imitation / matte bridal sets", "+919390483697", "Unknown", "WhatsApp for order & enquiry", "No", "None in snippet", "2026 (verify)", "Unknown", "Wholesale-style captions; opening-video policy.", "wholesale,choker,black beads,bridal", "Explicit WhatsApp order line in indexed reel slug.", "WhatsApp automation, CRM, ecommerce", "Unknown", "8", "Strong WhatsApp-first operations signal."),
("radha_rani_imitation_7", "Radha Rani Imitation", "Mumbai", "Maharashtra", "Imitation wholesale", "+917023725950", "Unknown", "Call / WhatsApp (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Bhuleshwar market wholesale address in caption.", "imitation,wholesale,mumbai,bangles", "Physical wholesale shop plus Instagram discovery.", "POS, ecommerce, inventory", "https://www.google.com/maps/search/Bhuleshwar+Mumbai+jewellery", "7", "Wholesale orientation; still SMB tooling upside."),
("y.j.jewellery_mumbai", "Y J Jewellery", "Mumbai", "Maharashtra", "Fashion jewellery", "Unknown", "Unknown", "DM (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Fashion jewellery reels.", "fashion,mumbai,reels", "Mumbai-named handle; socially active posting.", "Instagram growth, content studio", "Unknown", "6", "Confirm WhatsApp presence in bio."),
("chudiwale_", "Chudiwale Fashion Jewellery", "Unknown", "India", "Customized bangles / bridal bangles", "+917972380643", "Unknown", "WhatsApp booking", "No", "None in snippet", "2026 (verify)", "Unknown", "Custom bangle sets; WhatsApp booking line.", "bangles,custom,bridal,velvet", "Explicit WhatsApp for customized sets.", "WhatsApp automation, custom order CRM", "Unknown", "9", "High intent for customization workflow software."),
("indukurisjewel", "Jewel Indukuri's", "Unknown", "India", "Lab-grown diamond pendants (custom)", "+916302720676", "Unknown", "WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Customization via WhatsApp mentioned.", "lab grown diamond,custom,pendant", "Custom SKU messaging fits CRM upsell.", "CRM, 3D renders, ecommerce", "Unknown", "7", "Niche; confirm India base from bio."),
("bjs2k", "Biswakarma Jewellery Shilpaya", "Unknown", "India", "Diamond nosepins & earrings (retail)", "+919874085669", "Unknown", "WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Long-form WhatsApp CTAs in posts.", "diamond,nosepin,earrings,whatsapp", "Heavy WhatsApp CTA pattern.", "WhatsApp automation, ads, landing pages", "Unknown", "7", "Luxury claims—verify authenticity before outreach."),
("jewelsofkarnataka", "Jewels of Karnataka", "Karnataka", "Karnataka", "One-gram / fashion jewellery", "+919740234813", "Unknown", "WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "State-focused brand name; WhatsApp in caption.", "one gram,karnataka,whatsapp", "Regional SMB with WhatsApp ordering.", "Ecommerce, WhatsApp bot, CRM", "Unknown", "8", "Good fit for localized ads + catalog site."),
("nandijewels", "Nandi Jewellers", "Mysuru", "Karnataka", "Gold antique / bridal", "Unknown", "Unknown", "DM / visit store (verify)", "Unclear", "Unknown", "2026 (verify)", "Unknown", "Mysore-tagged bridal gold reels.", "gold,bridal,mysore", "Store-forward brand; still social-led discovery.", "Website, bookings, CRM", "Unknown", "5", "May be more showroom-led—qualify before pitching IG-only stack."),
("goharjewelsofficial", "Gohar Jewels", "Unknown", "India", "Handmade resin jhumkas", "Unknown", "Unknown", "DM (caption)", "No", "None in snippet", "2026 (verify)", "Unknown", "Resin floral jhumkas; customization implied.", "resin,jhumka,handmade", "Artisan product style; DM-led commerce.", "Ecommerce, Meta ads, packaging", "Unknown", "8", "Strong handmade story for Shopify-lite build."),
("mahandi_artificial", "Mahandi Artificial", "Unknown", "India", "Gold-plated / artificial jewellery", "Unknown", "Unknown", "DM (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Tagged in influencer-style posts.", "artificial,gold plated", "SMB manufacturing vibe from collaborations.", "Catalog site, influencer CRM", "Unknown", "6", "Need direct bio capture."),
("jj_resin.memo", "jj_resin.memo", "Unknown", "India", "Resin memo / personalized resin gifts", "+918489166598", "Unknown", "WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Custom resin name products.", "resin,custom,personalized", "WhatsApp ordering explicitly listed.", "WhatsApp automation, ecommerce", "Unknown", "8", "Micro-SMB custom workflow."),
("begumbazar_wholesale_jewelry", "BegumBazar Wholesale Jewelry", "Hyderabad", "Telangana", "One-gram gold plated wholesale", "+919618136342", "Unknown", "WhatsApp + DM", "No", "None in snippet", "2026 (verify)", "Unknown", "Begum Bazar positioning; screenshot-to-order flow.", "one gram,wholesale,begum bazar", "Screenshot ordering is automation-friendly.", "WhatsApp flows, ERP-light", "Unknown", "9", "Very strong WhatsApp + reel commerce pattern."),
("janvish_onegramgold_and_boutiq", "Janvish One Gram Gold & Boutique", "Unknown", "India", "One-gram gold & boutique", "+918121769801", "Unknown", "WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "WhatsApp groups mentioned for updates.", "one gram,boutique,whatsapp group", "Group selling indicates CRM opportunity.", "Community CRM, ecommerce", "Unknown", "8", "COD / policies: verify current caption."),
("sakhi_1_gram_gold_jewellery", "Sakhi 1 Gram Gold Jewellery", "Unknown", "India", "One-gram gold jewellery", "+919652417754", "Unknown", "WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Price-in-caption + WhatsApp.", "one gram,gold plated", "Classic SMB one-gram model.", "Catalog + payments stack", "Unknown", "8", "PAN-India shipping claims—verify."),
("silver_store_chennai", "Silver Store Chennai", "Chennai", "Tamil Nadu", "925 silver idols & jewellery", "+918181871717", "Unknown", "WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Valasaravakkam location in posts.", "silver 925,chennai,religious", "Local silver shop with WhatsApp ordering.", "Local SEO, ecommerce, chatbot", "https://www.google.com/maps/search/Valasaravakkam+silver+jewellery", "8", "Strong geo + WhatsApp combo."),
("chezian_velli_maaligai", "Chezhiyan Velli Maaligai", "Unknown", "Tamil Nadu", "925 silver wedding rings (laser name)", "+917010078402", "Unknown", "DM + WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Customization + DM/WhatsApp.", "silver 925,custom,wedding", "Custom SKU + WhatsApp = CRM fit.", "Product customizer ecommerce", "Unknown", "9", "High customization intent."),
("lakshmi_creations_9", "Lakshmi Creations Imitation Jewellery", "Hyderabad", "Telangana", "Imitation wholesale", "+919849567353", "Unknown", "WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Wholesale pricing language.", "imitation,wholesale,jhumkas", "Wholesale + WhatsApp.", "B2B portal, WhatsApp catalog", "Unknown", "8", "Good candidate for catalog automation."),
("rajaveer_imitation_ahemadabad", "Raja Veer Imitation Jewellery", "Ahmedabad", "Gujarat", "Gold-plated imitation", "+918511513997", "Unknown", "WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Naroda address style captions.", "imitation,ahmedabad,1 gram plated", "Screenshot-to-order behaviour.", "WhatsApp automation, ads", "https://www.google.com/maps/search/Naroda+Ahmedabad+jewellery", "8", "Strong SMB signals."),
("sairajimmitation_01", "Sai Raj Immitation", "Ahmedabad", "Gujarat", "Wholesale imitation", "+918866462720", "Unknown", "WhatsApp / call", "No", "None in snippet", "2026 (verify)", "Unknown", "Multiple wholesale numbers listed.", "wholesale,korean earrings,old city", "Multi-number wholesale desk.", "IVR, CRM, wholesale ecommerce", "Unknown", "7", "Wholesale-first; pitch B2B tools."),
("bj_imitation_ahmedabad", "BJ Imitation Ahmedabad", "Ahmedabad", "Gujarat", "Brass / imitation rings", "Unknown", "Unknown", "DM (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Men's rings focus in reel title.", "rings,brass,ahmedabad", "Fashion imitation niche.", "UGC, reels ads", "Unknown", "6", "Limited phone in snippet—verify bio."),
("dhanshi_fashion_jewellery", "Dhanshi Fashion Jewellery", "Kerala", "Kerala", "Kerala palakka / fashion sets", "Unknown", "Unknown", "DM", "No", "None in snippet", "2026 (verify)", "Unknown", "Palakka + DM-to-order caption pattern.", "palakka,kerala,bridal", "Regional catalogue opportunity.", "Ecommerce, Malayalam creatives", "Unknown", "8", "Regional bridal sets."),
("jhoolylalartificial", "Jhooly Lal Artificial Jewellery", "Unknown", "India", "Artificial jewellery", "Unknown", "Unknown", "DM (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Artificial jewellery account.", "artificial,fashion", "SMB catalogue play.", "Shopify-lite, Meta catalog", "Unknown", "6", "Sparse contact in snippet."),
("mahavirimitationjewelle", "Mahavir Imitation Jewellery", "Unknown", "India", "Oxidised / imitation bangles", "+918320499102", "Unknown", "Call / DM (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Call-for-details pattern.", "oxidised,imitation,bangles", "Phone-led support.", "Click-to-call landing, CRM", "Unknown", "7", "Verify city from bio."),
("jodhpuri_silver", "Jodhpuri Silver (KHUSHBU_JWELLERS posts)", "Jodhpur", "Rajasthan", "Silver payal / silver fashion", "+919358839704", "Unknown", "WhatsApp screenshot order", "Unclear", "Mentions website discount text in some posts", "2026 (verify)", "Unknown", "Screenshot-to-order pattern.", "silver,payal,screenshot order", "Heavy performance-marketing style captions.", "WhatsApp automation, compliance", "Unknown", "7", "Some posts mention website discounts—verify website status."),
("lavanyajewellers_slj", "Lavanya Jewellers SLJ", "Vijayawada", "Andhra Pradesh", "Gold / diamond pendants & chains", "+919441176530", "Unknown", "DM + WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Custom orders + shipping India/US claims.", "gold,diamond,custom", "High-ticket SMB with WhatsApp.", "CRM, appointment scheduling", "Unknown", "7", "Also tags other cities—verify primary base."),
("indranibiswas_", "Indrani's Collection", "Kolkata", "West Bengal", "Clay / handmade chokers", "Unknown", "Unknown", "DM to buy", "No", "None in snippet", "2026 (verify)", "Unknown", "Clay jewellery + Kolkata tags.", "clay,choker,handmade,kolkata", "DM-first handmade seller.", "Ecommerce, commissions portal", "Unknown", "9", "Very IG-native creator-commerce."),
("_jewellery_palace_bjs", "Jewellery Palace BJS", "Unknown", "India", "Silver / fashion pieces", "+918440038551", "Unknown", "WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "WhatsApp order lines with codes.", "silver,fashion,whatsapp", "Code-based SKUs = inventory tool fit.", "SKU + WhatsApp bot", "Unknown", "8", "Good automation candidate."),
("omkar_jewels_surat", "Omkar Jewels Surat", "Surat", "Gujarat", "Custom gold / bespoke", "+918141248248", "Unknown", "Call / visit + DM (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Surat workshop address in reel.", "custom,surat,gold", "Bespoke positioning.", "CRM, 3D visualization", "https://www.google.com/maps/search/Uttran+Surat+jewellery", "7", "More atelier than IG-only—still digital upside."),
("vajubhai_and_sons", "Vajubhai & Sons", "Surat", "Gujarat", "Gold manufacturing heritage", "Unknown", "Unknown", "DM (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Long-established Surat manufacturer vibe.", "gold,manufacturing,surat", "Heritage manufacturer; digital modernization angle.", "B2B portal, video catalog", "Unknown", "6", "Larger heritage—pitch carefully."),
("samashajewellery", "SamAsha Jewellery", "Unknown", "India", "Oxidised / German silver earrings", "+919711107695", "Unknown", "DM + WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Unboxing policy text = scaled ops.", "oxidised,german silver,jhumka", "Operational policies in caption.", "WhatsApp CRM, returns workflow", "Unknown", "9", "Strong SMB maturity."),
("wear_nd_shine_jewelry", "Wear nd Shine Jewelry", "Coimbatore", "Tamil Nadu", "Bridal / AD jewellery", "+917981803973", "Unknown", "DM + WhatsApp", "Unclear", "Third-party blog lists WhatsApp; separate Shopify-like brand may exist—verify", "2026 (verify)", "Unknown", "South India wedding hashtags.", "bridal,AD stone,coimbatore", "DM + WhatsApp hybrid bridal seller.", "CRM, brand-safety research", "Unknown", "7", "Verify brand confusion with similarly named Shopify store."),
("prema_jewellery_sultanpet", "Prema Jewellery Sultanpet", "Palakkad", "Kerala", "Silver traditional", "+917907190065", "Unknown", "Call / WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Palakkad-tagged silver content.", "silver,palakkad,traditional", "Local jeweller digital presence.", "Local SEO, WhatsApp", "Unknown", "7", "Two numbers in some posts—dedupe on outreach."),
("pooja_shree_jewellary_onegram", "Pooja Shree Jewellery (One Gram)", "Sambhajinagar", "Maharashtra", "One-gram temple / mangalsutra", "+919503080030", "Unknown", "DM / WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Maharashtra-wide hashtags.", "one gram,temple,mangalsutra", "Regional one-gram SMB.", "WhatsApp catalog, CRM", "Unknown", "8", "Multiple numbers in caption—confirm active."),
("__silver_jewellery_psj", "Silver Jewellery by PSJ", "New Delhi", "Delhi", "925 silver kada / men's silver", "+918920857565", "Unknown", "DM + WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Lajpat Nagar shop address.", "silver 925,lajpat nagar,mens kada", "Delhi shop + WhatsApp.", "Local ads, inventory POS", "https://www.google.com/maps/search/Lajpat+Nagar+2+silver+jewellery", "8", "Physical + digital hybrid."),
("poshsilverjewellery", "Posh Silver Jewellery", "Bengaluru", "Karnataka", "Silver boutique Malleshwaram", "Unknown", "Unknown", "DM / visit store", "No", "None in snippet", "2026 (verify)", "Unknown", "Launch-style reel for Bengaluru store.", "silver,bangalore,malleshwaram", "New store digital growth window.", "Local SEO, ecommerce", "https://www.google.com/maps/search/Malleshwaram+silver+jewellery", "7", "Retail store forward."),
("mahalaxmi_gold99", "Mahalaxmi Jwellers", "Mysuru", "Karnataka", "916 hallmark chains", "+919880820391", "Unknown", "DM + WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Multi-region hashtags.", "gold,916,mysore", "Gold SMB using WhatsApp.", "CRM, payments, compliance pages", "Unknown", "6", "Gold-heavy; ensure not unlicensed pitching."),
("pooja_jewellerpj", "Pooja Jewellers", "Unknown", "India", "Silver moti / silver fashion", "Unknown", "Unknown", "DM (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Silver moti ring style posts.", "silver,fashion", "SMB silver reel account.", "Catalog ecommerce", "Unknown", "6", "Limited public contact in snippet."),
("atampara", "Atampara (Silver jewellery & articles)", "Unknown", "India", "Silver articles / festive toys", "Unknown", "Unknown", "DM (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Laddu Gopal silver artifacts.", "silver,artifacts,festive", "Niche silver gifting SMB.", "Seasonal campaigns, WhatsApp", "Unknown", "6", "Seasonal demand spikes—good for automation."),
("ar_gold_covering", "AR Gold Covering", "Unknown", "India", "Gold-plated temple / haram sets", "+918606878555", "Unknown", "DM + WhatsApp + link-in-bio site", "Yes", "Link-in-bio website referenced in posts", "2026 (verify)", "Unknown", "Gold covering / micro-plated catalogue.", "gold plated,haram,palakka", "Has mini-site via link-in-bio; still heavy IG commerce.", "Funnel optimization, CRM", "Unknown", "7", "Not strictly no-website; score reflects hybrid."),
("gsvgoldcovering", "GSV Gold Covering", "Unknown", "India", "Gold covering jewellery", "Unknown", "Unknown", "DM (verify)", "No", "None confirmed", "2026 (verify)", "Unknown", "Gold covering niche sibling market.", "gold covering,plating", "Parallel niche to AR Gold Covering.", "WhatsApp catalog", "Unknown", "6", "Sparse data—verify contacts."),
("arysasilver", "Arysa Silver", "Unknown", "India", "925 sterling silver accessories", "+918985035000", "Unknown", "DM + call", "No", "None in snippet", "2026 (verify)", "Unknown", "DM to order + call line.", "sterling silver,boho", "Premium silver SMB.", "Shopify, subscriptions", "Unknown", "8", "Good ecommerce candidate."),
("khushbujewellers.com_", "Khushbujewellers.com_", "Unknown", "India", "Rajputi silver / bridal silver", "+919875791031", "Unknown", "WhatsApp screenshot order", "Unclear", "Posts mention website discount language", "2026 (verify)", "Unknown", "Username implies web presence—verify.", "rajputi,silver,screenshot order", "Heavy DR-style promos.", "Marketing automation, compliance", "Unknown", "6", "Verify website + brand safety."),
("ridhi_sidhi_jewellers", "Ridhi Sidhi Jewellers", "Barmer", "Rajasthan", "Silver bangles COD", "+917849810107", "Unknown", "WhatsApp screenshot", "No", "None in snippet", "2026 (verify)", "Unknown", "COD + screenshot flow.", "silver,bangles,COD", "COD logistics = ops tooling.", "COD reconciliation, CRM", "https://www.google.com/maps/search/Barmer+jewellery", "8", "COD SMB—payments stack upsell."),
("swarnam_varnam", "Swarnam Varnam Jewellery", "Hyderabad", "Telangana", "Bridal / zircon replica sets", "Unknown", "Unknown", "DM", "Unclear", "MyDukaan / marketplace links appear in some indexes—verify", "2026 (verify)", "Unknown", "Hyderabad bride hashtags.", "bridal,zircon,replica", "DM-first with possible micro-store.", "Ecommerce migration, CRM", "Unknown", "8", "Verify external storefront duplication."),
("sai_jewellers_rajat_ujjain", "Sai Jewellers Rajat", "Ujjain", "Madhya Pradesh", "Gold-plated / one-gram style", "+917024274632", "Unknown", "WhatsApp + DM", "No", "None in snippet", "2026 (verify)", "Unknown", "Geo-tagged Ujjain captions.", "one gram,gold plated,ujjain", "Classic tier-2/3 IG commerce.", "WhatsApp payments, catalog", "https://www.google.com/maps/search/Ujjain+jewellery", "8", "Strong SMB profile."),
("flabelcreations", "Flabel Creations", "Unknown", "India", "Imitation / AD jewellery", "+917711990044", "Unknown", "WhatsApp + DM", "No", "None in snippet", "2026 (verify)", "Unknown", "Same-day dispatch claims.", "imitation,AD,jhumka", "Fast dispatch SMB.", "Ops automation, CRM", "Unknown", "9", "High velocity ecommerce signals."),
("kichu_collection", "Kichu Collection", "Kerala", "Kerala", "Gold-look jewellery", "Unknown", "Unknown", "DM", "No", "None in snippet", "2026 (verify)", "Unknown", "Kerala jewellery hashtags.", "kerala,haram,nagapadam", "Regional IG-first catalogue.", "Ecommerce, Malayalam ads", "Unknown", "8", "DM-heavy seasonal promos."),
("chicjewells", "ChicJewells (South India Jewels)", "Unknown", "India", "Temple / bridal chokers", "+917200404607", "Unknown", "DM + WhatsApp", "Yes", "Posts mention chicjewells.in", "2026 (verify)", "Unknown", "Website exists but IG/WhatsApp still core.", "temple,choker,bridal", "Hybrid commerce model.", "Omnichannel CRM", "Unknown", "6", "Website present—lower fit for 'no website' stack but still automation upside."),
("rcpkjewellers", "RCPK Jewellers", "Unknown", "India", "22kt wax-filled gold bangles", "Unknown", "Unknown", "DM pricing", "No", "None in snippet", "2026 (verify)", "Unknown", "Hallmark gold product focus.", "gold,bangles,hallmark", "DM-for-price gold SMB.", "CRM, compliance content", "Unknown", "6", "Verify local regulations messaging."),
("kalepalli_jewellers", "Kalepalli Jewellers", "Rajahmundry", "Andhra Pradesh", "Gold necklaces / fancy", "Unknown", "Unknown", "DM (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Rajahmundry address in reel.", "gold,fancy,rajahmundry", "Geo-tagged jeweller.", "Local performance marketing", "https://www.google.com/maps/search/Rajahmundry+jewellers", "6", "Showroom-forward."),
("rajratanjewellersdgp", "Raj Ratan Jewellers", "Durgapur", "West Bengal", "Hallmark gold jewellery", "Unknown", "Unknown", "Visit showroom", "No", "None in snippet", "2026 (verify)", "Unknown", "Showroom-forward captions.", "gold,hallmark,durgapur", "Traditional retailer on IG.", "Online booking, CRM", "Unknown", "5", "Less IG-commerce—still modernization."),
("kpr_jewellery", "KPR Jewellery", "Chennai", "Tamil Nadu", "Kerala-style palakka imitation (DM-priced)", "Unknown", "Unknown", "DM to order", "No", "None confirmed in public embed", "2026 (verify)", "~21K followers (embed); engagement varies", "Public post: Kerala-style Palakka collections ₹250–₹999; DM to order; geo tag Chennai.", "palakka,imitation,kerala style,dm", "Verified @kpr_jewellery via Instagram embed; DM-first catalogue.", "WhatsApp CTAs, lightweight catalog site, CRM", "https://www.google.com/maps/search/Chennai+jewellery", "8", "Bio/ordering flow: confirm in-app."),
("_amethyst__jewelz", "AmethystJewelz", "Kottayam", "Kerala", "Matt palakka / fancy imitation", "Unknown", "Unknown", "DM (verify)", "No", "None confirmed in public embed", "2026 (verify)", "~23K followers (embed); engagement varies", "Matt finish palakka pricing in captions; Kottayam location tag in embed.", "palakka,matt,kerala,oxidized", "Verified @_amethyst__jewelz via Instagram embed.", "Catalog + reels + WhatsApp optional", "https://www.google.com/maps/search/Kottayam+jewellery", "8", "Confirm WhatsApp if added later."),
("saaz_jewels", "Saaz Jewels / Saaz Chains", "Mumbai", "Maharashtra", "Antique gold jewellery", "Unknown", "Unknown", "DM (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Mumbai-tagged antique styles.", "antique,gold,mumbai", "Pvt Ltd style—may be mid-market.", "B2B content, site", "Unknown", "5", "Could be larger—qualify."),
("creativebhel", "Creative Bhel", "Unknown", "India", "Handmade festive bangles / stacks", "Unknown", "Unknown", "DM (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Handmade stack bangles.", "handmade,bangles,navratri", "Accessory craft SMB.", "Ecommerce, UGC", "Unknown", "7", "Jewellery-adjacent festive accessories."),
("talkwithart_byrach", "Talkwithart_byrach (Resin & Fluid artworks)", "Unknown", "India", "Resin jewellery & gifts", "Unknown", "Unknown", "DM", "No", "None in snippet", "2026 (verify)", "Unknown", "Custom resin pendants.", "resin,custom,rakhi", "DM-led custom orders.", "Ecommerce customizer", "Unknown", "8", "Custom order heavy."),
("jyoti.jewellers.surat", "Jyoti Jewellers Surat", "Surat", "Gujarat", "Gold / diamond mangalsutra retail", "Unknown", "Unknown", "Visit showroom", "No", "None in snippet", "2026 (verify)", "Unknown", "Starbucks-adjacent mall address style.", "mangalsutra,surat", "Retail jeweller reels.", "Hyperlocal ads", "https://www.google.com/maps/search/Adajan+Surat+jewellers", "5", "More showroom-led."),
("aartijewellers.surat", "Aarti Jewellers Surat", "Surat", "Gujarat", "Gold promotions", "Unknown", "Unknown", "Visit store", "No", "None in snippet", "2026 (verify)", "Unknown", "Offer-style reels.", "gold,surat,promo", "Retail marketing on IG.", "Appointment booking", "Unknown", "5", "Retail-heavy."),
("dreams.jewellery2023", "Dreams Jewellery 2023", "Unknown", "India", "One-gram gold plated", "+919099003670", "Unknown", "WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Strict replacement policy text.", "one gram,forming,worldwide shipping", "Policy-heavy SMB.", "Policy pages + chatbot", "Unknown", "8", "Also lists secondary number +9106503944."),
("roshi.collections", "Roshi Collections", "Tamil Nadu", "Tamil Nadu", "One-gram forming / temple sets", "+919092327836", "Unknown", "WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "TN free shipping positioning.", "one gram,forming,temple", "Screenshot order flow.", "WhatsApp automation", "Unknown", "9", "Very strong IG-commerce ops."),
("s.swarnakarandson", "S. Swarnakar & Son", "Kolkata", "West Bengal", "Gold & silver collections", "+918981948452", "Unknown", "Booking line / DM", "No", "None in snippet", "2026 (verify)", "Unknown", "Chetla / Kolkata tags.", "kolkata,silver,gold", "Traditional shop with IG.", "Online catalogue", "https://www.google.com/maps/search/Chetla+jewellery", "6", "May be more established showroom."),
("sujatha_gold_covering_works", "Sujatha Gold Covering Works", "Machilipatnam", "Andhra Pradesh", "Micro gold-plated wholesale", "+917382222208", "Unknown", "WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Multiple lines for bulk COD.", "gold covering,micro plated,wholesale", "Multi-number wholesale desk.", "ERP-light, WhatsApp bot", "https://www.google.com/maps/search/Machilipatnam+jewellery", "8", "Also lists alternate numbers in posts."),
("lucknow_artificial_jewellery_", "Lucknow Artificial Jewellery", "Lucknow", "Uttar Pradesh", "Artificial / one-gram polish", "+918957754721", "Unknown", "WhatsApp booking", "No", "None in snippet", "2026 (verify)", "Unknown", "COD + India shipping claims.", "lucknow,artificial,one gram", "City-named SMB.", "Local + national ads", "https://www.google.com/maps/search/Lucknow+artificial+jewellery", "9", "Very explicit WhatsApp booking."),
("silvershine_jewelery", "Silver Shine Jewellery", "Vadodara", "Gujarat", "925 silver", "+917572962224", "Unknown", "DM + WhatsApp", "No", "None in snippet", "2026 (verify)", "Unknown", "Vadodara tags.", "silver 925,vadodara", "Local silver SMB.", "Local SEO", "https://www.google.com/maps/search/Vadodara+silver+jewellery", "8", "Hallmark claims—verify."),
("_bahawa_creation_", "Bahawa Creation", "Unknown", "Maharashtra", "Maharashtrian pearl / putali jewellery", "+919757289727", "Unknown", "WhatsApp booking", "No", "None in snippet", "2026 (verify)", "Unknown", "15-20 day delivery window stated.", "maharashtrian,pearl,bridal", "Regional bridal craft.", "Preorder ecommerce", "Unknown", "9", "Preorder model = strong CRM."),
("aashus_pearl_creation", "Aashus Pearl Creation", "Unknown", "Maharashtra", "Marathi traditional handmade sets", "Unknown", "Unknown", "DM", "No", "None in snippet", "2026 (verify)", "Unknown", "Gudi Padwa special captions.", "marathi,handmade,choker", "Festival-led SMB.", "Seasonal automation", "Unknown", "8", "DM-first festive drops."),
("krjewellersgoa", "KR Jewellers Goa", "Ponda", "Goa", "Goan patli / wedding gold", "+919511641757", "Unknown", "DM + call", "No", "None in snippet", "2026 (verify)", "Unknown", "Ponda address in reel.", "goa,gold,wedding", "Regional gold jeweller IG.", "Local SEO, WhatsApp", "https://www.google.com/maps/search/Ponda+Goa+jewellers", "6", "Hallmark gold focus—enterprise risk moderate."),
("amita_jewellery", "Amita Jewellery", "Goa", "Goa", "Goan black bead bangles", "Unknown", "Unknown", "DM (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Goan design hashtags.", "goa,black bead,gold", "Regional design niche.", "Storytelling ecommerce", "Unknown", "7", "Niche cultural designs."),
("khushbu_jewellers_tinwari", "Khushbu Jewellers Tinwari (primary 9929595357 network)", "Unknown", "India", "Silver / gold-polish fashion", "+919929595357", "Unknown", "WhatsApp screenshot order", "Unclear", "Posts mention website discount language", "2026 (verify)", "Unknown", "Representative handle for widely reused order number cluster—treat as one ops network.", "silver,screenshot,COD", "Screenshot ordering + COD.", "Fraud controls, WhatsApp CRM", "Unknown", "7", "Multiple satellite pages may share workflows—verify ethically."),
("imitation_jewel_sangeetha_fash", "Imitation Jewel Sangeetha Fash", "Unknown", "India", "Matt bridal hip chains", "Unknown", "Unknown", "DM (verify)", "No", "None in snippet", "2026 (verify)", "Unknown", "Matt hipchain catalogue posts.", "matt,bridal,hipchain", "Catalogue SMB.", "Ecommerce", "Unknown", "7", "Price ranges in captions."),
("sethanijewlleryhouse", "Sethani Jewellery House", "Kolkata", "West Bengal", "Rajasthani / Padmaavat style nath", "Unknown", "Unknown", "DM", "No", "None in snippet", "2026 (verify)", "Unknown", "DM-to-order language.", "nath,rajasthani,bridal", "Niche SKU SMB.", "UGC + DM automation", "https://www.google.com/maps/search/Kolkata+imitation+jewellery", "8", "Kolkata imitation bridal niche."),
("petalsbyswathi", "Petals by Swathi", "Unknown", "India", "Jadau kundan jhumkas (vendor)", "+917013645835", "Unknown", "WhatsApp / DM", "No", "None in snippet", "2026 (verify)", "Unknown", "Featured on South India Jewels network post.", "jadau,kundan,jhumka", "Vendor-style SMB.", "Marketplace + owned site", "Unknown", "7", "Also referenced with shopping portal—verify dependence."),
("nikhiljewelleryhyderabad", "Nikhil Jewellery Hyderabad", "Hyderabad", "Telangana", "916 gold temple pieces", "Unknown", "Unknown", "DM / visit", "No", "None in snippet", "2026 (verify)", "Unknown", "Hyderabad LB Nagar tags.", "916gold,hyderabad,temple", "May be larger gold retailer—qualify.", "Video commerce", "Unknown", "5", "Could be mid/large showroom."),
("poojajewels_", "Pooja Jewels (925 silver)", "Unknown", "India", "925 silver fashion / payal / bracelets", "+917597344552", "Unknown", "WhatsApp + COD (caption)", "No", "None in embed", "2026 (verify)", "~219K followers (embed); verify engagement", "Indexed reels show India-wide COD + WhatsApp ordering line.", "silver 925,COD,whatsapp", "Verified posting account via Instagram embed on sampled reel.", "WhatsApp automation, catalog pages, CRM", "Unknown", "8", "Large follower base—still D2C WhatsApp motion."),
("rj_silver_wala", "RJ Silver Wala (Shree Balaji style silver)", "Unknown", "Rajasthan", "925 silver payal / fashion", "+916350035731", "Unknown", "Screenshot on WhatsApp + COD", "No", "None in embed", "2026 (verify)", "~84K followers (embed)", "Reel caption: screenshot order line + all-India COD language.", "silver,payal,COD", "Verified @rj_silver_wala via Instagram embed.", "WhatsApp flows, COD reconciliation", "Unknown", "8", "Confirm city from bio."),
("shoptikl", "This Is Kinda Lit (Silver)", "Unknown", "India", "Hallmarked silver sets", "+919313872224", "Unknown", "WhatsApp to order", "No", "None in embed", "2026 (verify)", "~91K followers (embed)", "Reel: hallmarked silver + free shipping + WhatsApp order.", "silver,hallmark,whatsapp", "Verified @shoptikl via Instagram embed.", "Ecommerce checkout, Meta catalog", "Unknown", "8", "Premium positioning."),
("silver_palace45", "Silver Palace", "Unknown", "India", "Silver mangalsutra / payal / kids silver", "+919887305357", "Unknown", "WhatsApp order", "No", "None in embed", "2026 (verify)", "~97K followers (embed)", "Post: WhatsApp order + discount language.", "silver,mangalsutra,payal", "Verified @silver_palace45 via Instagram embed.", "WhatsApp automation, ads", "Unknown", "7", "High-volume retail tone."),
("vernika.silver.jewellery", "Vernika Silver (Sri Lakshmi Venkateshwara)", "Bengaluru", "Karnataka", "92.5 silver retail", "+917406810666", "Unknown", "Call / video visit booking", "No", "None in embed", "2026 (verify)", "Unknown", "Chickpet / Avenue Road addresses in reel text.", "silver 925,bangalore,chickpet", "Local silver shop + video-call shopping.", "Local SEO, appointment booking", "https://www.google.com/maps/search/Chickpet+silver+jewellery+Bengaluru", "8", "Retail-heavy but strong digital booking angle."),
("rajputi_jewelery_wholsaler_s.c", "Rajputi Jewellery Wholesaler", "Unknown", "India", "Rajputi / wholesale fashion", "+917877634674", "Unknown", "WhatsApp + group link", "No", "None in snippet", "2026 (verify)", "Unknown", "Reel: WhatsApp me + join group for prices.", "rajputi,wholesale,whatsapp group", "B2B-style community selling.", "Community CRM, catalog bot", "Unknown", "8", "Wholesale compliance messaging."),
("creative_zeal_", "CreativeZeal by Sapna Wadhwani", "Chennai", "Tamil Nadu", "German silver / oxidised earrings", "Unknown", "Unknown", "DM to place order", "No", "None in embed", "2026 (verify)", "~164K followers (embed)", "Reel explicitly: DM to place an order + Chennai tags.", "oxidised,german silver,chennai", "Verified @creative_zeal_ via Instagram embed.", "DM automation, Shopify-lite", "https://www.google.com/maps/search/Chennai+oxidised+jewellery", "8", "Mid-size creator-commerce."),
("sri_sai_silvers", "Sri Sai Silvers by Priya", "Unknown", "India", "Handmade 92.5 colour-stone silver", "Unknown", "Unknown", "DM / call (verify)", "No", "None confirmed", "2026 (verify)", "Unknown", "Indexed posts show handmade 92.5 bridal-heavy SKUs.", "92.5 silver,handmade,bridal", "Strong handmade catalogue voice.", "Ecommerce, product customizer", "Unknown", "7", "Confirm WhatsApp in bio."),
("oxidized_radhe_krishna", "Radhe Krishna Oxidized", "Unknown", "India", "Oxidised / imitation reels", "Unknown", "Unknown", "DM (verify)", "No", "None in embed", "2026 (verify)", "~76K followers (embed)", "Hashtag-forward oxidised catalogue account.", "oxidised,jhumka,imitation", "Verified @oxidized_radhe_krishna via Instagram embed.", "Reels ads, WhatsApp catalog", "Unknown", "7", "Add WhatsApp from bio when confirmed."),
("dixitkandre", "Dixit Kandre (1 gram outlet)", "Hyderabad", "Telangana", "One-gram gold plated / factory outlet", "+919177609018", "Unknown", "Call / WhatsApp (multi-line)", "No", "None confirmed", "2026 (verify)", "~154K followers (embed)", "Begum Bazar / Lee Chee Pearls style captions in search.", "one gram,hyderabad,begum bazar", "High-volume wholesale-retail hybrid.", "POS, B2B portal", "https://www.google.com/maps/search/Begum+Bazar+Hyderabad+jewellery", "6", "Larger outlet vibe—qualify before SMB pitch."),
("jewelz_by_aayushi", "Jewelz by Aayushi", "Unknown", "India", "Fashion / dream jewel store", "Unknown", "Unknown", "DM for order", "No", "None in embed", "2026 (verify)", "~17K followers (embed)", "Sample post text: Dm for order.", "dm order,fashion,silver mix", "Verified @jewelz_by_aayushi via Instagram embed.", "Instagram shopping, lightweight checkout", "Unknown", "9", "Strong DM-native SMB."),
("_virajewels_", "Vira Jewels by Aayushi Gindani", "Unknown", "India", "Fashion rings / adjustable styles", "Unknown", "Unknown", "DM (verify)", "No", "None in embed", "2026 (verify)", "~160K followers (embed)", "Product-forward reels; bow rings sample.", "rings,fashion,fyp", "Verified @_virajewels_ via Instagram embed.", "UGC, influencer collabs", "Unknown", "7", "Larger following—still creator-led."),
("nr_silver_jewels", "Nirvi Reddy Silver Jewels", "Unknown", "India", "925 / Swarovski-style silver", "Unknown", "Unknown", "WhatsApp screenshots (verify number in bio)", "No", "None confirmed", "2026 (verify)", "Unknown", "Indexed reel mentions WhatsApp screenshot flow for live sale.", "silver,live sale,screenshot", "Ops-heavy conversational commerce.", "WhatsApp CRM, live-sale tooling", "Unknown", "7", "Re-verify WhatsApp digits from latest reel."),
("sstchandighar", "S.S.T Chandighar (Silver payal)", "Unknown", "India", "Silver anklets / payal wholesale-retail", "Unknown", "Unknown", "DM / follow for booking (verify)", "No", "None in embed", "2026 (verify)", "~8K followers (embed)", "Reel: silver payal weight slabs + booking CTA.", "silver payal,wholesale,smallbusiness", "Verified @sstchandighar via Instagram embed.", "Inventory + WhatsApp SKU bot", "Unknown", "9", "Compact SMB scale."),
("silverjewelleryy0", "Fusi Fine Silver Jewellery (silverjewelleryy0)", "Unknown", "India", "Silver payal / fashion silver", "Unknown", "Unknown", "DM (verify)", "No", "None in embed", "2026 (verify)", "~103K followers (embed)", "Reel branding as Fusi fine silver in search title.", "silver,payal,reels", "Verified @silverjewelleryy0 via Instagram embed.", "Branding unification, ecommerce", "Unknown", "7", "Handle vs display name mismatch—confirm."),
("wholesalepearlsjewells.onkar", "Pearls & Jewells Design Studio (Onkar)", "Unknown", "India", "Fashion / wholesale custom manufacturing", "+919996698633", "Unknown", "DM for catalog", "No", "None in snippet", "2026 (verify)", "Unknown", "Heavy B2B SEO-style caption + India contact line.", "wholesale,custom,pearls", "Manufacturer-style Instagram funnel.", "B2B portal, lead forms", "Unknown", "6", "More manufacturer than retailer—pitch ERP-lite."),
("pinakijewellers", "Pinaki Jewellers", "Hyderabad", "Telangana", "22k gold nakshi / bridal", "+919000005048", "Unknown", "DM + WhatsApp + call", "No", "None confirmed standalone site in sampled post", "2026 (verify)", "~40K followers (embed)", "Caption: DM/call/WhatsApp for details.", "gold,hyderabad,nakshi", "Verified @pinakijewellers via Instagram embed.", "CRM, appointment scheduling", "https://www.google.com/maps/search/Hyderabad+gold+jewellers", "7", "Gold-forward; compliance-sensitive outreach."),
("nawlakha_jewellers", "Nawlakha Jewellers", "Rajnandgaon", "Chhattisgarh", "Hallmark gold / silver / diamond mix", "+919752190903", "Unknown", "Online order + call", "No", "None in snippet", "2026 (verify)", "Unknown", "Local CG address + online order language.", "gold,hallmark,raj nandgaon", "Tier-2/3 retailer modernizing.", "Online booking, WhatsApp bot", "https://www.google.com/maps/search/Rajnandgaon+jewellers", "6", "Showroom + online hybrid."),
("varudijewellers", "Varudi Jewellers", "Surat", "Gujarat", "Certified gold retail / DM instant buy", "Unknown", "Unknown", "DM instant buy (caption)", "No", "None confirmed", "2026 (verify)", "Unknown", "Reel copy: Surat shop + DM instant buy.", "surat,gold,dm", "DM-first jewellery purchase motion.", "Payments + DM automation", "https://www.google.com/maps/search/Surat+jewellers", "7", "Verify payment compliance."),
("yash_ornaments", "Yash Ornaments", "New Delhi", "Delhi", "1gm gold rings / Chandni Chowk", "Unknown", "Unknown", "DM / visit store (verify)", "No", "None in embed", "2026 (verify)", "~92K followers (embed)", "Caption lists Chandni Chowk address; 1gm ring promo.", "gold ring,chandni chowk,1gm", "Verified @yash_ornaments via Instagram embed.", "Local performance ads, maps SEO", "https://www.google.com/maps/search/Chandni+Chowk+gold+jewellery", "7", "Delhi dense market; digital uplift opportunity."),
("silver_jewellery_indian", "Indian Silver Jewellery 92.5", "Unknown", "India", "925 marketing catalogue", "Unknown", "Unknown", "Shop now CTA (verify DM/WhatsApp)", "Unclear", "May use external checkout—verify", "2026 (verify)", "~7K followers (embed)", "Marketing-heavy 925 positioning in embed caption.", "925silver,luxury,catalog", "Verified @silver_jewellery_indian via Instagram embed.", "Owned commerce + CRM", "Unknown", "7", "Confirm whether sales are IG-DM or web-only."),
("silver.attractions", "Silver Attractions", "Unknown", "India", "92.5 rose-gold solitaire rings etc.", "Unknown", "Unknown", "Order yours now CTA (verify)", "Unclear", "None in embed", "2026 (verify)", "~100K followers (embed)", "Product-forward 92.5 silver reel copy.", "silver 925,solitaire,shipping", "Verified @silver.attractions via Instagram embed.", "Shopify, shipping automation", "Unknown", "7", "Mid/large D2C silver."),
("krishnajewelsraj", "Krishna Jewels Raj", "Beawar", "Rajasthan", "Antique rajwadi kada / gold-look", "+917300001066", "Unknown", "DM + WhatsApp + call", "No", "None confirmed", "2026 (verify)", "Unknown", "Search snippet: antique kada + WhatsApp line.", "antique,kada,rajwadi,beawar", "Heritage design SMB with direct lines.", "WhatsApp catalog, local SEO", "https://www.google.com/maps/search/Beawar+jewellery", "8", "Re-verify post still live (404 on sample embed)."),
("kadaitheru_official", "Kadai Theru (jewellery features)", "Chennai", "Tamil Nadu", "Wedding gold jhumkas / features", "Unknown", "Unknown", "Referral to tagged stores (verify)", "No", "None confirmed", "2026 (verify)", "Unknown", "Aggregator-style reels tagging Chennai jewellers.", "jimikki,gold,wedding", "Influencer/aggregator model—cross-sell tooling.", "Affiliate CRM, content studio", "Unknown", "5", "Not a pure seller—qualify relationship."),
("mahalaxmiadyar", "Mahalaxmi Gold & Diamond Merchants (Adyar)", "Chennai", "Tamil Nadu", "Wedding gold jimikki / lightweight sets", "+919283916916", "Unknown", "Call / video shopping", "No", "None confirmed", "2026 (verify)", "Unknown", "Featured in Kadai Theru reel with order-online call line.", "gold jimikki,chennai,bridal", "Chennai bridal gold with video-call shopping.", "Video commerce stack", "https://www.google.com/maps/search/Adyar+Chennai+jewellers", "6", "Established retailer—digital upgrade angle."),
]

def _digits_last10(s: str) -> str | None:
    if not s or str(s).lower() == "unknown":
        return None
    d = re.sub(r"\D", "", str(s))
    if len(d) >= 10:
        return d[-10:]
    return None


# Deduplicate by Instagram handle and Indian mobile last-10 (same WhatsApp = one lead).
seen_handles: set[str] = set()
seen_phones: set[str] = set()
unique_rows: list[tuple[str, ...]] = []
for row in LEADS:
    h = row[0].lower()
    if h in seen_handles:
        continue
    ph = _digits_last10(row[5])
    if ph and ph in seen_phones:
        continue
    seen_handles.add(h)
    if ph:
        seen_phones.add(ph)
    unique_rows.append(row)

# If under 100, fail loudly in CI context; we expect exactly 100 curated rows after edits.
assert len(unique_rows) == 100, len(unique_rows)

out = Path("/agent/india_jewellery_instagram_leads.txt")
lines: list[str] = []
lines.append("INDIA JEWELLERY – INSTAGRAM / WHATSAPP-FIRST LEADS")
lines.append("Generated: 2026-05-22")
lines.append("Source: public web search snippets (verify every field on Instagram before outreach).")
lines.append("Deduplication: unique Instagram handles; duplicate Indian mobile numbers (last 10 digits) skipped; duplicate WhatsApp clusters noted in rows where applicable.")
lines.append("")

for i, row in enumerate(unique_rows, start=1):
    (
        handle,
        biz,
        city,
        state,
        btype,
        wa,
        email,
        ordering,
        web_yn,
        web_url,
        recent,
        eng,
        bio,
        kw,
        reason,
        services,
        maps,
        score,
        notes,
    ) = row
    lines.append("=" * 50)
    lines.append(f"LEAD #{i}")
    lines.append("=" * 50)
    lines.append(f"Business Name: {biz}")
    lines.append(f"Instagram Handle: @{handle}")
    lines.append(f"Instagram URL: https://www.instagram.com/{handle}/")
    if "followers (embed)" in eng.lower():
        parts = eng.split(";", 1)
        fc = parts[0].strip() + " — verify current count in Instagram app"
        rest = parts[1].strip() if len(parts) > 1 else ""
        if rest.lower() in {"verify engagement", "engagement varies"}:
            eng_out = "Unknown (use Instagram Insights after access)"
        elif rest:
            eng_out = rest
        else:
            eng_out = "Unknown (use Instagram Insights after access)"
    else:
        fc = "Not available from indexed search snippets (verify in-app)"
        eng_out = eng
    lines.append(f"Followers Count: {fc}")
    lines.append(f"City: {city}")
    lines.append(f"State: {state}")
    lines.append(f"Business Type: {btype}")
    lines.append(f"WhatsApp Number: {wa}")
    lines.append(f"Email: {email}")
    lines.append(f"Ordering Method: {ordering}")
    lines.append(f"Website Present: {web_yn}")
    lines.append(f"Website URL: {web_url}")
    lines.append(f"Recent Activity Date: {recent}")
    lines.append(f"Average Engagement: {eng_out}")
    lines.append(f"Bio Text: {bio}")
    lines.append(f"Keywords: {kw}")
    lines.append(f"Reason Qualified: {reason}")
    lines.append(f"Potential Services Needed: {services}")
    lines.append(f"Google Maps Link: {maps}")
    lines.append(f"Lead Quality Score: {score}")
    lines.append(f"Notes: {notes}")
    lines.append("")

out.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {out} with {len(unique_rows)} leads")
