#!/usr/bin/env python3
"""Generate india_jewellery_instagram_leads.txt from curated discovery metadata."""

from __future__ import annotations

import textwrap
from pathlib import Path

# Tuple: handle, business_name, city, state, business_type, whatsapp, email,
# ordering_method, website_yesno, website_url, recent_activity, avg_engagement,
# bio_text, keywords, reason, services, maps_link, score, notes
RAW: list[tuple[str, ...]] = [
    ("thoselittleblinggss", "Those Little Bling", "Unknown", "Unknown", "Oxidised / moissanite fashion jewellery", "", "Not listed publicly", "DM to order; free shipping on posts", "No", "", "Active reels (2025)", "Not indexed in public search", "Posts advertise oxidised/moissanite sets with DM-to-order and India shipping hashtags.", "dm to order, oxidised, moissanite, jhumka, free shipping", "Public posts explicitly say DM to order for jewellery SKUs.", "Website, WhatsApp automation, Instagram shop, CRM", "Not listed", 8, "Discovery via public web index; confirm follower count in-app."),
    ("chudiwale_", "Chudiwale Fashion Jewellery", "Unknown", "Gujarat", "Bridal bangles / velvet bangles", "+917972380643", "Not listed publicly", "WhatsApp booking for customised bangle sets", "No", "", "Reels/posts promoting bookings", "Not indexed in public search", "Caption invites WhatsApp for customised bridal bangle sets.", "custom bangles, bridal, velvet bangles, WhatsApp", "Strong WhatsApp-led fulfilment for customised bridal jewellery.", "WhatsApp automation, ecommerce, CRM", "Not listed", 8, "City inferred from common Surat/India bridal bangle niche; verify."),
    ("_jewellery_palace_bjs", "Jewellery Palace (BJS)", "Unknown", "Rajasthan", "Rajputi / silver-plated fashion", "+918440038551", "Not listed publicly", "WhatsApp order on posted codes", "No", "", "Posts reference WhatsApp ordering", "Not indexed in public search", "Post captions include WhatsApp ordering instructions.", "WhatsApp order, nath, silver jewellery", "Clear WhatsApp order path without a dedicated brand site in indexed snippets.", "WhatsApp automation, lightweight catalog site", "Not listed", 7, "Handle suggests Bikaner Jodhpur style inventory; verify location."),
    ("indukurisjewel", "Jewel Indukuri's", "Hyderabad", "Telangana", "Lab-grown diamond / custom pendants", "+916302720676", "Not listed publicly", "WhatsApp for details/customisation", "No", "", "Reels mention customisation", "Not indexed in public search", "Caption: customise pendant/chain; WhatsApp for details.", "lab grown diamond, custom, WhatsApp", "Custom orders + WhatsApp-led sales motion.", "Ecommerce, CRM, AI chatbot for specs", "Not listed", 7, "Treat as SMB studio; validate corporate site separately."),
    ("lakshmi_creations_9", "Lakshmi Creations (Imitation)", "Unknown", "Tamil Nadu", "Imitation / wholesale jhumkas", "+919849567353", "Not listed publicly", "WhatsApp for wholesale and catalogue", "No", "", "Posts mention WhatsApp wholesale", "Not indexed in public search", "Caption references imitation jewellery wholesale via WhatsApp.", "imitation jewellery, wholesale, jhumka, WhatsApp", "Wholesale imitation seller using WhatsApp as primary order channel.", "B2B portal, WhatsApp catalogue automation", "Not listed", 8, "Exact city not in indexed caption; likely South India wholesale hub."),
    ("oxidised_jewellery_wholesaler", "Oxidised Jewellery Wholesaler", "Unknown", "India", "Oxidised wholesale", "", "Not listed publicly", "DM / WhatsApp typical for wholesaler posts", "No", "", "Indexed post present", "Not indexed in public search", "Username signals oxidised wholesale niche.", "oxidised, wholesale, german silver", "Wholesale-first oxidised niche fits Instagram distribution.", "Wholesale CRM, catalog site, WA broadcast compliance tooling", "Not listed", 6, "Limited public contact in indexed snippet; verify bio."),
    ("templejewelleryhub_bypriya", "Temple Jewellery Hub by Priya", "Unknown", "India", "Temple / Nagas jewellery", "", "Not listed publicly", "DM typical for priced temple sets", "No", "", "Posts show priced temple sets", "Not indexed in public search", "Posts price temple/Nagas style sets with shipping notes.", "temple jewellery, nagas mala, bridal", "Temple jewellery niche with Instagram-first merchandising.", "Ecommerce, payments, logistics pages", "Not listed", 7, "Confirm WhatsApp from bio; not visible in indexed search text."),
    ("_virajewels_", "Vira Jewels by Aayushi Gindani", "Unknown", "India", "Fashion / demi-fine jewellery", "", "Not listed publicly", "Comment/DM for product links", "No", "", "Reels prompt engagement", "Not indexed in public search", "Reel asks audience to comment for product links.", "comment for links, DM, fashion jewellery", "Comment-to-DM workflow indicates Instagram-native selling.", "Instagram automation, link-in-bio optimisation", "Not listed", 7, "WhatsApp not shown in indexed snippet."),
    ("aakanksha_jewellery", "Aakanksha Jewellery", "Unknown", "Maharashtra", "Maharashtrian traditional / pearl sets", "", "Not listed publicly", "DM to purchase", "No", "", "Post invites DM to own piece", "Not indexed in public search", "Caption: DM to own Chinchpeti-style necklace.", "chinchpeti, DM order, traditional", "DM-first ordering for regional bridal styles.", "WhatsApp follow-up, small catalog site", "Not listed", 7, "City inferred from Maharashtrian bridal niche; verify."),
    ("silver_store_chennai", "Silver Store Chennai", "Chennai", "Tamil Nadu", "925 silver idols & silver jewellery", "+918181871717", "Not listed publicly", "WhatsApp orders; Chennai pickup context", "No", "", "Posts mention Valasaravakkam", "Not indexed in public search", "Caption lists WhatsApp and Chennai locality.", "silver idols, Chennai, WhatsApp", "Geo-tagged Chennai seller using WhatsApp for orders.", "Local SEO site, WhatsApp click-to-chat, CRM", "https://maps.google.com/?q=Valasaravakkam%2C%20Chennai", 8, "Map query approximate to caption location."),
    ("vernika.silver.jewellery", "Vernika Silver (Raja Market)", "Bengaluru", "Karnataka", "92.5 silver retail", "+917406810666", "Not listed publicly", "Call / video call bookings", "No", "", "Reels mention Raja Market shop", "Not indexed in public search", "Caption lists Chikpete/Raja Market addresses and phone.", "925 silver, Bangalore, video call", "Phone-first bookings for silver SKUs.", "Appointment booking, ecommerce, inventory POS", "https://maps.google.com/?q=Raja%20Market%20Bangalore", 7, "Physical shop plus Instagram; still SMB motion."),
    ("silver_palace45", "Silver Palace 45", "Unknown", "India", "Silver fashion jewellery", "", "Not listed publicly", "DM / comment typical", "No", "", "Indexed engagement snippet", "Not indexed in public search", "Appears in indexed Instagram engagement surfaces.", "silver, fashion jewellery", "Instagram-native silver catalogue pattern.", "Catalog automation, WhatsApp", "Not listed", 6, "Limited indexed caption data; verify bio."),
    ("trend_jewelryys", "Trend Jewelryys", "Unknown", "India", "Trend-led costume jewellery", "", "Not listed publicly", "DM ordering implied", "No", "", "Shows in indexed comment threads", "Not indexed in public search", "Handle signals trend-led costume inventory.", "trending jewellery, reels", "Reels-first merchandising without indexed standalone site.", "Reels ads, UGC, WhatsApp", "Not listed", 6, "Sparse public metadata; validate."),
    ("wear_nd_shine_jewelry", "Wear and Shine Jewelry", "Unknown", "India", "Fashion jewellery", "", "Not listed publicly", "DM typical", "No", "", "Indexed post surface", "Not indexed in public search", "Appears on indexed Instagram surfaces.", "fashion jewellery, reels", "SMB-style handle; Instagram-led discovery.", "WhatsApp automation, catalog", "Not listed", 6, "Verify contact channels on profile."),
    ("rajputii_jewellery_", "Rajputii Jewellery", "Unknown", "Rajasthan", "Rajputi fashion jewellery", "", "Not listed publicly", "DM / WhatsApp common in niche", "No", "", "Indexed comments show activity", "Not indexed in public search", "Rajputi-themed jewellery content.", "rajputi, traditional", "Niche ethnic jewellery with Instagram-first distribution.", "Regional ecommerce, WhatsApp", "Not listed", 7, "Location inferred from style niche."),
    ("nikhiljewelleryhyderabad", "Nikhil and Brothers Jewellery", "Hyderabad", "Telangana", "916 gold designs", "", "Not listed publicly", "DM / store visit typical for gold SMB", "No", "", "Reels tagged Hyderabad/LB Nagar", "Not indexed in public search", "Hyderabad gold jeweller posting new designs.", "916 gold, Hyderabad, locket", "Strong regional gold SMB with Instagram catalogue.", "Online booking, CRM, video consult", "https://maps.google.com/?q=LB%20Nagar%20Hyderabad", 6, "Enterprise-scale risk; still single-region family jeweller pattern—verify."),
    ("jewellery_rajasthan", "Rajputi Jewellery (Rajasthan)", "Jaipur", "Rajasthan", "Rajputi earrings/pendants", "", "Not listed publicly", "DM typical", "No", "", "Posts in indexed search", "Not indexed in public search", "Rajasthan jewellery aesthetic posts.", "rajputi, earrings", "Regional costume jewellery merchandised on IG.", "WhatsApp, microsite", "https://maps.google.com/?q=Jaipur%20jewellery%20market", 6, "Exact shop not confirmed from snippet."),
    ("samashajewellery", "SamAsha Jewellery", "Unknown", "India", "German silver / oxidised earrings", "+919711107695", "Not listed publicly", "DM or WhatsApp; unboxing policy stated", "No", "", "Reel shows DM/WhatsApp order line", "Not indexed in public search", "Caption: DM or WhatsApp with number; returns policy notes.", "oxidised, german silver, jhumka, COD policy", "Dual DM+WhatsApp ordering with SMB policies.", "WhatsApp automation, returns workflow", "Not listed", 8, "Good fit for automation due to policy text in captions."),
    ("jewelsofkarnataka", "Jewels of Karnataka", "Bengaluru", "Karnataka", "One-gram gold-plated fashion", "+919740234813", "Not listed publicly", "WhatsApp for JK collection orders", "No", "", "Indexed WhatsApp order posts", "Not indexed in public search", "Caption references JK collection and WhatsApp.", "one gram gold, fashion jewellery, Karnataka", "WhatsApp-first ordering for lightweight fashion gold.", "Catalog site, UPI automation", "Not listed", 8, "Strong WhatsApp screenshot order pattern."),
    ("varudijewellers", "Varudi Jeweller (Surat)", "Surat", "Gujarat", "Gold retail (BIS mentioned in snippet)", "", "Not listed publicly", "DM instant buy messaging", "No", "", "Reel: DM for purchase", "Not indexed in public search", "Surat jeweller promoting DM-led buying.", "gold, Surat, DM", "DM-led gold SMB (verify scale).", "Compliance content, ecommerce", "https://maps.google.com/?q=Surat%20jewellers", 6, "May be mid-size; validate not large chain."),
    ("gn._jewellery", "GN Artificial Jewellery (Sirhind)", "Sirhind", "Punjab", "Artificial / gold-look sets", "+919517222272", "Not listed publicly", "WhatsApp order; GPAY/Bank transfer", "No", "", "Reels show WhatsApp order line", "Not indexed in public search", "Caption: WhatsApp order with UPI options.", "artificial jewellery, bridal set, Sirhind", "Clear WhatsApp + UPI stack for SMB.", "WhatsApp payments receipts, ecommerce", "Not listed", 8, "Good WhatsApp-led artificial jewellery lead."),
    ("goharjewelsofficial", "Gohar Jewels Official", "Unknown", "India", "Resin / flower jhumkas", "", "Not listed publicly", "DM typical for custom resin", "No", "", "Posts about custom resin jhumkas", "Not indexed in public search", "Handmade resin jhumkas with dried flowers.", "resin, handmade, jhumka", "Custom handmade niche fits DM selling.", "Shopify-lite, DM CRM", "Not listed", 7, "Email/phone not in indexed snippet; check bio."),
    ("floralartbysrishti", "Floral Art by Srishti", "Unknown", "India", "Floral jewellery / wedding accessories", "+919833989613", "Not listed publicly", "DM + WhatsApp; pan-India shipping", "No", "", "Wedding floral sets promoted", "Not indexed in public search", "Caption: DM and WhatsApp with shipping pan India.", "floral jewellery, wedding, custom", "Dual-channel wedding accessories SMB.", "Wedding CRM, WhatsApp templates", "Not listed", 8, "Strong custom wedding upsell potential."),
    ("aashus_pearl_creation", "Aashu's Pearl Creation", "Unknown", "Maharashtra", "Handmade pearl Maharashtrian sets", "", "Not listed publicly", "DM for order", "No", "", "Reels mention handmade + DM", "Not indexed in public search", "Caption: DM for order; handmade pearl pieces.", "pearl, marathi bride, DM", "DM-first handmade regional jewellery.", "WhatsApp, ecommerce", "Not listed", 7, "Phone not in indexed snippet."),
    ("chettinad_creations", "Chettinad Creations", "Unknown", "Tamil Nadu", "Imitation temple/statement necklaces", "", "Not listed publicly", "DM for price/order", "No", "", "Indexed comment thread shows pricing replies", "Not indexed in public search", "Posts show priced imitation necklaces.", "temple necklace, imitation, DM", "Comment/DM price discovery pattern.", "Instagram inbox automation", "Not listed", 7, "Chettinad naming suggests TN; verify."),
    ("finds_reviews", "Finds Reviews (Meesho curator)", "Unknown", "India", "Affiliate / Meesho jewellery finds", "", "Not listed publicly", "Comment 'Link' for DM links", "No", "", "Reels drive comment-to-DM", "Not indexed in public search", "Caption: comment for Meesho kundan links.", "Meesho, affiliate, DM links", "Instagram-native affiliate motion (not manufacturer).", "Affiliate tooling, compliance", "Not listed", 5, "Lower score: affiliate vs brand; still IG-commerce workflow."),
    ("poddarjewels", "Poddar Jewels", "Unknown", "India", "Kundan / artificial bridal", "+919899134124", "Not listed publicly", "WhatsApp wholesale/retail enquiries", "No", "", "Posts invite WhatsApp for kundan sets", "Not indexed in public search", "Caption: WhatsApp for wholesale/retail on kundan sets.", "kundan, polki, wholesale", "Explicit WhatsApp enquiry line for bridal SKUs.", "B2B portal, CRM", "Not listed", 8, "Validate MOQ and fulfilment model."),
    ("lucknow_artificial_jewellery_", "Lucknow Artificial Jewellery", "Lucknow", "Uttar Pradesh", "One-gram gold polish fashion", "+918957754721", "Not listed publicly", "WhatsApp booking; COD mentioned", "No", "", "Reels mention COD India shipping", "Not indexed in public search", "Caption: COD available; booking number listed.", "COD, artificial jewellery, Lucknow", "COD + WhatsApp is classic SMB stack needing automation.", "COD reconciliation, WhatsApp flows", "https://maps.google.com/?q=Lucknow", 8, "City explicit in handle."),
    ("banjara_jewellery_om", "Banjara Jewellery OM", "Unknown", "India", "Banjara / ethnic costume jewellery", "", "Not listed publicly", "DM typical", "No", "", "Festive posts", "Not indexed in public search", "Banjara ethnic jewellery content.", "banjara, ethnic, jewellery", "Niche ethnic SMB merchandising.", "WhatsApp, reels ads", "Not listed", 6, "Sparse indexed contact data."),
    ("rajputi_jwellery_ombanna_7773", "Om Banna Rajputi Jewellery", "Bhilwara", "Rajasthan", "Rajputi wholesale jewellery", "+918239382159", "Not listed publicly", "WhatsApp + WhatsApp groups (per third-party index)", "No", "", "Third-party index shows high posting volume", "Not indexed in public search", "Wholesale Rajputi shop notes + WhatsApp community links in third-party profile mirrors.", "rajputi, wholesale, Bhilwara", "Wholesale + WhatsApp community selling pattern.", "B2B ordering portal, WA group moderation tools", "https://maps.google.com/?q=Bhilwara%20jewellery%20market", 7, "Second number +919462695159 also referenced in some indexes; verify active."),
    ("aaras_terracotta", "Aaras Terracotta Jewellery", "Chennai", "Tamil Nadu", "Terracotta artisan jewellery", "+919940438577", "Not listed publicly", "DM to order (number in caption)", "No", "", "Custom orders referenced", "Not indexed in public search", "Government-certified artisan; DM to order with phone.", "terracotta, customised, Chennai", "Artisan DM + phone hybrid.", "Ecommerce, artist site", "Not listed", 8, "Phone taken from indexed caption text."),
    ("sruthiterracottacreations", "Sruthi Terracotta Creations", "Bengaluru", "Karnataka", "Terracotta / heavy sets", "+919036384234", "Not listed publicly", "DM / wa.me style contact in caption", "No", "", "Bangalore fashion tags", "Not indexed in public search", "Caption references DM/wa.me contact line.", "terracotta, customised, Bangalore", "wa.me pattern indicates WhatsApp-first.", "WhatsApp deep links, catalog", "Not listed", 8, "Confirm wa.me formatting in latest posts."),
    ("elegant_fashion6095", "Elegant Fashion by Rupika", "Unknown", "India", "Terracotta earrings", "+919087319846", "Not listed publicly", "DM or WhatsApp", "No", "", "Custom colours noted", "Not indexed in public search", "Caption: DM @elegant_fashion6095 or WhatsApp.", "terracotta, customised earrings", "Dual DM/WhatsApp for handmade SKUs.", "WhatsApp automation", "Not listed", 7, "Self-referential DM handle matches account."),
    ("lakshmijewells", "Lakshmi Jewells (Wholesale)", "Unknown", "India", "South Indian bridal imitation", "+919390483697", "Not listed publicly", "WhatsApp order & enquiry", "No", "", "Reels show order line", "Not indexed in public search", "Caption: order & enquiry via WhatsApp; no COD policy text.", "black beads, choker, wholesale", "Wholesale-style policies posted on IG.", "B2B portal, CRM", "Not listed", 7, "Validate manufacturer vs reseller."),
    ("kpr_jewellery", "KPR Jewellery", "Unknown", "Tamil Nadu", "Gold-plated / South Indian styles", "", "Not listed publicly", "DM / WhatsApp typical", "No", "", "Indexed Instagram surface", "Not indexed in public search", "Appears on indexed jewellery threads.", "south indian, jewellery", "Regional SMB pattern.", "WhatsApp", "Not listed", 6, "Sparse indexed metadata."),
    ("_amethyst__jewelz", "Amethyst Jewelz", "Unknown", "India", "Fashion / stone jewellery", "", "Not listed publicly", "DM typical", "No", "", "Indexed engagement", "Not indexed in public search", "Handle signals semi-precious fashion niche.", "amethyst, fashion jewellery", "SMB merchandising on IG.", "Shopify, CRM", "Not listed", 6, "Verify stock model."),
    ("rajputi_jewelery_wholsaler_s.c", "Rajputi Jewellery Wholesaler S.C.", "Jodhpur", "Rajasthan", "Rajputi wholesale sets", "+917877634674", "Not listed publicly", "WhatsApp + group link invites", "No", "", "Wholesale reels", "Not indexed in public search", "Caption: WhatsApp me + join group link.", "rajputi, wholesale, group", "WhatsApp community distribution model.", "Group automation, catalog", "https://maps.google.com/?q=Jodhpur%20jewellery", 7, "Group selling increases compliance needs."),
    ("sai_jewellers_rajat_ujjain", "Sai Jewellers Rajat (Ujjain)", "Ujjain", "Madhya Pradesh", "Gold-plated short necklaces", "+917024274632", "Not listed publicly", "DM / WhatsApp for gold-plated SKUs", "No", "", "Comment shows MP/Ujjain context", "Not indexed in public search", "Caption references WhatsApp for DM-only orders.", "gold plated, Ujjain, WhatsApp", "Geo-tagged SMB with WhatsApp-led buying.", "WhatsApp automation, UPI receipts", "https://maps.google.com/?q=Ujjain%20jewellery", 8, "Strong DM+WhatsApp motion in indexed thread."),
    ("mohabygeetanjali", "Moha by Geetanjali", "Thane", "Maharashtra", "925 silver designer", "+919930898047", "hello@mohabygeetanjali.com (brand site)", "WhatsApp / studio visits; Shopify-like brand site exists", "Yes", "https://mohabygeetanjali.com/", "Brand posts + WhatsApp", "Not indexed in public search", "Designer silver brand with studio in Thane; WhatsApp on site/posts.", "925 silver, designer, Thane", "Has website but still heavy WhatsApp/studio motion—useful for automation upsell.", "WhatsApp CRM, reviews, ads", "https://maps.google.com/?q=Ghodbunder%20Road%20Thane", 5, "Lower 'no-website' score due to mohabygeetanjali.com presence."),
    ("keka.lifestyle", "Keka Lifestyle by Anjaly", "Unknown", "India", "Brass / jadau-style jhumkas", "", "Not listed publicly", "DM / comment with product picture", "No", "", "Post lays out DM order rules", "Not indexed in public search", "Caption: DM to order; bank/GPay; shipping rules.", "DM order, brass jadau, policies", "Very explicit DM commerce policy text.", "Policy pages, checkout, CRM", "Not listed", 9, "Excellent automation candidate due to detailed policies in-caption."),
    ("pukhraj.jewellers1", "Pukhraj Jewellers", "Ahmedabad", "Gujarat", "Antique 22KT gold rings", "+919409151772", "Not listed publicly", "DM + WhatsApp/call", "No", "", "Posts mention Satellite Ahmedabad address", "Not indexed in public search", "Caption: DM order + WhatsApp/call; hallmark emphasis.", "antique gold, customised, Ahmedabad", "Custom gold SMB with DM + phone.", "Appointment booking, CRM", "https://maps.google.com/?q=Satellite%20Ahmedabad%20Vaibhav%20Tower", 6, "Has physical showroom; still DM-led online intake."),
    ("krjewellersgoa", "KR Jewellers Goa", "Ponda", "Goa", "Goan patli / wedding gold", "+919511641757", "Not listed publicly", "DM for order + phone", "No", "", "Reels show Ponda address", "Not indexed in public search", "Caption: DM for order; phone listed; Goan patli niche.", "Goan patli, wedding gold, Goa", "Regional wedding gold with DM ordering.", "Local SEO, WhatsApp", "https://maps.google.com/?q=Ponda%20Goa%20jewellers", 7, "Gold SMB; verify hallmark workflows."),
    ("nagabeadsjewellery", "Naga Beads Jewellery", "Mokokchung", "Nagaland", "Tribal beads / brass jewellery", "", "Not listed publicly", "DM typical for artisan posts", "No", "", "Educational long captions", "Not indexed in public search", "Posts focus on Naga tribal jewellery storytelling.", "tribal, beads, Nagaland", "Cultural artisan brand; likely DM sales.", "Ecommerce, storytelling site", "https://maps.google.com/?q=Mokokchung", 7, "Phone not in indexed snippet."),
    ("nagalandbuyorsell", "Nagaland Buy or Sell", "Dimapur", "Nagaland", "Classifieds (incl. jewellery)", "+917005834158", "Not listed publicly", "WhatsApp contact on listings", "No", "", "Marketplace-style posts", "Not indexed in public search", "Listings include jewellery with phone contact.", "classifieds, traditional clothes, jewellery", "Marketplace SMB; jewellery appears in listings.", "Listing automation, trust & safety", "https://maps.google.com/?q=Dimapur", 5, "Not a pure jeweller; included for regional discovery."),
    ("mahavirimitationjewelle", "Mahavir Imitation Jewellery", "Unknown", "India", "Imitation bangles wholesale/retail", "+918320499102", "Not listed publicly", "Call / WhatsApp for designs", "No", "", "Navratri stock posts", "Not indexed in public search", "Caption: call for details & designs.", "imitation, oxidised bangles, wholesale", "Call-first imitation wholesaler using IG catalogue.", "IVR, WhatsApp catalog", "Not listed", 7, "Exact city not in indexed caption."),
    ("cenorajewels", "Cenora Jewels", "Unknown", "India", "Fashion jewellery promos", "+917021923226", "Not listed publicly", "DM / WhatsApp buy-1-get-1 style promos", "No", "", "Indexed promo post", "Not indexed in public search", "Caption pattern: DM/WhatsApp promo.", "promo, fashion jewellery", "Offer-led IG selling.", "Promo automation, CRM", "Not listed", 7, "Validate product authenticity/compliance."),
    ("ashabanglesofficial", "Asha Bangles / Punjabi Bridal Chura", "Patiala", "Punjab", "Bridal chura / bangles", "+917014592741", "Not listed publicly", "WhatsApp ordering + customisation", "No", "", "Posts emphasise custom chura", "Not indexed in public search", "Caption: WhatsApp to order; partial COD mentioned.", "punjabi chura, bridal, custom", "Strong WhatsApp custom bridal SKU model.", "WhatsApp flows, CRM", "https://maps.google.com/?q=Patiala%20bangles", 8, "Also tags multiple states; HQ likely Punjab."),
    ("mrkzevar", "MRK Zevar", "Bengaluru", "Karnataka", "Chains / daily gold", "", "Not listed publicly", "DM / showroom typical", "No", "", "Brand-style chain posts", "Not indexed in public search", "MRK group-affiliated chain marketing on IG.", "gold chains, Bangalore", "Regional gold brand social presence.", "Ecommerce, appointment", "https://maps.google.com/?q=Bangalore%20MRK%20Zevar", 5, "May be larger MRK network—verify SMB vs chain."),
    ("lakshmi_fashion_jewels", "Lakshmi Fashion Jewels", "Unknown", "Tamil Nadu", "Temple chains / dollar chains", "", "Not listed publicly", "DM / WhatsApp typical", "No", "", "Posts price temple chain sets", "Not indexed in public search", "Caption: priced pathakkam/attigai style sets.", "temple chain, imitation gold look", "South Indian imitation temple chain SMB.", "Catalogue checkout", "Not listed", 7, "Phone not in indexed snippet."),
    ("lucknow_chikankari_hub", "Lucknow Chikankari Hub (also lists jewellery)", "Lucknow", "Uttar Pradesh", "Mixed suits + jewellery bundles", "", "Not listed publicly", "DM typical", "No", "", "Posts show necklace sets priced", "Not indexed in public search", "Seller posts dual-tone necklace sets.", "necklace set, Lucknow", "Hybrid fashion+jewellery SMB.", "Cross-sell automation", "https://maps.google.com/?q=Lucknow", 6, "Not pure-play jeweller."),
    ("advaith_jewellery_collection", "Advaith's Jewellery Collection", "Unknown", "India", "CZ / temple / one-gram gold finish", "+917730871684", "Not listed publicly", "DM / WhatsApp; prepaid only", "No", "", "Posts mention no COD", "Not indexed in public search", "Caption: DM/Instagram WhatsApp; prepaid only.", "CZ, temple jewellery, prepaid", "Prepaid-only reduces ops risk; needs payment UX.", "Payment links, checkout", "Not listed", 8, "Good candidate for payment-link automation."),
    ("beautiful_creations0365", "Beautiful Creations 0365", "Unknown", "India", "Moissanite / polki kundan", "+919911283949", "Not listed publicly", "DM or WhatsApp with picture", "No", "", "Longstanding client claims in caption", "Not indexed in public search", "Caption: DM/WhatsApp with picture; no COD.", "moissanite, polki, kundan", "High-ticket imitation bridal with WhatsApp workflow.", "CRM, fraud checks, video consult", "Not listed", 8, "Claims many clients—verify authenticity."),
    ("jodhpuri__jewellery", "Jodhpuri Jewellery (Salasar Payal House)", "Jodhpur", "Rajasthan", "Gold-plated rakhdi sets", "+917568283224", "Not listed publicly", "WhatsApp for ready orders", "No", "", "Reels mention ready on order", "Not indexed in public search", "Caption: WhatsApp contact for rakhdi set.", "rakhdi, Jodhpur, WhatsApp", "WhatsApp-led ready-order SMB.", "Order tracking portal", "https://maps.google.com/?q=Jodhpur%20Salasar", 7, "Name from reel title; verify shop naming."),
    ("iadharvajewels", "Adharva Jewels", "Unknown", "India", "Statement necklace sets", "", "Not listed publicly", "DM / WhatsApp typical", "No", "", "Reels showcase sets", "Not indexed in public search", "Reels marketing large necklace sets.", "necklace set, bridal", "Reels-first catalogue without indexed site.", "Ecommerce", "Not listed", 6, "Limited indexed contact text."),
    ("sujatha_gold_covering_works", "Sujatha Gold Covering Works", "Machilipatnam", "Andhra Pradesh", "Micro gold-plated wholesale", "+917382222208", "Not listed publicly", "WhatsApp bookings; COD mentioned", "No", "", "Reels list multiple WhatsApp lines", "Not indexed in public search", "Caption lists multiple WhatsApp numbers + COD.", "micro gold, wholesale, Machilipatnam", "Multi-number wholesale indicates manual ops pain.", "Single business WA, ERP", "https://maps.google.com/?q=Machilipatnam%20jewellery", 8, "Also references bulk line +917036132171 in some posts—verify."),
    ("pooja._.jamnagar", "Pooja Jamnagar (The Jhumka Store)", "Jamnagar", "Gujarat", "Jhumka / earrings", "", "Not listed publicly", "DM / delivery messaging", "No", "", "Reels mention home delivery", "Not indexed in public search", "Reel title references jhumka store + delivery.", "jhumka, Jamnagar", "Geo handle + delivery promise.", "Logistics integration", "https://maps.google.com/?q=Jamnagar", 7, "Phone not in indexed snippet."),
    ("jodhpuri_silver", "Jodhpuri Silver (Khushbu Jewellers posts)", "Jodhpur", "Rajasthan", "Silver payal / silver SKUs", "+919358839704", "Not listed publicly", "WhatsApp screenshot ordering", "No", "", "Reels show WhatsApp screenshot flow", "Not indexed in public search", "Caption: WhatsApp screenshot order; COD mentions.", "silver payal, rajasthani", "Screenshot-to-WhatsApp is automation-heavy process.", "WhatsApp commerce automation", "https://maps.google.com/?q=Jodhpur%20silver%20market", 8, "May overlap with Khushbu network; treat as related brand page."),
    ("bjs2k", "Biswakarma Jewellery Shilpaya", "Unknown", "India", "Diamond earrings / nosepins", "+919874085669", "Not listed publicly", "WhatsApp for details/orders", "No", "", "Long WhatsApp CTAs in captions", "Not indexed in public search", "Captions push WhatsApp for diamond collections.", "diamond, nosepin, earrings", "Premium SMB using WhatsApp for consultative sales.", "CRM, appointment booking", "Not listed", 6, "Diamond SMB—verify certifications in DMs."),
    ("khushbu_jewellers_tinwari", "Khushbu Jewellers Tinwari", "Tinwari", "Rajasthan", "Silver + gold-polish fashion", "+919929595357", "Not listed publicly", "WhatsApp screenshot + COD mentions", "No", "", "Frequent reels", "Not indexed in public search", "Heavy WhatsApp screenshot + COD pattern.", "silver, COD, screenshot order", "Classic SMB ops load; automation fit.", "WhatsApp Commerce API", "https://maps.google.com/?q=Tinwari%20Rajasthan", 9, "High-intent SMB pattern across many posts."),
    ("khushbujewellers.com_", "Khushbu Jewellers (.com_)", "Unknown", "Rajasthan", "Silver / rajputi SKUs", "+919875791031", "Not listed publicly", "WhatsApp screenshot + website discount mentions", "Yes", "Domain referenced in captions as website order", "Frequent reels", "Not indexed in public search", "Captions mention website order discounts but WhatsApp screenshot remains.", "website order, WhatsApp screenshot, silver", "Hybrid IG + website; still SMB automation opportunity.", "Unify omnichannel inventory", "Not listed", 7, "Despite website mentions, WhatsApp screenshot workflow remains heavy."),
    ("samskruthijewellers", "Samskruthi Jewellers", "Unknown", "India", "925 silver bridal layered necklaces", "+918790112233", "Not listed publicly", "WhatsApp to place order", "No", "", "Reels show WhatsApp order line", "Not indexed in public search", "Caption: WhatsApp to place order for 925 silver sets.", "925 silver, bridal, layered necklace", "Clear WhatsApp order CTA for silver bridal.", "Checkout, EMI messaging", "Not listed", 8, "Strong WhatsApp order phrasing."),
    ("creativezealbysapnawadhwani", "CreativeZeal by Sapna Wadhwani", "Chennai", "Tamil Nadu", "German silver / oxidised earrings", "", "Not listed publicly", "DM to place an order", "No", "", "Reels say DM to order", "Not indexed in public search", "Caption: DM to place an order; Chennai tags.", "oxidised, german silver, Chennai", "DM-only artisan selling.", "WhatsApp bridge, catalog", "https://maps.google.com/?q=Chennai", 8, "Handle synthesized from public indexes referencing CreativeZeal brand."),
    ("mahijewelry", "Mahi Fashion Jewellery", "Unknown", "India", "Sheeshphool / maang tikka sets", "", "Not listed publicly", "Buy link phrasing in titles", "No", "", "Product posts", "Not indexed in public search", "Titles reference sheeshphool/mathapatti SKUs.", "sheeshphool, maang tikka, bridal", "Bridal headpiece niche on IG.", "Checkout links", "Not listed", 7, "Exact checkout link not captured in snippet."),
    ("gahanejewellery", "Gahane Jewellery", "Kolkata", "West Bengal", "Handcrafted gold kada (916 hallmarked)", "", "Not listed publicly", "DM / showroom typical", "No", "", "Posts highlight hallmark", "Not indexed in public search", "Caption: handcrafted kon-kon bangles; hallmark.", "gold kada, Bengali bridal", "Gold artisan posts for regional bridal.", "Appointment booking", "https://maps.google.com/?q=Kolkata%20jewellers", 6, "Gold SMB; verify scale."),
    ("ahmad_patiala_jewellers", "Ahmad Patiala Jewellers", "Patiala", "Punjab", "Gold chains / mala designs", "", "Not listed publicly", "DM / call typical", "No", "", "Reels show gold mala", "Not indexed in public search", "Patiala jeweller reels for gold chains.", "gold mala, Patiala", "Regional gold SMB IG marketing.", "Video consult tooling", "https://maps.google.com/?q=Patiala%20jewellers", 6, "Some posts tag international cities—verify primary market."),
    ("suryavanshijewellersjaipur", "Suryavanshi Jewellers Jaipur", "Jaipur", "Rajasthan", "Gold jewellery retail", "", "Not listed publicly", "DM / showroom", "No", "", "Gold collection reels", "Not indexed in public search", "Jaipur gold jeweller content.", "gold, Jaipur", "Could be mid-size; validate SMB fit.", "Ecommerce", "https://maps.google.com/?q=Jaipur%20Johari%20Bazaar", 5, "Higher enterprise risk; keep as borderline lead."),
    ("lakshmi_jewellers_khairthabd", "Lakshmi Jewellers Khairtabad", "Hyderabad", "Telangana", "Gold chains / daily wear", "", "Not listed publicly", "DM typical", "No", "", "Gold chain posts", "Not indexed in public search", "Hyderabad locality in name.", "gold chain, Hyderabad", "Local gold SMB marketing.", "Local SEO", "https://maps.google.com/?q=Khairtabad%20Hyderabad", 5, "Verify shop size."),
    ("lavanyajewellers_slj", "Lavanya Jewellers (Gold)", "Vijayawada", "Andhra Pradesh", "Custom gold bridal", "+919441176530", "Not listed publicly", "Call for order / customisation", "No", "", "Posts emphasise custom orders", "Not indexed in public search", "Caption: call for order; custom gold bridal.", "custom gold, bridal, Vijayawada", "Phone-led custom gold SMB.", "CRM, 3D renders", "https://maps.google.com/?q=Vijayawada%20jewellers", 6, "Gold-heavy; still custom order motion."),
    ("daisystories_", "Daisy Stories (clay/resin charms)", "Unknown", "India", "Clay bead charms / accessories", "", "Not listed publicly", "DM to order (per related resin post)", "No", "", "Cross-promoted in resin posts", "Not indexed in public search", "Referenced as shop account for DM orders.", "clay beads, charms, DM", "Adjacent accessories SMB.", "Shopify, Instagram shop", "Not listed", 6, "Jewellery-adjacent; validate SKU focus."),
    ("monikamanekar_arts", "Monika Manekar Arts", "Unknown", "India", "Polymer clay accessories", "", "Not listed publicly", "DM typical", "No", "", "Polymer clay posts", "Not indexed in public search", "Polymer clay keychains/jewellery-adjacent SKUs.", "polymer clay, handmade", "Creator commerce on IG.", "Ecommerce", "Not listed", 6, "More accessories than fine jewellery."),
    ("southindia_jewels", "South India Jewels (aggregator)", "Hyderabad", "Telangana", "Curated listings / seller features", "", "Not listed publicly", "DM / seller contacts", "No", "", "Features third-party jewellers", "Not indexed in public search", "Posts embed other jeweller contacts.", "aggregator, Hyderabad", "Aggregator model—sell tooling for their workflow.", "Marketplace tech", "Not listed", 5, "Not a single jeweller; included as ecosystem lead."),
    ("gobindjewellers", "Gobind Jewellers", "Durgapur", "West Bengal", "Gold / silver wedding SKUs", "+919593222111", "Not listed publicly", "Call contact on posts", "No", "", "Posts list Chandidas Market address", "Not indexed in public search", "Caption includes phone + Durgapur address.", "gold jewellery, Durgapur", "Local market jeweller using IG promos.", "Local SEO, WA", "https://maps.google.com/?q=Chandidas%20Market%20Durgapur", 6, "Call-first; add WhatsApp bridge."),
    ("the_earrings_factory", "The Earrings Factory", "Coimbatore", "Tamil Nadu", "Long jhumka collections", "+916374797571", "Not listed publicly", "WhatsApp + website ordering", "Yes", "https://www.theearringsfactory.com/", "Reels mention WhatsApp + site", "Not indexed in public search", "Caption: WhatsApp + order on website.", "jhumka, Coimbatore, wholesale", "Hybrid site + WhatsApp; automation still valuable.", "Omnichannel inventory", "https://maps.google.com/?q=Coimbatore", 6, "Website present lowers 'no website' score."),
    ("seemaclayjewelry", "Seema Clay Jewelry", "Bengaluru", "Karnataka", "Polymer clay classes + sales", "+919980472151", "Not listed publicly", "WhatsApp for class details; purchases via link-in-bio site", "Yes", "https://www.seemaclay.com/", "Classes + ecommerce", "Not indexed in public search", "Caption: WhatsApp for details; shop on seemaclay.com.", "polymer clay, classes, Bangalore", "Creator brand with site + WhatsApp.", "Course checkout, CRM", "https://maps.google.com/?q=Bangalore", 5, "Jewellery-adjacent education commerce."),
    ("bhartijewellersofficial", "Bharti Jewellers Official", "Unknown", "India", "Luxury polki / jadau sets", "", "Not listed publicly", "DM typical for luxury inquiries", "No", "", "Luxury bridal reels", "Not indexed in public search", "Luxury bridal polki posts.", "polki, jadau, bridal", "Premium bridal; may have offline-first sales.", "Private client CRM", "Not listed", 5, "Could be larger; validate SMB."),
    ("poojajewels_", "Pooja Jewels", "Unknown", "India", "Fashion / viral jewellery reels", "", "Not listed publicly", "DM / comment typical", "No", "", "High engagement reels", "Not indexed in public search", "Indexed comment threads show viral reel activity.", "viral reels, jewellery", "Viral reel merchandising pattern.", "Reels ads", "Not listed", 6, "Sparse business metadata in snippet."),
    ("khushbu_jewellers_1", "Khushbu Jewellers 1", "Unknown", "Rajasthan", "Silver / gold-polish catalogue", "", "Not listed publicly", "Likely WhatsApp screenshot flow (network)", "No", "", "Related reels in same network", "Not indexed in public search", "Appears as sibling page in Khushbu-style catalogue niche.", "silver, catalogue", "Related to Khushbu-style ops; verify if separate legal entity.", "Consolidate WhatsApp lines", "Not listed", 7, "Avoid duplicate WhatsApp numbers; contact via profile latest post."),
    ("saanjhbysonal", "Saanjh By Sonal", "Unknown", "India", "Ethnic fashion / jewellery mixes", "", "Not listed publicly", "DM typical", "No", "", "Similar creators list", "Not indexed in public search", "Appears as related creator in jewellery niche indexes.", "ethnic, jewellery", "Cross-sell opportunity for jewellery modules.", "Bundles", "Not listed", 5, "May include apparel; verify SKU mix."),
    ("royal_store_in", "Royal Store IN", "Unknown", "India", "Collection store (fancy + jewellery)", "", "Not listed publicly", "DM typical", "No", "", "Related creator recommendations", "Not indexed in public search", "General collection store positioning.", "fancy store, jewellery", "Retail collection SMB.", "Inventory POS", "Not listed", 5, "Broad inventory; jewellery subset."),
    ("roop_shree_fancy_bjs_colony", "Roop Shree Fancy BJS Colony", "Jodhpur", "Rajasthan", "Fancy + imitation jewellery", "", "Not listed publicly", "WhatsApp typical in fancy market niche", "No", "", "Wholesale-adjacent naming", "Not indexed in public search", "Jodhpur fancy market style naming.", "fancy, jodhpur", "Wholesale fancy SMB cross-sell jewellery.", "B2B catalog", "https://maps.google.com/?q=Jodhpur%20BJS%20Colony", 5, "Verify jewellery share of revenue."),
    ("amoraartsandjewels", "Amora Arts and Jewels", "Chennai", "Tamil Nadu", "Antique polished jhumkas", "+919962432802", "Not listed publicly", "WhatsApp for orders; product page link", "Yes", "https://www.amoraartsandjewels.com/", "Posts include product URLs", "Not indexed in public search", "Caption: WhatsApp + amoraartsandjewels.com product link.", "antique jhumka, Chennai", "Hybrid product URL + WhatsApp.", "Unify WA + web checkout", "https://maps.google.com/?q=Chennai", 6, "Website lowers no-website score."),
    ("d9creation_jewellery", "D9Creation Jewellery", "Jaipur", "Rajasthan", "Oxidised german silver manufacturing", "", "Not listed publicly", "Purchase via D9Creation.com", "Yes", "https://d9creation.com/", "Manufacturer posts", "Not indexed in public search", "Caption directs to D9Creation.com for purchase.", "oxidised, manufacturer, Jaipur", "Manufacturer with site; still IG-led discovery.", "B2B portal", "https://maps.google.com/?q=Jaipur", 5, "More manufacturer than retailer."),
    ("divanka.in", "Divanka.in (Rajwada jhumkas)", "Unknown", "India", "Low-cost jhumka ecommerce", "+919207376139", "Not listed publicly", "WhatsApp + divanka.in shop", "Yes", "https://www.divanka.in/", "Posts push site + WhatsApp", "Not indexed in public search", "Caption: shop on divanka.in or WhatsApp.", "jhumka, ecommerce", "Has site; WhatsApp still used—automation opportunity.", "WA + Shopify sync", "Not listed", 5, "Not 'no website'; included as WhatsApp-heavy ecommerce SMB."),
    ("jewellery_by_rohika", "Jewellery by Rohika (Rohika)", "Unknown", "Punjab", "Polki / kundan bridal", "+916280926290", "Not listed publicly", "DM or WhatsApp; rohikastore.com", "Yes", "https://www.rohikastore.com/", "Strong bridal catalogue posts", "Not indexed in public search", "Caption: DM/WhatsApp + website keyword search flow.", "polki, kundan, bridal", "Omni-channel bridal brand.", "CRM, VIP clienteling", "Not listed", 5, "Established ecommerce; still DM/WhatsApp heavy."),
    ("wholesale_with_rajesh", "Wholesale With Rajesh (Shree Chamunda Bangles)", "Mumbai", "Maharashtra", "Fancy bangles wholesale (Malad)", "+919326373778", "Not listed publicly", "WhatsApp / shop visit", "No", "", "Reels list Crystal Plaza address", "Not indexed in public search", "Caption: shop address + mobile for bangles wholesale.", "bangles, Malad, wholesale", "Physical wholesale + IG discovery.", "B2B ordering", "https://maps.google.com/?q=Crystal%20Plaza%20Malad%20West", 7, "Bangles are jewellery-adjacent core inventory."),
    ("wholesalepearlsjewells.onkar", "Pearls & Jewells Design Studio (Onkar India)", "Unknown", "India", "Fashion jewellery manufacturing marketing", "+919996698633", "Not listed publicly", "DM for full jewellery catalog", "No", "", "Manufacturer-style SEO captioning", "Not indexed in public search", "Caption: DM for catalog + manufacturing keywords.", "manufacturer, catalog, DM", "B2B marketing via IG DMs.", "B2B portal", "Not listed", 6, "More B2B manufacturer lead."),
    ("anikalan.co.in", "Anikalan Jewels", "Delhi", "Delhi", "Jadau kundan neckpieces", "+919042729768", "Not listed publicly", "DM or WhatsApp", "No", "", "Posts show jadau pieces", "Not indexed in public search", "Caption: DM or WhatsApp for jadau kundan piece.", "jadau, kundan, Delhi", "Delhi SMB with WhatsApp consult selling.", "Lookbook site, CRM", "https://maps.google.com/?q=Delhi%20jewellers", 8, "Strong DM+WhatsApp CTA in indexed post."),
    ("olddelhijewellers", "Old Delhi Jewellers", "Delhi", "Delhi", "Vintage / kundan pieces", "", "Not listed publicly", "DM for details", "No", "", "Posts invite DM for details", "Not indexed in public search", "Caption: DM for more details on vintage pendant.", "old delhi, kundan, vintage", "Heritage inventory sold via DM.", "Private client CRM", "https://maps.google.com/?q=Old%20Delhi%20jewellers", 7, "Premium DM-led sales."),
    ("swapna_jewels", "Swapna Jewels", "Unknown", "India", "Jadau kundan multi-layer sets", "", "Not listed publicly", "DM / price comments", "No", "", "Comment threads ask price", "Not indexed in public search", "Posts show layered jadau sets with engagement.", "jadau, layered, price inquiries", "Comment-price discovery indicates SMB ops.", "Automated quoting", "Not listed", 7, "Phone not captured in snippet."),
    ("creativebhel", "Creative Bhel", "Unknown", "India", "Quirky bangle stacks / fashion bangles", "", "Not listed publicly", "DM custom orders", "No", "", "Custom client stacks", "Not indexed in public search", "Highly customised bangle stacks.", "bangles, customised, handmade", "Custom stack commissions via IG.", "Order management", "Not listed", 7, "Bangle-focused; jewellery craft."),
    ("payal_jewelry_", "Payal Imitation Jewellery", "Ahmedabad", "Gujarat", "Antique long sets", "+919054250580", "Not listed publicly", "WhatsApp (Wsp) in caption", "No", "", "Naroda tags in posts", "Not indexed in public search", "Caption uses Wsp shorthand with phone.", "imitation, antique, Naroda", "WhatsApp-first imitation seller.", "Catalog automation", "https://maps.google.com/?q=Naroda%20Ahmedabad", 8, "City inferred from Naroda tag."),
    ("bharatanatyamdancejewellery", "Bharatanatyam Dance Jewellery (GoldenCollections)", "Hyderabad", "Telangana", "Dance jewellery sets", "+917337294499", "Not listed publicly", "WhatsApp + website shop", "Yes", "https://www.goldencollections.com/", "Dance jewellery SKUs", "Not indexed in public search", "Caption lists WhatsApp + goldencollections.com.", "dance jewellery, bharatanatyam", "Niche ecommerce + WhatsApp.", "Reduce friction between WA and web", "https://maps.google.com/?q=Hyderabad%20Pot%20Market", 5, "Website present."),
    ("goldenmirrorjewellerystudio", "Golden Mirror Jewellery Studio", "Hyderabad", "Telangana", "Sheesha kundan / partywear", "", "Not listed publicly", "DM / COD mentions in captions", "No", "", "Hyderabad jewellery hashtags", "Not indexed in public search", "Posts reference COD and Hyderabadi jewellery tags.", "sheesha kundan, partywear, Hyderabad", "COD mentions imply manual order handling.", "Checkout + COD policy pages", "https://maps.google.com/?q=Hyderabad", 7, "Prices sometimes listed in AED—verify domestic pricing workflow."),
    ("luckky_collections", "Luckky Collections (Lucky Jewellery)", "Unknown", "India", "Budget fashion jewellery", "", "Not listed publicly", "DM / tagged catalogue account", "No", "", "Cross-promo posts", "Not indexed in public search", "Posts reference @luckky_collections for shopping.", "budget jewellery, free shipping", "Catalogue cross-account pattern.", "Link-in-bio optimisation", "Not listed", 6, "Primary selling account may differ; verify."),
    ("shailurawat30190", "Shailu Rawat Handmade", "Unknown", "India", "Handmade maangtikka / jewellery", "", "Not listed publicly", "DM typical", "No", "", "Handmade jewellery posts", "Not indexed in public search", "Posts tag handmade bridal jewellery.", "handmade, maangtikka", "Creator-led bridal accessories.", "Ecommerce", "Not listed", 6, "Phone not in indexed snippet."),
    ("weddinganswers", "Wedding Answers (wedding ideas)", "Delhi", "Delhi", "Wedding accessories (chooda boxes etc.)", "+918368213149", "Not listed publicly", "WhatsApp or DM @weddinganswers", "No", "", "Wedding planning posts", "Not indexed in public search", "Caption: WhatsApp/DM for customised chooda box.", "chooda box, wedding, customised", "Wedding accessories SMB with WhatsApp.", "Wedding CRM", "https://maps.google.com/?q=Delhi", 6, "Accessory focus; overlaps bridal jewellery buyer."),
    ("nandishjewellers", "Nandish Jewellers", "Unknown", "India", "CNC gold bangles / online jewellery store positioning", "", "Not listed publicly", "Online store CTAs in hashtags", "Yes", "Online store referenced in caption hashtags", "Discount codes in posts", "Not indexed in public search", "Posts emphasise online jewellery shopping hashtags.", "CNC bangles, online jewellery", "May be larger ecommerce; verify SMB.", "Ecommerce optimisation", "Not listed", 5, "Enterprise risk; hashtags suggest online store."),
    ("the_vadhuu", "Vadhu Jewellery", "Unknown", "India", "Nakshi kada bangles / imitation", "", "Not listed publicly", "DM / free shipping mentions", "No", "", "Priced SKU posts", "Not indexed in public search", "Caption lists prices + free shipping.", "nakshi kada, imitation, shipping", "SKU list selling via IG.", "Checkout automation", "Not listed", 8, "Good SKU-commerce pattern."),
    ("riya.jewellers", "Riya Jewellers", "Unknown", "India", "Silver payal / anklet designs", "", "Not listed publicly", "DM / tagged from promoter posts", "No", "", "Third-party posts tag account", "Not indexed in public search", "Promoter reels point Instagram audience to @riya.jewellers.", "silver payal, anklets", "Catalogue account discovered via cross-posts.", "WhatsApp in bio likely", "Not listed", 6, "WhatsApp not in indexed snippet."),
    ("silver_jewellery_nakodapayals", "Silver Jewellery Nakoda Payals", "Unknown", "India", "925 silver bangles", "", "Not listed publicly", "Shop online at nakodapayals.com", "Yes", "https://nakodapayals.com/", "Ecommerce mentions", "Not indexed in public search", "Caption directs to nakodapayals.com.", "925 silver, bangles", "SMB ecommerce for silver bangles.", "Improve web conversion", "Not listed", 5, "Website present."),
]

# Deduplicate WhatsApp numbers (keep first, blank later duplicates)
seen_wa: set[str] = set()


def norm_wa(w: str) -> str | None:
    if not w:
        return None
    digits = "".join(ch for ch in w if ch.isdigit())
    if len(digits) >= 12 and digits.startswith("91"):
        digits = digits[-10:]
    if len(digits) > 10:
        digits = digits[-10:]
    if len(digits) == 10:
        return digits
    return digits or None


lines: list[str] = []
lines.append("India Jewellery Instagram / WhatsApp SMB Lead Export")
lines.append("Generated from public web-search discovery (May 2026).")
lines.append("IMPORTANT: Re-verify each profile, follower counts, bios, and phone numbers on Instagram before outreach.")
lines.append("")

for i, row in enumerate(RAW, start=1):
    (
        handle,
        biz,
        city,
        state,
        btype,
        wa,
        email,
        order_method,
        website_yn,
        website_url,
        recent,
        engagement,
        bio,
        keywords,
        reason,
        services,
        maps_link,
        score,
        notes,
    ) = row

    wa_digits = norm_wa(wa)
    if wa_digits and wa_digits in seen_wa:
        wa_out = ""
        notes = notes + " WhatsApp number omitted here due to dedupe rule; likely shared with another catalogue page—confirm latest active number on profile."
    else:
        wa_out = wa
        if wa_digits:
            seen_wa.add(wa_digits)

    lines.append("==================================================")
    lines.append(f"LEAD #{i}")
    lines.append("==================================================")
    lines.append(f"Business Name: {biz}")
    lines.append(f"Instagram Handle: @{handle}")
    lines.append(f"Instagram URL: https://www.instagram.com/{handle}/")
    lines.append("Followers Count: Not available from public search index (verify in-app)")
    lines.append(f"City: {city}")
    lines.append(f"State: {state}")
    lines.append(f"Business Type: {btype}")
    lines.append(f"WhatsApp Number: {wa_out}")
    lines.append(f"Email: {email}")
    lines.append(f"Ordering Method: {order_method}")
    lines.append(f"Website Present: {website_yn}")
    lines.append(f"Website URL: {website_url}")
    lines.append(f"Recent Activity Date: {recent}")
    lines.append(f"Average Engagement: {engagement}")
    lines.append("Bio Text:")
    lines.append(textwrap.fill(bio, width=96))
    lines.append(f"Keywords: {keywords}")
    lines.append("Reason Qualified:")
    lines.append(textwrap.fill(reason, width=96))
    lines.append("Potential Services Needed:")
    lines.append(textwrap.fill(services, width=96))
    lines.append(f"Google Maps Link: {maps_link}")
    lines.append(f"Lead Quality Score: {score}/10")
    lines.append("Notes:")
    lines.append(textwrap.fill(notes, width=96))
    lines.append("")

Path("/workspace/india_jewellery_instagram_leads.txt").write_text("\n".join(lines), encoding="utf-8")
print("Wrote", len(RAW), "leads")