#!/usr/bin/env python3
"""Generate india_jewellery_instagram_leads.txt with 100 unique, deduplicated leads.

Sources: public web search snippets (Instagram-indexed captions). Follower counts and
exact bios are not always present in search snippets; placeholders note verification.
"""

from __future__ import annotations

from pathlib import Path

# Each tuple: business_name, handle, city, state, business_type, whatsapp_e164_or_digits,
# email, ordering_methods, website_present, website_url, recent_activity, avg_engagement,
# bio_text, keywords_csv, reason, services_csv, maps_link, score, notes
# whatsapp_e164_or_digits: store as +91XXXXXXXXXX when known from snippet
LEADS_RAW: list[tuple] = [
    ("Beautiful Creations (Indian Kundan Jewellery)", "beautiful_creations0365", "Delhi NCR", "Delhi", "Kundan / polki imitation", "+919911283949", "Not indexed", "DM; WhatsApp with product screenshot", "No", "—", "Verify on Instagram", "Verify on Instagram", "Booking via DM/WhatsApp; no COD per posts", "kundan,polki,moissanite,DM,WhatsApp", "Indexed posts show DM/WhatsApp booking for imitation kundan; no standalone ecommerce site cited", "Website; WhatsApp automation; CRM", "—", 8, "Phone deduped: single lead for this WhatsApp."),
    ("Alankar Imitation", "alankar_imitation_", "India (shipping)", "—", "Brass / imitation", "+919909804412", "Not indexed", "WhatsApp screenshot order", "No", "—", "Verify on Instagram", "Verify on Instagram", "Screenshot-to-WhatsApp ordering; delivery 3–5 days in posts", "brass,imitation,screenshot order,WhatsApp", "Public posts show WhatsApp-first ordering flow", "WhatsApp automation; ecommerce; CRM", "—", 8, "—"),
    ("Shivay Imitation", "shivay.imitation", "Surat", "Gujarat", "Imitation / fashion", "+917435084868", "Not indexed", "WhatsApp screenshot; UPI", "No", "—", "Verify on Instagram", "Verify on Instagram", "Surat address in captions; screenshot order workflow", "imitation,mangalsutra,Surat,WhatsApp", "Strong WhatsApp + screenshot ordering signals; local Surat seller tone", "WhatsApp automation; lightweight checkout; CRM", "https://www.google.com/maps/search/Surat+imitation+jewellery", 8, "—"),
    ("Payal Imitation Jewellery", "payal_jewelry_", "Ahmedabad", "Gujarat", "One-gram / imitation", "+919054250580", "Not indexed", "WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "Naroda area address referenced in posts", "mangalsutra,one gram,WhatsApp", "WhatsApp ordering + physical shop cues", "WhatsApp automation; local SEO; CRM", "https://www.google.com/maps/search/Naroda+Ahmedabad+jewellery", 7, "—"),
    ("Jewellery Palace (BJS)", "_jewellery_palace_bjs", "India", "—", "Fashion / silver tone", "+918440038551", "Not indexed", "WhatsApp with product code", "No", "—", "Verify on Instagram", "Verify on Instagram", "Posts advertise WhatsApp order with codes", "WhatsApp,code order", "Simple WhatsApp-led sales motion in indexed captions", "WhatsApp automation; catalog on web", "—", 7, "—"),
    ("Jewellery Shopper", "jewellery_shopper_", "India", "—", "Silver articles / gifting", "+918905291031", "Not indexed", "WhatsApp screenshot order", "No", "—", "Verify on Instagram", "Verify on Instagram", "COD mentioned in some posts; screenshot workflow", "silver,WhatsApp,COD", "Screenshot WhatsApp ordering; separate posts also show other numbers for same brand family", "WhatsApp automation; CRM", "—", 7, "Exclude duplicate +919929595357 usage by prioritizing unique number for this handle in dataset."),
    ("Chudiwale Fashion Jewellery", "chudiwale_", "India", "—", "Bangles / fashion jewellery", "+917972380643", "Not indexed", "WhatsApp booking", "No", "—", "Verify on Instagram", "Verify on Instagram", "Customized bangle sets; WhatsApp booking", "bangles,custom,WhatsApp", "Strong WhatsApp CTA for bookings/custom orders", "WhatsApp automation; CRM; IG shopping setup", "—", 8, "—"),
    ("Khushbu Jewellers (Tinwari network)", "khushbu_jewellers_tinwari", "Rajasthan", "Rajasthan", "Rajputi / silver", "+919929595357", "Not indexed", "WhatsApp screenshot; COD mentioned", "No", "—", "Verify on Instagram", "Verify on Instagram", "Heavy WhatsApp + COD language in multiple indexed posts", "rajputi,silver,WhatsApp,COD", "High-intent SMB: repeat WhatsApp screenshot ordering pattern", "WhatsApp automation; CRM; marketing automation", "—", 8, "Deduped: other handles sharing this number omitted as separate leads."),
    ("Khushbu Jewellers (dot com handle)", "khushbujewellers.com_", "India", "—", "Silver / traditional", "+919875791031", "Not indexed", "WhatsApp screenshot; mentions website discount lines", "Unknown", "Not verified (posts mention website order lines)", "Verify on Instagram", "Verify on Instagram", "Screenshot ordering; promotional website wording in captions", "silver,WhatsApp,COD", "Qualifies on WhatsApp-first selling; verify if standalone ecommerce exists", "WhatsApp automation; ecommerce audit", "—", 6, "Website presence unclear from snippets; verify before outreach."),
    ("Maharashtrian Nath (handmade)", "maharashtrian_nath", "Maharashtra", "Maharashtra", "Handmade / bridal accents", "Not in snippet", "Not indexed", "DM for price/orders", "No", "—", "Verify on Instagram", "Verify on Instagram", "DM-first language in indexed caption", "handmade,DM,small business", "DM-led sales; small-business hashtags", "Website; DM automation; CRM", "—", 7, "WhatsApp not shown in indexed snippet."),
    ("Aashu's Pearl Creation", "aashus_pearl_creation", "Maharashtra", "Maharashtra", "Handmade / traditional", "Not in snippet", "Not indexed", "DM orders; customization", "No", "—", "Verify on Instagram", "Verify on Instagram", "Customization available; DM ordering referenced", "handmade,custom,DM", "Custom orders + DM purchase path", "CRM; IG automation; website", "—", 7, "—"),
    ("Moha by Geetanjali", "mohabygeetanjali", "India", "—", "Designer silver", "Not in snippet", "Not indexed", "DM / link-in-bio (verify)", "Unknown", "—", "Verify on Instagram", "Verify on Instagram", "Designer silver positioning in search title", "silver,designer", "Premium SMB jeweller vibe; verify purchase path", "Website; ecommerce; CRM", "—", 6, "Verify checkout method on profile."),
    ("Kolhapuri Thushi / Rishabh Gold", "kolhapurithushi", "Kolhapur", "Maharashtra", "Traditional Thushi", "+919403830260", "Not indexed", "WhatsApp; link in bio (verify)", "Unknown", "—", "Verify on Instagram", "Verify on Instagram", "WhatsApp number appears in indexed posts", "thushi,kolhapuri,WhatsApp", "Traditional category + WhatsApp selling", "WhatsApp automation; content; CRM", "https://www.google.com/maps/search/Kolhapur+jewellery", 7, "Another account also referenced same WhatsApp in snippets; phone deduped to this handle."),
    ("Wedding Collection (Kundan & Hyderabadi)", "weddingcollections143", "Hyderabad", "Telangana", "Bridal / Hyderabadi", "+919837777292", "Not indexed", "DM; call; WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "Hyderabad blogger tags in indexed caption", "bridal,Hyderabad,WhatsApp", "Explicit DM/call/WhatsApp ordering language", "WhatsApp automation; CRM; ads", "https://www.google.com/maps/search/Hyderabad+bridal+jewellery", 8, "—"),
    ("South Indian Temple Jewellery", "southindian__templejewellery", "Chennai", "Tamil Nadu", "Temple / matt finish", "+917904076978", "Not indexed", "DM; WhatsApp; UPI", "No", "—", "Verify on Instagram", "Verify on Instagram", "Chennai seller hashtag; WhatsApp group link referenced", "temple,south indian,WhatsApp", "Temple jewellery niche + WhatsApp/DM stack", "WhatsApp automation; CRM; catalog site", "https://www.google.com/maps/search/Chennai+jewellery", 8, "Second number +918610765751 also appears—verify active routing."),
    ("Jhooly Lal Artificial Jewellery", "jhoolylalartificial", "Delhi", "Delhi", "Artificial jewellery", "Not in snippet", "Not indexed", "Visit / DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Chandni Chowk ecosystem seller references", "artificial,Delhi", "Delhi market-adjacent SMB", "Website; local SEO; CRM", "https://www.google.com/maps/search/Chandni+Chowk+jewellery", 6, "WhatsApp not confirmed in snippet used."),
    ("Mahandi Artificial", "mahandi_artificial", "India", "—", "Gold-plated fashion", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Tagged seller from influencer posts in results", "artificial,gold plated", "SMB distribution via collabs; verify contact", "IG growth; CRM", "—", 6, "—"),
    ("Jewels of Karnataka", "jewelsofkarnataka", "Karnataka", "Karnataka", "One-gram gold fashion", "+919740234813", "Not indexed", "WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "WhatsApp contact in indexed caption", "one gram,WhatsApp,Karnataka", "State-scoped SMB naming + WhatsApp", "WhatsApp automation; CRM", "—", 7, "—"),
    ("Samskruthi Jewellers", "samskruthijewellers", "India", "—", "925 silver bridal layers", "+918790112233", "Not indexed", "WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "Bridal pearl layers; WhatsApp order line", "925 silver,bridal,WhatsApp", "Strong WhatsApp purchase CTA", "Ecommerce; WhatsApp automation; CRM", "—", 8, "—"),
    ("SuruArts Creation (SAC Jewellery)", "suruarts_creation_official", "Navi Mumbai / Mumbai", "Maharashtra", "Maharashtrian imitation", "+919373722506", "Not indexed", "WhatsApp; wa.me link in posts", "No", "—", "Verify on Instagram", "Verify on Instagram", "Multiple branch addresses in indexed captions", "maharashtrian,imitation,wa.me", "wa.me + inbox ordering is SMB-friendly stack", "WhatsApp automation; CRM", "https://www.google.com/maps/search/Nerul+jewellery", 8, "—"),
    ("Stree Jewels By Surbhi", "streejewelsbysurbhi", "India", "—", "Fashion / inspired sets", "Not in snippet", "Not indexed", "DM to book", "No", "—", "Verify on Instagram", "Verify on Instagram", "DM TO BOOK language in indexed reel title", "DM,bridal,inspired", "DM-native selling motion", "CRM; IG automation; lightweight checkout", "—", 7, "—"),
    ("Omkar Jewels Surat", "omkar_jewels_surat", "Surat", "Gujarat", "Custom jewellery", "+918141248248", "Not indexed", "Visit + phone (verify WhatsApp)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Physical Surat address + customization messaging", "custom,surat", "Custom SMB jeweller; good services upsell fit", "Website; CRM; showroom booking automation", "https://www.google.com/maps/search/Uttran+Surat+jewellery", 6, "Confirm WhatsApp usage on profile."),
    ("Oxidised Jewellery Wholesaler", "oxidised_jewellery_wholesaler", "India", "—", "Oxidised wholesale", "Not in snippet", "Not indexed", "DM/WhatsApp (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Wholesale-oriented handle name", "oxidised,wholesale", "Wholesale IG discovery account", "B2B portal; WhatsApp automation", "—", 6, "Contact not in snippet captured here."),
    ("Biswakarma Jewellery Shilpaya", "bjs2k", "Kolkata", "West Bengal", "Diamond jewellery retail", "+919874085669", "Not indexed", "WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "Kolkata-area luxury SMB posts with WhatsApp CTAs", "diamond,WhatsApp,Kolkata", "WhatsApp-led showroom style sales", "CRM; WhatsApp automation", "https://www.google.com/maps/search/Kolkata+diamond+jewellery", 6, "Larger retail vibe than nano brands; score moderated."),
    ("S. Swarnakar & Son", "s.swarnakarandson", "Kolkata", "West Bengal", "Gold / silver retail", "+918981948452", "Not indexed", "Call/WhatsApp booking (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Kolkata tags in indexed posts", "Kolkata,hallmark", "Local jeweller IG presence", "Local SEO; WhatsApp automation", "https://www.google.com/maps/search/Chetla+jewellery", 6, "—"),
    ("Gobind Jewellers", "gobindjewellers", "Durgapur", "West Bengal", "Gold / silver", "+919593222111", "Not indexed", "Call/WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "Chandidas Market address in posts", "Durgapur,WhatsApp", "Multi-number SMB; IG used for offers", "CRM; WhatsApp routing; ads", "https://www.google.com/maps/search/Chandidas+Market+Durgapur+jewellery", 6, "Also cites +919851464538 in some posts."),
    ("Asha Bangles Official", "ashabanglesofficial", "Patiala", "Punjab", "Bridal chura / bangles", "+917014592741", "Not indexed", "WhatsApp; partial COD", "No", "—", "Verify on Instagram", "Verify on Instagram", "Long-running chura seller messaging in indexed posts", "chura,Punjabi,WhatsApp", "Very WhatsApp-forward bridal SKU seller", "WhatsApp automation; CRM", "https://www.google.com/maps/search/Patiala+chura", 8, "Deduped phone across multiple Asha-related post accounts."),
    ("Bridals Chura (Deepali Saluja)", "bridals_chura", "Hisar", "Haryana", "AD chura / bridal", "+918607355159", "Not indexed", "DM; WhatsApp; COD", "No", "—", "Verify on Instagram", "Verify on Instagram", "COD + worldwide delivery claims in indexed caption", "chura,COD,DM,WhatsApp", "DM+WhatsApp + COD is strong services fit", "WhatsApp automation; CRM", "—", 8, "—"),
    ("Fashion Darbar Hub", "fashion_darbar_hub_", "India", "—", "Couple bracelets / fashion", "+919887305357", "Not indexed", "WhatsApp screenshot", "No", "—", "Verify on Instagram", "Verify on Instagram", "Reels-style selling with WhatsApp number", "fashion,screenshot order", "Screenshot-to-WhatsApp motion", "WhatsApp automation", "—", 7, "—"),
    ("Radha Rani Imitation", "radha_rani_imitation_7", "Mumbai", "Maharashtra", "Imitation wholesale", "+917023725950", "Not indexed", "Call/WhatsApp (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Bhuleshwar market address in caption", "Mumbai,imitation,wholesale", "Wholesale market SMB", "WhatsApp automation; B2B mini-site", "https://www.google.com/maps/search/Bhuleshwar+jewellery", 7, "—"),
    ("Lakshmi Creations Imitation", "lakshmi_creations_9", "Mumbai", "Maharashtra", "Imitation wholesale", "+919849567353", "Not indexed", "WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "Wholesale pricing language", "imitation,WhatsApp", "WhatsApp-first wholesale", "WhatsApp automation; CRM", "—", 7, "—"),
    ("Mangalmurti Art Jewellery (Jewellery of World)", "jewellery_of_world", "Palghar", "Maharashtra", "Maharashtrian bridal", "+918446200337", "Not indexed", "WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "Rent/purchase bridal lines in indexed caption", "maharashtrian,bridal,WhatsApp", "Hybrid rent/sell SMB model", "CRM; WhatsApp automation; booking system", "https://www.google.com/maps/search/Palghar+jewellery", 7, "—"),
    ("Rajputi Jewellery Wholesaler", "rajputi_jewelery_wholsaler_s.c", "India", "—", "Rajputi imitation", "+917877634674", "Not indexed", "WhatsApp; groups", "No", "—", "Verify on Instagram", "Verify on Instagram", "Group link + WhatsApp in reels", "rajputi,WhatsApp,group", "Community selling via WhatsApp groups", "WhatsApp automation; group ops tooling", "—", 7, "—"),
    ("Mahek Khan (Belgaum artificial)", "mahek_khan70", "Belagavi", "Karnataka", "Artificial gold-plated", "+918590880378", "Not indexed", "Call/WhatsApp (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Local market address style caption", "Belgaum,artificial", "Hyperlocal SMB IG seller", "WhatsApp automation; local SEO", "https://www.google.com/maps/search/Khade+Bazar+Belgaum+jewellery", 7, "—"),
    ("Lucknow Artificial Jewellery", "lucknow_artificial_jewellery_", "Lucknow", "Uttar Pradesh", "One-gram fashion", "+918957754721", "Not indexed", "Call booking / WhatsApp (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "COD + India shipping language", "Lucknow,one gram,COD", "COD-led SMB motion", "WhatsApp automation; COD ops", "https://www.google.com/maps/search/Lucknow+artificial+jewellery", 7, "—"),
    ("RUKMI by PCS Jewellers", "rukmi_silver_jewellery", "Indore", "Madhya Pradesh", "Silver retail", "+918827876987", "Not indexed", "Call/WhatsApp (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Store address in captions; festival promos", "silver,Indore", "Store-forward SMB silver", "CRM; WhatsApp automation", "https://www.google.com/maps/search/Annapurna+Road+Indore+jewellery", 6, "Also references +918817578721 in posts."),
    ("Silver Shine Jewellery", "silvershine_jewelery", "Vadodara", "Gujarat", "925 silver", "+917572962224", "Not indexed", "DM; WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "Explicit DM/WhatsApp ordering in reel text", "925,silver,DM,WhatsApp", "Dual-channel ordering SMB", "WhatsApp automation; CRM", "https://www.google.com/maps/search/Vadodara+silver+jewellery", 8, "—"),
    ("Jodhpuri Silver (Khushbu network)", "jodhpuri_silver", "Jodhpur", "Rajasthan", "Silver payal / articles", "+919358839704", "Not indexed", "WhatsApp screenshot", "Unknown", "Posts mention website-order promos", "Verify on Instagram", "Verify on Instagram", "COD + website-order language in captions", "silver,COD,Jodhpur", "High WhatsApp velocity; verify site scope", "WhatsApp automation; ecommerce cleanup", "https://www.google.com/maps/search/Jodhpur+silver", 6, "—"),
    ("Jodhpuri Jewellery (Salasar Payal House)", "jodhpuri__jewellery", "Jodhpur", "Rajasthan", "Gold rakhdi orders", "+917568283224", "Not indexed", "WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "Order-ready language on WhatsApp", "rakhdi,WhatsApp", "Custom order SMB", "WhatsApp automation", "https://www.google.com/maps/search/Jodhpur+jewellery", 7, "—"),
    ("Vernika Silver Jewellery", "vernika.silver.jewellery", "Bengaluru", "Karnataka", "925 silver retail", "+917406810666", "Not indexed", "Call; video call bookings", "No", "—", "Verify on Instagram", "Verify on Instagram", "Avenue Road / Raja market cues", "silver,Bangalore,video call", "Video-call commerce SMB", "Booking automation; CRM", "https://www.google.com/maps/search/Avenue+Road+Bangalore+silver", 7, "—"),
    ("Siddaganga Jewellers", "siddagangajewellery1073", "Dobbaspet (Bengaluru Rural)", "Karnataka", "925 silver", "+919972341073", "Not indexed", "Call / DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Rural Bengaluru district location tags", "silver,925", "Regional silver SMB", "Website; local SEO", "https://www.google.com/maps/search/Dobbaspet+silver+jewellery", 6, "—"),
    ("Garv Silver Jewellery", "garvsilverjewellery", "India", "—", "Victorian silver", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Victorian/polki silver niche in title", "victorian,silver", "Niche silver SMB", "Ecommerce; CRM", "—", 6, "—"),
    ("Angaja Silver Jewellery", "angaja.silver", "Gurugram", "Haryana", "925 silver", "Not in snippet", "Not indexed", "DM / visit (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Gurgaon-tagged silver niche", "silver,Gurgaon", "Local silver boutique tone", "Local SEO; CRM", "https://www.google.com/maps/search/Gurgaon+silver+jewellery", 6, "—"),
    ("AAI Mogal Imitation Jewellery", "aai_mogal_imitation_", "Kolkata", "West Bengal", "Gold-plated imitation", "+918511494642", "Not indexed", "WhatsApp screenshot; prepay", "No", "—", "Verify on Instagram", "Verify on Instagram", "No COD; screenshot workflow", "imitation,Kolkata,screenshot", "Strict prepay SMB; automation helps", "WhatsApp automation; payments", "—", 7, "—"),
    ("Suryavanshi Jewellers Jaipur", "suryavanshijewellersjaipur", "Jaipur", "Rajasthan", "Gold jewellery", "Not in snippet", "Not indexed", "Visit / DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Jaipur jeweller posts in results", "gold,Jaipur", "Local jeweller IG", "CRM; local ads", "https://www.google.com/maps/search/Jaipur+jewellers", 6, "—"),
    ("Kundan Creations By Jinal", "kundancreations_", "India", "—", "Gold-plated kundan", "+917359147370", "Not indexed", "WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "WhatsApp for pricing/orders in indexed reel", "kundan,WhatsApp,moissanite", "WhatsApp-first pricing requests", "WhatsApp automation; catalog", "—", 8, "—"),
    ("Jaipur Jewellery Damoh", "jaipur_jewellary_damoh", "Damoh", "Madhya Pradesh", "Designer earrings retail", "Not in snippet", "Not indexed", "Visit store (verify DMs)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Bundabahu complex reference", "earrings,Damoh", "Tier-2/3 city SMB", "Website; local SEO", "https://www.google.com/maps/search/Damoh+jewellery", 5, "—"),
    ("Tulasi Maharani Jewellery", "tulasi.maharani.jewellery", "India", "—", "Sterling silver bespoke", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Handmade silver tone in title", "silver,handmade", "Artisan SMB positioning", "Website; CRM", "—", 6, "—"),
    ("Indukuri's Jewel", "indukurisjewel", "India", "—", "Lab-grown diamond custom", "+916302720676", "Not indexed", "WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "Customization via WhatsApp in reel text", "lab grown,custom,WhatsApp", "WhatsApp-led consult selling", "CRM; appointment automation", "—", 7, "—"),
    ("KR Jewellers Goa", "krjewellersgoa", "Ponda", "Goa", "Goan patli / gold", "+919511641757", "Not indexed", "DM; call", "No", "—", "Verify on Instagram", "Verify on Instagram", "Ponda address + DM order CTA", "Goa,gold,DM", "Regional traditional jewellery SMB", "WhatsApp automation; CRM", "https://www.google.com/maps/search/Ponda+jewellery", 7, "—"),
    ("Amita Jewellery", "amita_jewellery", "Goa", "Goa", "Goan black bead designs", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Goan design niche", "goa,black bead", "Local design SMB", "Website; IG shopping", "—", 6, "—"),
    ("L Gopal Jewellers", "lgopaljewellers", "Guwahati", "Assam", "Gold / diamond retail", "Not in snippet", "Not indexed", "Visit showroom (verify WhatsApp)", "Unknown", "—", "Verify on Instagram", "Verify on Instagram", "Guwahati hashtags; classic showroom IG", "Guwahati,gold", "Showroom-led; verify DMs", "CRM; local SEO", "https://www.google.com/maps/search/Guwahati+jewellers", 5, "—"),
    ("Mahaveer Jewellery", "mahaveer_jewelery", "Guwahati", "Assam", "Jewellery retail", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Local profile surfaced in search", "Guwahati", "Local SMB discovery", "CRM", "—", 5, "—"),
    ("Swarn Prabha Jewellers Bhopal", "swarnprabhajewellersbhopal", "Bhopal", "Madhya Pradesh", "Diamond retail", "Not in snippet", "Not indexed", "Visit / DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Bhopal tags", "diamond,Bhopal", "Regional diamond SMB", "CRM", "https://www.google.com/maps/search/Bhopal+jewellers", 5, "—"),
    ("Rohit Bhai Jewellers", "RohitBhaiJewellers", "Delhi", "Delhi", "Gold bridal", "+919953916916", "Not indexed", "WhatsApp; visit", "No", "—", "Verify on Instagram", "Verify on Instagram", "Chandni Chowk address + WhatsApp numbers", "Chandni Chowk,WhatsApp", "Strong WhatsApp + legacy market SMB", "WhatsApp automation; CRM", "https://www.google.com/maps/search/Kucha+Mahajani+jewellery", 6, "Also cites +919953916903 in posts."),
    ("Silvera (V Silvera India)", "vsilveraindia", "Ahmedabad", "Gujarat", "Silver antique festive", "+919925096554", "Not indexed", "Call branch numbers / DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Two Ahmedabad branches listed", "silver,Navratri,Ahmedabad", "Multi-branch SMB (moderated score)", "WhatsApp routing; CRM", "https://www.google.com/maps/search/Shivranjani+Ahmedabad+silver", 5, "Also lists +919925096599."),
    ("Begum Bazar Wholesale Jewelry", "begumbazar_wholesale_jewelry", "Hyderabad", "Telangana", "Wholesale sets", "+919908136342", "Not indexed", "DM; WhatsApp screenshot", "No", "—", "Verify on Instagram", "Verify on Instagram", "No COD; screenshot workflow", "Begum Bazar,wholesale,screenshot", "Classic wholesale IG motion", "WhatsApp automation; ERP-light", "https://www.google.com/maps/search/Begum+Bazar+jewellery", 8, "Some posts also show +919618136342—verify active numbers."),
    ("Sai Brindavan Jewellers", "saibrindavan_jewellers", "Hyderabad", "Telangana", "Begum Bazar wholesale/retail", "Not in snippet", "Not indexed", "Visit / DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Wholesale/retail positioning in reel title", "Begum Bazar,wholesale", "Market-linked SMB", "CRM", "—", 6, "—"),
    ("Pooja Jewels (Silver)", "poojajewels_", "India", "—", "Sterling silver", "+919993284004", "Not indexed", "WhatsApp; COD mentions in Threads mirror text", "Unknown", "—", "Verify on Instagram", "Verify on Instagram", "Multiple WhatsApp numbers appear across web mirrors; verify canonical", "silver,COD,WhatsApp", "COD + WhatsApp is strong fit for automation", "WhatsApp automation; CRM", "—", 7, "Threads mirror text also referenced +917073962052; reconcile on Instagram."),
    ("Pooja Shree Jewellery (One gram)", "pooja_shree_jewellary_onegram", "Chhatrapati Sambhajinagar", "Maharashtra", "One-gram temple mangalsutra", "+919503080030", "Not indexed", "DM; call", "No", "—", "Verify on Instagram", "Verify on Instagram", "Dual numbers in caption (+919156535485 also)", "one gram,temple,DM", "DM-led SMB in MH cities", "WhatsApp automation; CRM", "—", 7, "—"),
    ("Rajputi Jewellery Bhilwara", "rajputijewellerybhilwara00", "Bhilwara", "Rajasthan", "Rajputi gold-look sets", "+919829900459", "Not indexed", "WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "Online prepay; no COD language", "rajputi,WhatsApp", "WhatsApp-first imitation premium", "WhatsApp automation; payments", "https://www.google.com/maps/search/Bhilwara+jewellery", 7, "—"),
    ("Jewellery Rajasthan", "jewellery_rajasthan", "Rajasthan", "Rajasthan", "Rajputi fashion", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Rajasthan catalogue tone", "rajputi,Rajasthan", "SMB catalogue IG", "CRM", "—", 6, "—"),
    ("Stylika", "stylika_", "Ahmedabad", "Gujarat", "Oxidised / Navratri", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Ahmedabad hidden-gem positioning in title", "oxidised,Navratri,Ahmedabad", "Fashion retail discovery account", "Local SEO; WhatsApp automation", "https://www.google.com/maps/search/Ahmedabad+oxidised+jewellery", 6, "—"),
    ("Kanak Saanvi Jewels", "kanak_saanvi_agra", "Agra", "Uttar Pradesh", "Gold antique sets", "+918899930328", "Not indexed", "Call / visit", "No", "—", "Verify on Instagram", "Verify on Instagram", "MG Road Agra address", "Agra,gold", "Showroom SMB", "CRM; ads", "https://www.google.com/maps/search/MG+Road+Agra+jewellery", 5, "—"),
    ("Varaa Shree Jewels", "varaashreejewels", "India", "—", "Statement / luxury earrings", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Statement jewellery tone", "statement,luxury", "Premium SMB brand tone", "Website; CRM", "—", 5, "—"),
    ("Lavanya Jewellers", "lavanyajewellers_slj", "Vijayawada", "Andhra Pradesh", "Handmade gold custom", "+919441176530", "Not indexed", "DM; WhatsApp; call", "No", "—", "Verify on Instagram", "Verify on Instagram", "Custom orders + worldwide shipping claims", "handmade,gold,custom,WhatsApp", "Custom gold SMB with WhatsApp consult path", "CRM; WhatsApp automation", "https://www.google.com/maps/search/Vijayawada+jewellers", 6, "—"),
    ("Nikhil Jewellery Hyderabad", "nikhiljewelleryhyderabad", "Hyderabad", "Telangana", "916 gold bespoke", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Heavy gold bespoke reels tone", "916,gold,Hyderabad", "Gold SMB IG marketing", "CRM", "https://www.google.com/maps/search/LB+Nagar+gold+jewellery", 5, "—"),
    ("JK Jewellers Jodhpur", "jkjewellersjodhpur36", "Jodhpur", "Rajasthan", "925 silver wholesale/retail", "+918619090636", "Not indexed", "DM; WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "DM + WhatsApp same number in indexed reel", "silver,Jodhpur,DM,WhatsApp", "Dual DM/WhatsApp SMB", "WhatsApp automation; wholesale portal", "https://www.google.com/maps/search/Jodhpur+silver+jewellery", 8, "Handle inferred from hashtag #jkjewellersjodhpur36; verify exact username."),
    ("Sai Jewellers Rajat (Ujjain)", "sai_jewellers_rajat_ujjain", "Ujjain", "Madhya Pradesh", "Gold-plated fashion", "+917024274632", "Not indexed", "DM; WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "Indexed comment thread shows WhatsApp selling", "gold plated,WhatsApp,Ujjain", "Comment-thread selling is SMB signal", "WhatsApp automation; CRM", "https://www.google.com/maps/search/Ujjain+jewellery", 7, "—"),
    ("VYRA Gold (Vijayakrishna)", "vyra_gold", "India", "—", "Temple gold / diamonds", "+919995901152", "Not indexed", "WhatsApp", "Unknown", "—", "Verify on Instagram", "Verify on Instagram", "Temple collection + WhatsApp CTA in indexed results", "temple,gold,WhatsApp", "Larger regional brand tone; still WhatsApp-led in posts", "CRM; call center integration", "—", 5, "Score moderated due to multi-showroom brand likelihood."),
    ("Sri Krishna Gold", "sri_krishnagold", "Mysuru", "Karnataka", "Gold chains / mangalya", "+919741119406", "Not indexed", "WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "Mysore Ashoka Road reference", "gold chain,mangalya,WhatsApp", "WhatsApp-led chain designs SMB", "WhatsApp automation", "https://www.google.com/maps/search/Ashoka+Road+Mysore+gold", 7, "—"),
    ("Vijay Gold Palace", "vijaygold1", "Mysuru", "Karnataka", "Antique lightweight gold", "+918904628627", "Not indexed", "WhatsApp", "No", "—", "Verify on Instagram", "Verify on Instagram", "Temple jewellery hashtags + WhatsApp", "antique,temple,WhatsApp", "WhatsApp-first antique gold SMB", "WhatsApp automation; CRM", "https://www.google.com/maps/search/Mysore+gold+jewellery", 7, "—"),
    ("Silver Palace 45", "silver_palace45", "India", "—", "Silver (verify niche)", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Discovered via indexed comment-thread surface", "silver,DM", "Low public metadata; verify before outreach", "CRM", "—", 4, "Sparse snippet; needs profile verification."),
    ("Swarnam Varnam", "swarnam_varnam", "India", "—", "Jewellery creator (verify)", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Surfaced via search snippet routing", "fashion,DM", "Verify niche + location", "CRM", "—", 4, "Sparse snippet; needs profile verification."),
    ("Trend Jewelryys", "trend_jewelryys", "India", "—", "Fashion jewellery", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Low-comment reel account surfaced in search", "trending,DM", "Nano influencer retail pattern (verify)", "IG growth; CRM", "—", 4, "Sparse snippet; needs profile verification."),
    ("Wear N Shine Jewelry", "wear_nd_shine_jewelry", "India", "—", "Fashion jewellery", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Low-comment reel account surfaced in search", "fashion,DM", "Nano seller pattern (verify)", "IG growth; CRM", "—", 4, "Sparse snippet; needs profile verification."),
    ("Jewellry Junction Nagpur", "jewellryjunction", "Nagpur", "Maharashtra", "Imitation retail", "+919730162779", "Not indexed", "Call / WhatsApp (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Teen Nal Chowk location surfaced via blogger reel", "imitation,Nagpur", "Local imitation retail SMB", "WhatsApp automation; local SEO", "https://www.google.com/maps/search/Teen+Nal+Chowk+Nagpur+jewellery", 6, "—"),
    ("Kaurz Crown Jewellery", "kaurzcrownjewellery", "Punjab", "Punjab", "925 silver kundan plated", "+919888298050", "Not indexed", "WhatsApp; DM", "No", "—", "Verify on Instagram", "Verify on Instagram", "Customization + worldwide shipping claims in indexed post family", "925,kundan,silver,WhatsApp", "Strong WhatsApp + customization SMB", "WhatsApp automation; CRM", "—", 8, "Handle taken from viral reel hashtag family; verify exact username spelling on Instagram."),
    ("DM Jewellers", "dm_jewellers", "India", "—", "Diamond statement", "Not in snippet", "Not indexed", "DM for details", "No", "—", "Verify on Instagram", "Verify on Instagram", "DM-led diamond content in indexed reel", "diamond,DM,bridal", "DM consult selling", "CRM; automation", "—", 6, "Name collision risk; verify not international."),
    ("JCS Jewel Creations Chennai", "jcsjewelcreations", "Chennai", "Tamil Nadu", "Temple jewellery designs", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Temple collection marketing tone", "temple,Chennai", "SMB studio tone (verify contact)", "Website; CRM", "https://www.google.com/maps/search/Chennai+jewellery", 6, "—"),
    ("Patiala Wedding Gallery / Chuda Wholesaler Punjab", "chuda_wholesaler_punjab_", "Patiala", "Punjab", "Kundan bridal chura", "+917508300898", "Not indexed", "DM; WhatsApp; COD", "Yes", "https://www.bridalchuda.com/", "Verify on Instagram", "Verify on Instagram", "Website present in indexed caption; still heavy WhatsApp/DM", "chura,kundan,COD,WhatsApp", "Hybrid SMB: IG + site; services still relevant", "WhatsApp automation; ecommerce optimization", "—", 6, "Included because WhatsApp/DM + COD still central; not 'no website'."),
    ("Sudarshan Jewellers (Jodhpur)", "sudarshan.jewellers", "Jodhpur", "Rajasthan", "Gold / silver / rakhdi", "+917231021000", "Not indexed", "DM; WhatsApp; store", "No", "—", "Verify on Instagram", "Verify on Instagram", "Large Jodhpur store network cues; WhatsApp/DM still present", "Jodhpur,gold,silver,WhatsApp", "Major local brand; included for WhatsApp/DM depth but lower fit score", "Enterprise-grade CRM", "https://www.google.com/maps/search/Ghodo+Ka+Chowk+Jodhpur+jewellery", 4, "Larger showroom SMB/regional brand."),
    ("Shri Ji Jewellers Vrindavan", "shrijijewellersvbn", "Vrindavan", "Uttar Pradesh", "925 silver articles", "+919897684094", "Not indexed", "DM; call", "No", "—", "Verify on Instagram", "Verify on Instagram", "Pure silver + religious tourism retail tone", "silver,vrindavan,DM", "Tourism-heavy retail; WhatsApp automation helps peak season", "WhatsApp automation; CRM", "https://www.google.com/maps/search/Vrindavan+silver+jewellery", 7, "—"),
    ("Silver Jewels Pune (Shree Silver)", "silver_jewels_pune", "Pune", "Maharashtra", "925 silver retail", "Not in snippet", "Not indexed", "Visit / online (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Raviwar Peth address style posts", "silver,Pune,925", "Local silver retail SMB", "Local SEO; CRM", "https://www.google.com/maps/search/Raviwar+Peth+Pune+silver", 6, "—"),
    ("Everbrite Jewellery", "everbritejewellery", "Bhopal", "Madhya Pradesh", "Lab-grown diamond retail", "Not in snippet", "Not indexed", "Event/studio (verify)", "Unknown", "—", "Verify on Instagram", "Verify on Instagram", "Trunk show collabs in indexed captions", "lab grown,Bhopal", "Modern retail marketing SMB", "CRM; events automation", "https://www.google.com/maps/search/Bhopal+jewellery", 5, "—"),
    ("Luckky Collections (tagged seller)", "luckky_collections", "India", "—", "Fashion jewellery", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Tagged from Lucky Jewellery post snippet", "fashion,shipping", "Tagged seller account; verify ownership", "IG growth; CRM", "—", 4, "Sparse; verify."),
    ("Sudarshan Silver", "sudarshan.silver", "Jodhpur", "Rajasthan", "Silver payal / antique", "+918058054700", "Not indexed", "DM; store", "No", "—", "Verify on Instagram", "Verify on Instagram", "Large department-style contacts list in posts", "silver,Jodhpur,DM", "Large silver department; still DM path", "CRM", "https://www.google.com/maps/search/Jodhpur+silver", 4, "Linked to major store family; lower SMB priority."),
    ("Hiranya Jewellers (WhatsApp-forward reel)", "hiranyajewellers", "Nepal/India (verify)", "—", "Jewellery (verify category)", "+919851293511", "Not indexed", "WhatsApp; Viber", "No", "—", "Verify on Instagram", "Verify on Instagram", "Indexed reel uses #hiranyajewellers; location not confirmed", "WhatsApp,viber", "Contact-forward reel; verify country/city compliance", "WhatsApp automation", "—", 4, "Location uncertain from snippet; verify India operations."),
    ("Those Little Bling", "thoselittleblinggss", "India", "—", "Moissanite / oxidised fashion", "Not in snippet", "Not indexed", "DM to order", "No", "—", "Verify on Instagram", "Verify on Instagram", "Indexed posts show fixed prices + 'DM to order' + free shipping language", "moissanite,oxidised,DM,free shipping", "DM-native checkout without cited standalone ecommerce site", "DM automation; lightweight checkout; CRM", "—", 7, "—"),
    ("Sri Bhavani Jewels", "sribhavanijewels", "India", "—", "Temple / jhumkas", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Temple motif storytelling in indexed titles", "temple,jhumka", "Traditional motif SMB content marketing", "Website; CRM; ads", "—", 6, "—"),
    ("CH Patiala Jewellers", "chpatiala_jewellers", "Patiala", "Punjab", "Gold kara / retail", "Not in snippet", "Not indexed", "Visit / DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Patiala jeweller posts surfaced in discovery searches", "gold,Patiala", "Local gold retail IG presence", "Local SEO; CRM", "https://www.google.com/maps/search/Patiala+jewellers", 5, "—"),
    ("Jyoti Jewellers Surat", "jyoti.jewellers.surat", "Surat", "Gujarat", "Gold / diamond / trendy", "Not in snippet", "Not indexed", "Visit showroom (verify WhatsApp)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Surat showroom address style captions in indexed reels", "Surat,mangalsutra,trendy", "Showroom-forward SMB with IG discovery", "WhatsApp automation; CRM", "https://www.google.com/maps/search/Adajan+Surat+jewellers", 5, "—"),
    ("Devi Pavitra Gold & Diamonds", "devipavitravijayawada", "Vijayawada", "Andhra Pradesh", "Gold / diamond retail", "+919666234916", "Not indexed", "Call / visit / DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "FM Plaza Vijayawada + multi-city mentions in indexed posts", "gold,diamond,Vijayawada", "Regional jeweller IG marketing with phone contact", "CRM; ads; website", "https://www.google.com/maps/search/FM+Plaza+Vijayawada+jewellery", 5, "—"),
    ("Goyaz Silver Jewellery", "goyazsilverjewellery", "Hyderabad", "Telangana", "925 silver / bridal", "+918669626666", "Not indexed", "Call / video shopping / visit", "Unknown", "—", "Verify on Instagram", "Verify on Instagram", "Multi-location phone list surfaced in indexed reels (incl. Hyderabad/Bengaluru)", "silver,925,Hyderabad,video shopping", "Multi-branch silver retailer; still phone-led discovery", "Call routing; CRM; ecommerce", "https://www.google.com/maps/search/Kukatpally+silver+jewellery", 4, "Likely multi-branch; treat as mid-market lead."),
    ("Rajesh Silver Jewellery", "rajesh_silver_jewellery", "India", "—", "925 silver gold-polish", "+917829379892", "Not indexed", "DM; WhatsApp; website ordering", "Yes", "https://www.rajeshjewels.com/", "Verify on Instagram", "Verify on Instagram", "Posts cite website + WhatsApp/DM paths", "925,temple,silver,WhatsApp", "Hybrid commerce SMB (IG + site + WhatsApp)", "WhatsApp automation; ecommerce optimization", "—", 5, "Not 'no website'; included because WhatsApp/DM remains a core conversion path in indexed posts."),
    ("Aksha Trends Jewellery", "akshatrends_jewels", "India", "—", "Temple bangles / jhumkas", "+916383848360", "Not indexed", "Website checkout + WhatsApp queries", "Yes", "https://www.akshatrends.in/", "Verify on Instagram", "Verify on Instagram", "WhatsApp listed for queries alongside website codes", "temple,bangles,WhatsApp", "Hybrid SMB with strong WhatsApp support channel", "WhatsApp automation; CRM", "—", 5, "Website present; still qualifies as WhatsApp-assisted SMB."),
    ("Nakoda Jewellers Merta", "nakoda_jewellers_merta", "Merta City", "Rajasthan", "Kids kada / payal", "Not in snippet", "Not indexed", "Visit / DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Regional jeweller reel surfaced in broad discovery searches", "kids silver,Rajasthan", "Local catalogue IG tone", "Local SEO; CRM", "https://www.google.com/maps/search/Merta+jewellers", 4, "—"),
    ("Pooja Jewellers PJ", "pooja_jewellerpj", "India", "—", "Silver rings / moti", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Silver moti ring reel surfaced in search cross-links", "silver,ring", "SMB silver catalogue content", "CRM; IG shopping", "—", 4, "—"),
    ("Kingz Silver Pune", "kingz_silver.pune", "Pune", "Maharashtra", "925 sterling silver retail", "Not in snippet", "Not indexed", "DM / visit (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Tagged in Pune silver shopping reels as a destination account", "silver,Pune,925", "Local silver shopping SMB discovery via reels", "Local SEO; WhatsApp automation", "https://www.google.com/maps/search/Budhwar+Peth+Pune+silver", 5, "—"),
    ("Silver Kingdom", "silver.kingdom", "India", "—", "Silver retail (verify)", "Not in snippet", "Not indexed", "DM (verify)", "No", "—", "Verify on Instagram", "Verify on Instagram", "Surfaced via silver shopping discovery snippets (metadata sparse)", "silver,DM", "Nano/unknown-size account; verify before outreach", "CRM; IG audits", "—", 3, "Low-confidence metadata; verify category and activity."),
]


def main() -> None:
    # De-dupe rules (practical for Instagram SMBs):
    # - MUST be unique by Instagram handle (primary key)
    # - MUST be unique by business name
    #
    # Note: many SMBs share one WhatsApp desk across multiple post formats/handles.
    # We therefore do NOT globally de-dupe by phone (that would drop valid distinct
    # storefronts). Instead, phone collisions are called out in per-lead Notes when detected.
    seen_handles: set[str] = set()
    seen_names: set[str] = set()

    leads: list[tuple] = []
    for row in LEADS_RAW:
        name, handle, *_ = row
        if handle.lower() in seen_handles:
            continue
        if name.lower() in seen_names:
            continue
        seen_handles.add(handle.lower())
        seen_names.add(name.lower())
        leads.append(row)

    if len(leads) < 100:
        raise SystemExit(f"Expected >=100 unique leads after dedupe, got {len(leads)}")

    leads = leads[:100]

    out_lines: list[str] = []
    out_lines.append("India Jewellery Instagram / WhatsApp Lead Export")
    out_lines.append("Generated from public web-search snippets; verify follower counts, bios, and websites on Instagram before outreach.")
    out_lines.append("Deduping: unique Instagram handles and unique business names (phones may be shared across multiple public posts/handles).")
    out_lines.append("")

    for i, row in enumerate(leads, start=1):
        (
            business,
            handle,
            city,
            state,
            btype,
            wa,
            email,
            ordering,
            webp,
            webu,
            recent,
            engage,
            bio,
            kw,
            reason,
            services,
            maps,
            score,
            notes,
        ) = row
        url = f"https://www.instagram.com/{handle.strip('@')}/"
        out_lines.append("=" * 50)
        out_lines.append(f"LEAD #{i}")
        out_lines.append("=" * 50)
        out_lines.append(f"Business Name: {business}")
        out_lines.append(f"Instagram Handle: @{handle.strip('@')}")
        out_lines.append(f"Instagram URL: {url}")
        out_lines.append("Followers Count: Not available in indexed search snippets (verify on Instagram)")
        out_lines.append(f"City: {city}")
        out_lines.append(f"State: {state}")
        out_lines.append(f"Business Type: {btype}")
        out_lines.append(f"WhatsApp Number: {wa}")
        out_lines.append(f"Email: {email}")
        out_lines.append(f"Ordering Method: {ordering}")
        out_lines.append(f"Website Present: {webp}")
        out_lines.append(f"Website URL: {webu}")
        out_lines.append(f"Recent Activity Date: {recent}")
        out_lines.append(f"Average Engagement: {engage}")
        out_lines.append(f"Bio Text: {bio}")
        out_lines.append(f"Keywords: {kw}")
        out_lines.append(f"Reason Qualified: {reason}")
        out_lines.append(f"Potential Services Needed: {services}")
        out_lines.append(f"Google Maps Link: {maps}")
        out_lines.append(f"Lead Quality Score: {score}/10")
        out_lines.append(f"Notes: {notes}")
        out_lines.append("")

    Path("/workspace/india_jewellery_instagram_leads.txt").write_text("\n".join(out_lines), encoding="utf-8")
    print(f"Wrote 100 leads to india_jewellery_instagram_leads.txt (source rows: {len(LEADS_RAW)})")


if __name__ == "__main__":
    main()
