#!/usr/bin/env python3
"""Assemble india_jewellery_instagram_leads.txt with deduped handles + phones."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True)
class Lead:
    business: str
    handle: str
    city: str
    state: str
    business_type: str
    whatsapp: str
    email: str
    ordering_method: str
    website_present: str
    website_url: str
    recent_activity: str
    avg_engagement: str
    bio_text: str
    keywords: str
    reason_qualified: str
    potential_services: str
    gmaps: str
    score: int
    notes: str


def norm_phone(p: str) -> str | None:
    if not p or p.strip().lower() == "unknown":
        return None
    digits = "".join(ch for ch in p if ch.isdigit())
    if not digits:
        return None
    if digits.startswith("91") and len(digits) > 10:
        digits = digits[-10:]
    if len(digits) == 10:
        return digits
    if len(digits) > 10:
        return digits[-10:]
    return digits


def dedupe(leads: Iterable[Lead]) -> list[Lead]:
    seen_handles: set[str] = set()
    seen_phones: set[str] = set()
    out: list[Lead] = []
    for L in leads:
        h = L.handle.strip().lstrip("@").lower()
        if h in seen_handles:
            continue
        ph = norm_phone(L.whatsapp)
        if ph and ph in seen_phones:
            continue
        seen_handles.add(h)
        if ph:
            seen_phones.add(ph)
        out.append(L)
    return out


UNKNOWN = "Unknown (not available from public web index; verify live on Instagram)"


def fmt(lead: Lead, idx: int) -> str:
    url = f"https://www.instagram.com/{lead.handle.strip().lstrip('@')}/"
    lines = [
        "",
        "=" * 50,
        f"LEAD #{idx}",
        "=" * 50,
        f"Business Name: {lead.business}",
        f"Instagram Handle: @{lead.handle.strip().lstrip('@')}",
        f"Instagram URL: {url}",
        f"Followers Count: {UNKNOWN}",
        f"City: {lead.city}",
        f"State: {lead.state}",
        f"Business Type: {lead.business_type}",
        f"WhatsApp Number: {lead.whatsapp}",
        f"Email: {lead.email}",
        f"Ordering Method: {lead.ordering_method}",
        f"Website Present: {lead.website_present}",
        f"Website URL: {lead.website_url}",
        f"Recent Activity Date: {UNKNOWN}",
        f"Average Engagement: {UNKNOWN}",
        f"Bio Text: {lead.bio_text}",
        f"Keywords: {lead.keywords}",
        f"Reason Qualified: {lead.reason_qualified}",
        f"Potential Services Needed: {lead.potential_services}",
        f"Google Maps Link: {lead.gmaps}",
        f"Lead Quality Score: {lead.score}/10",
        f"Notes: {lead.notes}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    leads: list[Lead] = [
        Lead(
            business="Asha Bangles Official",
            handle="ashabanglesofficial",
            city="Patiala",
            state="Punjab",
            business_type="Punjabi bridal chura / bangles",
            whatsapp="+917014592741",
            email="Unknown",
            ordering_method="WhatsApp; customization; partial COD mentioned in posts",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Public Instagram captions advertise WhatsApp ordering for bridal chura and customization.",
            keywords="punjabi chura, bridal bangles, whatsapp order",
            reason_qualified="India-based bridal jewellery seller using WhatsApp as a primary order channel in indexed captions.",
            potential_services="WhatsApp automation, CRM, ecommerce, IG ads",
            gmaps="Unknown",
            score=8,
            notes="Lead sourced from indexed Instagram post metadata; confirm details on the live profile before outreach.",
        ),
        Lead(
            business="Jewellery Shopper",
            handle="jewellery_shopper_",
            city="Unknown",
            state="India",
            business_type="Silver / fashion jewellery (screenshot-to-order model)",
            whatsapp="+918905291031",
            email="Unknown",
            ordering_method="WhatsApp screenshot-to-order; COD mentioned in captions",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Indexed posts show WhatsApp screenshot ordering flow for silver pieces.",
            keywords="silver jewellery, COD, screenshot order",
            reason_qualified="Classic Instagram-first Indian jewellery workflow with explicit WhatsApp ordering.",
            potential_services="WhatsApp catalog automation, payments, lightweight ecommerce",
            gmaps="Unknown",
            score=7,
            notes="City not explicit in the indexed snippet; verify location and policies on profile.",
        ),
        Lead(
            business="Jodhpuri Silver (Khushbu Jewellers line)",
            handle="jodhpuri_silver",
            city="Jodhpur",
            state="Rajasthan",
            business_type="Silver payal / silver jewellery",
            whatsapp="+919358839704",
            email="Unknown",
            ordering_method="WhatsApp screenshot-to-order; COD mentioned",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Caption language typical of WhatsApp-led silver sellers in Jodhpur cluster.",
            keywords="silver payal, jodhpur, COD",
            reason_qualified="Separate Instagram storefront from the +91 9929595357 cluster; distinct WhatsApp line.",
            potential_services="WhatsApp automation, CRM, ecommerce",
            gmaps="Unknown",
            score=7,
            notes="Keep separate from the +91 9929595357 deduped lead; numbers differ.",
        ),
        Lead(
            business="Khushbu Jewellers Tinwari (deduped hub for +91 9929595357)",
            handle="khushbu_jewellers_tinwari",
            city="Jodhpur region",
            state="Rajasthan",
            business_type="Silver / gold-polish fashion jewellery",
            whatsapp="+919929595357",
            email="Unknown",
            ordering_method="WhatsApp screenshot-to-order; customization and COD mentioned in captions",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Hindi/English captions push WhatsApp screenshot orders and customization.",
            keywords="silversolution, COD, customize, rajasthani silver",
            reason_qualified="High-intent WhatsApp commerce; multiple pages reuse this number—store once as a single operational hub.",
            potential_services="CRM, WhatsApp automation, catalog website, deduped customer inbox",
            gmaps="Unknown",
            score=8,
            notes="DEDUPED: exclude other pages that only repeat +91 9929595357 without a distinct business reason.",
        ),
        Lead(
            business="Biswakarma Jewellery Shilpalaya",
            handle="bjs2k",
            city="Barasat",
            state="West Bengal",
            business_type="Diamond nosepins / earrings; gold jewellery",
            whatsapp="+919874085669",
            email="Unknown",
            ordering_method="WhatsApp for details/orders; delivery messaging in posts",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Posts reference Barasat location and WhatsApp contact for collections and orders.",
            keywords="Barasat, diamond nosepin, whatsapp",
            reason_qualified="Regional jeweller using Instagram with explicit WhatsApp CTAs.",
            potential_services="Local SEO, WhatsApp automation, ecommerce",
            gmaps="https://www.google.com/maps/search/Biswakarma+Jewellery+Shilpalaya+Barasat",
            score=8,
            notes="Validate SMB vs larger showroom on audit; Instagram positioning is SMB-like.",
        ),
        Lead(
            business="Chudiwale Fashion Jewellery",
            handle="chudiwale_",
            city="Unknown",
            state="India",
            business_type="Customized bridal bangles / fashion jewellery",
            whatsapp="+9197972380643",
            email="Unknown",
            ordering_method="WhatsApp for booking and details",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Caption advertises customized bangle sets and WhatsApp booking.",
            keywords="velvet bangle, bridal, customized",
            reason_qualified="Custom orders + WhatsApp booking indicates manual fulfilment suitable for automation tooling.",
            potential_services="WhatsApp automation, IG ads, CRM",
            gmaps="Unknown",
            score=8,
            notes="Strong bridal accessory overlap with jewellery buyers.",
        ),
        Lead(
            business="I Imitation Jewellery",
            handle="i_imitation_jewellery",
            city="Unknown",
            state="India",
            business_type="Imitation necklace and bangles",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="DM for order (caption indexed)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Indexed caption includes DM-to-order language for imitation sets.",
            keywords="imitation jewellery, DM order",
            reason_qualified="Instagram-native ordering signal without a surfaced standalone ecommerce site in the index snippet.",
            potential_services="WhatsApp bridge, lightweight ecommerce, automation",
            gmaps="Unknown",
            score=6,
            notes="WhatsApp not shown in indexed snippet; verify contact method in bio.",
        ),
        Lead(
            business="Lakshmi Creations (imitation jewellery)",
            handle="lakshmi_creations_9",
            city="Unknown",
            state="India",
            business_type="Imitation jewellery wholesale/retail",
            whatsapp="+919849567353",
            email="Unknown",
            ordering_method="WhatsApp for orders and more collections (caption)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Wholesale pricing language; WhatsApp for collections.",
            keywords="imitation, wholesale, jhumkas",
            reason_qualified="Wholesale motion over WhatsApp is operationally heavy and benefits from tooling.",
            potential_services="B2B portal, CRM, WhatsApp automation",
            gmaps="Unknown",
            score=7,
            notes="City not explicit in indexed caption; confirm on profile.",
        ),
        Lead(
            business="Aakanksha Jewellery",
            handle="aakanksha_jewellery",
            city="Mumbai",
            state="Maharashtra",
            business_type="Maharashtrian bridal moti / traditional sets",
            whatsapp="+919324512333",
            email="Unknown",
            ordering_method="WhatsApp for details; DM prompts appear on other posts",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Bridal moti sets with WhatsApp contact lines in indexed posts.",
            keywords="Maharashtrian bride, moti jewellery, bridal",
            reason_qualified="Regional bridal niche with WhatsApp-led discovery and servicing.",
            potential_services="WhatsApp automation, content production, performance ads",
            gmaps="Unknown",
            score=8,
            notes="Confirm absence of a dedicated ecommerce site in bio; not verified from snippet alone.",
        ),
        Lead(
            business="Wedding Answers",
            handle="weddinganswers",
            city="Delhi NCR (shipping tags in posts)",
            state="India",
            business_type="Bridal accessories (chooda boxes, etc.)",
            whatsapp="+918368213149",
            email="Unknown",
            ordering_method="WhatsApp or DM; advance payment policies in captions",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Customized wedding accessory boxes; WhatsApp/DM purchase lines.",
            keywords="chooda box, wedding, customised",
            reason_qualified="Adjacent bridal commerce with strong Instagram plus WhatsApp workflow.",
            potential_services="WhatsApp automation, CRM, ecommerce",
            gmaps="Unknown",
            score=7,
            notes="Not a pure jeweller, but overlaps heavily with bridal jewellery purchase intent.",
        ),
        Lead(
            business="South Indian Temple Jewellery",
            handle="southindian__templejewellery",
            city="Chennai (seller tags)",
            state="Tamil Nadu",
            business_type="Temple / traditional jewellery",
            whatsapp="+917904076978",
            email="Unknown",
            ordering_method="DM or WhatsApp; prepay/UPI style policies referenced",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Public posts include DM/WhatsApp lines and temple-jewellery hashtags.",
            keywords="temple jewellery, south indian, chennai seller",
            reason_qualified="Temple jewellery niche with social selling and WhatsApp routing.",
            potential_services="Community management, WhatsApp automation, ecommerce",
            gmaps="Unknown",
            score=8,
            notes="Some posts reference multiple numbers; confirm the active line on the latest posts.",
        ),
        Lead(
            business="Temple Jewellery Hub by Priya",
            handle="templejewelleryhub_bypriya",
            city="Unknown",
            state="India",
            business_type="Temple jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM (not explicit in indexed snippet)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Indexed posts show priced temple-style listings.",
            keywords="temple, nagas, south indian",
            reason_qualified="Temple jewellery catalogue style posts; good candidate for ecommerce uplift.",
            potential_services="Ecommerce, WhatsApp bridge, CRM",
            gmaps="Unknown",
            score=5,
            notes="Contact method not confirmed in the web index snippet; verify before outreach.",
        ),
        Lead(
            business="Rashi Collection",
            handle="rashi_collection_",
            city="Jaipur",
            state="Rajasthan",
            business_type="Handmade / floral custom celebration jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM (verify on profile)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Collaboration posts position bespoke floral and name jewellery for wedding events.",
            keywords="custom jewellery, jaipur, haldi, mehendi",
            reason_qualified="Custom-order-led maker segment aligned to Instagram discovery.",
            potential_services="Ecommerce, IG shopping, CRM",
            gmaps="Unknown",
            score=6,
            notes="Phone not present in indexed snippet; confirm ordering workflow in bio.",
        ),
        Lead(
            business="Mahandi Artificial",
            handle="mahandi_artificial",
            city="Jaipur",
            state="Rajasthan",
            business_type="Artificial / lightweight gold-look jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM (verify on profile)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Tagged repeatedly as an artificial jewellery supplier in creator posts.",
            keywords="artificial jewellery, jaipur, gold look",
            reason_qualified="Artificial jewellery supplier niche commonly monetized via Instagram DMs.",
            potential_services="Website, ads, WhatsApp automation",
            gmaps="Unknown",
            score=6,
            notes="Verify WhatsApp presence in bio; not shown in snippet.",
        ),
        Lead(
            business="Rajputi Jewellery Wholesaler SC",
            handle="rajputi_jewelery_wholsaler_s.c",
            city="Unknown",
            state="India",
            business_type="Wholesale-forward fashion jewellery",
            whatsapp="+917877634674",
            email="Unknown",
            ordering_method="WhatsApp for price/order; group link mentions in reels",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Wholesale-style captions with WhatsApp-first ordering language.",
            keywords="wholesale, rajputi, instagram reels",
            reason_qualified="WhatsApp-first wholesale motion is CRM-heavy.",
            potential_services="B2B portal, WhatsApp automation, inventory systems",
            gmaps="Unknown",
            score=7,
            notes="Confirm retail policy and legitimacy during qualification.",
        ),
        Lead(
            business="Jewel Indukuri's",
            handle="indukurisjewel",
            city="Hyderabad (inferred; verify)",
            state="Telangana",
            business_type="Lab-grown diamond pendants (customizable)",
            whatsapp="+916302720676",
            email="Unknown",
            ordering_method="WhatsApp for customization details",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Customization requests routed to WhatsApp in indexed reel text.",
            keywords="lab grown diamond, customize, pendant",
            reason_qualified="Custom SKUs with consultative selling over WhatsApp.",
            potential_services="CRM, appointment booking, ecommerce",
            gmaps="Unknown",
            score=7,
            notes="City inferred from regional ecosystem; confirm on profile/about.",
        ),
        Lead(
            business="Pooja Jewels (Unique Jewelryys)",
            handle="unique_jewelryys",
            city="Unknown",
            state="India",
            business_type="Silver fashion jewellery / payal",
            whatsapp="+917597344552",
            email="Unknown",
            ordering_method="WhatsApp; COD available (caption)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Reels mention checking stories for offers; WhatsApp ordering.",
            keywords="silver, COD, smallbusiness",
            reason_qualified="COD plus WhatsApp indicates manual ops suitable for automation.",
            potential_services="WhatsApp automation, payments stack, ecommerce",
            gmaps="Unknown",
            score=8,
            notes="Multiple reels show the same WhatsApp number.",
        ),
        Lead(
            business="Lakshmi Jewells (Sree Wholesale Jewellery)",
            handle="lakshmijewells",
            city="Unknown",
            state="India",
            business_type="South Indian style gold-finish sets (wholesale cues)",
            whatsapp="+919390483697",
            email="Unknown",
            ordering_method="WhatsApp order and enquiry; strict fulfilment notes in captions",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Operational policies (opening video, no COD) typical of WhatsApp-first wholesalers.",
            keywords="wholesale, matte finish, bridal",
            reason_qualified="Operational complexity maps well to CRM and automation upgrades.",
            potential_services="WhatsApp API, ERP connectors, CRM",
            gmaps="Unknown",
            score=7,
            notes="Phone parsed from indexed caption formatting.",
        ),
        Lead(
            business="Jewellery Palace BJS",
            handle="_jewellery_palace_bjs",
            city="Unknown",
            state="India",
            business_type="Traditional nath / nose jewellery",
            whatsapp="+918440038551",
            email="Unknown",
            ordering_method="WhatsApp ordering with product codes",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="WhatsApp order lines with numeric codes in indexed posts.",
            keywords="nath, pech, traditional",
            reason_qualified="Code-based WhatsApp SKU model is a strong automation fit.",
            potential_services="WhatsApp catalog, structured order forms, CRM",
            gmaps="Unknown",
            score=7,
            notes="Good candidate for structured WhatsApp commerce templates.",
        ),
        Lead(
            business="Sujatha Gold Covering Works",
            handle="sujatha_gold_covering_works",
            city="Machilipatnam",
            state="Andhra Pradesh",
            business_type="One-gram gold microplated / AD jewellery",
            whatsapp="+917382222208",
            email="Unknown",
            ordering_method="WhatsApp bookings; COD mentioned; separate bulk line in some posts",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Multiple WhatsApp numbers for retail and bulk in indexed captions.",
            keywords="one gram gold, microplated, machilipatnam",
            reason_qualified="Multi-number wholesale/retail implies inbox fragmentation solvable with CRM.",
            potential_services="CRM, WhatsApp automation, inventory website",
            gmaps="Unknown",
            score=8,
            notes="Confirm which numbers are still active; posts list alternates.",
        ),
        Lead(
            business="Flabel Creations",
            handle="flabelcreations",
            city="Unknown",
            state="India",
            business_type="Fashion / AD jewellery",
            whatsapp="+917711990044",
            email="Unknown",
            ordering_method="WhatsApp (link-in-bio mention) plus DM",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Snippet references WhatsApp and DM with same-day dispatch messaging.",
            keywords="AD jewellery, dispatch, explore",
            reason_qualified="Hybrid DM/WhatsApp selling with urgency messaging.",
            potential_services="WhatsApp automation, ecommerce, checkout",
            gmaps="Unknown",
            score=7,
            notes="Verify whether link-in-bio is Linktree vs a full store; update qualification accordingly.",
        ),
        Lead(
            business="Shree Silver Pune (Silver Jewels Pune)",
            handle="silver_jewels_pune",
            city="Pune",
            state="Maharashtra",
            business_type="925 hallmarked silver jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Shop visit and phone bookings (WhatsApp not confirmed in snippet)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Indexed reel mentions Raviwar Peth address and hallmarked silver.",
            keywords="925 silver, pune, hallmarked",
            reason_qualified="Local retailer using Instagram discovery; likely still SMB.",
            potential_services="Local ads, bookings automation, ecommerce",
            gmaps="https://www.google.com/maps/search/Shree+Silver+Raviwar+Peth+Pune",
            score=6,
            notes="Confirm WhatsApp line in bio; snippet emphasizes call/visit.",
        ),
        Lead(
            business="Varudi Jewellers",
            handle="varudijewellers",
            city="Surat",
            state="Gujarat",
            business_type="Hallmarked gold jewellery (DM retail)",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="DM for instant buy messaging in indexed reels",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="DM-led purchasing language plus safe delivery messaging.",
            keywords="Surat, BIS gold, DM",
            reason_qualified="DM-first retail on Instagram for a local jeweller brand.",
            potential_services="WhatsApp bridge, automation, ecommerce",
            gmaps="https://www.google.com/maps/search/Varudi+Jewellers+Surat",
            score=6,
            notes="WhatsApp not confirmed in snippet; verify on profile.",
        ),
        Lead(
            business="Omkar Jewels Surat",
            handle="omkar_jewels_surat",
            city="Surat",
            state="Gujarat",
            business_type="Custom gold jewellery",
            whatsapp="+918141248248",
            email="Unknown",
            ordering_method="Phone/WhatsApp implied by number in caption; showroom visit",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Custom jewelry positioning with Uttran address in indexed reel.",
            keywords="custom, bespoke, surat",
            reason_qualified="Custom orders plus direct phone contact indicates consultative selling.",
            potential_services="CRM, ecommerce, 3D visualization",
            gmaps="https://www.google.com/maps/search/Omkar+Jewels+Surat",
            score=7,
            notes="Showroom business; still social-led enquiries.",
        ),
        Lead(
            business="Patadia Brothers",
            handle="patadia_brothers",
            city="Vadodara",
            state="Gujarat",
            business_type="Gold jewellery retail",
            whatsapp="+919426765530",
            email="Unknown",
            ordering_method="WhatsApp-only contact phrasing in indexed post",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Post frames new arrivals and asks customers to contact on WhatsApp.",
            keywords="vadodara, gold, whatsapp only",
            reason_qualified="WhatsApp-only routing from a public post is a strong automation signal.",
            potential_services="WhatsApp automation, catalog, CRM",
            gmaps="https://www.google.com/maps/search/Patadia+Brothers+Vadodara",
            score=7,
            notes="Verify whether a separate ecommerce site exists beyond Instagram.",
        ),
        Lead(
            business="Pukhraj Jewellers",
            handle="pukhraj.jewellers1",
            city="Ahmedabad",
            state="Gujarat",
            business_type="22K antique gold rings; customization",
            whatsapp="+919409151772",
            email="Unknown",
            ordering_method="DM and WhatsApp/call (caption)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="All India delivery; customization and hallmark language in indexed caption.",
            keywords="antique gold, satellite, customization",
            reason_qualified="DM plus WhatsApp plus customization is a services-rich SMB profile.",
            potential_services="CRM, automation, ecommerce",
            gmaps="https://www.google.com/maps/search/Pukhraj+Jewellers+Satellite+Ahmedabad",
            score=7,
            notes="Physical store present; still social-led enquiries.",
        ),
        Lead(
            business="Lavanya Jewellers SLJ",
            handle="lavanyajewellers_slj",
            city="Vijayawada",
            state="Andhra Pradesh",
            business_type="916 gold / diamond pendants / kasu jewellery",
            whatsapp="+919441176530",
            email="Unknown",
            ordering_method="DM or WhatsApp; customized orders",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Shipping India/USA references alongside DM/WhatsApp contact lines.",
            keywords="gold, kasu, bridal, temple",
            reason_qualified="Custom orders plus WhatsApp servicing for gold jewellery.",
            potential_services="CRM, international shipping stack, ecommerce",
            gmaps="Unknown",
            score=7,
            notes="Validate SMB sizing; some gold retailers scale quickly.",
        ),
        Lead(
            business="Cenora Jewels",
            handle="cenorajewels",
            city="Unknown",
            state="India",
            business_type="Fashion jewellery promos",
            whatsapp="+917021923226",
            email="Unknown",
            ordering_method="DM and WhatsApp (caption)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Offer-led captions referencing DM/WhatsApp ordering.",
            keywords="offer, buy 1 get 1, explore",
            reason_qualified="Offer-led Instagram selling with explicit WhatsApp line.",
            potential_services="Ads, WhatsApp automation, fraud safeguards",
            gmaps="Unknown",
            score=6,
            notes="Light evidence; do extra legitimacy checks before outreach.",
        ),
        Lead(
            business="Lucknow Artificial Jewellery",
            handle="lucknow_artificial_jewellery_",
            city="Lucknow",
            state="Uttar Pradesh",
            business_type="One-gram gold polish imitation jewellery",
            whatsapp="+918957754721",
            email="Unknown",
            ordering_method="Booking number for orders; COD shipping language",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="City-branded account with COD and India shipping claims.",
            keywords="lucknow, imitation, COD",
            reason_qualified="City-specific Instagram shop with COD fits SMB Instagram commerce.",
            potential_services="Ecommerce, payments, automation",
            gmaps="https://www.google.com/maps/search/Lucknow+artificial+jewellery",
            score=8,
            notes="Strong local SEO angle for Lucknow campaigns.",
        ),
        Lead(
            business="Sai Jewellers Rajat (Ujjain)",
            handle="sai_jewellers_rajat_ujjain",
            city="Ujjain",
            state="Madhya Pradesh",
            business_type="1gm gold-plated jewellery",
            whatsapp="+917024274632",
            email="Unknown",
            ordering_method="WhatsApp/DM (captions and comments indexed)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Gold-plated chains and lightweight sets marketed for WhatsApp/DM.",
            keywords="1gm gold, ujjain, plated",
            reason_qualified="Price-sensitive segment with manual WhatsApp selling.",
            potential_services="WhatsApp automation, catalog site",
            gmaps="https://www.google.com/maps/search/Sai+Jewellers+Ujjain",
            score=7,
            notes="Multiple indexed interactions reference the same number.",
        ),
        Lead(
            business="Mahalaxmi Jwellers",
            handle="mahalaxmi_gold99",
            city="Mysuru",
            state="Karnataka",
            business_type="916 hallmark casting chains",
            whatsapp="+919880820391",
            email="Unknown",
            ordering_method="DM and WhatsApp numbers in captions",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Multi-region tags with WhatsApp lines for enquiries.",
            keywords="gold chain, casting, hallmark",
            reason_qualified="Dual DM/WhatsApp CTA pattern is common for SMB jewellers.",
            potential_services="CRM, automation, ecommerce",
            gmaps="Unknown",
            score=7,
            notes="Second number may appear; confirm primary on latest posts.",
        ),
        Lead(
            business="Jewels of Karnataka",
            handle="jewelsofkarnataka",
            city="Bengaluru",
            state="Karnataka",
            business_type="One-gram gold fashion earrings",
            whatsapp="+919740234813",
            email="Unknown",
            ordering_method="WhatsApp contact in indexed caption",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="JK collection language with WhatsApp routing.",
            keywords="one gram gold, karnataka",
            reason_qualified="WhatsApp-led SKU selling for lightweight fashion jewellery.",
            potential_services="WhatsApp automation, ecommerce",
            gmaps="Unknown",
            score=7,
            notes="Confirm exact operating base; name implies Karnataka focus.",
        ),
        Lead(
            business="Vernika Silver",
            handle="vernika.silver.jewellery",
            city="Bengaluru",
            state="Karnataka",
            business_type="92.5 silver jewellery",
            whatsapp="+917406810666",
            email="Unknown",
            ordering_method="Phone bookings and video-call shopping (WhatsApp not explicit in snippet)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Avenue Road and Raja Market addresses in indexed reel.",
            keywords="925 silver, avenue road, chikpete",
            reason_qualified="Hybrid offline plus remote selling via phone/video.",
            potential_services="Bookings automation, ecommerce, ads",
            gmaps="https://www.google.com/maps/search/Vernika+Silver+Avenue+Road+Bengaluru",
            score=6,
            notes="Confirm WhatsApp availability in bio; snippet emphasizes phone.",
        ),
        Lead(
            business="Rohit Bhai Jewellers",
            handle="RohitBhaiJewellers",
            city="Delhi",
            state="Delhi",
            business_type="916 antique bridal gold",
            whatsapp="+919953916916",
            email="Unknown",
            ordering_method="WhatsApp/contact lines with showroom visit prompts",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Chandni Chowk address and hallmark-forward messaging.",
            keywords="chandni chowk, antique choker, bridal",
            reason_qualified="Traditional market jeweller using Reels plus WhatsApp routing.",
            potential_services="Omnichannel, CRM, ads",
            gmaps="https://www.google.com/maps/search/Rohit+Bhai+Jewellers+Chandni+Chowk",
            score=6,
            notes="Old Delhi showroom; verify SMB fit vs larger operation.",
        ),
        Lead(
            business="BJH Jewels Karol Bagh",
            handle="bjhjewels_karolbagh",
            city="New Delhi",
            state="Delhi",
            business_type="Natural diamond wholesale/retail",
            whatsapp="+919354357066",
            email="Unknown",
            ordering_method="DM and WhatsApp; wholesale mention",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Karol Bagh Bank Street address with DM for info prompts.",
            keywords="diamond, HUID, karol bagh",
            reason_qualified="DM/WhatsApp-led enquiries for a Karol Bagh jewellery office.",
            potential_services="B2B portal, CRM, automation",
            gmaps="https://www.google.com/maps/search/BJH+Jewels+Karol+Bagh",
            score=6,
            notes="Wholesale positioning; confirm SMB vs enterprise during qualification.",
        ),
        Lead(
            business="Nikhil Jewellery Hyderabad",
            handle="nikhiljewelleryhyderabad",
            city="Hyderabad",
            state="Telangana",
            business_type="916 gold regional specialty pieces",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM for catalogue reels (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Hyderabad locality tags in indexed reels.",
            keywords="puligoru, hyderabad, gold",
            reason_qualified="Regional gold catalogue content distributed on Instagram.",
            potential_services="WhatsApp automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Phone not in snippet; verify contact method in bio.",
        ),
        Lead(
            business="Gobind Jewellers",
            handle="gobindjewellers",
            city="Durgapur",
            state="West Bengal",
            business_type="Hallmark gold and silver mix",
            whatsapp="+919593222111",
            email="Unknown",
            ordering_method="Call/WhatsApp implied; showroom-first",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Chandidas Market address in indexed post.",
            keywords="durgapur, hallmark, bridal",
            reason_qualified="Local market jeweller using Instagram promos with phone contact.",
            potential_services="Local performance marketing, CRM",
            gmaps="https://www.google.com/maps/search/Gobind+Jewellers+Durgapur",
            score=6,
            notes="Showroom-first; verify website absence.",
        ),
        Lead(
            business="Rajshree Jewellers Hyderabad",
            handle="rajshreejewellers",
            city="Hyderabad",
            state="Telangana",
            business_type="Gold jewellery showroom content",
            whatsapp="+919000070515",
            email="Unknown",
            ordering_method="Phone contact; DM likely",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Manikonda showroom promos in indexed reels.",
            keywords="nakshi, 22k, showroom",
            reason_qualified="Showroom jeweller using Instagram discovery.",
            potential_services="Omnichannel, ads, CRM",
            gmaps="https://www.google.com/maps/search/Rajshree+Jewellers+Manikonda",
            score=5,
            notes="May be larger showroom; verify SMB fit.",
        ),
        Lead(
            business="Safa Bangles",
            handle="safa_bangles",
            city="Hyderabad",
            state="Telangana",
            business_type="Hyderabadi bridal chudi/bangles",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Hyderabadi bride and walima positioning in indexed reels.",
            keywords="chudiya, hyderabad, bridal",
            reason_qualified="Bridal bangle niche adjacent to jewellery sets.",
            potential_services="WhatsApp automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Contact truncated in search index; verify on profile.",
        ),
        Lead(
            business="A Foodie Rider (Albeli 1gm Jewellery Pune feature)",
            handle="afoodierider",
            city="Pune",
            state="Maharashtra",
            business_type="1gm imitation jewellery discovery content",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Showroom visit (DM/WhatsApp not confirmed in snippet)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Lists Albeli showroom branches in Pune captions.",
            keywords="1gm gold, pune, laxmi road",
            reason_qualified="Creator-led discovery of SMB jewellery retail in Pune.",
            potential_services="Local SEO, IG commerce, partnerships",
            gmaps="https://www.google.com/maps/search/Albeli+1gm+jewellery+Pune",
            score=4,
            notes="This is primarily a creator account; use it to locate the brand-owned handle if needed.",
        ),
        Lead(
            business="I Am Surat City (Attrangi feature)",
            handle="iamsuratcity",
            city="Surat",
            state="Gujarat",
            business_type="Featured jewellery retail (Attrangi)",
            whatsapp="+917990782270",
            email="Unknown",
            ordering_method="Phone contact shown for featured retailer",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="IFC Vesu address and phone line in a feature reel.",
            keywords="surat, personalised shopping, retail",
            reason_qualified="City promo content still surfaces direct phone contact for a jewellery retailer.",
            potential_services="Ads, CRM, landing pages",
            gmaps="https://www.google.com/maps/search/Attrangi+Jewellery+Surat",
            score=5,
            notes="Feature account; cross-check the brand-owned Instagram separately.",
        ),
        Lead(
            business="MIHARA Gold & Diamonds",
            handle="mihara_gold_n_diamonds",
            city="Kochi",
            state="Kerala",
            business_type="Gold and diamond retail",
            whatsapp="+919072464916",
            email="Unknown",
            ordering_method="WhatsApp and call; online purchase language in posts",
            website_present="Unknown",
            website_url="Unknown (verify)",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Multiple Kochi branch references with WhatsApp numbers in indexed posts.",
            keywords="kochi, gold, diamonds, whatsapp",
            reason_qualified="WhatsApp-first servicing with Instagram catalogue distribution.",
            potential_services="Omnichannel, CRM, automation",
            gmaps="https://www.google.com/maps/search/Mihara+Gold+and+Diamonds+Kochi",
            score=6,
            notes="Also lists +91 9778269916 in posts; confirm primary line; multi-branch risk.",
        ),
        Lead(
            business="Chennai Gold Covering (page)",
            handle="covering_jewellery_chennai_62",
            city="Chennai",
            state="Tamil Nadu",
            business_type="Gold covering / lightweight fashion gold",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-indexed Instagram results for Chennai gold covering niche.",
            keywords="gold covering, chennai, reels",
            reason_qualified="Niche SMB Instagram vertical common in South India.",
            potential_services="WhatsApp automation, ecommerce, ads",
            gmaps="Unknown",
            score=5,
            notes="Contact not extracted reliably from index; verify on profile.",
        ),
        Lead(
            business="AMA Gold Covering Chennai",
            handle="ama_gold_covering_chennai",
            city="Chennai",
            state="Tamil Nadu",
            business_type="Gold covering jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Appeared in niche search results for Chennai gold covering sellers.",
            keywords="gold covering, chennai",
            reason_qualified="Niche manufacturing/retail style Instagram segment.",
            potential_services="Catalog site, automation, ads",
            gmaps="Unknown",
            score=5,
            notes="Verify phone in bio; not in snippet.",
        ),
        Lead(
            business="Rathi Gold Covering",
            handle="rathigoldcovering",
            city="Chennai",
            state="Tamil Nadu",
            business_type="Gold covering jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Appeared in niche search results for Chennai gold covering sellers.",
            keywords="gold covering, chennai",
            reason_qualified="Same niche cluster as other covering accounts; good list expansion seed.",
            potential_services="WhatsApp automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Verify legitimacy and contact lines on profile.",
        ),
        Lead(
            business="SK Gold Covering",
            handle="sk_gold_covering",
            city="Chennai",
            state="Tamil Nadu",
            business_type="Gold covering jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Appeared in niche search results for Chennai gold covering sellers.",
            keywords="gold covering, chennai",
            reason_qualified="Niche SMB cluster discovered via HTML search sampling.",
            potential_services="Automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Hari Jewellery HJ",
            handle="hari_jewellery_hj",
            city="Chennai",
            state="Tamil Nadu",
            business_type="Fashion/gold covering jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via niche search clustering for Chennai covering sellers.",
            keywords="jewellery, chennai, reels",
            reason_qualified="Candidate for follow-up enrichment from profile bio.",
            potential_services="WhatsApp automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Low confidence until bio is opened.",
        ),
        Lead(
            business="MR Gold Covering",
            handle="m_r_gold_covering_",
            city="Chennai",
            state="Tamil Nadu",
            business_type="Gold covering jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via niche search clustering for Chennai gold covering sellers.",
            keywords="gold covering, chennai",
            reason_qualified="Same cluster; useful for geo campaigns.",
            potential_services="Automation, ads",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Indian Kundan Jewelry",
            handle="indian_kundan_jewelry",
            city="Unknown",
            state="India",
            business_type="Kundan / traditional jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for kundan-focused Instagram pages.",
            keywords="kundan, traditional, instagram",
            reason_qualified="Traditional jewellery niche commonly sold via DMs.",
            potential_services="Ecommerce, ads, automation",
            gmaps="Unknown",
            score=5,
            notes="Enrich from profile before outreach.",
        ),
        Lead(
            business="Temple Jewellery (underscore brand)",
            handle="temple__jewellery_",
            city="Unknown",
            state="India",
            business_type="Temple jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for temple jewellery pages.",
            keywords="temple jewellery, south indian",
            reason_qualified="Temple jewellery is a high-intent bridal category on Instagram.",
            potential_services="WhatsApp automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Temple Jewellery Collection",
            handle="temple_jewellerycollection",
            city="Unknown",
            state="India",
            business_type="Temple jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for temple jewellery pages.",
            keywords="temple, collection, instagram",
            reason_qualified="Catalog-heavy niche suitable for structured commerce.",
            potential_services="Ecommerce, CRM",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Rathi Temple Jewels",
            handle="rathi_templejewels",
            city="Unknown",
            state="India",
            business_type="Temple jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for temple jewellery pages.",
            keywords="temple, rathi, jewels",
            reason_qualified="Temple niche listing for enrichment and outreach testing.",
            potential_services="Automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Traditional South Indian Jewel",
            handle="traditional_south_indian_jewel",
            city="Unknown",
            state="India",
            business_type="South Indian traditional jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for south Indian jewellery pages.",
            keywords="south indian, traditional, jewel",
            reason_qualified="Broad niche handle worth enriching from bio and posts.",
            potential_services="Content, ads, automation",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Jewellss by Sukritiii",
            handle="jewellss_by_sukritiii",
            city="Unknown",
            state="India",
            business_type="Fashion jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for jewellery creator storefronts.",
            keywords="fashion jewellery, instagram shop",
            reason_qualified="Creator-brand pattern often monetizes via DMs.",
            potential_services="IG shop, automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Jewelry by Arlene",
            handle="jewelry_by_arlene",
            city="Unknown",
            state="India",
            business_type="Fashion jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for jewellery creator storefronts.",
            keywords="fashion jewellery, creator",
            reason_qualified="Creator-brand pattern often monetizes via DMs.",
            potential_services="IG shop, automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Shas Jewelry",
            handle="shas.jewelry",
            city="Unknown",
            state="India",
            business_type="Fashion jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for jewellery creator storefronts.",
            keywords="jewelry, instagram",
            reason_qualified="SMB-style handle for enrichment.",
            potential_services="Automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Silver Cravings Jewellery",
            handle="silvercravingsjewellery",
            city="Unknown",
            state="India",
            business_type="Silver jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for silver jewellery pages.",
            keywords="silver, cravings",
            reason_qualified="Silver niche commonly uses WhatsApp for orders.",
            potential_services="WhatsApp automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Silver Jewellery MLS",
            handle="silverjewellery.mls",
            city="Unknown",
            state="India",
            business_type="Silver jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for silver jewellery pages.",
            keywords="silver, MLS",
            reason_qualified="Silver niche listing for enrichment.",
            potential_services="Automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Rajesh Silver Jewellery",
            handle="rajesh_silver_jewellery",
            city="Unknown",
            state="India",
            business_type="Silver jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for silver jewellery pages.",
            keywords="silver, rajesh",
            reason_qualified="Silver niche listing for enrichment.",
            potential_services="Automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Nakshatra Jewels",
            handle="nakshatra_jewels",
            city="Unknown",
            state="India",
            business_type="Fashion/traditional jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for jewellery brand handles.",
            keywords="nakshatra, jewels",
            reason_qualified="Brand-style handle for enrichment.",
            potential_services="Ecommerce, ads",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Nakshatra Jewellery 3",
            handle="nakshatra_jewellery_3",
            city="Unknown",
            state="India",
            business_type="Fashion/traditional jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for jewellery brand handles.",
            keywords="nakshatra, jewellery",
            reason_qualified="Brand-style handle for enrichment.",
            potential_services="Ecommerce, ads",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Niranjanam Jewellery",
            handle="niranjanam_jewellery",
            city="Unknown",
            state="India",
            business_type="Traditional jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for traditional jewellery pages.",
            keywords="traditional, jewellery",
            reason_qualified="Traditional jewellery niche for enrichment.",
            potential_services="Automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Galista Jewels",
            handle="galista__jewels",
            city="Unknown",
            state="India",
            business_type="Fashion jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for jewellery brand handles.",
            keywords="galista, jewels",
            reason_qualified="Brand-style handle for enrichment.",
            potential_services="IG shop, ads",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Blysss Studio",
            handle="blysssstudio",
            city="Unknown",
            state="India",
            business_type="Jewellery / accessories studio",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for studio-style jewellery pages.",
            keywords="studio, jewellery",
            reason_qualified="Studio-style SMB often sells via DMs.",
            potential_services="Ecommerce, automation",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Indian Jwellery",
            handle="indian.jwellery",
            city="Unknown",
            state="India",
            business_type="Mixed Indian jewellery content",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for broad Indian jewellery pages.",
            keywords="indian jewellery, instagram",
            reason_qualified="Broad handle; enrich before outreach.",
            potential_services="Ads, automation",
            gmaps="Unknown",
            score=4,
            notes="Low specificity; verify business legitimacy.",
        ),
        Lead(
            business="Kankanam",
            handle="kankanam_",
            city="Unknown",
            state="India",
            business_type="Traditional jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for traditional jewellery pages.",
            keywords="traditional, kankanam",
            reason_qualified="Traditional niche handle for enrichment.",
            potential_services="Ecommerce, automation",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Artify Indiaaa",
            handle="artifyindiaaa",
            city="Unknown",
            state="India",
            business_type="Fashion jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for fashion jewellery pages.",
            keywords="artify, fashion",
            reason_qualified="Fashion jewellery SMB candidate.",
            potential_services="IG shop, ads",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Oxidised Jewellery Wholesaler",
            handle="oxidised_jewellery_wholesaler",
            city="Unknown",
            state="India",
            business_type="Oxidised / German silver jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for oxidised jewellery wholesalers.",
            keywords="oxidised, wholesale",
            reason_qualified="Wholesale oxidised niche often uses Instagram catalogues.",
            potential_services="B2B portal, automation",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Wholesale Kundan Jewelery",
            handle="wholesalekundanjewelery",
            city="Unknown",
            state="India",
            business_type="Kundan wholesale catalogue",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for wholesale kundan pages.",
            keywords="kundan, wholesale",
            reason_qualified="Wholesale catalogue pattern maps to CRM needs.",
            potential_services="CRM, automation, B2B site",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Tikamdas1234",
            handle="tikamdas1234",
            city="Unknown",
            state="India",
            business_type="Diamond/polki style jewellery posts",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling for polki/jadau style pages.",
            keywords="polki, jadau, diamond",
            reason_qualified="High-ticket lookbooks often start as DM-led sales.",
            potential_services="CRM, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Silver Palace 45",
            handle="silver_palace45",
            city="Unknown",
            state="India",
            business_type="Silver jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Appeared as a source account in indexed Instagram comment threads.",
            keywords="silver, palace",
            reason_qualified="Silver niche candidate for enrichment.",
            potential_services="Automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="KPR Jewellery",
            handle="kpr_jewellery",
            city="Unknown",
            state="India",
            business_type="Jewellery retail posts",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Appeared in indexed Instagram results tied to jewellery posts.",
            keywords="KPR, jewellery",
            reason_qualified="Candidate for enrichment from bio.",
            potential_services="Ecommerce, ads",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Chithus Jewel World",
            handle="chithus_jewel_world",
            city="Perundurai",
            state="Tamil Nadu",
            business_type="Imitation/fashion jewellery (stall events)",
            whatsapp="+919865299960",
            email="Unknown",
            ordering_method="Phone/WhatsApp implied by indexed stall promo",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Stall promo posts reference contact number for offers.",
            keywords="erode, stall, imitation",
            reason_qualified="Event/stall selling pattern with direct phone contact.",
            potential_services="CRM, IG ads, ecommerce",
            gmaps="https://www.google.com/maps/search/Perundurai+URC+mini+hall",
            score=6,
            notes="Sourced from indexed collaboration/stall post; confirm year-round operations.",
        ),
        Lead(
            business="Wear and Shine Jewelry",
            handle="wear_nd_shine_jewelry",
            city="Unknown",
            state="India",
            business_type="Fashion jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Appeared in indexed Instagram results tied to jewellery posts.",
            keywords="fashion jewellery, shine",
            reason_qualified="SMB candidate for enrichment.",
            potential_services="Automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Trend Jewelryys",
            handle="trend_jewelryys",
            city="Unknown",
            state="India",
            business_type="Fashion jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Appeared in indexed Instagram results tied to jewellery posts.",
            keywords="trend, jewelry",
            reason_qualified="SMB candidate for enrichment.",
            potential_services="Ads, automation",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Swarnam Varnam",
            handle="swarnam_varnam",
            city="Unknown",
            state="India",
            business_type="Traditional jewellery posts",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Appeared in indexed Instagram results tied to jewellery posts.",
            keywords="traditional, swarnam",
            reason_qualified="Traditional niche candidate for enrichment.",
            potential_services="Content, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="Just Kundan",
            handle="just_kundan",
            city="Unknown",
            state="India",
            business_type="Kundan jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Appeared in indexed Instagram results tied to kundan posts.",
            keywords="kundan, bridal",
            reason_qualified="Kundan niche candidate for enrichment.",
            potential_services="Ecommerce, automation",
            gmaps="Unknown",
            score=5,
            notes="Profile verification required.",
        ),
        Lead(
            business="GC Diamond Jewels",
            handle="gcdiamondjewels",
            city="New Delhi",
            state="Delhi",
            business_type="Diamond jewellery (Karol Bagh area cues)",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM (verify)",
            website_present="Unknown",
            website_url="Unknown (verify)",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Karol Bagh diamond jeweller style posts appear in search indexes.",
            keywords="diamond, karol bagh, delhi",
            reason_qualified="DM-led luxury SKU enquiries common for Karol Bagh offices.",
            potential_services="CRM, secure client portal, ads",
            gmaps="https://www.google.com/maps/search/GC+Diamond+Jewels+Karol+Bagh",
            score=5,
            notes="Verify phone and website presence on profile; may be larger showroom.",
        ),
        Lead(
            business="JK Jewellers Jodhpur",
            handle="jkjewellersjodhpur36",
            city="Jodhpur",
            state="Rajasthan",
            business_type="92.5 silver jewellery wholesale/retail",
            whatsapp="+918619090636",
            email="Unknown",
            ordering_method="DM and WhatsApp (caption)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Indexed captions include JUST DM US plus WhatsApp number for silver lines.",
            keywords="silver, jodhpur, wholesale",
            reason_qualified="DM plus WhatsApp dual channel for silver catalogue selling.",
            potential_services="WhatsApp automation, ecommerce, inventory",
            gmaps="https://www.google.com/maps/search/JK+Jewellers+Jodhpur",
            score=8,
            notes="Handle inferred from branded hashtag in indexed posts; confirm handle spelling live.",
        ),
        Lead(
            business="Klitz Jewellery",
            handle="klitz_jewellery",
            city="Mumbai",
            state="Maharashtra",
            business_type="Anti-tarnish fashion jewellery (B2B wholesale positioning)",
            whatsapp="+918433572955",
            email="Unknown",
            ordering_method="DM for catalogue; WhatsApp wa.me link referenced in third-party index",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Third-party creator index shows DM-for-catalogue and WhatsApp line.",
            keywords="mumbai, wholesale, anti tarnish",
            reason_qualified="Explicit WhatsApp discovery path even if primary sales are B2B.",
            potential_services="B2B portal, WhatsApp automation, CRM",
            gmaps="Unknown",
            score=7,
            notes="Cross-check bio on Instagram; third-party indexes can be stale.",
        ),
        Lead(
            business="Kapoor Bangles",
            handle="kapoorbangles",
            city="New Delhi",
            state="Delhi",
            business_type="1 gram gold jewellery wholesale",
            whatsapp="+919310820050",
            email="Unknown",
            ordering_method="WhatsApp wa.me discovery referenced in third-party index",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Karol Bagh beadon pura address appears in third-party creator index.",
            keywords="1gm gold, karol bagh, wholesale",
            reason_qualified="Manufacturer positioning with WhatsApp discovery fits SMB tooling upsell.",
            potential_services="WhatsApp automation, B2B site, CRM",
            gmaps="https://www.google.com/maps/search/Kapoor+Bangles+Karol+Bagh",
            score=7,
            notes="Cross-check bio on Instagram; third-party indexes can be stale.",
        ),
        Lead(
            business="Shuma Jewellers",
            handle="shuma_jewellery",
            city="Unknown",
            state="India",
            business_type="Jewellery (recommended adjacent brand)",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Appears as a related creator in third-party jewellery indexes; treat as enrichment seed.",
            keywords="jewellery, wholesale, instagram",
            reason_qualified="Discovered as a clustered related brand to other WhatsApp-heavy sellers.",
            potential_services="Automation, ecommerce",
            gmaps="Unknown",
            score=4,
            notes="Low confidence seed; must be enriched from Instagram bio before outreach.",
        ),
        Lead(
            business="ST Wholesale",
            handle="st_wholesale07",
            city="Unknown",
            state="India",
            business_type="Wholesale jewellery (related creator seed)",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Appears as a related creator in third-party jewellery indexes; treat as enrichment seed.",
            keywords="wholesale, instagram",
            reason_qualified="Wholesale cluster seed for further qualification.",
            potential_services="B2B portal, automation",
            gmaps="Unknown",
            score=4,
            notes="Low confidence seed; verify business type is jewellery before outreach.",
        ),
        Lead(
            business="Jadau Jewellery by Falguni Mehta",
            handle="jadaujewellerybyfalgunimehta",
            city="Mumbai",
            state="Maharashtra",
            business_type="Designer jadau / bridal jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM (verify)",
            website_present="Unknown",
            website_url="Unknown (verify)",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Frequently tagged in Mumbai bridal content as jewellery source.",
            keywords="jadau, designer, bridal",
            reason_qualified="Designer bridal jewellery commonly closes via DMs and appointments.",
            potential_services="CRM, ecommerce, lookbook site",
            gmaps="Unknown",
            score=5,
            notes="May be premium designer; verify SMB fit vs luxury atelier with full ecommerce.",
        ),
        Lead(
            business="Padmakshya Jaipur",
            handle="padmakshya_jaipur",
            city="Jaipur",
            state="Rajasthan",
            business_type="Silver / moissanite / heritage jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM (verify)",
            website_present="Unknown",
            website_url="Unknown (verify)",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Indexed posts position Jaipur heritage jewellery styling and collections.",
            keywords="jaipur, silver, moissanite, heritage",
            reason_qualified="Jaipur jewellery brand with strong Instagram catalogue behavior.",
            potential_services="Ecommerce, ads, CRM",
            gmaps="https://www.google.com/maps/search/Padmakshya+Jaipur",
            score=5,
            notes="Verify whether a standalone ecommerce site exists; upgrade qualification accordingly.",
        ),
        Lead(
            business="Kattam",
            handle="kattam.in",
            city="Unknown",
            state="India",
            business_type="Jewellery / design brand (handle resembles domain)",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Unknown (verify)",
            website_present="Unknown",
            website_url="Unknown (verify)",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Discovered via search-index sampling; handle resembles a domain brand.",
            keywords="brand, jewellery, instagram",
            reason_qualified="Candidate lead; may or may not match strict no-website filter after verification.",
            potential_services="Brand site, ecommerce, automation",
            gmaps="Unknown",
            score=3,
            notes="High risk of failing the no-website filter; verify carefully before counting as qualified prospect.",
        ),
        Lead(
            business="Naresh Choudhary (925 silver mangalsutra seller)",
            handle="naresh_choudhary916",
            city="Unknown",
            state="India",
            business_type="925 silver mangalsutra / silver jewellery",
            whatsapp="+919828661180",
            email="Unknown",
            ordering_method="DM for order; COD available (indexed caption)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Indexed post advertises pure silver 925 mangalsutra with DM ordering and India COD shipping language.",
            keywords="925, mangalsutra, COD, DM order",
            reason_qualified="DM-first silver SKU selling with COD claims fits Instagram-native SMB workflows.",
            potential_services="WhatsApp automation, ecommerce, payments",
            gmaps="Unknown",
            score=7,
            notes="Handle confirmed via Instagram post footer (“More posts from …”).",
        ),
        Lead(
            business="Silver Attractions",
            handle="silver.attractions",
            city="Unknown",
            state="India",
            business_type="925 / rose-gold solitaire style silver jewellery",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify on profile)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Indexed posts position limited-stock 92.5 silver jewellery with India shipping language.",
            keywords="925, silver, solitaire, shipping",
            reason_qualified="Silver catalogue account surfaced in public HTML fetches; needs bio enrichment.",
            potential_services="Ecommerce, WhatsApp automation, ads",
            gmaps="Unknown",
            score=6,
            notes="Handle confirmed via Instagram post footer (“More posts from …”).",
        ),
        Lead(
            business="Jewels by Shreya (Jewelsbyshreya)",
            handle="jewelsbyshreyasethi",
            city="Unknown",
            state="India",
            business_type="Fashion jewellery (kundan to western)",
            whatsapp="+919896346090",
            email="Unknown",
            ordering_method="Screenshot via DM or WhatsApp (brand write-up); WhatsApp line published in third-party article",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Third-party brand profile describes screenshot-to-order via DM/WhatsApp for pricing and availability.",
            keywords="fashion jewellery, DM, WhatsApp, screenshot order",
            reason_qualified="Explicit DM/WhatsApp ordering motion aligned to the mission profile.",
            potential_services="CRM, WhatsApp automation, ecommerce",
            gmaps="Unknown",
            score=8,
            notes="Cross-check WhatsApp and policies on the live Instagram bio; third-party articles can be stale.",
        ),
        Lead(
            business="Shreya Collection",
            handle="_shreyacollection",
            city="Unknown",
            state="India",
            business_type="Fashion / imitation jewellery reels",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Appears as an active reels-first jewellery collection account in public HTML sampling.",
            keywords="collection, reels, jewellery",
            reason_qualified="Reels-first jewellery storefront pattern; enrich contacts from bio.",
            potential_services="IG shop, ads, automation",
            gmaps="Unknown",
            score=5,
            notes="Handle confirmed via Instagram reel footer (“More posts from …”).",
        ),
        Lead(
            business="Nirvi Reddy Silver Jewels",
            handle="nr_silver_jewels",
            city="Unknown",
            state="India",
            business_type="Silver jewellery (Swarovski/live sale style posts)",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="WhatsApp screenshots for post-live enquiries (verify number formatting on profile)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Indexed reels mention sending screenshots on WhatsApp after live sessions.",
            keywords="silver, swarovski, live sale",
            reason_qualified="Live-sale + WhatsApp screenshot workflow is automation-heavy.",
            potential_services="WhatsApp automation, CRM, catalog site",
            gmaps="Unknown",
            score=6,
            notes="Some indexes garble the WhatsApp formatting; confirm the exact number on the profile.",
        ),
        Lead(
            business="Khushbu Jewellers (alternate page)",
            handle="khushbu_jewellers_1",
            city="Unknown",
            state="India",
            business_type="Silver / fashion jewellery (Khushbu network)",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely WhatsApp screenshot-to-order (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Appears in public Instagram threads related to screenshot-to-order silver catalogue posts.",
            keywords="khushbu, silver, screenshot order",
            reason_qualified="Satellite page pattern common in Indian WhatsApp-first jewellery networks; enrich separately from the deduped +91 9929595357 hub lead.",
            potential_services="CRM dedupe, WhatsApp automation, ecommerce",
            gmaps="Unknown",
            score=5,
            notes="Do not merge automatically with khushbu_jewellers_tinwari; confirm ownership and phone lines.",
        ),
        Lead(
            business="Rajputii Jewelleryy (Jskimitation)",
            handle="rajputii_jewelleryy",
            city="Unknown",
            state="India",
            business_type="Rajputi / imitation jewellery",
            whatsapp="+919680638433",
            email="Unknown",
            ordering_method="DM enquiries; WhatsApp group link referenced in third-party creator index",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Third-party creator index lists a direct contact line and WhatsApp community join language.",
            keywords="rajputi, imitation, DM, whatsapp group",
            reason_qualified="WhatsApp group + DM hybrid distribution is a strong automation and moderation opportunity.",
            potential_services="Community tooling, WhatsApp automation, catalog site",
            gmaps="Unknown",
            score=7,
            notes="Third-party index data; verify the WhatsApp group link and contact line on Instagram before outreach.",
        ),
        Lead(
            business="Jeweave Wholesale Jewellery",
            handle="jeweave_",
            city="New Delhi",
            state="Delhi",
            business_type="Wholesale Indian/Korean anti-tarnish jewellery",
            whatsapp="+919220383731",
            email="Unknown",
            ordering_method="WhatsApp wholesale lines (second line may exist: +91 7291914990)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Wholesale-only positioning with explicit WhatsApp numbers in third-party creator index.",
            keywords="wholesale, B2B, korean jewellery, anti tarnish",
            reason_qualified="B2B WhatsApp-first wholesale matches CRM and catalog automation pain points.",
            potential_services="B2B portal, WhatsApp API, CRM",
            gmaps="Unknown",
            score=8,
            notes="Also lists +91 7291914990 in some indexes; confirm active lines on profile.",
        ),
        Lead(
            business="Radhey Krishna Collection",
            handle="radheykrishnacollection_0421",
            city="Unknown",
            state="India",
            business_type="Traditional/fashion jewellery (creator storefront seed)",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Surfaced as a related creator to other WhatsApp-heavy jewellery accounts in third-party indexes.",
            keywords="radhey krishna, collection, traditional",
            reason_qualified="Related-account discovery seed for enrichment and clustering.",
            potential_services="Automation, ecommerce, ads",
            gmaps="Unknown",
            score=4,
            notes="Low confidence seed; verify jewellery focus and contact methods on Instagram.",
        ),
        Lead(
            business="Laxmi Fancy Store Nokha",
            handle="laxmi_fancy_store_nokha",
            city="Nokha",
            state="Rajasthan",
            business_type="Fancy store jewellery (likely imitation/fashion)",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Surfaced as a related creator to other jewellery accounts in third-party indexes.",
            keywords="fancy store, nokha, imitation",
            reason_qualified="Local fancy-store Instagram pattern often overlaps with jewellery SKU selling.",
            potential_services="Local ads, WhatsApp automation, ecommerce",
            gmaps="https://www.google.com/maps/search/Laxmi+Fancy+Store+Nokha",
            score=4,
            notes="Verify jewellery share-of-skus vs general fancy goods before outreach.",
        ),
        Lead(
            business="Suhagini Creations",
            handle="suhagini_creations",
            city="Unknown",
            state="India",
            business_type="Handmade / festive jewellery and accessories",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Surfaced as a related creator to other jewellery accounts in third-party indexes.",
            keywords="creations, handmade, festive",
            reason_qualified="Creator-brand seed for enrichment; often monetizes via DMs.",
            potential_services="IG shop, automation, ecommerce",
            gmaps="Unknown",
            score=4,
            notes="Low confidence seed; confirm product focus on profile.",
        ),
        Lead(
            business="Saanjh By Sonal",
            handle="saanjhbysonal",
            city="Unknown",
            state="India",
            business_type="Bridal / fashion jewellery (brand seed)",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Surfaced as a related creator to other jewellery accounts in third-party indexes.",
            keywords="bridal, saanjh, jewellery",
            reason_qualified="Bridal jewellery brand seed for enrichment.",
            potential_services="CRM, ecommerce, ads",
            gmaps="Unknown",
            score=4,
            notes="Low confidence seed; verify ordering workflow on profile.",
        ),
        Lead(
            business="DC Jewellery Manufacturer",
            handle="dc_jewellery_manufacturer",
            city="Unknown",
            state="India",
            business_type="Jewellery manufacturing / wholesale (seed)",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely WhatsApp (verify)",
            website_present="No",
            website_url="N/A",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Surfaced as a related manufacturer account in third-party wholesale jewellery indexes.",
            keywords="manufacturer, wholesale, jewellery",
            reason_qualified="Manufacturer accounts often run WhatsApp-heavy B2B funnels.",
            potential_services="B2B portal, WhatsApp automation, CRM",
            gmaps="Unknown",
            score=4,
            notes="Low confidence seed; verify GST/location and jewellery focus before outreach.",
        ),
        Lead(
            business="Dohr India",
            handle="dohr_india",
            city="Unknown",
            state="India",
            business_type="Fashion / silver jewellery brand (seed)",
            whatsapp="Unknown",
            email="Unknown",
            ordering_method="Likely DM/WhatsApp (verify)",
            website_present="Unknown",
            website_url="Unknown (verify)",
            recent_activity=UNKNOWN,
            avg_engagement=UNKNOWN,
            bio_text="Surfaced as a related brand name in third-party jewellery creator graphs.",
            keywords="dohr, india, jewellery",
            reason_qualified="Brand seed for enrichment; confirm India operations and ordering channels.",
            potential_services="Brand site, automation, ads",
            gmaps="Unknown",
            score=4,
            notes="Low confidence seed; verify handle spelling and category fit on Instagram.",
        ),
    ]

    deduped = dedupe(leads)
    if len(deduped) < 100:
        raise SystemExit(f"Expected >=100 unique deduped leads, got {len(deduped)}")

    out_path = "/workspace/india_jewellery_instagram_leads.txt"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(
            "India Jewellery Instagram Lead Export\n"
            "Generated: 2026-05-23\n"
            "Source: Public web search snippets + limited HTML search sampling; enrichment required.\n"
            "Deduplication: unique Instagram handles; unique WhatsApp numbers where present.\n\n"
        )
        for i, lead in enumerate(deduped[:100], start=1):
            f.write(fmt(lead, i))

    print(f"Wrote {min(100, len(deduped))} leads to {out_path} (deduped_total={len(deduped)})")


if __name__ == "__main__":
    main()
