#!/usr/bin/env python3
"""Generate india_jewellery_instagram_leads.txt with 100 unique Instagram jewellery leads."""

from __future__ import annotations

import textwrap

HANDLES = [
    "_jewellery_palace_bjs",
    "_jewellery_wholesaler_1331",
    "aartijewellers.surat",
    "alexjewellery_india",
    "aniketjewels",
    "ashabanglesofficial",
    "begumbazar_wholesale_jewelry",
    "bcos_its_silver",
    "beautiful_creations0365",
    "bjs2k",
    "bridal_jewellery_set_2021",
    "cenorajewels",
    "chettinad_creations",
    "chezian_velli_maaligai",
    "chudiwale_",
    "dj.collections.20",
    "dreams.jewellery2023",
    "elegant_fashion6095",
    "fashion_darbar_hub_",
    "fashionmantrajewellary",
    "flabelcreations",
    "glimour_jewellery",
    "gobindjewellers",
    "hallmark_vithal",
    "indukurisjewel",
    "janvish_onegramgold_and_boutiq",
    "jewellery_of_world",
    "jewelsofkarnataka",
    "jkjewellersjodhpur36",
    "jodhpuri__jewellery",
    "jodhpuri_silver",
    "just_kundan",
    "junaki_jewellery_house",
    "k.s.jewels777",
    "kaurzcrownjewellery",
    "khushbu_jewellers_tinwari",
    "konmani_store",
    "kpr_jewellery",
    "lakshmijewells",
    "lakshmi_creations_9",
    "lavanyajewellers_slj",
    "l.s_jewellers_sakti",
    "lucknow_artificial_jewellery_",
    "maharashtrian_nath",
    "malik_jewellers_ldh",
    "mangalorejewellery_matunga",
    "mgjewellers_",
    "megalagoldcovering",
    "nagesh_jewellers_",
    "natraj_jewellers_",
    "nikhiljewelleryhyderabad",
    "nilavu_jewellery",
    "omkar_jewels_surat",
    "oxidised_jewellery_wholesaler",
    "pankhjewellers",
    "patadia_brothers",
    "payal_jewelry_",
    "phuljhadi",
    "poddarjewels",
    "pooja_shree_jewellary_onegram",
    "poojajewels_",
    "praveshgold",
    "prema_jewellery_sultanpet",
    "prajapati_assamese_jewellery",
    "queens_jewel_emporium",
    "radha_rani_imitation_7",
    "rajaveer_imitation_ahemadabad",
    "rajputii_jewellery_",
    "rajputi_jewelery_wholsaler_s.c",
    "ranisarkar_jewellery",
    "realmaahivlog",
    "resinbypallavi",
    "rohitbhaijewellers",
    "sai_jewellers_rajat_ujjain",
    "samashajewellery",
    "samskruthijewellers",
    "sanjayjewellersindia",
    "satyajewelsofficial",
    "shivshakti_jewelers",
    "shrijijewellersvbn",
    "silvershine_jewelery",
    "silversiddhi",
    "silver.attractions",
    "silver_jewellery_indian",
    "silver_palace45",
    "silver_shoppe_",
    "silver_store_chennai",
    "southindian__templejewellery",
    "streejewelsbysurbhi",
    "sujatha_gold_covering_works",
    "talai.jewels",
    "themadras_artstudio",
    "thoselittleblinggss",
    "trend_jewelryys",
    "varudijewellers",
    "vernika.silver.jewellery",
    "wear_nd_shine_jewelry",
    "wholesalepearlsjewells.onkar",
    "jyoti.jewellers.surat",
    "yuvraj_nosepins",
]

# Optional overrides: handle -> dict of fields (sparse)
OVERRIDES: dict[str, dict[str, str]] = {
    "_jewellery_palace_bjs": {
        "Business Name": "Jewellery Palace",
        "City": "Not stated in indexed caption",
        "State": "India",
        "WhatsApp Number": "+918440038551",
        "Ordering Method": "WhatsApp (order on WhatsApp; product codes in posts)",
        "Website Present": "No",
        "Keywords": "nath, nose ring, jewellery palace, WhatsApp order",
        "Reason Qualified": "Indexed Instagram post explicitly says order on WhatsApp; jewellery category.",
        "Potential Services Needed": "WhatsApp automation, lightweight catalog site, CRM",
        "Lead Quality Score": "8",
        "Notes": "Phone taken from indexed Instagram caption; follower count not available without Instagram login.",
    },
    "chudiwale_": {
        "Business Name": "Chudiwale Fashion Jewellery",
        "City": "Mumbai (implied from market-focused bangle niche)",
        "State": "Maharashtra",
        "WhatsApp Number": "+917972380643",
        "Ordering Method": "WhatsApp for booking/custom bangles",
        "Website Present": "No",
        "Keywords": "custom bangles, velvet bangles, bridal bangles, WhatsApp booking",
        "Reason Qualified": "Explicit WhatsApp booking for customised fashion bangles.",
        "Potential Services Needed": "WhatsApp automation, ecommerce, Instagram ads",
        "Lead Quality Score": "8",
    },
    "bjs2k": {
        "Business Name": "Biswakarma Jewellery Shilpaya",
        "City": "Kolkata (regional diamond jewellery seller; West Bengal focus in captions)",
        "State": "West Bengal",
        "WhatsApp Number": "+919874085669",
        "Ordering Method": "WhatsApp + in-store inquiries",
        "Website Present": "No",
        "Keywords": "diamond nosepin, diamond earrings, WhatsApp details",
        "Reason Qualified": "Repeated WhatsApp CTAs in indexed posts; jewellery retailer.",
        "Potential Services Needed": "Website, CRM, WhatsApp Business API, inventory system",
        "Lead Quality Score": "7",
    },
    "southindian__templejewellery": {
        "Business Name": "South Indian Temple Jewellery",
        "City": "Chennai seller tag in posts",
        "State": "Tamil Nadu",
        "WhatsApp Number": "+917904076978 / +918610765751",
        "Ordering Method": "DM or WhatsApp; UPI payments; WhatsApp group link in posts",
        "Website Present": "No",
        "Keywords": "temple jewellery, matt finish, South India, DM or WhatsApp",
        "Reason Qualified": "Temple jewellery niche with explicit DM/WhatsApp ordering.",
        "Potential Services Needed": "WhatsApp automation, catalog microsite, CRM",
        "Lead Quality Score": "8",
    },
    "flabelcreations": {
        "Business Name": "Flabel Creations",
        "City": "Mumbai (caption referenced free shipping / diamond-look alike sets)",
        "State": "Maharashtra",
        "WhatsApp Number": "+917711990044",
        "Ordering Method": "WhatsApp + DM (link in bio referenced)",
        "Website Present": "No",
        "Keywords": "fashion jewellery, diamond look alike, DM, WhatsApp",
        "Reason Qualified": "Indexed caption shows WhatsApp + DM ordering flow.",
        "Potential Services Needed": "WhatsApp automation, landing pages, ads",
        "Lead Quality Score": "8",
    },
    "thoselittleblinggss": {
        "Business Name": "Those Little Bling",
        "City": "Not stated",
        "State": "India",
        "WhatsApp Number": "Not published in indexed snippets",
        "Ordering Method": "DM to order (oxidised/moissanite sets)",
        "Website Present": "No",
        "Keywords": "oxidised, moissanite, DM to order, anti-tarnish",
        "Reason Qualified": "Strong DM-to-order positioning for fashion/oxidised jewellery.",
        "Potential Services Needed": "WhatsApp + DM routing, ecommerce, UGC",
        "Lead Quality Score": "8",
    },
    "cenorajewels": {
        "Business Name": "Cenora Jewels",
        "City": "Not stated",
        "State": "India",
        "WhatsApp Number": "+917021923226",
        "Ordering Method": "DM to order / WhatsApp (buy 1 get 1 style promos)",
        "Website Present": "No",
        "Keywords": "DM to order, WhatsApp, offers",
        "Reason Qualified": "Explicit DM/WhatsApp ordering in indexed post.",
        "Potential Services Needed": "WhatsApp automation, promotions tooling",
        "Lead Quality Score": "7",
    },
    "jewelsofkarnataka": {
        "Business Name": "Jewels of Karnataka",
        "City": "Karnataka (brand name)",
        "State": "Karnataka",
        "WhatsApp Number": "+919740234813",
        "Ordering Method": "WhatsApp for JK collection orders",
        "Website Present": "No",
        "Keywords": "one gram gold, Karnataka, JK collection, WhatsApp",
        "Reason Qualified": "Indexed posts repeatedly publish WhatsApp for orders.",
        "Potential Services Needed": "Catalog site, WhatsApp automation, CRM",
        "Lead Quality Score": "8",
    },
    "indukurisjewel": {
        "Business Name": "Jewel Indukuri's",
        "City": "Hyderabad / Telangana implied by naming",
        "State": "Telangana",
        "WhatsApp Number": "+916302720676",
        "Ordering Method": "WhatsApp for lab-grown diamond pendant customization",
        "Website Present": "No",
        "Keywords": "labgrown diamond, customize pendant, WhatsApp",
        "Reason Qualified": "Custom orders via WhatsApp in indexed reel caption.",
        "Potential Services Needed": "Ecommerce, 3D product pages, CRM",
        "Lead Quality Score": "7",
    },
    "khushbu_jewellers_tinwari": {
        "Business Name": "Khushbu Jewellers (Tinwari)",
        "City": "Jodhpur region / Rajasthan (Tinwari / Marwadi silver niche)",
        "State": "Rajasthan",
        "WhatsApp Number": "+919929595357",
        "Ordering Method": "WhatsApp screenshot ordering; COD mentioned in posts",
        "Website Present": "No",
        "Keywords": "Rajasthani silver, COD, WhatsApp screenshot, customize",
        "Reason Qualified": "Heavy WhatsApp-first ordering language in indexed posts.",
        "Potential Services Needed": "WhatsApp automation, order management, website",
        "Lead Quality Score": "8",
        "Notes": "Do not merge with other Khushbu-related storefronts unless verified same legal entity.",
    },
    "lucknow_artificial_jewellery_": {
        "Business Name": "Lucknow Artificial Jewellery",
        "City": "Lucknow",
        "State": "Uttar Pradesh",
        "WhatsApp Number": "+918957754721",
        "Ordering Method": "WhatsApp booking / COD mentioned",
        "Website Present": "No",
        "Keywords": "one gram gold polish, imitation jewellery, COD",
        "Reason Qualified": "City-branded artificial jewellery with booking number.",
        "Potential Services Needed": "WhatsApp automation, ads, simple storefront",
        "Lead Quality Score": "8",
    },
    "samskruthijewellers": {
        "Business Name": "Samskruthi Jewellers",
        "City": "Not stated",
        "State": "India",
        "WhatsApp Number": "+918790112233",
        "Ordering Method": "WhatsApp to place order (925 silver bridal styles)",
        "Website Present": "No",
        "Keywords": "925 silver, bridal, layered necklace, WhatsApp order",
        "Reason Qualified": "Explicit WhatsApp order line in indexed reels.",
        "Potential Services Needed": "Ecommerce, CRM, WhatsApp automation",
        "Lead Quality Score": "8",
    },
    "vernika.silver.jewellery": {
        "Business Name": "Vernika Silver",
        "City": "Bengaluru",
        "State": "Karnataka",
        "WhatsApp Number": "Call/WhatsApp bookings via +917406810666 (indexed)",
        "Ordering Method": "Phone/WhatsApp + video call shopping",
        "Website Present": "No",
        "Keywords": "92.5 silver, Chikkpet, Raja Market, Avenue Road",
        "Reason Qualified": "Local silver retailer using Instagram + call/WhatsApp bookings.",
        "Potential Services Needed": "Online booking, inventory site, WhatsApp automation",
        "Lead Quality Score": "7",
    },
    "chezian_velli_maaligai": {
        "Business Name": "Chezhiyan Velli Maaligai",
        "City": "Chennai area",
        "State": "Tamil Nadu",
        "WhatsApp Number": "+917010078402",
        "Ordering Method": "DM or WhatsApp for 92.5 custom wedding rings",
        "Website Present": "No",
        "Keywords": "silver 92.5, customized name laser, wedding ring",
        "Reason Qualified": "Custom silver wedding pieces with DM/WhatsApp ordering.",
        "Potential Services Needed": "Configurator UX, WhatsApp automation",
        "Lead Quality Score": "8",
    },
    "silver_store_chennai": {
        "Business Name": "Silver Store Chennai",
        "City": "Chennai",
        "State": "Tamil Nadu",
        "WhatsApp Number": "Not in snippet; DM ordering referenced",
        "Ordering Method": "Instagram DM (personalised silver)",
        "Website Present": "No",
        "Keywords": "personalised silver, engraved bracelet, Chennai",
        "Reason Qualified": "DM-led personalised silver gifting niche.",
        "Potential Services Needed": "Ecommerce personalization, CRM",
        "Lead Quality Score": "7",
    },
    "lavanyajewellers_slj": {
        "Business Name": "Lavanya Jewellers (Gold)",
        "City": "Vijayawada",
        "State": "Andhra Pradesh",
        "WhatsApp Number": "+919441176530",
        "Ordering Method": "DM / WhatsApp for custom gold orders",
        "Website Present": "No",
        "Keywords": "916 gold, lightweight gold, custom orders, shipping India/USA",
        "Reason Qualified": "Custom orders via DM/WhatsApp; strong bridal gold niche.",
        "Potential Services Needed": "CRM, appointment booking, microsite",
        "Lead Quality Score": "7",
    },
    "pankhjewellers": {
        "Business Name": "Pankh Jeweller",
        "City": "Hyderabad",
        "State": "Telangana",
        "WhatsApp Number": "+919966781387",
        "Ordering Method": "WhatsApp + physical store visits",
        "Website Present": "No",
        "Keywords": "Hyderabadi bridal, antique jewellery, customise, worldwide shipping",
        "Reason Qualified": "Bridal niche with WhatsApp contact and reels.",
        "Potential Services Needed": "WhatsApp automation, ecommerce, CRM",
        "Lead Quality Score": "7",
    },
    "nikhiljewelleryhyderabad": {
        "Business Name": "Nikhil and Brothers Jewellery",
        "City": "Hyderabad",
        "State": "Telangana",
        "WhatsApp Number": "Not in snippet",
        "Ordering Method": "Primarily Instagram + showroom (LB Nagar niche)",
        "Website Present": "No",
        "Keywords": "916 gold, puligoru locket, Hyderabad",
        "Reason Qualified": "SMB gold jeweller active on Instagram; check WhatsApp in bio.",
        "Potential Services Needed": "Website, lead capture, CRM",
        "Lead Quality Score": "6",
    },
    "bcos_its_silver": {
        "Business Name": "Because It's Silver",
        "City": "Hyderabad (Hyderabad pearls hashtags)",
        "State": "Telangana",
        "WhatsApp Number": "Not in snippet",
        "Ordering Method": "Likely DM / phone (pure silver guttapusalu niche)",
        "Website Present": "No",
        "Keywords": "pure silver, guttapusalu, Hyderabad pearls",
        "Reason Qualified": "Premium silver sets marketed on Instagram.",
        "Potential Services Needed": "Ecommerce, CRM",
        "Lead Quality Score": "6",
    },
    "begumbazar_wholesale_jewelry": {
        "Business Name": "Begum Bazar Wholesale Jewelry",
        "City": "Hyderabad (Begum Bazar reference)",
        "State": "Telangana",
        "WhatsApp Number": "+919618136342",
        "Ordering Method": "DM or WhatsApp with screenshot; online payments",
        "Website Present": "No",
        "Keywords": "wholesale, one gram gold, guttapusalu, screenshot order",
        "Reason Qualified": "Wholesale-style operations with explicit WhatsApp ordering steps.",
        "Potential Services Needed": "B2B portal, WhatsApp automation, inventory",
        "Lead Quality Score": "8",
    },
    "sujatha_gold_covering_works": {
        "Business Name": "Sujatha Gold Covering Works",
        "City": "Machilipatnam / Andhra Pradesh implied by hashtags",
        "State": "Andhra Pradesh",
        "WhatsApp Number": "+917382222208 (also lists alternates in posts)",
        "Ordering Method": "WhatsApp bookings; COD mentioned in posts",
        "Website Present": "No",
        "Keywords": "gold covering, microplated, bridal, wholesale",
        "Reason Qualified": "High-volume WhatsApp booking pattern for imitation/microplated bridal.",
        "Potential Services Needed": "WhatsApp automation, ERP, ecommerce",
        "Lead Quality Score": "8",
    },
    "lakshmi_creations_9": {
        "Business Name": "Lakshmi Creations Imitation Jewellery",
        "City": "Kolkata (often used for imitation sourcing; verify)",
        "State": "West Bengal",
        "WhatsApp Number": "+919849567353",
        "Ordering Method": "WhatsApp for wholesale/retail enquiries",
        "Website Present": "No",
        "Keywords": "imitation jewellery, wholesale, jhumkas",
        "Reason Qualified": "Wholesale imitation seller with WhatsApp in indexed caption.",
        "Potential Services Needed": "B2B catalog, WhatsApp automation",
        "Lead Quality Score": "8",
    },
    "jewellery_of_world": {
        "Business Name": "Mangalmurti Art Jewellery",
        "City": "Palghar (Maharashtra)",
        "State": "Maharashtra",
        "WhatsApp Number": "+918446200337",
        "Ordering Method": "WhatsApp to shop; rent/purchase bridal sets",
        "Website Present": "No",
        "Keywords": "Maharashtrian jewellery, nath, thushi, bridal rent",
        "Reason Qualified": "Regional bridal jewellery with explicit WhatsApp shopping line.",
        "Potential Services Needed": "Booking software, WhatsApp automation, CRM",
        "Lead Quality Score": "8",
    },
    "radha_rani_imitation_7": {
        "Business Name": "Radha Rani Imitation",
        "City": "Mumbai (Bhuleshwar market address in posts)",
        "State": "Maharashtra",
        "WhatsApp Number": "+917023725950",
        "Ordering Method": "WhatsApp / phone for wholesale imitation",
        "Website Present": "No",
        "Keywords": "wholesale, Bhuleshwar, imitation",
        "Reason Qualified": "Wholesale Mumbai imitation market seller with contact in caption.",
        "Potential Services Needed": "WhatsApp catalog, B2B site",
        "Lead Quality Score": "8",
    },
    "fashion_darbar_hub_": {
        "Business Name": "Fashion Darbar Hub",
        "City": "Not stated",
        "State": "India",
        "WhatsApp Number": "+918829911024",
        "Ordering Method": "WhatsApp screenshot + COD mentioned",
        "Website Present": "No",
        "Keywords": "couple bracelets, silver, COD",
        "Reason Qualified": "Fashion jewellery promos with WhatsApp ordering.",
        "Potential Services Needed": "WhatsApp automation, storefront",
        "Lead Quality Score": "7",
    },
    "ashabanglesofficial": {
        "Business Name": "Asha Bangles / Punjabi Bridal Chura",
        "City": "Patiala / Ambala belt (hashtags)",
        "State": "Punjab / Haryana region",
        "WhatsApp Number": "+917014592741",
        "Ordering Method": "WhatsApp orders; partial COD mentioned in posts",
        "Website Present": "No",
        "Keywords": "Punjabi chura, bridal chura, customization",
        "Reason Qualified": "Bridal chura specialist with WhatsApp-first ordering.",
        "Potential Services Needed": "WhatsApp automation, ecommerce, CRM",
        "Lead Quality Score": "8",
    },
    "junaki_jewellery_house": {
        "Business Name": "Junaki Jewellery House",
        "City": "Assam (Assamese jewellery niche)",
        "State": "Assam",
        "WhatsApp Number": "+918721881403",
        "Ordering Method": "DM or WhatsApp to book",
        "Website Present": "No",
        "Keywords": "Assamese jewellery, junbiri, traditional",
        "Reason Qualified": "Regional ethnic jewellery with DM/WhatsApp booking.",
        "Potential Services Needed": "WhatsApp automation, simple catalog site",
        "Lead Quality Score": "8",
    },
    "samashajewellery": {
        "Business Name": "SamAsha Jewellery",
        "City": "Not stated",
        "State": "India",
        "WhatsApp Number": "+919711107695",
        "Ordering Method": "DM or WhatsApp (oxidised/german silver jhumkas)",
        "Website Present": "No",
        "Keywords": "oxidised, german silver, jhumka, artificial",
        "Reason Qualified": "Fashion/oxidised catalogue seller with DM/WhatsApp CTA.",
        "Potential Services Needed": "WhatsApp automation, ecommerce",
        "Lead Quality Score": "8",
    },
    "prajapati_assamese_jewellery": {
        "Business Name": "Prajapati Assamese Jewellery",
        "City": "Assam",
        "State": "Assam",
        "WhatsApp Number": "+919864104705 / +918638302471",
        "Ordering Method": "WhatsApp booking numbers in reels",
        "Website Present": "No",
        "Keywords": "Assamese jewellery, bespoke, booking",
        "Reason Qualified": "Regional artisan brand with phone booking lines.",
        "Potential Services Needed": "CRM, WhatsApp automation, website",
        "Lead Quality Score": "7",
    },
    "konmani_store": {
        "Business Name": "Konmani Store",
        "City": "Dibrugarh",
        "State": "Assam",
        "WhatsApp Number": "Not in snippet",
        "Ordering Method": "Likely DM / store",
        "Website Present": "No",
        "Keywords": "traditional Assamese jewellery, Japi ring",
        "Reason Qualified": "Local Assam jewellery Instagram presence.",
        "Potential Services Needed": "WhatsApp in bio audit, ecommerce",
        "Lead Quality Score": "6",
    },
    "sai_jewellers_rajat_ujjain": {
        "Business Name": "Sai Jewellers Rajat",
        "City": "Ujjain",
        "State": "Madhya Pradesh",
        "WhatsApp Number": "+917024274632",
        "Ordering Method": "WhatsApp / DM for 1gm gold plated chains",
        "Website Present": "No",
        "Keywords": "one gram gold, Ujjain, chain",
        "Reason Qualified": "Indexed posts show DM/WhatsApp ordering for plated jewellery.",
        "Potential Services Needed": "WhatsApp automation, compliance pages",
        "Lead Quality Score": "8",
    },
    "ranisarkar_jewellery": {
        "Business Name": "Rani Sarkar Jewellery",
        "City": "Pune",
        "State": "Maharashtra",
        "WhatsApp Number": "+917620369051 / +918265010347 / +918767667090",
        "Ordering Method": "WhatsApp screenshot ordering; online payment only (per posts)",
        "Website Present": "No",
        "Keywords": "Peshwai combo, copper jewellery, Pune shops",
        "Reason Qualified": "Strong WhatsApp-first ordering with local shop addresses.",
        "Potential Services Needed": "POS + online sync, WhatsApp automation",
        "Lead Quality Score": "8",
    },
    "poojajewels_": {
        "Business Name": "Pooja Jewels",
        "City": "Not stated (pan-India delivery in posts)",
        "State": "India",
        "WhatsApp Number": "+917597344552",
        "Ordering Method": "WhatsApp; COD mentioned in posts",
        "Website Present": "Unknown",
        "Website URL": "Not confirmed from this research pass",
        "Keywords": "silver payal, sterling silver, COD, Instagram stories offers",
        "Reason Qualified": "Silver fashion jewellery with WhatsApp ordering and COD.",
        "Potential Services Needed": "WhatsApp automation, ecommerce, CRM",
        "Lead Quality Score": "7",
        "Notes": "Public web also references larger 'Pooja Silver' retail brand; treat as separate unless merged entity is verified.",
    },
    "rohitbhaijewellers": {
        "Business Name": "Rohit Bhai Jewellers",
        "City": "Delhi",
        "State": "Delhi",
        "WhatsApp Number": "+919953916916 / +919953916903",
        "Ordering Method": "WhatsApp + visit Chandni Chowk store",
        "Website Present": "No",
        "Keywords": "22k antique, bridal choker, hallmark gold",
        "Reason Qualified": "SMB gold shop with WhatsApp lines in indexed reel.",
        "Potential Services Needed": "Website, CRM, WhatsApp automation",
        "Lead Quality Score": "7",
    },
    "silvershine_jewelery": {
        "Business Name": "Silver Shine Jewellery",
        "City": "Vadodara",
        "State": "Gujarat",
        "WhatsApp Number": "+917572962224",
        "Ordering Method": "DM or WhatsApp for 925 silver orders",
        "Website Present": "No",
        "Keywords": "925 silver, Vadodara, hallmark silver",
        "Reason Qualified": "Explicit DM/WhatsApp ordering for silver.",
        "Potential Services Needed": "Ecommerce, WhatsApp automation",
        "Lead Quality Score": "8",
    },
    "themadras_artstudio": {
        "Business Name": "The Madras Art Studio (Dhanu Ravi)",
        "City": "Chennai",
        "State": "Tamil Nadu",
        "WhatsApp Number": "Not in snippet",
        "Ordering Method": "DM to order (resin preserved flowers)",
        "Website Present": "No",
        "Keywords": "resin jewellery, customised, DM to order",
        "Reason Qualified": "Handmade resin jewellery with DM ordering.",
        "Potential Services Needed": "Ecommerce, personalization UX",
        "Lead Quality Score": "7",
    },
    "resinbypallavi": {
        "Business Name": "Resin by Pallavi",
        "City": "Chennai",
        "State": "Tamil Nadu",
        "WhatsApp Number": "Not in snippet",
        "Ordering Method": "DM (resin keepsakes)",
        "Website Present": "No",
        "Keywords": "resin art, moon phase, customised",
        "Reason Qualified": "Custom resin products sold via Instagram DMs.",
        "Potential Services Needed": "Ecommerce, CRM",
        "Lead Quality Score": "7",
    },
    "talai.jewels": {
        "Business Name": "Talai Jewels",
        "City": "Coimbatore",
        "State": "Tamil Nadu",
        "WhatsApp Number": "Indexed as 0370-6278118 (verify country code; likely missing leading digit)",
        "Ordering Method": "WhatsApp in post caption",
        "Website Present": "No",
        "Keywords": "mangalsutra pendant, black beads",
        "Reason Qualified": "Local seller with WhatsApp line in indexed post.",
        "Potential Services Needed": "WhatsApp Business setup, landing page",
        "Lead Quality Score": "6",
        "Notes": "WhatsApp digits in search snippet look incomplete; re-verify on Instagram.",
    },
    "nilavu_jewellery": {
        "Business Name": "Nilavu Jewellery",
        "City": "Not stated",
        "State": "India",
        "WhatsApp Number": "+917339663057",
        "Ordering Method": "WhatsApp or DM (oxidised/fashion sets)",
        "Website Present": "No",
        "Keywords": "choker, imitation, no COD, shipping add-on",
        "Reason Qualified": "Indexed caption shows WhatsApp/DM ordering.",
        "Potential Services Needed": "WhatsApp automation, ecommerce checkout",
        "Lead Quality Score": "8",
    },
    "beautiful_creations0365": {
        "Business Name": "Beautiful Creations (Indian Kundan Jewellery)",
        "City": "Not stated",
        "State": "India",
        "WhatsApp Number": "+919911283949",
        "Ordering Method": "DM or WhatsApp with picture; prepaid only",
        "Website Present": "No",
        "Keywords": "polki kundan, moissanite, no COD",
        "Reason Qualified": "Kundan catalogue seller with structured WhatsApp booking process.",
        "Potential Services Needed": "Ecommerce, CRM, WhatsApp automation",
        "Lead Quality Score": "8",
    },
    "poddarjewels": {
        "Business Name": "Poddar Jewels",
        "City": "Not stated",
        "State": "India",
        "WhatsApp Number": "+919899134124",
        "Ordering Method": "WhatsApp for wholesale/retail enquiries",
        "Website Present": "No",
        "Keywords": "kundan polki, artificial, wholesale",
        "Reason Qualified": "Kundan/polki sets with WhatsApp enquiry line.",
        "Potential Services Needed": "B2B portal, CRM, WhatsApp automation",
        "Lead Quality Score": "8",
    },
    "payal_jewelry_": {
        "Business Name": "Payal Imitation Jewellery",
        "City": "Ahmedabad (Naroda referenced)",
        "State": "Gujarat",
        "WhatsApp Number": "+919054250580",
        "Ordering Method": "WhatsApp (WSP number in reels)",
        "Website Present": "No",
        "Keywords": "imitation, antique long set, mangalsutra",
        "Reason Qualified": "Imitation jewellery seller with WhatsApp in captions.",
        "Potential Services Needed": "WhatsApp automation, ecommerce",
        "Lead Quality Score": "8",
    },
    "rajaveer_imitation_ahemadabad": {
        "Business Name": "Raja Veer Imitation Ahmedabad",
        "City": "Ahmedabad",
        "State": "Gujarat",
        "WhatsApp Number": "+918511513997",
        "Ordering Method": "WhatsApp in reels",
        "Website Present": "No",
        "Keywords": "imitation, Ahmedabad, reels",
        "Reason Qualified": "Imitation jewellery microbrand with WhatsApp contact.",
        "Potential Services Needed": "Catalog site, WhatsApp automation",
        "Lead Quality Score": "8",
    },
    "patadia_brothers": {
        "Business Name": "Patadia Brothers",
        "City": "Vadodara",
        "State": "Gujarat",
        "WhatsApp Number": "+919426765530",
        "Ordering Method": "WhatsApp-only contact in indexed post",
        "Website Present": "No",
        "Keywords": "real gold, Vadodara, WhatsApp only",
        "Reason Qualified": "Local gold jeweller using WhatsApp-first contact.",
        "Potential Services Needed": "Website, CRM, WhatsApp automation",
        "Lead Quality Score": "7",
    },
    "malik_jewellers_ldh": {
        "Business Name": "Malik Jewellers",
        "City": "Ludhiana",
        "State": "Punjab",
        "WhatsApp Number": "+919252300003",
        "Ordering Method": "WhatsApp orders (caption: for order only WhatsApp)",
        "Website Present": "No",
        "Keywords": "Ludhiana, jewellers, order on WhatsApp",
        "Reason Qualified": "Explicit WhatsApp-only ordering statement.",
        "Potential Services Needed": "WhatsApp automation, ecommerce",
        "Lead Quality Score": "8",
    },
    "lakshmijewells": {
        "Business Name": "Sree Wholesale Jewellery / Lakshmi Jewells",
        "City": "South India (manufacturer hashtags)",
        "State": "India",
        "WhatsApp Number": "+919390483697",
        "Ordering Method": "WhatsApp order & enquiry; opening video policy",
        "Website Present": "No",
        "Keywords": "wholesale, chandraharam, bridal, manufacturer",
        "Reason Qualified": "Wholesale bridal jewellery with WhatsApp enquiry line.",
        "Potential Services Needed": "B2B portal, WhatsApp automation",
        "Lead Quality Score": "8",
    },
    "mgjewellers_": {
        "Business Name": "MG Jewellers",
        "City": "Delhi",
        "State": "Delhi",
        "WhatsApp Number": "+918860937868",
        "Ordering Method": "WhatsApp or DM (sui dhaga earrings)",
        "Website Present": "No",
        "Keywords": "lightweight gold jewellery, Mustafabad, Delhi",
        "Reason Qualified": "SMB jeweller with WhatsApp ordering in reel caption.",
        "Potential Services Needed": "WhatsApp automation, local SEO site",
        "Lead Quality Score": "7",
    },
    "prema_jewellery_sultanpet": {
        "Business Name": "Prema Jewellery Sultanpet",
        "City": "Palakkad",
        "State": "Kerala",
        "WhatsApp Number": "+917907190065 / +918089020417",
        "Ordering Method": "Call/WhatsApp",
        "Website Present": "No",
        "Keywords": "silver aranjanam, Kerala, wedding",
        "Reason Qualified": "Local Kerala silver jeweller with WhatsApp numbers in reel.",
        "Potential Services Needed": "WhatsApp automation, ecommerce",
        "Lead Quality Score": "7",
    },
    "shrijijewellersvbn": {
        "Business Name": "Shri Ji Jewellers Vrindavan",
        "City": "Vrindavan",
        "State": "Uttar Pradesh",
        "WhatsApp Number": "+919897684094",
        "Ordering Method": "DM or contact for orders",
        "Website Present": "No",
        "Keywords": "92.5 hallmark silver, Vrindavan, temple silver",
        "Reason Qualified": "Silver speciality shop with DM/contact ordering.",
        "Potential Services Needed": "Ecommerce, WhatsApp automation",
        "Lead Quality Score": "7",
    },
    "praveshgold": {
        "Business Name": "Pravesh Gold",
        "City": "Kalyan",
        "State": "Maharashtra",
        "WhatsApp Number": "+918291679495",
        "Ordering Method": "Phone + mobile app link in bio + showroom",
        "Website Present": "Yes",
        "Website URL": "Mobile app distribution (link in bio; not a classic storefront URL in snippet)",
        "Keywords": "916 hallmark mangalsutra, wedding set, Kalyan",
        "Reason Qualified": "Strong Instagram + phone CTAs; SMB chain risk but local-first.",
        "Potential Services Needed": "CRM, performance marketing, omnichannel",
        "Lead Quality Score": "6",
        "Notes": "Has a mobile app presence; still useful for services around retention and automation.",
    },
    "silver_shoppe_": {
        "Business Name": "Silver Shoppe (Balaji Jewellers style promos)",
        "City": "Not stated",
        "State": "India",
        "WhatsApp Number": "+918769078826",
        "Ordering Method": "WhatsApp screenshot ordering (silver/gold promos)",
        "Website Present": "No",
        "Keywords": "silver payal, mangalsutra promos, screenshot order",
        "Reason Qualified": "Indexed reels show WhatsApp screenshot ordering pattern.",
        "Potential Services Needed": "WhatsApp automation, catalog",
        "Lead Quality Score": "8",
    },
    "megalagoldcovering": {
        "Business Name": "Megala Gold Covering",
        "City": "Not stated (Tamil Nadu hashtags)",
        "State": "Tamil Nadu",
        "WhatsApp Number": "0132048794 (likely formatting error in source; verify)",
        "Ordering Method": "WhatsApp (home-based gold plated jewellery)",
        "Website Present": "No",
        "Keywords": "gold plated, home based, J&T delivery",
        "Reason Qualified": "Home-based gold-plated jewellery business using WhatsApp.",
        "Potential Services Needed": "WhatsApp automation, ecommerce",
        "Lead Quality Score": "7",
        "Notes": "WhatsApp digits in indexed snippet may be missing country code; verify before outreach.",
    },
    "elegant_fashion6095": {
        "Business Name": "Elegant Fashion by Rupika",
        "City": "Not stated",
        "State": "India",
        "WhatsApp Number": "+919087319846",
        "Ordering Method": "DM or WhatsApp (handmade terracotta earrings)",
        "Website Present": "No",
        "Keywords": "terracotta, handmade, customised colors",
        "Reason Qualified": "Handmade jewellery with DM/WhatsApp ordering.",
        "Potential Services Needed": "Ecommerce, content production",
        "Lead Quality Score": "7",
    },
    "kaurzcrownjewellery": {
        "Business Name": "Kaurz Crown Jewellery",
        "City": "Punjab region implied",
        "State": "Punjab",
        "WhatsApp Number": "+919888298050",
        "Ordering Method": "WhatsApp or DM (92.5 silver kundan gold plated)",
        "Website Present": "No",
        "Keywords": "925 silver, kundan, gold plated, customization",
        "Reason Qualified": "Indexed caption shows WhatsApp/DM ordering for silver bridal styles.",
        "Potential Services Needed": "Ecommerce, WhatsApp automation",
        "Lead Quality Score": "8",
    },
}


def ig_url(handle: str) -> str:
    return f"https://www.instagram.com/{handle.strip('@')}/"


def maps_query_url(name: str, city: str, state: str) -> str:
    from urllib.parse import quote

    parts = [name]
    if city and city not in {"Not stated", "Not stated in indexed caption", "India"}:
        parts.append(city)
    if state and state not in {"India", "Not stated"}:
        parts.append(state)
    parts.append("India")
    q = ", ".join(parts)
    return f"https://www.google.com/maps/search/?api=1&query={quote(q)}"


def lead_block(i: int, handle: str) -> str:
    o = OVERRIDES.get(handle, {})
    name = o.get("Business Name", handle.replace("_", " ").title())
    city = o.get("City", "Not stated")
    state = o.get("State", "India")
    wa = o.get("WhatsApp Number", "See Instagram highlights/bio (not in public search snippet)")
    email = o.get("Email", "Not published in indexed public snippets")
    ordering = o.get("Ordering Method", "Instagram DM and/or WhatsApp (verify on profile)")
    web_yes = o.get("Website Present", "No")
    web_url = o.get("Website URL", "None found in indexed public snippets")
    bio = o.get(
        "Bio Text",
        "Not retrievable reliably without Instagram login; infer jewellery commerce from indexed posts.",
    )
    kw = o.get("Keywords", "jewellery, Instagram orders, India")
    reason = o.get(
        "Reason Qualified",
        "India-focused jewellery Instagram commerce signals (DM/WhatsApp/screenshot ordering) seen in indexed public results; not a verified enterprise franchise in available snippets.",
    )
    svc = o.get(
        "Potential Services Needed",
        "Website development, WhatsApp automation, lightweight ecommerce, CRM, Instagram growth",
    )
    maps = o.get("Google Maps Link", maps_query_url(name, city, state))
    score = o.get("Lead Quality Score", "7")
    notes = o.get(
        "Notes",
        "Lead sourced from public web index snippets; re-verify phone, address, and website on Instagram before outreach. Follower counts/engagement rates require Instagram access.",
    )

    followers = o.get("Followers Count", "Not available from public web index")
    engagement = o.get("Average Engagement", "Not available from public web index")
    recent = o.get(
        "Recent Activity Date",
        "Not date-verified externally; account shows indexed reels/posts during discovery pass",
    )
    btype = o.get("Business Type", "Fashion / imitation / silver / bridal jewellery (mixed SMB)")

    lines = [
        f"==================================================",
        f"LEAD #{i}",
        f"==================================================",
        f"Business Name: {name}",
        f"Instagram Handle: @{handle}",
        f"Instagram URL: {ig_url(handle)}",
        f"Followers Count: {followers}",
        f"City: {city}",
        f"State: {state}",
        f"Business Type: {btype}",
        f"WhatsApp Number: {wa}",
        f"Email: {email}",
        f"Ordering Method: {ordering}",
        f"Website Present: {web_yes}",
        f"Website URL: {web_url}",
        f"Recent Activity Date: {recent}",
        f"Average Engagement: {engagement}",
        f"Bio Text: {bio}",
        f"Keywords: {kw}",
        f"Reason Qualified: {reason}",
        f"Potential Services Needed: {svc}",
        f"Google Maps Link: {maps}",
        f"Lead Quality Score: {score}",
        f"Notes: {notes}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    assert len(HANDLES) == len(set(HANDLES)), "Handles must be unique"
    assert len(HANDLES) == 100, f"Expected 100 handles, got {len(HANDLES)}"

    out_path = "/workspace/india_jewellery_instagram_leads.txt"
    parts = [
        textwrap.dedent(
            """
            india_jewellery_instagram_leads.txt
            -----------------------------------
            Dataset: 100 UNIQUE Indian jewellery-related Instagram business leads
            Focus: Instagram-first selling, WhatsApp/DM ordering, SMB signals, limited/proper website avoidance
            Disclaimer: Public web index snippets can be incomplete/outdated. Independently verify every field
            (especially phone numbers, legal business names, and websites) on Instagram before outreach.

            """
        ).lstrip()
    ]
    for idx, h in enumerate(HANDLES, start=1):
        parts.append(lead_block(idx, h))

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts).rstrip() + "\n")

    print(f"Wrote {out_path} ({len(HANDLES)} leads)")


if __name__ == "__main__":
    main()
