#!/usr/bin/env python3
"""Generate india_jewellery_instagram_leads.txt with 100 unique Instagram-based leads.

Data is compiled from public web-search snippets and lightweight Instagram HTML
probes performed in-repo (not logged-in scraping). Fields like follower counts and
exact engagement are often not available from those sources and are marked
"Not verified in public index" where applicable.
"""

from __future__ import annotations

import re
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "india_jewellery_instagram_leads.txt"

# Each tuple: (business_name, handle, city, state, business_type, whatsapp, email,
# ordering_method, website_present, website_url, recent_activity, avg_engagement,
# bio_text, keywords, reason, services, maps_link, score, notes)
RAW: list[tuple[str, ...]] = [
    ("Beautiful Creations (Indian Kundan / Polki)", "beautiful_creations0365", "Unknown", "India", "Kundan / polki / moissanite sets", "+919911283949", "Not listed in public index", "DM or WhatsApp with product picture; prepaid; no COD", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "Moissanite polki kundan; booking via DM/WhatsApp; no COD/returns policy cited", "kundan, polki, moissanite, bridal, necklace", "WhatsApp + DM ordering; India shipping; long-running seller cues in indexed captions", "Website build, WhatsApp automation, CRM, catalog ordering flow", "Not listed in public index", "8", "Public posts reference @beautiful_creations0365 as follow account for bookings."),
    ("Khushbu Jewellers (Silver / Rajputi)", "khushbujewellers.com_", "Likely Rajasthan / North India", "Rajasthan (inferred)", "925 silver / rajputi silver", "+919875791031", "Not listed in public index", "WhatsApp screenshot-to-order; COD mentioned in posts", "No", "Posts mention website discount promos; treat as mixed social + promos (verify)", "Active in indexed posts (2025)", "Not verified in public index", "Rajputi / silver bridal pieces; WhatsApp screenshot ordering", "silver, rajputi, hathful, payal, COD", "Strong WhatsApp-first ordering pattern; SMB social selling", "WhatsApp automation, ecommerce, CRM, clearer catalog UX", "Not listed in public index", "8", "Also shows alternate WhatsApp numbers on some posts; consolidate on profile before outreach."),
    ("Jewellery Shopper", "jewellery_shopper_", "Unknown", "India", "Silver / devotional silver articles", "+918905291031", "Not listed in public index", "WhatsApp screenshot-to-order; COD mentioned", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "WhatsApp screenshot ordering; COD promos in captions", "silver, Radha Krishna, screenshot order", "Clear WhatsApp screenshot workflow", "WhatsApp automation, lightweight checkout, CRM", "Not listed in public index", "7", "Some posts in the wild show other numbers; dedupe by handle and confirm primary."),
    ("Jewellery Palace (BJS)", "_jewellery_palace_bjs", "Unknown", "India", "Imitation / fashion jewellery", "+918440038551", "Not listed in public index", "WhatsApp order on post", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "WhatsApp order line published on product posts", "nath, imitation, code-based SKUs", "WhatsApp-first SKU ordering", "WhatsApp automation, inventory/SKU system", "Not listed in public index", "7", "Handle naming suggests SMB; verify location and catalog discipline."),
    ("Biswakarma Jewellery Shilpaya", "bjs2k", "Kolkata (inferred from Biswakarma / Shilpalaya cues)", "West Bengal", "Diamond / fine jewellery (store-led)", "+919874085669", "Not listed in public index", "WhatsApp for details/orders", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "WhatsApp-led inquiries for diamond nosepins/earrings", "diamond, nosepin, earrings, WhatsApp", "Strong WhatsApp CTA on posts", "WhatsApp automation, appointment booking, CRM", "Not listed in public index", "6", "Higher-ticket category; still Instagram/WhatsApp led in indexed snippets."),
    ("Chudiwale Fashion Jewellery", "chudiwale_", "Unknown", "India", "Velvet / fashion bangles", "+917972380643", "Not listed in public index", "WhatsApp booking", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "Customized bangle sets; WhatsApp booking", "bangles, bridal, customized", "Custom orders + WhatsApp", "WhatsApp automation, customization workflow, CRM", "Not listed in public index", "8", "Good fit for SMB tooling around custom orders."),
    ("Jodhpuri Silver / Khushbu Network (representative)", "jodhpuri_silver", "Jodhpur (inferred)", "Rajasthan", "Silver payals / silver fashion", "+919929595357", "Not listed in public index", "WhatsApp screenshot-to-order; COD cited", "No", "Posts mention website-order discounts; verify if separate ecommerce exists", "Active in indexed posts (2025)", "Not verified in public index", "Screenshot-to-order; COD; frequent reels", "silver, payal, screenshot order, COD", "High-intent WhatsApp commerce pattern", "WhatsApp automation, omnichannel catalog, CRM", "Not listed in public index", "8", "Multiple related pages share similar numbers; keep one primary handle per network after field verification."),
    ("Asha Bangles / Red Chooda (bridal bangles)", "ashabanglesofficial", "Ambala / North India (inferred)", "Haryana (inferred)", "Bridal chura / bangles", "+917014592741", "Not listed in public index", "WhatsApp ordering; partial COD cited", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "22+ years positioning; customization", "chura, bridal, punjabi, customize", "Strong WhatsApp + customization offer", "WhatsApp automation, CRM, customization intake forms", "Not listed in public index", "8", "Also referenced alongside @Redchooda; map duplicates carefully."),
    ("Samskruthi Jewellers", "samskruthijewellers", "Hyderabad (inferred)", "Telangana", "925 silver / pearl layered necklaces", "+918790112233", "Not listed in public index", "WhatsApp to place order", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "Bridal layered necklaces; WhatsApp order CTA", "925 silver, pearls, bridal", "WhatsApp-first ordering on reels", "WhatsApp automation, catalog pages, CRM", "Not listed in public index", "8", "Strong match to target persona."),
    ("Vari Artificial Jewellery by Ritu Soni", "vari_artificials_jewellery", "Unknown", "India", "Artificial / temple bangles", "+918769988299", "Not listed in public index", "DM or call; local delivery cited", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "Temple jewellery bangles; DM/contact ordering", "temple, artificial, DM, delivery", "DM + phone + delivery messaging", "WhatsApp automation, local delivery logistics, CRM", "Not listed in public index", "8", "Second number sometimes appears in posts; confirm primary."),
    ("Temple Jewellery Hub by Priya", "templejewelleryhub_bypriya", "Unknown", "India", "Temple / Nagas-inspired jewellery", "Not listed in public index", "Not listed in public index", "DM / message to order (price-in-caption pattern)", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "Temple jewellery posts with pricing + shipping notes", "temple, nagas, necklace", "Instagram-native selling; likely needs web + automation", "Website, WhatsApp automation, checkout", "Not listed in public index", "7", "WhatsApp not captured in indexed snippet; confirm on profile."),
    ("Pooja Jewels", "poojajewels_", "Unknown", "India", "Silver fashion / payal", "+917597344552", "Not listed in public index", "WhatsApp; COD cited", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "COD + WhatsApp; stories offers", "silver, payal, COD, handmade cues", "COD + WhatsApp is high commercial intent", "WhatsApp automation, CRM, ecommerce uplift", "Not listed in public index", "9", "Very strong SMB signal in indexed captions."),
    ("Radha Rani Imitation (Mumbai wholesale)", "radha_rani_imitation_7", "Mumbai", "Maharashtra", "Imitation wholesale", "+917023725950", "Not listed in public index", "WhatsApp / phone for orders", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "Bhuleshwar market address cited in reel text", "imitation, wholesale, Mumbai", "Wholesale + WhatsApp discovery", "B2B portal, WhatsApp catalog, CRM", "https://maps.google.com/?q=Bhuleshwar%20Mumbai%20imitation%20jewellery%20market", "7", "Wholesale orientation; still Instagram-led discovery."),
    ("Lakshmi Creations Imitation Jewellery", "lakshmi_creations_9", "Surat (inferred)", "Gujarat", "Imitation wholesale / jhumkas", "+919849567353", "Not listed in public index", "WhatsApp for orders/collections", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "Wholesale pricing language in captions", "imitation, wholesale, jhumkas", "WhatsApp wholesale motion", "WhatsApp automation, distributor CRM", "Not listed in public index", "8", "Good Surat cluster lead."),
    ("Sai Jewellers Rajat (Ujjain)", "sai_jewellers_rajat_ujjain", "Ujjain", "Madhya Pradesh", "1 gram gold plated", "+917024274632", "Not listed in public index", "DM / WhatsApp", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "Gold plated chains; WhatsApp/DM ordering", "one gram gold, plated, WhatsApp", "Classic SMB WhatsApp commerce", "WhatsApp automation, catalog, ads", "https://maps.google.com/?q=Ujjain%20jewellery%20market", "8", "Same WhatsApp appears on multiple posts; keep single lead row."),
    ("Oxidised Jewellery Wholesaler", "oxidised_jewellery_wholesaler", "Unknown", "India", "Oxidised / wholesale", "Not listed in public index", "Not listed in public index", "Likely DM/WhatsApp (verify on profile)", "No", "Not listed in public index", "Indexed posts found via search", "Not verified in public index", "Wholesale-oriented handle naming", "oxidised, wholesale", "Needs profile verification for number", "WhatsApp automation once number confirmed", "Not listed in public index", "6", "Low data completeness; prioritize profile review."),
    ("Trend Jewelryys", "trend_jewelryys", "Unknown", "India", "Fashion jewellery", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Indexed posts found via search", "Not verified in public index", "Reels-forward account", "fashion jewellery, reels", "Social-first; needs verification", "Instagram growth, content ops", "Not listed in public index", "5", "Sparse structured contact in public index."),
    ("Wear and Shine Jewelry", "wear_nd_shine_jewelry", "Unknown", "India", "Fashion jewellery", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Indexed posts found via search", "Not verified in public index", "Low-comment posts in index snapshot", "fashion jewellery", "Needs verification", "Instagram growth, creative", "Not listed in public index", "5", "Use profile highlights to confirm ordering."),
    ("Rajputii Jewellery", "rajputii_jewellery_", "Unknown", "India", "Rajputi / traditional fashion", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Indexed posts found via search", "Not verified in public index", "Community engagement visible in indexed comments", "rajputi, traditional", "Engaged audience signals", "WhatsApp automation if number exists in bio", "Not listed in public index", "6", "Verify WhatsApp in bio."),
    ("Varudi Jewellers (Surat)", "varudijewellers", "Surat", "Gujarat", "Gold / certified gold (verify)", "Not listed in public index", "Not listed in public index", "DM ordering cited in indexed title", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "DM-first buying language", "gold, DM, Surat", "DM commerce; compliance messaging", "CRM, trust/compliance content, web", "https://maps.google.com/?q=Surat%20Varudi%20jewellers", "6", "Verify hallmark claims and storefront vs online-only."),
    ("Fine Silver Jewels Jaipur", "finesilverjewels_rj", "Jaipur", "Rajasthan", "925 silver / appointments", "+919829314701", "Not listed in public index", "WhatsApp customization; store appointments", "Yes", "https://www.instagram.com/finesilverjewels_rj/ (external shop referenced in posts; verify domain)", "Active in indexed posts (2025)", "Not verified in public index", "Bani Park appointment language; WhatsApp customization", "925 silver, Jaipur, customization", "Still heavy Instagram + WhatsApp servicing", "Booking automation, CRM, polished catalog site", "https://maps.google.com/?q=Bani%20Park%20Jaipur%20silver%20jewellery", "6", "Has store + online cues; still good services upsell."),
    ("Jaipur Silver Jewellery / JSJ", "jaipur.silver.jewellery", "Ahmedabad / Jaipur mix (verify)", "Gujarat / Rajasthan (verify)", "Handcrafted silver", "Not listed in public index", "Not listed in public index", "DM / visit (verify)", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "Mall location cited in snippet; verify", "silver, handcrafted, showroom", "Showroom + Instagram hybrid", "Local SEO, bookings, CRM", "https://maps.google.com/?q=Iscon%20Emporio%20Ahmedabad%20silver%20jewellery", "6", "Location text in snippet may be Ahmedabad showroom."),
    ("Those Little Bling", "thoselittleblingss", "Unknown", "India", "Moissanite / oxidized fashion", "Not listed in public index", "Not listed in public index", "DM to order (caption)", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "DM to order; moissanite studs priced in caption", "moissanite, oxidized, DM", "DM-native checkout", "WhatsApp enablement + lightweight cart", "Not listed in public index", "8", "Strong DM-to-order language."),
    ("Fashion Mantra Jewellery (Sonnathi Pavani)", "fashionmantrajewellary", "Unknown", "India", "Handmade earrings / panchaloham", "+918985480894", "Not listed in public index", "WhatsApp / dual numbers cited", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "Sale posts with WhatsApp booking numbers", "handmade, earrings, sale", "WhatsApp booking + offers", "WhatsApp automation, CRM", "Not listed in public index", "7", "Two numbers appear; consolidate."),
    ("Chic Quilling", "chic_quilling", "Unknown", "India", "Paper quilling earrings", "Not listed in public index", "Not listed in public index", "DM for order", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "DM for order; artisan positioning", "quilling, earrings, eco", "Niche handmade; DM ordering", "Ecommerce + DM assistant", "Not listed in public index", "7", "Handle may include underscore variants; verify exact handle live."),
    ("Quillingstuff Handcrafted", "quillingstuff", "Unknown", "India", "Quilling bridal bangles", "Not listed in public index", "Not listed in public index", "DM (caption)", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Custom bridal quilling bangles", "quilling, bridal, customized", "Customization-heavy", "Customization portal + CRM", "Not listed in public index", "7", "Confirm WhatsApp if added later."),
    ("Thohai Silks (Jewellery lines)", "thohaisilks", "Unknown", "India", "Imitation jewellery + silks crossover", "+918072590331", "Not listed in public index", "WhatsApp booking cited", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "Fashion jewellery promos alongside silks", "imitation, necklace, WhatsApp", "WhatsApp booking for jewellery posts", "WhatsApp automation, cross-sell", "Not listed in public index", "7", "Mixed category brand; still useful for WhatsApp automation upsell."),
    ("Roshi Collections", "roshicollections", "Tamil Nadu (shipping note)", "Tamil Nadu", "One gram gold forming", "+919092327836", "Not listed in public index", "WhatsApp; online payment only", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "Screenshot + strict policies", "one gram gold, forming, prepaid", "Strong ops-heavy D2C", "WhatsApp flows, payment reconciliation, CRM", "Not listed in public index", "8", "No COD; good candidate for checkout automation."),
    ("Sakhi 1 Gram Gold Jewellery", "sakhi_1_gram_gold_jewellery", "Unknown", "India", "One gram gold", "+919652417754", "Not listed in public index", "WhatsApp orders", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Simple WhatsApp order caption", "one gram gold, necklace", "WhatsApp-first", "Catalog microsite + WhatsApp", "Not listed in public index", "8", ""),
    ("Janvish Onegramgold & Boutique", "janvish_onegramgold_and_boutiq", "Unknown", "India", "One gram gold + boutique", "+918121769801", "Not listed in public index", "Screenshot WhatsApp; groups cited", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "WhatsApp group updates language", "one gram gold, WhatsApp group", "Community selling model", "Community CRM + WhatsApp", "Not listed in public index", "8", ""),
    ("Dreams Jewellery 2023", "dreams.jewellery2023", "Unknown", "India", "One gram / mens bracelet lines", "+919099003670", "Not listed in public index", "WhatsApp for price", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Dual numbers sometimes listed", "one gram gold, bracelet", "WhatsApp price discovery", "WhatsApp automation", "Not listed in public index", "7", "Also seen with alternate number in some posts; verify."),
    ("Aaras Terracotta Jewellery", "aaras_terracotta", "Chennai (custom order mention)", "Tamil Nadu", "Terracotta jewellery", "+919940438577", "Not listed in public index", "DM to order / WhatsApp", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Eco/custom; worldwide shipping language", "terracotta, customized, Chennai", "Custom orders + WhatsApp", "Customization workflow + CRM", "https://maps.google.com/?q=Chennai%20terracotta%20jewellery", "9", "Strong SMB + customization."),
    ("Elegant Fashion by Rupika", "elegant_fashion6095", "Bangalore", "Karnataka", "Terracotta earrings", "+919087319846", "Not listed in public index", "DM or WhatsApp", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Color customization", "terracotta, handmade, party", "DM + WhatsApp hybrid", "WhatsApp automation", "https://maps.google.com/?q=Bangalore%20handmade%20jewellery", "8", ""),
    ("Sruthi Terracotta Creations", "sruthiterracottacreations", "Bangalore", "Karnataka", "Terracotta / heavy sets", "+919036384234", "Not listed in public index", "DM / wa.me style routing", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "wa.me referenced in caption pattern", "terracotta, customized, Bangalore", "wa.me + DM", "Click-to-WhatsApp landing pages", "https://maps.google.com/?q=Bangalore%20terracotta%20jewellery", "8", ""),
    ("Kayels Creations Terracotta", "kayels_creations", "Unknown", "India", "Terracotta jewellery", "+919486034402", "Not listed in public index", "WhatsApp numbers in caption", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Dual WhatsApp lines", "terracotta, wellness-themed captions", "WhatsApp-first", "WhatsApp routing + CRM", "Not listed in public index", "7", "Two numbers; consolidate."),
    ("Vernika Silver", "vernika.silver.jewellery", "Bangalore", "Karnataka", "92.5 silver", "+917406810666", "Not listed in public index", "Call / video call bookings", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Chickpet / Avenue road address language", "925 silver, Bangalore, video call", "Hybrid retail + phone bookings", "Appointment booking + CRM", "https://maps.google.com/?q=Avenue%20Road%20Bangalore%20silver%20jewellery", "7", "Physical market presence."),
    ("Gohar Jewels Official", "goharjewelsofficial", "Unknown", "India", "Resin / preserved flower jhumkas", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Resin jhumka customization niche", "resin, handmade, jhumka", "Niche artisan brand", "D2C site + DM assistant", "Not listed in public index", "7", "Confirm WhatsApp in bio."),
    ("The Madras Art Studio", "themadras_artstudio", "Chennai", "Tamil Nadu", "Resin flower jewellery", "Not listed in public index", "Not listed in public index", "DM to order", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Customization of colors/shapes", "resin, rose petals, DM", "DM custom product", "Customization tooling + ecommerce", "https://maps.google.com/?q=Chennai%20resin%20jewellery", "8", ""),
    ("Aashus Pearl Creation", "aashus_pearl_creation", "Maharashtra (inferred)", "Maharashtra", "Maharashtrian traditional / handmade", "Not listed in public index", "Not listed in public index", "DM for order", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Customization available language", "handmade, marathi traditional, DM", "DM-first SMB", "WhatsApp + forms + CRM", "Not listed in public index", "8", ""),
    ("Jewellery by Lalitha (imitation)", "jewellery_by_lalitha", "Unknown", "India", "Imitation jewellery", "+917672044475", "Not listed in public index", "DM or WhatsApp; screenshot workflow", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Strict policies; opening video requirements", "imitation, screenshot, prepaid", "Ops-heavy D2C", "Policy pages + WhatsApp automation", "Not listed in public index", "8", ""),
    ("Jewels of Karnataka", "jewelsofkarnataka", "Karnataka", "Karnataka", "One gram gold", "+919740234813", "Not listed in public index", "WhatsApp", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Low ticket items; free shipping language", "one gram gold, Karnataka", "WhatsApp-first", "WhatsApp catalog", "https://maps.google.com/?q=Karnataka%20one%20gram%20gold%20jewellery", "8", ""),
    ("Kolhapuri Thushi / Rishabh Gold", "kolhapurithushi", "Kolhapur (inferred)", "Maharashtra", "Kolhapuri saaj / 1gm mangalsutra", "+919403830260", "Not listed in public index", "WhatsApp; link-in-bio language", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Regional specialty pieces", "kolhapuri, thushi, mangalsutra", "Regional craft + WhatsApp", "Regional SEO + WhatsApp", "https://maps.google.com/?q=Kolhapur%20thushi%20jewellery", "8", ""),
    ("Jewellery of World / Mangalmurti Art", "jewellery_of_world", "Palghar", "Maharashtra", "Maharashtrian bridal rent/purchase", "+918446200337", "Not listed in public index", "WhatsApp to shop", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Rent/purchase bridal sets", "maharashtrian, nath, rent", "Hybrid service commerce", "CRM + scheduling + WhatsApp", "https://maps.google.com/?q=Palghar%20bhaji%20market%20jewellery", "8", ""),
    ("Anmol Jewellers Ludhiana", "anmoljewellersludhiana", "Ludhiana", "Punjab", "Gold jewellery showroom", "+918872533180", "Not listed in public index", "Phone / visit", "Yes", "Likely storefront-led (verify website)", "Active in indexed posts", "Not verified in public index", "Mall road / fountain chowk cues", "gold, ludhiana, showroom", "Store-led but Instagram discovery", "Local ads + appointment booking", "https://maps.google.com/?q=Anmol%20Jewellers%20Mall%20Road%20Ludhiana", "5", "More traditional retail; lower fit vs pure IG shops."),
    ("Kaurz Crown Jewellery (Kuljeet Kaur Virk)", "kaurzcrownjewellery", "Punjab (inferred)", "Punjab", "925 silver kundan plated", "+919888298050", "Not listed in public index", "WhatsApp or DM", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Customization + worldwide shipping language", "925, kundan, punjabi culture", "WhatsApp + customization", "CRM + catalog", "Not listed in public index", "8", ""),
    ("Lavanya Jewellers (Gold)", "lavanyajewellers_slj", "Vijayawada", "Andhra Pradesh", "916 gold / handmade gold", "+919441176530", "Not listed in public index", "DM or WhatsApp; shipping India/USA cited", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Handmade gold bangles; customization", "gold bangles, handmade, shipping", "DM + WhatsApp hybrid", "CRM + international shipping ops", "https://maps.google.com/?q=Vijayawada%20Lavanya%20Jewellers", "6", "More gold-forward; still social commerce."),
    ("Nath Sringar by Supriya", "nath_sringar_by_supriya", "Maharashtra (inferred)", "Maharashtra", "Handmade nath / bridal", "Not listed in public index", "Not listed in public index", "DM / WhatsApp for price", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Customization language", "nath, maharashtrian, customized", "DM + WhatsApp", "WhatsApp automation", "Not listed in public index", "8", ""),
    ("Wholesale Pearls Jewells Onkar", "wholesalepearlsjewells.onkar", "India", "India", "Fashion / wholesale jewellery", "+919996698633", "Not listed in public index", "DM for catalog", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Manufacturer-style SEO captioning", "wholesale, manufacturer, DM catalog", "B2B + DM catalog", "B2B portal + CRM", "Not listed in public index", "6", "More B2B; still Instagram discovery."),
    ("Lakshmi Jewells / Sree Wholesale", "lakshmijewells", "South India (inferred)", "India", "Matte / rose gold finish sets", "+919390483697", "Not listed in public index", "Order & enquiry WhatsApp", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Strict policies (opening video)", "matte gold, choker, wholesale", "Policy-heavy WhatsApp D2C", "WhatsApp automation + policy pages", "Not listed in public index", "7", ""),
    ("Deepanu27 (clip-on nose pins)", "deepanu27", "Unknown", "India", "Fashion nose pins / accessories", "Not listed in public index", "Not listed in public index", "Comment-to-order pattern cited", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Giveaway mechanics in caption", "nose pin, clip on, giveaway", "Comment-led growth", "Comment automation + WhatsApp", "Not listed in public index", "6", "Verify WhatsApp presence in bio."),
    ("Rajputi Poshak Jewellery Sari", "rajputi_poshak_jewellery_sari", "Unknown", "India", "Rajputi / 1gm gold fashion", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Indexed posts", "Not verified in public index", "Poshak crossover listings", "rajputi, 1 gram gold", "Cross-category SMB", "WhatsApp + landing pages", "Not listed in public index", "6", ""),
    ("Jewel Indukuri's", "indukurisjewel", "Unknown", "India", "Lab-grown diamond pendants", "+916302720676", "Not listed in public index", "WhatsApp for details", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Customization language", "lab grown, customize", "WhatsApp consult selling", "CRM + consult booking", "Not listed in public index", "7", ""),
    ("Sujatha Gold Covering Works", "sujatha_gold_covering_works", "Machilipatnam cluster", "Andhra Pradesh", "Micro gold plated / bridal", "+917382222208", "Not listed in public index", "WhatsApp bookings; COD cited", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Multiple numbers for bulk vs retail", "micro plated, wholesale, COD", "Wholesale + COD", "Wholesale CRM + WABA", "https://maps.google.com/?q=Machilipatnam%20gold%20covering%20jewellery", "8", "Multiple WhatsApp lines; dedupe carefully."),
    ("Fashion Darbar Hub", "fashion_darbar_hub_", "Unknown", "India", "Fashion / couple bracelets", "+918829911024", "Not listed in public index", "WhatsApp screenshot + COD cited", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Screenshot ordering pattern", "fashion jewellery, COD", "Screenshot commerce", "WhatsApp automation", "Not listed in public index", "7", ""),
    ("Lucknow Artificial Jewellery", "lucknow_artificial_jewellery_", "Lucknow", "Uttar Pradesh", "One gram gold polish / artificial", "+918957754721", "Not listed in public index", "WhatsApp booking; COD cited", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "City-tagged reels", "lucknow, artificial, COD", "City SMB cluster", "Local SEO + WhatsApp", "https://maps.google.com/?q=Lucknow%20artificial%20jewellery", "8", ""),
    ("Jewellery by Avni Gujral", "jewellery_by_avnigujral", "India", "India", "Meenakari / handcrafted sets", "Not listed in public index", "Not listed in public index", "Message for details", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Meenakari educational captioning", "meenakari, choker, handcrafted", "DM-led premium SMB", "CRM + lookbook site", "Not listed in public index", "7", ""),
    ("Sheesh Mahal Imitation Jewellery", "sheeshmahalamitation", "Unknown", "India", "Imitation / polky earrings", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Indexed posts", "Not verified in public index", "Polky / earrings focus", "imitation, polky, earrings", "Needs profile verification", "Catalog + WhatsApp", "Not listed in public index", "6", ""),
    ("Silver Palace 45", "silver_palace45", "Unknown", "India", "Silver fashion (verify)", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Indexed posts", "Not verified in public index", "Silver-forward naming", "silver", "Sparse indexed contact", "WhatsApp discovery", "Not listed in public index", "5", ""),
    ("Supriya Affordable Jewellery", "supriya.affordable_jewellery", "Unknown", "India", "Affordable enamel earrings", "Not listed in public index", "Not listed in public index", "DM orders; prepaid policies", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Affordable SKU posts", "enamel, affordable, DM", "DM-first affordable SKUs", "Microcart + DM", "Not listed in public index", "8", ""),
    ("Farbfleck Resin Art Pune", "farbfleck_resinart", "Pune", "Maharashtra", "Resin accessories / customization", "Not listed in public index", "Not listed in public index", "DM for customization", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Resin keychains/jewellery crossover", "resin, customized, Pune", "DM customization", "Customization intake", "https://maps.google.com/?q=Pune%20resin%20art", "6", "More accessories; still DM-commerce."),
    ("Yash Ornaments", "yash_ornaments", "Delhi", "Delhi", "Chandni Chowk gold retail", "+919958113991", "Not listed in public index", "Phone / visit", "Yes", "Store-led (verify site)", "Active in indexed posts", "Not verified in public index", "Kucha Mahajani address language", "gold, chandni chowk", "Traditional market retail", "Local performance marketing", "https://maps.google.com/?q=Kucha%20Mahajani%20Chandni%20Chowk%20jewellery", "4", "More showroom-led; included for Delhi cluster mapping."),
    ("Rohit Bhai Jewellers", "rohitbhaijewellers", "Delhi", "Delhi", "Antique / bridal gold", "+919953916916", "Not listed in public index", "WhatsApp / visit", "Yes", "Store-led (verify site)", "Active in indexed posts", "Not verified in public index", "Chandni Chowk showroom cues", "antique, bridal, gold", "WhatsApp + showroom hybrid", "Appointment + WhatsApp routing", "https://maps.google.com/?q=Rohit%20Bhai%20Jewellers%20Chandni%20Chowk", "5", "Higher ticket showroom."),
    ("Riyas Artistry", "riyas_artistry01", "Unknown", "India", "Clay / handmade accessories", "+919468654816", "Not listed in public index", "DM / WhatsApp", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Handmade clay keychains/jewellery crossover", "clay, handmade, DM", "DM + WhatsApp", "D2C mini-site", "Not listed in public index", "7", ""),
    ("Jewellio Jewelry Wholesale", "jewellio_jewelry_wholesale", "Unknown", "India", "Gemstone wholesale (verify)", "Not listed in public index", "Not listed in public index", "DM to order (USD batch posts)", "No", "Not listed in public index", "Indexed posts", "Not verified in public index", "Wholesale batch posts", "gemstone, wholesale, DM", "Export-ish wholesale", "B2B portal", "Not listed in public index", "5", "Verify India base and compliance."),
    ("Ahilya Fine Silver Jewels", "ahilyafinesilverjewels", "India / global (verify)", "India", "925 silver / Kolhapuri thushi", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Heritage silver storytelling", "925 silver, thushi, heritage", "Premium silver brand cues", "Shopify-like uplift (verify)", "Not listed in public index", "6", ""),
    ("Yuvraj Nosepins", "yuvraj_nosepins", "Delhi", "Delhi", "Gold nosepins / lightweight gold", "Not listed in public index", "Not listed in public index", "Visit Chandni Chowk (verify WhatsApp)", "Yes", "Pvt Ltd cues; verify", "Active in indexed posts", "Not verified in public index", "Chandni Chowk market specialization", "nosepins, gold, chandni chowk", "Market stall + IG", "Inventory + WhatsApp", "https://maps.google.com/?q=Yuvraj%20Nosepins%20Chandni%20Chowk", "5", ""),
    ("Nikhil Jewellery Hyderabad", "nikhiljewelleryhyderabad", "Hyderabad", "Telangana", "916 gold bespoke pieces", "Not listed in public index", "Not listed in public index", "DM / visit LB Nagar (verify)", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "916 gold speciality reels", "916 gold, hyderabad, locket", "Instagram catalogue for gold store", "CRM + video consult", "https://maps.google.com/?q=LB%20Nagar%20Hyderabad%20jewellery", "6", ""),
    ("Vyra Gold and Diamonds", "vyragoldanddiamonds", "India (verify)", "India", "916 hallmark temple gold", "+919995901152", "Not listed in public index", "WhatsApp details", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Temple gold reels", "916, nagas, temple", "WhatsApp-led inquiries", "CRM + content", "Not listed in public index", "6", ""),
    ("Gobind Jewellers", "gobindjewellers", "Durgapur", "West Bengal", "Gold / silver showroom mix", "+919593222111", "Not listed in public index", "Phone / visit", "Yes", "Store-led (verify site)", "Active in indexed posts", "Not verified in public index", "Chandidas market address", "gold, durgapur, bridal", "Showroom discovery via IG", "Local SEO + events", "https://maps.google.com/?q=Chandidas%20Market%20Durgapur%20Gobind%20Jewellers", "5", ""),
    ("SamAsha Jewellery", "samashajewellery", "Unknown", "India", "Oxidised / German silver jhumkas", "+919711107695", "Not listed in public index", "DM or WhatsApp", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Unboxing video policy language", "oxidised, jhumka, german silver", "SMB WhatsApp + policies", "WhatsApp automation + returns workflow", "Not listed in public index", "8", ""),
    ("Begum Bazar Wholesale Jewelry", "begumbazar_wholesale_jewelry", "Hyderabad (inferred)", "Telangana", "Wholesale fashion jewellery", "+919618136342", "Not listed in public index", "WhatsApp", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Begum Bazar wholesale cues", "wholesale, offers, free shipping language", "Wholesale WhatsApp motion", "Wholesale CRM", "https://maps.google.com/?q=Begum%20Bazar%20Hyderabad%20wholesale%20jewellery", "7", ""),
    ("Sri Bhagyalakshmi Pearls", "sribhagyalakshmi_pearls", "India (verify)", "India", "Pearl chains / lockets", "+919059432265", "Not listed in public index", "Phone orders cited", "No", "Not listed in public index", "Older indexed post still useful", "Not verified in public index", "Two numbers cited in caption", "pearls, locket, chain", "Phone commerce", "WhatsApp migration + catalog", "Not listed in public index", "6", "Also lists alternate number in same post; verify active."),
    ("KPR Jewellery", "kpr_jewellery", "Kolkata (inferred)", "West Bengal", "Gold / traditional (verify)", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Indexed posts", "Not verified in public index", "Kolkata cluster handle surfaced in search index", "gold, kolkata", "Needs profile confirmation", "Profile optimization + WhatsApp", "https://maps.google.com/?q=Kolkata%20KPR%20jewellery", "5", ""),
    ("Gold Mart Jewellers Pune", "goldmartjeweller", "Pune", "Maharashtra", "Gold / diamond showroom", "+919923347834", "Not listed in public index", "Call / EMI schemes", "Yes", "Showroom-led (verify site)", "Active in indexed posts", "Not verified in public index", "EMI language in captions", "gold, EMI, pune", "Showroom marketing via IG", "Lead capture + CRM", "https://maps.google.com/?q=Gold%20Mart%20Jewellers%20Pune", "4", "More traditional showroom."),
    ("Lakshmi Srinivasa Jewelleries", "lakshmi_srinivasa_jewelleries", "Khammam", "Telangana", "925 silver / antique silver", "+917416588396", "Not listed in public index", "WhatsApp / video call", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Video call shopping language", "925 silver, video call", "Remote selling workflow", "Video commerce stack + CRM", "https://maps.google.com/?q=Khammam%20silver%20jewellery", "8", ""),
    ("Kanak Saanvi Jewels Agra", "kanak_saanvi_agra", "Agra", "Uttar Pradesh", "Hallmarked gold jewellery", "+918899930328", "Not listed in public index", "Phone / visit", "Yes", "Store-led (verify site)", "Active in indexed posts", "Not verified in public index", "MG Road Agra address", "gold, agra, hallmark", "Store + IG", "Local ads + appointments", "https://maps.google.com/?q=Kanak%20Saanvi%20Jewels%20Agra", "5", ""),
    ("Aayush Bangles", "ayushbangles", "Unknown", "India", "Bridal chuda / bangles", "+919772923196", "Not listed in public index", "WhatsApp ordering language", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Size grid language in captions", "chuda, bangles, sizes", "SMB chuda seller", "WhatsApp forms + CRM", "Not listed in public index", "8", ""),
    ("Silver Shoppe", "silver_shoppe_", "India (shipping tags)", "India", "Silver payal / anklets", "+918769078826", "Not listed in public index", "WhatsApp screenshot ordering", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Discount + screenshot workflow", "silver, payal, screenshot", "Screenshot commerce", "WhatsApp automation", "Not listed in public index", "7", ""),
    ("Silver Jewelleryy0 (Fusi fine silver)", "silverjewelleryy0", "Unknown", "India", "Silver payal reels", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Indexed reels", "Not verified in public index", "Payal-forward reels", "silver, payal", "Needs bio review for number", "WhatsApp discovery", "Not listed in public index", "5", ""),
    ("Swarnam Varnam", "swarnam_varnam", "Unknown", "India", "Temple / gold-plated fashion (verify)", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Indexed posts", "Not verified in public index", "Commenters asking price", "temple, jadau, DM", "Engagement signals", "Auto-reply + WhatsApp", "Not listed in public index", "6", ""),
    ("Silver Store Mata Payals", "silver_store_matapayals", "Unknown", "India", "925 silver anklets", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Indexed reels", "Not verified in public index", "Oxidised kada anklet product reels", "925, anklet, oxidised", "Product reels without indexed number", "WhatsApp in bio likely", "Not listed in public index", "6", ""),
    ("Swapna Jewels", "swapna_jewels", "Unknown", "India", "Jadau kundan sets (verify)", "Not listed in public index", "Not listed in public index", "DM price inquiries (comments)", "No", "Not listed in public index", "Indexed posts", "Not verified in public index", "Comment price requests", "jadau, kundan", "Needs WhatsApp capture", "Comment-to-WhatsApp bridge", "Not listed in public index", "6", ""),
    ("The Vadhuu", "the_vadhuu", "India", "India", "AD / bridal imitation sets", "Not listed in public index", "Not listed in public index", "DM (likely)", "No", "Not listed in public index", "Indexed posts", "Not verified in public index", "Free shipping language", "AD necklace, bridal", "SKU-style posts", "Microsite + WhatsApp", "Not listed in public index", "7", ""),
    ("Western Jewelleryy", "western_jewelleryy", "Unknown", "India", "Fashion / silver reels (Hindi captions)", "Confirm in Instagram bio (not consistently indexed here)", "Not listed in public index", "WhatsApp screenshot-to-order language in indexed reels", "No", "Not listed in public index", "Active in indexed posts (2025)", "Not verified in public index", "Screenshot-to-order messaging patterns", "screenshot order, WhatsApp, reels", "IG-native selling; confirm number in bio before outreach", "WhatsApp automation + catalog landing pages", "Not listed in public index", "6", "Do not assume a WhatsApp number without opening the live profile; indexed snippets vary."),
    ("Gemi Jewllery World", "gemijewllery_world", "India", "India", "Kundan / fusion manufacturing (verify)", "+918928286885", "Not listed in public index", "Phone / inquiry line cited", "No", "Not listed in public index", "Indexed posts", "Not verified in public index", "Manufacturing-forward caption", "kundan, fusion, wholesale", "B2B-ish but IG-present", "B2B portal + WhatsApp", "Not listed in public index", "6", "Handle spelling uses double L; verify live handle."),
    ("Just Kundan", "just_kundan", "Unknown", "India", "Kundan jewellery", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Indexed posts", "Not verified in public index", "Kundan-forward posts", "kundan", "Niche IG brand", "WhatsApp + catalog", "Not listed in public index", "6", ""),
    ("Anaha Kundan Jewelry", "anahakundanjewelry", "Chandigarh (tags)", "Chandigarh", "Luxury kundan / heritage", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Luxury storytelling captions", "kundan, luxury, heritage", "Premium IG brand", "Lookbooks + CRM", "https://maps.google.com/?q=Chandigarh%20kundan%20jewellery", "6", ""),
    ("Rumman Jewellers", "rumman_jewellers", "Lucknow", "Uttar Pradesh", "Gold sets / rani haar", "Not listed in public index", "Not listed in public index", "DM for orders language", "Yes", "Showroom likely (verify)", "Active in indexed posts", "Not verified in public index", "dmfororders hashtag", "gold, lucknow, dmfororders", "DM commerce + showroom", "Lead routing", "https://maps.google.com/?q=Akbari%20Gate%20Lucknow%20jewellery", "6", ""),
    ("MJ Jewels Lucknow", "mjjewelslucknow", "Lucknow", "Uttar Pradesh", "Gold / diamond offers", "+918429619322", "Not listed in public index", "Phone / visit", "Yes", "Promo pages (verify site)", "Active in indexed posts", "Not verified in public index", "Festive discount promos", "gold, diamond, lucknow", "Showroom promos via IG", "CRM + offers automation", "https://maps.google.com/?q=MJ%20Jewels%20Lucknow%20Aliganj", "5", ""),
    ("Dishis Designer Jewellery", "dishisdesignerjewellery", "India (verify)", "India", "Mangalsutra pendants / daily gold", "+919310403936", "Not listed in public index", "DM / phone; shop now links", "Yes", "Shop now links in posts (verify domain)", "Active in indexed posts", "Not verified in public index", "D2C gold pendant marketing", "mangalsutra, gold, DM", "Hybrid D2C", "Checkout optimization", "Not listed in public index", "5", "Likely has ecommerce; still services upsell."),
    ("Disha Arts Fashion Jewellery", "dishaarts_fashionjewellery", "India", "India", "Kundan AD brass necklaces", "Not listed in public index", "Not listed in public index", "Bulk orders accepted (caption)", "No", "Not listed in public index", "Active in indexed posts", "Not verified in public index", "Bulk order language", "kundan AD, bulk", "Wholesale + IG", "B2B quoting tool", "Not listed in public index", "7", ""),
    ("Nandi Jewels Mysore", "nandijewels", "Mysuru", "Karnataka", "Gold antique bangles", "Not listed in public index", "Not listed in public index", "Visit / phone (verify)", "Yes", "Store-led", "Active in indexed posts", "Not verified in public index", "22ct gold weight posts", "gold, antique, Mysore", "Store catalogue IG", "Inventory photography pipeline", "https://maps.google.com/?q=Nandi%20Jewels%20Mysore", "5", ""),
    ("TP Jwellers Official", "tp_jwellers_official", "India (verify)", "India", "Gold earrings / jhumka", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Indexed reels", "Not verified in public index", "Shorts-style gold promos", "gold earrings, shorts", "Needs WhatsApp confirmation", "WhatsApp + catalog", "Not listed in public index", "5", ""),
    ("Yaazh Valaivi Silk Thread Bangles", "yaazh_valaivi", "India (verify)", "India", "Silk thread / kundan bangles", "+919488021239", "Not listed in public index", "WhatsApp", "No", "Not listed in public index", "Indexed posts", "Not verified in public index", "Customization sizes newborn+", "silk thread, kundan bangles, customized", "Customization + WhatsApp", "Customization CRM", "Not listed in public index", "9", ""),
    ("Sonal Art Jewellery", "sonal_art_jewellery", "Unknown", "India", "Fashion jewellery (verify)", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Handle existence probed via HTTP redirect", "Not verified in public index", "Candidate handle for outreach validation", "fashion jewellery", "Needs manual qualification", "Profile audit", "Not listed in public index", "4", "HTTP 302 only; must verify content before use."),
    ("Ruhani Jewels", "ruhani_jewels", "Unknown", "India", "Fashion jewellery (verify)", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Handle existence probed via HTTP redirect", "Not verified in public index", "Candidate handle for outreach validation", "jewellery", "Needs manual qualification", "Profile audit", "Not listed in public index", "4", "HTTP 302 only; must verify content before use."),
    ("Kinni Kundan House", "kinni_kundan_house", "Unknown", "India", "Kundan (verify)", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Handle existence probed via HTTP redirect", "Not verified in public index", "Candidate handle for outreach validation", "kundan", "Needs manual qualification", "Profile audit", "Not listed in public index", "4", "HTTP 302 only; must verify content before use."),
    ("Shimmer Vault Jewels", "shimmer_vault_jewels", "Unknown", "India", "Fashion jewellery (verify)", "Not listed in public index", "Not listed in public index", "DM (verify)", "No", "Not listed in public index", "Handle existence probed via HTTP redirect", "Not verified in public index", "Candidate handle for outreach validation", "jewellery", "Needs manual qualification", "Profile audit", "Not listed in public index", "4", "HTTP 302 only; must verify content before use."),
    ("Adornlane", "adornlane.in", "Unknown", "India", "Fashion jewellery (verify)", "Not listed in public index", "Not listed in public index", "DM (verify)", "Yes", "Dot-in handle implies domain brand (verify)", "Handle existence probed via HTTP redirect", "Not verified in public index", "Candidate handle for outreach validation", "jewellery", "Needs manual qualification", "Profile audit", "Not listed in public index", "4", "HTTP 302 only; must verify content before use."),
    ("Jewel4u.in (Earrings & Necklace)", "jewel4u.in_earrings_necklace", "Chennai (tags)", "Tamil Nadu", "German silver necklaces / earrings", "+918098999409", "Not listed in public index", "DM or WhatsApp; partial COD rules cited in posts", "Yes", "https://jewel4u.in (cited in posts)", "Active in indexed posts (2025)", "Not verified in public index", "Hybrid D2C: site + WhatsApp/DM", "german silver, COD, Chennai", "Still uses WhatsApp/DM alongside a website", "WhatsApp bridge, checkout UX, CRM", "https://maps.google.com/?q=Chennai%20jewellery%20instagram", "5", "Included because Instagram remains an active acquisition channel even with a website."),
]


def _dedupe(rows: list[tuple[str, ...]]) -> list[tuple[str, ...]]:
    seen_handles: set[str] = set()
    seen_phones: set[str] = set()
    out: list[tuple[str, ...]] = []
    for r in rows:
        handle = r[1].strip().lower()
        phone = re.sub(r"\D+", "", r[5] or "")
        if handle in seen_handles:
            continue
        if phone and phone in seen_phones:
            # Allow missing phones always; skip duplicate phone leads
            continue
        seen_handles.add(handle)
        if phone:
            seen_phones.add(phone)
        out.append(r)
    return out


def format_lead(i: int, r: tuple[str, ...]) -> str:
    fields = [
        "Business Name:",
        "Instagram Handle:",
        "Instagram URL:",
        "Followers Count:",
        "City:",
        "State:",
        "Business Type:",
        "WhatsApp Number:",
        "Email:",
        "Ordering Method:",
        "Website Present:",
        "Website URL:",
        "Recent Activity Date:",
        "Average Engagement:",
        "Bio Text:",
        "Keywords:",
        "Reason Qualified:",
        "Potential Services Needed:",
        "Google Maps Link:",
        "Lead Quality Score:",
        "Notes:",
    ]
    handle = r[1]
    lines = [f"==================================================", f"LEAD #{i}", f"=================================================="]
    mapping = {
        "Business Name:": r[0],
        "Instagram Handle:": "@" + handle,
        "Instagram URL:": f"https://www.instagram.com/{handle}/",
        "Followers Count:": "Not verified in public index",
        "City:": r[2],
        "State:": r[3],
        "Business Type:": r[4],
        "WhatsApp Number:": r[5],
        "Email:": r[6],
        "Ordering Method:": r[7],
        "Website Present:": r[8],
        "Website URL:": r[9],
        "Recent Activity Date:": r[10],
        "Average Engagement:": r[11],
        "Bio Text:": r[12],
        "Keywords:": r[13],
        "Reason Qualified:": r[14],
        "Potential Services Needed:": r[15],
        "Google Maps Link:": r[16],
        "Lead Quality Score:": r[17],
        "Notes:": r[18],
    }
    for k in fields:
        lines.append(f"{k} {mapping[k]}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    rows = _dedupe(RAW)
    if len(rows) < 100:
        raise SystemExit(f"Expected >=100 unique leads after dedupe, got {len(rows)}")
    rows = rows[:100]

    header = "\n".join(
        [
            "India Jewellery Instagram / WhatsApp Lead Export",
            "Generated for outbound research: SMBs using Instagram + WhatsApp/DM commerce.",
            "IMPORTANT: Re-verify each profile (bio, website link, recent posts) before outreach.",
            "",
        ]
    )

    chunks = [header]
    for idx, r in enumerate(rows, start=1):
        chunks.append(format_lead(idx, r))

    OUT.write_text("\n".join(chunks).strip() + "\n", encoding="utf-8")
    print(f"Wrote {OUT} with {len(rows)} leads")


if __name__ == "__main__":
    main()
