#!/usr/bin/env python3
"""Generate india_jewellery_instagram_leads.txt from merged discovery lists."""
from __future__ import annotations

import re
import urllib.parse
from pathlib import Path

OUT = Path("/workspace/india_jewellery_instagram_leads.txt")

# Curated facts from public search snippets (Instagram / DuckDuckGo). Many metrics need in-app verification.
FACTS: dict[str, dict] = {
    "indian.jwellery": {
        "business": "Indian Jewellery and Bags",
        "city": "Delhi",
        "state": "Delhi",
        "type": "Fashion & imitation jewellery",
        "wa": "+917016867717",
        "email": "Not listed in snippet",
        "order": "WhatsApp; bank/online transfer (no COD per snippet)",
        "website": ("No", ""),
        "followers": "~5.6K (per search snippet; verify)",
        "bio": "WhatsApp +917016867717. No COD; bank or online transfer.",
        "keywords": "Indian jewellery, bags, WhatsApp orders",
        "reason": "India-based seller; WhatsApp checkout; high posting volume implied by snippet.",
        "services": "WhatsApp automation, ecommerce checkout, CRM",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Indian%20jewellery%20Delhi",
        "score": 8,
        "notes": "Snippet from DuckDuckGo profile preview; re-verify followers and policies on Instagram.",
    },
    "artifyindiaaa": {
        "business": "Artify India Jewellery",
        "city": "Jalandhar",
        "state": "Punjab",
        "type": "Imitation / fashion jewellery retail",
        "wa": "+919803344777 / +918989044777",
        "email": "Not listed in snippet",
        "order": "WhatsApp ordering; Jalandhar city delivery mentioned",
        "website": ("No", ""),
        "followers": "~276K (per snippet; verify)",
        "bio": "Serving Jalandhar since 1985; WhatsApp numbers for orders; COD not mentioned.",
        "keywords": "Punjab jewellery, WhatsApp, deliveries",
        "reason": "Strong WhatsApp-led sales motion; Instagram-first storefront.",
        "services": "WhatsApp automation, CRM, marketing automation, optional lightweight ecommerce",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Artify%20India%20Jewellery%20Jalandhar",
        "score": 7,
        "notes": "Established retailer; still fits WhatsApp-led Instagram commerce pattern from snippet.",
    },
    "indian_kundan_jewelry": {
        "business": "Indian Kundan Jewelry (manufacturer)",
        "city": "Indore",
        "state": "Madhya Pradesh",
        "type": "Kundan / bridal imitation manufacturing",
        "wa": "+918383915050",
        "email": "Not listed in snippet",
        "order": "WhatsApp; worldwide shipping; COD mentioned in snippet",
        "website": ("No", ""),
        "followers": "~12K (per snippet; verify)",
        "bio": "Manufacturer; custom sets; WhatsApp contact.",
        "keywords": "Kundan, manufacturer, COD, worldwide shipping",
        "reason": "Clear WhatsApp-led B2C/B2B ordering; custom sets.",
        "services": "B2B portal, CRM, WhatsApp automation, catalogue website",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Indore%20kundan%20jewellery%20manufacturer",
        "score": 8,
        "notes": "City inferred from common cluster for this handle in search; confirm on profile.",
    },
    "traditional_south_indian_jewel": {
        "business": "Traditional South Indian Jewellery (TSIJ)",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "type": "Temple / stone imitation jewellery",
        "wa": "+919003715665",
        "email": "Not listed in snippet",
        "order": "WhatsApp; large catalogue on Instagram",
        "website": ("No", "Stone jewel sister brand @ad_stone_jewels per snippet"),
        "followers": "~147K (per snippet; verify)",
        "bio": "Est. 2017; WhatsApp 9003715665; customer review hashtag.",
        "keywords": "South Indian, temple, stone jewellery, WhatsApp",
        "reason": "High-volume Instagram retailer with WhatsApp hub.",
        "services": "WhatsApp automation, CRM, IG ads, inventory microsite",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Chennai%20imitation%20jewellery%20shop",
        "score": 8,
        "notes": "Large following; still primarily social commerce in snippet.",
    },
    "kattam.in": {
        "business": "Kattam - South Indian imitation jewellery",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "type": "Imitation / AD / oxidised jewellery",
        "wa": "+917871986807",
        "email": "Not listed in snippet",
        "order": "WhatsApp; same-day Chennai pickup mentioned",
        "website": ("Link-in-bio shop", "External shop link in bio (verify platform)"),
        "followers": "~154K (per snippet; verify)",
        "bio": "Online imitation jewellery; Chennai pickup; worldwide shipping.",
        "keywords": "Imitation, Chennai, oxidised, AD, WhatsApp",
        "reason": "Hybrid pickup + WhatsApp; strong candidate for automation.",
        "services": "Ecommerce migration, WhatsApp bots, local SEO, CRM",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Chennai%20imitation%20jewellery%20Kattam",
        "score": 7,
        "notes": "Snippet references shop online link; treat as non-custom standalone site pending verification.",
    },
    "wholesale_jewellery_09": {
        "business": "KP Wholesale Jewellery",
        "city": "Rajkot",
        "state": "Gujarat",
        "type": "Wholesale fashion / imitation jewellery",
        "wa": "+917604876617",
        "email": "Not listed in snippet",
        "order": "WhatsApp-only orders; WhatsApp group for updates",
        "website": ("No", ""),
        "followers": "~138K (per snippet; verify)",
        "bio": "Sunday holiday; WhatsApp-only ordering; customer reviews hashtag.",
        "keywords": "Wholesale, fashion jewellery, WhatsApp group",
        "reason": "Pure WhatsApp order funnel at scale.",
        "services": "B2B ordering portal, WhatsApp automation, CRM, ERP-light",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Rajkot%20wholesale%20jewellery",
        "score": 8,
        "notes": "City inferred from common KP wholesale cluster; confirm on profile.",
    },
    "khushbu_jewellers_tinwari": {
        "business": "Khushbu Jewellers Tinwari",
        "city": "Tinwari",
        "state": "Rajasthan",
        "type": "Silver / gold-polish fashion jewellery",
        "wa": "+919929595357",
        "email": "Not listed in snippet",
        "order": "WhatsApp screenshot order; COD mentioned in posts",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "Custom designs; WhatsApp screenshot ordering.",
        "keywords": "Silver, wedding season, COD, WhatsApp screenshot",
        "reason": "Classic Instagram + WhatsApp commerce without dedicated site in snippet.",
        "services": "Website, payments, WhatsApp automation, CRM",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Tinwari%20jewellery",
        "score": 8,
        "notes": "Exclude duplicate leads sharing same WhatsApp line used elsewhere.",
    },
    "flabelcreations": {
        "business": "Flabel Creations",
        "city": "Mumbai",
        "state": "Maharashtra",
        "type": "Fashion / diamond-look jewellery",
        "wa": "+917711990044",
        "email": "Not listed in snippet",
        "order": "WhatsApp + DM; free shipping on posts",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "DM for details; WhatsApp number in caption.",
        "keywords": "Mumbai, fashion jewellery, DM, WhatsApp",
        "reason": "DM + WhatsApp hybrid; no site in snippet.",
        "services": "Ecommerce, IG shopping integration, CRM",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Mumbai%20fashion%20jewellery%20instagram",
        "score": 7,
        "notes": "City inferred from typical Mumbai cluster for this niche; verify.",
    },
    "southindian__templejewellery": {
        "business": "South Indian Temple Jewellery",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "type": "Temple / matte finish jewellery",
        "wa": "+917904076978 / +918610765751",
        "email": "Not listed in snippet",
        "order": "DM or WhatsApp; UPI/GPay; WhatsApp customer group link in post",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "Chennai seller tags; temple collections.",
        "keywords": "Temple jewellery, matte finish, Tamil Nadu",
        "reason": "Explicit DM/WhatsApp ordering; active social proof in snippet.",
        "services": "WhatsApp automation, checkout links, CRM",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Chennai%20temple%20jewellery",
        "score": 8,
        "notes": "Numbers taken from indexed Instagram post.",
    },
    "chicjewells": {
        "business": "ChicJewells (South India Jewels)",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "type": "Bridal / temple jhumkas",
        "wa": "+917200404607",
        "email": "Not listed in snippet",
        "order": "DM + WhatsApp for details",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "DM for more details / WhatsApp per posts.",
        "keywords": "Temple jhumkas, kemp, south Indian",
        "reason": "Dual-channel ordering; strong bridal niche.",
        "services": "Catalogue site, WhatsApp flows, ads",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Chennai%20bridal%20jewellery%20ChicJewells",
        "score": 8,
        "notes": "Brand line referenced as South India Jewels-ChicJewells in search results.",
    },
    "jewelsofkarnataka": {
        "business": "Jewels of Karnataka",
        "city": "Bengaluru",
        "state": "Karnataka",
        "type": "One gram gold fashion jewellery",
        "wa": "+919740234813",
        "email": "Not listed in snippet",
        "order": "WhatsApp ordering on posts",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "JK collection; low ticket items with shipping mentioned.",
        "keywords": "One gram gold, Karnataka, WhatsApp",
        "reason": "WhatsApp-first price-point jewellery.",
        "services": "Ecommerce, payments, CRM, IG ads",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Bengaluru%20one%20gram%20gold%20jewellery",
        "score": 7,
        "notes": "City inferred; verify on profile.",
    },
    "vernika.silver.jewellery": {
        "business": "Vernika Silver / Sri Lakshmi Venkateshwara Jewellers",
        "city": "Bengaluru",
        "state": "Karnataka",
        "type": "925 silver jewellery",
        "wa": "+917406810666",
        "email": "Not listed in snippet",
        "order": "Call / bookings; video call shopping mentioned",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "Chickpet / Avenue Road area references in reel text.",
        "keywords": "Silver, Bengaluru, video call shopping",
        "reason": "Phone-first commerce with Instagram showcase.",
        "services": "Appointment booking automation, ecommerce, CRM",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Vernika%20silver%20Avenue%20Road%20Bangalore",
        "score": 7,
        "notes": "Physical shop plus Instagram; still upgrade candidate.",
    },
    "glisterjewellery": {
        "business": "Glister Jewellery",
        "city": "Mumbai",
        "state": "Maharashtra",
        "type": "Kundan / bridal sets",
        "wa": "+919868785606",
        "email": "Not listed in snippet",
        "order": "WhatsApp wa.me link; reseller WhatsApp group",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "Strict payment rules; worldwide shipping.",
        "keywords": "Kundan, bangles, WhatsApp ordering",
        "reason": "Heavy WhatsApp funnel with reseller community.",
        "services": "CRM, WhatsApp automation, loyalty, ecommerce",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Mumbai%20kundan%20jewellery%20wholesale",
        "score": 7,
        "notes": "City inferred; verify.",
    },
    "bjs2k": {
        "business": "Biswakarma Jewellery Shilpalaya",
        "city": "Barasat",
        "state": "West Bengal",
        "type": "Diamond nosepins / lightweight gold jewellery",
        "wa": "+919874085669",
        "email": "Not listed in snippet",
        "order": "WhatsApp for orders per posts",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "Repeated WhatsApp CTAs in captions.",
        "keywords": "Kolkata periphery, diamond nosepin, WhatsApp",
        "reason": "Kolkata-region seller using WhatsApp heavily.",
        "services": "Website, booking automation, ads",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Biswakarma%20Jewellery%20Shilpalaya%20Barasat",
        "score": 7,
        "notes": "Near Kolkata; confirm exact shop name on profile.",
    },
    "s.swarnakarandson": {
        "business": "S. Swarnakar & Son",
        "city": "Kolkata",
        "state": "West Bengal",
        "type": "Gold / silver wedding jewellery",
        "wa": "+918981948452",
        "email": "Not listed in snippet",
        "order": "Phone booking per posts",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "Chetla / Kolkata tags; wedding collections.",
        "keywords": "Kolkata, bridal, hallmarked",
        "reason": "Traditional jeweller using Instagram + phone bookings.",
        "services": "CRM, WhatsApp automation, ecommerce catalog",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=S%20Swarnakar%20and%20Son%20Chetla",
        "score": 7,
        "notes": "Verify WhatsApp vs voice-only on profile.",
    },
    "thoselittleblinggss": {
        "business": "Those Little Bling",
        "city": "Mumbai",
        "state": "Maharashtra",
        "type": "Moissanite / oxidised fashion jewellery",
        "wa": "See Instagram (DM-first in posts)",
        "email": "Not listed",
        "order": "DM to order; free shipping on posts",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "DM to order moissanite and oxidised styles.",
        "keywords": "DM to order, moissanite, oxidised",
        "reason": "Textbook Instagram DM commerce.",
        "services": "IG automation, lightweight checkout, CRM",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Mumbai%20fashion%20jewellery%20studio",
        "score": 8,
        "notes": "Handle confirmed from indexed post URL.",
    },
    "zivah_jewels": {
        "business": "Zivah Jewels",
        "city": "Kochi",
        "state": "Kerala",
        "type": "Gold-plated Kerala wedding sets",
        "wa": "See Instagram",
        "email": "Not listed",
        "order": "DM for orders per reel caption",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "Kerala wedding jewellery hashtags.",
        "keywords": "Kerala bride, temple, gold plated",
        "reason": "DM-led Kerala wedding niche.",
        "services": "WhatsApp automation, ecommerce, catalogue",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Kochi%20gold%20plated%20jewellery",
        "score": 7,
        "notes": "City inferred; verify.",
    },
    "ar_gold_covering": {
        "business": "AR Gold Covering",
        "city": "Thrissur",
        "state": "Kerala",
        "type": "Gold-plated traditional Kerala jewellery",
        "wa": "+918606878555",
        "email": "Not listed",
        "order": "DM or WhatsApp; website link also referenced in post",
        "website": ("Yes", "Link-in-bio website referenced in indexed post"),
        "followers": "Unknown (verify)",
        "bio": "Gold plated thalikootam sets; dual DM/WhatsApp.",
        "keywords": "Kerala, thalikootam, gold plated",
        "reason": "Still social-led; website may be simple landing—verify before pitching 'no website'.",
        "services": "Funnel optimisation, WhatsApp automation, performance marketing",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Thrissur%20gold%20covering%20jewellery",
        "score": 6,
        "notes": "Down-rank slightly due to website signal in snippet.",
    },
    "kundancreations_": {
        "business": "Kundan Creations by Jinal",
        "city": "Surat",
        "state": "Gujarat",
        "type": "Polki / moissanite bridal sets",
        "wa": "+917359147370",
        "email": "Not listed",
        "order": "WhatsApp for pricing and orders",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "No bargaining policy; premium gold-plated lines.",
        "keywords": "Surat, polki, moissanite, bridal",
        "reason": "WhatsApp-first premium imitation bridal.",
        "services": "CRM, WhatsApp bots, ecommerce, IG ads",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Surat%20kundan%20jewellery%20studio",
        "score": 8,
        "notes": "City inferred from Surat cluster; verify.",
    },
    "nakshatra_jewellery_3": {
        "business": "Nakshatra Jewellery",
        "city": "Hyderabad",
        "state": "Telangana",
        "type": "Wholesale fashion jewellery",
        "wa": "+917038060988",
        "email": "Not listed",
        "order": "WhatsApp; COD available per snippet",
        "website": ("No", ""),
        "followers": "~431 (per snippet; verify)",
        "bio": "All India free delivery; wholesale focus.",
        "keywords": "Wholesale, COD, India delivery",
        "reason": "Small SMB scale with explicit WhatsApp wholesale model.",
        "services": "B2B portal, inventory management, WhatsApp automation",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Hyderabad%20wholesale%20imitation%20jewellery",
        "score": 8,
        "notes": "Different from large nakshatra_jewels brand; keep separate.",
    },
    "jewellery_of_world": {
        "business": "Mangalmurti Art Jewellery / Jewellery of World",
        "city": "Palghar",
        "state": "Maharashtra",
        "type": "Maharashtrian bridal jewellery rent/purchase",
        "wa": "+918446200337",
        "email": "Not listed",
        "order": "WhatsApp to shop per post",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "Maharashtrian jewellery; rent and purchase.",
        "keywords": "Nath, thushi, bridal, Palghar",
        "reason": "Hyper-local + WhatsApp commerce.",
        "services": "Booking system, WhatsApp automation, website",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Palghar%20jewellery%20shop",
        "score": 8,
        "notes": "Mumbai MMR satellite market.",
    },
    "streejewelsbysurbhi": {
        "business": "Stree Jewels by Surbhi",
        "city": "Surat",
        "state": "Gujarat",
        "type": "Amrapali-inspired fashion sets",
        "wa": "See Instagram",
        "email": "Not listed",
        "order": "DM TO BOOK per reel",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "DM to book; wedding season focus.",
        "keywords": "Surat, inspired jewellery, DM booking",
        "reason": "DM-native checkout pattern.",
        "services": "Checkout links, CRM, IG ads",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Surat%20fashion%20jewellery%20boutique",
        "score": 8,
        "notes": "City inferred from Surat cluster; verify.",
    },
    "varudijewellers": {
        "business": "Varudi Jewellers",
        "city": "Surat",
        "state": "Gujarat",
        "type": "Certified gold jewellery retail",
        "wa": "See Instagram",
        "email": "Not listed",
        "order": "DM for instant buy per reel caption",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "DM-led instant purchase messaging.",
        "keywords": "Surat, gold retail, DM orders",
        "reason": "DM commerce on certified gold SKUs.",
        "services": "Ecommerce, finance integrations, CRM",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Varudi%20jewellers%20Surat",
        "score": 7,
        "notes": "Verify if showroom-only vs online.",
    },
    "omkar_jewels_surat": {
        "business": "Omkar Jewels Surat",
        "city": "Surat",
        "state": "Gujarat",
        "type": "Custom gold / diamond jewellery",
        "wa": "+918141248248",
        "email": "Not listed",
        "order": "Phone / visit + Instagram enquiries",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "Custom jewellery; Angel Square Uttran address in reel.",
        "keywords": "Custom, bespoke, Surat",
        "reason": "Custom order flow suits CRM + digital catalogue.",
        "services": "3D catalogue, CRM, WhatsApp automation",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Omkar%20Jewels%20Angel%20Square%20Surat",
        "score": 7,
        "notes": "Physical atelier; Instagram for lead gen.",
    },
    "silver_jewels_pune": {
        "business": "Shree Silver Pune",
        "city": "Pune",
        "state": "Maharashtra",
        "type": "925 silver retail",
        "wa": "See Instagram / shop",
        "email": "Not listed",
        "order": "Visit shop or order online via Instagram",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "Sonya Maruti Chowk, Raviwar Peth address.",
        "keywords": "Pune, 925 silver, evil eye",
        "reason": "Local silver retailer using reels.",
        "services": "Local SEO, ecommerce, WhatsApp",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Shree%20Silver%20Raviwar%20Peth%20Pune",
        "score": 7,
        "notes": "Confirm online order channel on profile.",
    },
    "samskruthijewellers": {
        "business": "Samskruthi Jewellers",
        "city": "Hyderabad",
        "state": "Telangana",
        "type": "Bridal / CZ / layered necklaces",
        "wa": "+918790112233",
        "email": "Not listed in snippet",
        "order": "WhatsApp ordering explicitly in reel caption",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "South Indian bridal hashtags; WhatsApp CTA in indexed reel.",
        "keywords": "Bridal, CZ, south Indian, WhatsApp",
        "reason": "Clear WhatsApp order path on indexed content.",
        "services": "CRM, WhatsApp automation, catalogue microsite",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Hyderabad%20Samskruthi%20jewellers",
        "score": 8,
        "notes": "Handle inferred from reel hashtag text; confirm exact @handle on Instagram.",
    },
    "dm_jewellery_kolkata": {
        "business": "DM Jewellery Kolkata",
        "city": "Kolkata",
        "state": "West Bengal",
        "type": "Fashion / bridal imitation",
        "wa": "See Instagram",
        "email": "Not listed",
        "order": "Likely DM (handle signal); verify",
        "website": ("No", ""),
        "followers": "Unknown (verify)",
        "bio": "Discovered via geo-targeted search; verify niche.",
        "keywords": "Kolkata, DM jewellery",
        "reason": "Handle matches DM-order pattern for region.",
        "services": "Branding, ecommerce, WhatsApp automation",
        "gmaps": "https://www.google.com/maps/search/?api=1&query=Kolkata%20imitation%20jewellery%20market",
        "score": 6,
        "notes": "Lower confidence—confirm on Instagram.",
    },
}

# Pool: merged discovery (batch1+batch2+manual) minus obvious non-India / bad paths
BATCH1 = set("""1gram_jewellery 1gram_jewellery_shop _.skr_jewels._ _itranajewellery _oxidisedjewelry_ aakarshanakcodejewellery amarus.in amogha_by_mallika batukbhaijewellers bgliim bhatter.silverarts boutiqueinchandigarh bridaljewellery_india chandigarh_boutique__ chandigarh_boutiquee cheshirecatgoa d.m_accessories_ahmedabad dm_jewellery_kolkata gbronegramgold imitaion_07 imitation_jewellery_pune_2025 jewellss_by_sukritiii joyous_fashion_jewellery kimayaacreation krishna.i.jewellery.pune krjewellersgoa kundan.jewellers kundan.jwellery kundanjewellers916 kundanjewellery.official kundanjewelleryofficial lets_goa_jewellery livia_art_jewels_ londejewellers mahalaxmi_jewellers_nagpur mewlo.resin one_gram_gold_jewellers onegramgold1 oxidised_collection_latest oxidised_jewellery_love oxidisedjeweelry oxidisedjewelerywholesale oxidisedjewellerycollection peshwaicreations pooja_jewellers_nagpur poojajewellers ppjewellerschandigarh rajesh_silver_jewellery rajputi_collection_jodhpur_19 resin_jewellery_india resinbyuneeba rj.jodhpur rjjodhpur111 saraf_jeweller shalibhadra_fashion_jewellery shobhajewellersgoa shreeram_jewellery_bhopal shriramjewellersnagpur silverauraa silvercravingsjewellery sm_hyderabadibpearljewellery sudheer_kt_one_gram_gold temple.jewellery.in temple__jewellery_ temple__jewels temple_jewellery temple_jewellerycollection templejewelleryhub_bypriya vaidehi_silver_jewellery wholesale_oxidisedjewellery wowfashionjewellry zudi.jewellers""".split())

BATCH2 = set("""__pearls__jewellery__ aarvee.chennai aka.jewellers american_diamond_jewellery22 american_diamond_jewellery_ americandiamondjewellery antique__jewellery_ antique_jewelery0 antique_jewellery_mumbai antique_jewelz antique_mumbai chandrani.pearls chokerset esha.jewels indian_imitation_jewellery infinity_silverstore jaipur_meenakari_studio jcsjewelcreations kangana_art leelagoldjewellery lovelyjewelleryjanpath meenakari_jewellery meenakarijewellery_official merry_gold_mumbai nupearlsjewellery pearljeweler pearljewelleryofficial pearljewelrystore pearls_.jewellery polki.jewellery polki_jewelleryy polkibysvj polkii.jewelry polkiparadise_official queens_choice_jewellry_brand rakhshanda94 realpearlsindia royal.meenakari stonedown_custom tesorijewels.india vintiquejewellery""".split())

MANUAL = set("""khushbu_jewellers_tinwari trend_jewelryys wear_nd_shine_jewelry flabelcreations rajaveer_imitation_ahemadabad jodhpuri_silver bjs2k s.swarnakarandson nikhiljewelleryhyderabad bcos_its_silver emmadi_silver_jewellery jaipur_jewellary_damoh jaipurgems_manufacture vernika.silver.jewellery jewelsofkarnataka mohabygeetanjali oxidised_jewellery_wholesaler olddelhijewellers rajputii_jewellery_ southindian__templejewellery lavanyajewellers_slj varudijewellers omkar_jewels_surat jyoti.jewellers.surat streejewelsbysurbhi silver_jewels_pune chicjewells jewelsofindia_official indukurisjewel glisterjewellery patel_mall_jamnagar jewellery_of_world zivah_jewels kpr_jewellery silver_palace45 thoselittleblinggss tyohaarsilverjewellery realmaahivlog ar_gold_covering anahakundanjewelry kundancreations_ indian_kundan_jewelry indian.jwellery artifyindiaaa traditional_south_indian_jewel kattam.in wholesale_jewellery_09 nakshatra_jewellery_3 samskruthijewellers""".split())

EXCLUDE = {
    "kundanjewellery.pk",
    "instagram",
    "jewellerystore.co",
    "imitaion_07",  # likely spam/typo farm
    "rakhshanda94",  # personal handle pattern
}

POOL = (BATCH1 | BATCH2 | MANUAL | set(FACTS.keys())) - EXCLUDE
# Prioritise handles with FACTS then alphabetical stable tie-break
ordered = sorted(FACTS.keys(), key=lambda h: (-FACTS[h]["score"], h))
rest = sorted(POOL - set(ordered), key=lambda h: h.lower())
handles: list[str] = []
seen_phone_suffix: set[str] = set()


def phone_key(wa: str) -> str | None:
    if not wa or wa.lower().startswith("see "):
        return None
    chunk = wa.split("/")[0]
    digits = re.sub(r"\D", "", chunk)
    if len(digits) >= 10:
        return digits[-10:]
    return None


for h in ordered + rest:
    if h in EXCLUDE:
        continue
    f = FACTS.get(h, {})
    wa = str(f.get("wa", ""))
    pk = phone_key(wa)
    if pk and pk in seen_phone_suffix:
        continue
    if pk:
        seen_phone_suffix.add(pk)
    handles.append(h)
    if len(handles) >= 100:
        break

if len(handles) < 100:
    raise SystemExit(f"only {len(handles)} handles after dedupe")

handles = handles[:100]


def pretty_name(handle: str) -> str:
    base = handle.replace("_", " ").replace(".", " ").strip()
    return base.title()


def default_fact(handle: str) -> dict:
    return {
        "business": pretty_name(handle),
        "city": "India (verify city on profile)",
        "state": "—",
        "type": "Jewellery retail / wholesale (verify)",
        "wa": "See Instagram bio or DM",
        "email": "Not scraped",
        "order": "Instagram DM and/or WhatsApp (verify)",
        "website": ("No", ""),
        "followers": "Not scraped — verify in Instagram app",
        "bio": "Public web index did not expose full bio text; review profile directly.",
        "keywords": "Jewellery, India, Instagram commerce",
        "reason": "Discovered via public search indexing of Instagram jewellery sellers in India.",
        "services": "Website, WhatsApp automation, CRM, Instagram growth, ads",
        "gmaps": f"https://www.google.com/maps/search/?api=1&query={urllib.parse.quote(handle + ' jewellery India')}",
        "score": 6,
        "notes": "Automated pool entry; validate niche, location, and ordering flow before outreach.",
    }


def block(i: int, handle: str) -> str:
    f = {**default_fact(handle), **FACTS.get(handle, {})}
    yn, wurl = f["website"]
    lines = [
        "=" * 50,
        f"LEAD #{i}",
        "=" * 50,
        f"Business Name: {f['business']}",
        f"Instagram Handle: @{handle}",
        f"Instagram URL: https://www.instagram.com/{handle}/",
        f"Followers Count: {f['followers']}",
        f"City: {f['city']}",
        f"State: {f['state']}",
        f"Business Type: {f['type']}",
        f"WhatsApp Number: {f['wa']}",
        f"Email: {f['email']}",
        f"Ordering Method: {f['order']}",
        f"Website Present: {yn}",
        f"Website URL: {wurl}",
        f"Recent Activity Date: Not scraped — verify last post date in app",
        f"Average Engagement: Not scraped — verify in analytics or manually sample posts",
        f"Bio Text: {f['bio']}",
        f"Keywords: {f['keywords']}",
        f"Reason Qualified: {f['reason']}",
        f"Potential Services Needed: {f['services']}",
        f"Google Maps Link: {f['gmaps']}",
        f"Lead Quality Score: {f['score']}/10",
        f"Notes: {f['notes']}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    chunks = [block(i + 1, h) for i, h in enumerate(handles)]
    OUT.write_text("\n".join(chunks), encoding="utf-8")
    print("wrote", OUT, "leads", len(handles))


if __name__ == "__main__":
    main()
