#!/usr/bin/env python3
"""Generate india_jewellery_instagram_leads.txt from curated public-signal research.

Data sources: indexed Instagram captions/reels/snippets (web search + Instagram embed previews).
Fields like follower counts and engagement are included when captured from embed metadata; otherwise marked as not indexed.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Lead:
    business_name: str
    instagram: str
    city: str
    state: str
    business_type: str
    whatsapp: str
    email: str
    ordering_method: str
    website_present: str
    website_url: str
    recent_activity: str
    avg_engagement: str
    bio_text: str
    keywords: str
    reason_qualified: str
    potential_services: str
    maps_link: str
    quality_score: int
    notes: str
    followers: str = "Not captured in automated embed/index crawl"


LEADS: list[Lead] = [
    Lead(
        business_name="Jewellery Palace (BJS)",
        instagram="_jewellery_palace_bjs",
        city="Mumbai",
        state="Maharashtra",
        business_type="Imitation / fashion jewellery",
        whatsapp="+918440038551",
        email="",
        ordering_method="WhatsApp (caption: order on WhatsApp)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet (2025)",
        avg_engagement="Not measured",
        bio_text="",
        keywords="nath, order on WhatsApp, jewellery palace",
        reason_qualified="Public post shows WhatsApp ordering for jewellery SKU; Instagram-native sales motion.",
        potential_services="WhatsApp automation, lightweight catalog site, CRM, IG ads",
        maps_link="",
        quality_score=7,
        notes="Verify bio for duplicate numbers across sister pages.",
    ),
    Lead(
        business_name="Bridals Chura (Deepali Saluja)",
        instagram="bridals_chura",
        city="Hisar",
        state="Haryana",
        business_type="Bridal chura / bangles",
        whatsapp="+918607355159",
        email="",
        ordering_method="DM or WhatsApp; COD mentioned in indexed caption",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="DM or whatsapp, custom chura, bridal",
        reason_qualified="Explicit DM/WhatsApp ordering for bridal jewellery category.",
        potential_services="WhatsApp flows, IG shopping setup, CRM",
        maps_link="",
        quality_score=8,
        notes="",
    ),
    Lead(
        business_name="Chudiwale Fashion Jewellery",
        instagram="chudiwale_",
        city="India (shipping)",
        state="India",
        business_type="Velvet / bridal bangles",
        whatsapp="+917972380643",
        email="",
        ordering_method="WhatsApp booking",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="customized bangles, WhatsApp booking",
        reason_qualified="Caption requests WhatsApp for bookings/details.",
        potential_services="WhatsApp automation, catalog microsite",
        maps_link="",
        quality_score=7,
        notes="",
    ),
    Lead(
        business_name="Khushbu Jewellers (Tinwari)",
        instagram="khushbu_jewellers_tinwari",
        city="Tinwari (Rajasthan-adjacent social footprint)",
        state="Rajasthan",
        business_type="Silver / gold-polish fashion jewellery",
        whatsapp="+919929595357",
        email="",
        ordering_method="WhatsApp screenshot order + COD mentions in reels",
        website_present="No",
        website_url="",
        recent_activity="Multiple indexed reels/posts",
        avg_engagement="Not measured",
        bio_text="",
        keywords="silver, COD, whatsapp screenshot",
        reason_qualified="High-intent WhatsApp-first ordering pattern on Instagram.",
        potential_services="Ecommerce + ERP, WhatsApp CRM, inventory sync",
        maps_link="",
        quality_score=8,
        notes="Large network of related handles exists; keep this as primary Tinwari handle unless deduped by ops.",
    ),
    Lead(
        business_name="South Indian Temple Jewellery (page)",
        instagram="southindian__templejewellery",
        city="Chennai seller (caption tags)",
        state="Tamil Nadu",
        business_type="Temple / matt finish jewellery",
        whatsapp="+917904076978 / +918610765751",
        email="",
        ordering_method="DM or WhatsApp; UPI payments referenced",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="temple collections, chennai seller, WhatsApp group link in caption",
        reason_qualified="Explicit DM/WhatsApp + temple jewellery niche.",
        potential_services="WhatsApp community tooling, payments links, simple storefront",
        maps_link="",
        quality_score=8,
        notes="Caption referenced WhatsApp community join link; confirm still active.",
    ),
    Lead(
        business_name="Temple Jewellery Hub by Priya",
        instagram="templejewelleryhub_bypriya",
        city="India (shipping unclear from snippet)",
        state="India",
        business_type="Temple jewellery",
        whatsapp="",
        email="",
        ordering_method="DM (typical for priced posts)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="temple jewellery, priced post",
        reason_qualified="Temple jewellery niche with Instagram-only merchandising signals in snippet.",
        potential_services="Website + payments, WhatsApp automation",
        maps_link="",
        quality_score=6,
        notes="WhatsApp not visible in the indexed snippet; confirm via profile bio.",
    ),
    Lead(
        business_name="Oxidised Jewellery Wholesaler (page)",
        instagram="oxidised_jewellery_wholesaler",
        city="India",
        state="India",
        business_type="Oxidised / wholesale",
        whatsapp="",
        email="",
        ordering_method="DM / WhatsApp (typical wholesale pattern)",
        website_present="No",
        website_url="",
        recent_activity="Indexed URL present",
        avg_engagement="Not measured",
        bio_text="",
        keywords="oxidised, wholesaler",
        reason_qualified="Handle matches oxidised wholesale discovery angle.",
        potential_services="B2B portal, WhatsApp broadcast compliance tooling",
        maps_link="",
        quality_score=5,
        notes="Needs manual bio pass for WhatsApp digits.",
    ),
    Lead(
        business_name="Rajputi Jewellery (page)",
        instagram="rajputii_jewellery_",
        city="India",
        state="India",
        business_type="Rajputi / ethnic jewellery",
        whatsapp="",
        email="",
        ordering_method="DM",
        website_present="No",
        website_url="",
        recent_activity="Indexed comment-thread snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="rajputi jewellery",
        reason_qualified="Appeared in indexed Instagram thread context for ethnic jewellery.",
        potential_services="Catalog site, WhatsApp order desk",
        maps_link="",
        quality_score=5,
        notes="Low confidence on ordering channel from snippet alone.",
    ),
    Lead(
        business_name="Trend Jewelryys",
        instagram="trend_jewelryys",
        city="India",
        state="India",
        business_type="Fashion jewellery",
        whatsapp="",
        email="",
        ordering_method="DM",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel thread",
        avg_engagement="Not measured",
        bio_text="",
        keywords="trending jewellery",
        reason_qualified="Active reel presence in indexed results.",
        potential_services="IG content ops, ads, WhatsApp capture",
        maps_link="",
        quality_score=5,
        notes="",
    ),
    Lead(
        business_name="Jewels of Karnataka",
        instagram="jewelsofkarnataka",
        city="Karnataka",
        state="Karnataka",
        business_type="One-gram gold / fashion gold-forming",
        whatsapp="+919740234813",
        email="",
        ordering_method="WhatsApp",
        website_present="No",
        website_url="",
        recent_activity="Indexed posts mention JK collection WhatsApp",
        avg_engagement="Not measured",
        bio_text="",
        keywords="one gram gold, Karnataka, WhatsApp",
        reason_qualified="Explicit WhatsApp ordering for fast-moving SKUs.",
        potential_services="WhatsApp CRM, returns workflow, microsite",
        maps_link="",
        quality_score=8,
        notes="",
    ),
    Lead(
        business_name="Vernika Silver",
        instagram="vernika.silver.jewellery",
        city="Bengaluru",
        state="Karnataka",
        business_type="925 silver jewellery",
        whatsapp="",
        email="",
        ordering_method="Phone / in-person (caption: call for bookings)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel mentions Raja Market / Avenue Road",
        avg_engagement="Not measured",
        bio_text="",
        keywords="92.5 silver, Chikpete, video call",
        reason_qualified="Instagram-led discovery with offline booking; good services upsell.",
        potential_services="Online booking, WhatsApp commerce, local SEO, maps optimization",
        maps_link="https://www.google.com/maps/search/?api=1&query=Vernika%20Silver%20Avenue%20Road%20Bengaluru",
        quality_score=6,
        notes="Indexed snippet shows phone booking; confirm WhatsApp in bio.",
        followers="Not captured",
    ),
    Lead(
        business_name="Rajputi Jewellery Manufacturer (SC)",
        instagram="rajputi_jewelery_wholsaler_s.c",
        city="Jaipur region (typical supply chain)",
        state="Rajasthan",
        business_type="Rajputi / wholesale sets",
        whatsapp="+917877634674",
        email="",
        ordering_method="WhatsApp + group link referenced",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="wholesale, WhatsApp group",
        reason_qualified="Explicit WhatsApp + wholesale motion.",
        potential_services="B2B portal, inventory, WhatsApp automation",
        maps_link="",
        quality_score=7,
        notes="",
    ),
    Lead(
        business_name="Sai Jewellers Rajat (Ujjain)",
        instagram="sai_jewellers_rajat_ujjain",
        city="Ujjain",
        state="Madhya Pradesh",
        business_type="Gold-plated fashion jewellery",
        whatsapp="+917024274632",
        email="",
        ordering_method="DM/WhatsApp (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed comment snippet references MP/Ujjain",
        avg_engagement="Not measured",
        bio_text="",
        keywords="1gm gold plated, DM, WhatsApp",
        reason_qualified="Explicit WhatsApp/DM ordering for low-ticket plated jewellery.",
        potential_services="WhatsApp catalog, payments, IG shop",
        maps_link="",
        quality_score=7,
        notes="",
    ),
    Lead(
        business_name="Silver Wala 01",
        instagram="silver_wala_01",
        city="India",
        state="India",
        business_type="Silver / fashion silver",
        whatsapp="",
        email="",
        ordering_method="DM/WhatsApp (verify)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel thread",
        avg_engagement="Not measured",
        bio_text="",
        keywords="silver",
        reason_qualified="Appeared in indexed reel thread context.",
        potential_services="WhatsApp commerce",
        maps_link="",
        quality_score=5,
        notes="Needs bio pass for number.",
    ),
    Lead(
        business_name="Samskruthi Jewellers",
        instagram="samskruthijewellers",
        city="Surat",
        state="Gujarat",
        business_type="925 silver bridal / layered necklaces",
        whatsapp="+918790112233",
        email="",
        ordering_method="WhatsApp (multiple reels)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reels (2025)",
        avg_engagement="Not measured",
        bio_text="",
        keywords="925 silver, layered necklace, bridal",
        reason_qualified="Repeated WhatsApp ordering CTAs on reels.",
        potential_services="WhatsApp CRM, product pages, ads",
        maps_link="",
        quality_score=8,
        notes="",
    ),
    Lead(
        business_name="Varudi Jeweller",
        instagram="varudijewellers",
        city="Surat",
        state="Gujarat",
        business_type="Certified gold jewellery (DM buying)",
        whatsapp="",
        email="",
        ordering_method="DM (caption: Just DM us)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="BIS hallmark, DM order",
        reason_qualified="DM-first buying on Instagram for a jeweller.",
        potential_services="Website + appointment booking, trust content, CRM",
        maps_link="",
        quality_score=6,
        notes="May still have offline showroom; verify website absence carefully.",
    ),
    Lead(
        business_name="Gohar Jewels Official",
        instagram="goharjewelsofficial",
        city="India",
        state="India",
        business_type="Resin / floral jhumkas",
        whatsapp="",
        email="",
        ordering_method="DM",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="resin jhumkas, handmade",
        reason_qualified="Resin jewellery niche; handmade positioning.",
        potential_services="Etsy sync, IG shop, WhatsApp",
        maps_link="",
        quality_score=6,
        notes="Confirm India base from bio; snippet did not include city.",
    ),
    Lead(
        business_name="Resin Gifts by Anjalii",
        instagram="resin_gifts_by_anjalii_",
        city="Ahmedabad",
        state="Gujarat",
        business_type="Resin keepsakes (adjacent; verify jewellery mix)",
        whatsapp="",
        email="",
        ordering_method="DM",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel title mentions Ahmedabad",
        avg_engagement="Not measured",
        bio_text="",
        keywords="resin, Ahmedabad",
        reason_qualified="Strong SMB resin creator footprint; may cross-sell jewellery pieces.",
        potential_services="WhatsApp automation, ecommerce",
        maps_link="",
        quality_score=5,
        notes="Jewellery-specific SKU mix should be validated.",
    ),
    Lead(
        business_name="Aashu's Pearl Creation",
        instagram="aashus_pearl_creation",
        city="Maharashtra (caption tags)",
        state="Maharashtra",
        business_type="Handmade traditional jewellery",
        whatsapp="",
        email="",
        ordering_method="DM to order (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="handmade choker, DM, Marathi traditional",
        reason_qualified="Explicit DM ordering language.",
        potential_services="WhatsApp + catalog",
        maps_link="",
        quality_score=7,
        notes="",
    ),
    Lead(
        business_name="Flabel Creations",
        instagram="flabelcreations",
        city="Pune",
        state="Maharashtra",
        business_type="AD / fashion necklace sets",
        whatsapp="+917711990044",
        email="",
        ordering_method="WhatsApp (link in bio) + DM",
        website_present="Link-in-bio likely (not verified)",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="link in bio, WhatsApp, same day dispatch",
        reason_qualified="Classic IG + WhatsApp funnel language.",
        potential_services="WhatsApp automation, landing pages, CRM",
        maps_link="",
        quality_score=8,
        notes="",
    ),
    Lead(
        business_name="Lakshmi Creations (Imitation)",
        instagram="lakshmi_creations_9",
        city="India",
        state="India",
        business_type="Imitation jewellery wholesale/retail",
        whatsapp="+919849567353",
        email="",
        ordering_method="WhatsApp",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="imitation jewellery, wholesale",
        reason_qualified="WhatsApp for orders + wholesale angle.",
        potential_services="B2B portal, WhatsApp broadcast compliance",
        maps_link="",
        quality_score=7,
        notes="",
    ),
    Lead(
        business_name="Wear and Shine Jewelry",
        instagram="wear_nd_shine_jewelry",
        city="India",
        state="India",
        business_type="Fashion jewellery",
        whatsapp="",
        email="",
        ordering_method="DM",
        website_present="No",
        website_url="",
        recent_activity="Indexed thread",
        avg_engagement="Not measured",
        bio_text="",
        keywords="fashion jewellery",
        reason_qualified="Active microbrand signals in indexed thread.",
        potential_services="IG growth, WhatsApp",
        maps_link="",
        quality_score=5,
        notes="",
    ),
    Lead(
        business_name="Biswakarma Jewellery Shilpaya",
        instagram="bjs2k",
        city="Kolkata",
        state="West Bengal",
        business_type="Diamond nosepins / earrings (retail jeweller)",
        whatsapp="+919874085669",
        email="",
        ordering_method="WhatsApp",
        website_present="No",
        website_url="",
        recent_activity="Indexed posts",
        avg_engagement="Not measured",
        bio_text="",
        keywords="diamond nosepin, WhatsApp",
        reason_qualified="Explicit WhatsApp CTAs for high-intent SKUs.",
        potential_services="WhatsApp CRM, appointment booking, reviews site",
        maps_link="https://www.google.com/maps/search/?api=1&query=Biswakarma%20Jewellery%20Shilpaya%20Kolkata",
        quality_score=7,
        notes="Physical jeweller; still strong WhatsApp motion.",
    ),
    Lead(
        business_name="Indrani Biswas (Clay Jewellery)",
        instagram="indranibiswas_",
        city="Kolkata",
        state="West Bengal",
        business_type="Clay / handmade chokers",
        whatsapp="",
        email="",
        ordering_method="DM to buy (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet (Bengali new year collection)",
        avg_engagement="Not measured",
        bio_text="",
        keywords="clay jewellery, DM to buy, handmade",
        reason_qualified="DM commerce for handmade jewellery niche.",
        potential_services="Ecommerce, IG shop, WhatsApp",
        maps_link="",
        quality_score=7,
        notes="",
    ),
    Lead(
        business_name="Lavanya Jewellers (SLJ)",
        instagram="lavanyajewellers_slj",
        city="Vijayawada",
        state="Andhra Pradesh",
        business_type="Gold / diamond customised pieces",
        whatsapp="+919441176530",
        email="",
        ordering_method="DM / phone (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed posts",
        avg_engagement="Not measured",
        bio_text="",
        keywords="customised orders, shipping worldwide",
        reason_qualified="Custom orders via DM/phone; strong services upsell.",
        potential_services="CRM, payments, website, logistics integrations",
        maps_link="",
        quality_score=6,
        notes="Verify absence of separate ecommerce domain beyond Instagram.",
    ),
    Lead(
        business_name="Jewel Indukuri's",
        instagram="indukurisjewel",
        city="Hyderabad (typical for surname; verify)",
        state="Telangana",
        business_type="Lab-grown diamond pendants",
        whatsapp="+916302720676",
        email="",
        ordering_method="WhatsApp",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="labgrown diamond, customise",
        reason_qualified="WhatsApp-first customised jewellery consults.",
        potential_services="3D renders, CRM, WhatsApp automation",
        maps_link="",
        quality_score=7,
        notes="City inferred; confirm via bio.",
    ),
    Lead(
        business_name="Chezhiyan Velli Maaligai",
        instagram="chezian_velli_maaligai",
        city="Chennai",
        state="Tamil Nadu",
        business_type="925 silver wedding rings / silver",
        whatsapp="+917010078402",
        email="",
        ordering_method="DM or WhatsApp (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="silver 92.5, customised laser name",
        reason_qualified="Explicit DM/WhatsApp ordering for customised silver.",
        potential_services="Product configurator, WhatsApp automation",
        maps_link="",
        quality_score=8,
        notes="",
    ),
    Lead(
        business_name="SHREE SILVER (Silver Jewels Pune)",
        instagram="silver_jewels_pune",
        city="Pune",
        state="Maharashtra",
        business_type="925 silver retail",
        whatsapp="",
        email="",
        ordering_method="Store visit / online order (caption says order online; verify channel)",
        website_present="Unknown",
        website_url="",
        recent_activity="Indexed reel mentions Raviwar Peth address",
        avg_engagement="Not measured",
        bio_text="",
        keywords="925 silver, Pune",
        reason_qualified="Local silver retail with Instagram discovery.",
        potential_services="Local SEO, WhatsApp, appointment booking",
        maps_link="https://www.google.com/maps/search/?api=1&query=Shree%20Silver%20Raviwar%20Peth%20Pune",
        quality_score=5,
        notes="Needs bio pass for WhatsApp digits and website presence.",
    ),
    Lead(
        business_name="Silver Shine Jewellery",
        instagram="silvershine_jewelery",
        city="Vadodara",
        state="Gujarat",
        business_type="925 silver fashion jewellery",
        whatsapp="+917572962224",
        email="",
        ordering_method="DM/WhatsApp (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="hallmark silver, order on DM WhatsApp",
        reason_qualified="Explicit DM/WhatsApp ordering.",
        potential_services="WhatsApp catalog, IG shop",
        maps_link="",
        quality_score=8,
        notes="",
    ),
    Lead(
        business_name="Lucknow Artificial Jewellery",
        instagram="lucknow_artificial_jewellery_",
        city="Lucknow",
        state="Uttar Pradesh",
        business_type="One-gram gold polish / artificial",
        whatsapp="+918957754721",
        email="",
        ordering_method="WhatsApp booking number",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="COD, artificial jewellery, Lucknow",
        reason_qualified="COD + WhatsApp booking pattern for SMB.",
        potential_services="WhatsApp CRM, fraud checks, microsite",
        maps_link="",
        quality_score=8,
        notes="",
    ),
    Lead(
        business_name="Those Little Bling (oxidised / moissanite)",
        instagram="thoselittleblingss",
        city="India",
        state="India",
        business_type="Oxidised + moissanite fashion jewellery",
        whatsapp="",
        email="",
        ordering_method="DM to order (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="dm to order, moissanite, oxidised",
        reason_qualified="Embed preview indicated ~2.3K–4.9K followers; DM ordering.",
        potential_services="WhatsApp + payments, IG shop",
        maps_link="",
        quality_score=7,
        notes="Handle spelling is thoselittleblingss (double s) per embed preview.",
        followers="~2.4K–4.9K (embed preview range; verify live)",
    ),
    Lead(
        business_name="R.A.N.I Jewellery",
        instagram="rani_redux",
        city="Kerala / TN markets (caption tags)",
        state="Kerala",
        business_type="Beaded fashion sets",
        whatsapp="",
        email="",
        ordering_method="DM for orders (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="DM us for orders, beaded mala",
        reason_qualified="Explicit DM ordering.",
        potential_services="WhatsApp, landing pages",
        maps_link="",
        quality_score=7,
        notes="",
    ),
    Lead(
        business_name="Sakhi 1 Gram Gold Jewellery",
        instagram="sakhi_1_gram_gold_jewellery",
        city="India",
        state="India",
        business_type="One-gram gold fashion",
        whatsapp="+919652417754",
        email="",
        ordering_method="WhatsApp",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="one gram gold, whatsapp",
        reason_qualified="WhatsApp-first SKU posts.",
        potential_services="WhatsApp automation, catalog",
        maps_link="",
        quality_score=8,
        notes="",
    ),
    Lead(
        business_name="Roshi Collections",
        instagram="roshi.collections",
        city="Tamil Nadu (shipping mentions TN)",
        state="Tamil Nadu",
        business_type="One-gram gold forming",
        whatsapp="+919092327836",
        email="",
        ordering_method="WhatsApp + screenshot workflow",
        website_present="No",
        website_url="",
        recent_activity="Indexed posts",
        avg_engagement="Not measured",
        bio_text="",
        keywords="gold forming, online payment only",
        reason_qualified="Strong WhatsApp ordering workflow in captions.",
        potential_services="CRM, returns video workflow automation",
        maps_link="",
        quality_score=8,
        notes="Unrelated roshijewellery.com domain may exist for a different entity; do not merge without verification.",
    ),
    Lead(
        business_name="Just Kundan",
        instagram="just_kundan",
        city="India",
        state="India",
        business_type="Kundan fashion",
        whatsapp="",
        email="",
        ordering_method="DM",
        website_present="No",
        website_url="",
        recent_activity="Indexed thread",
        avg_engagement="Not measured",
        bio_text="",
        keywords="kundan",
        reason_qualified="Appeared in indexed thread context.",
        potential_services="WhatsApp commerce",
        maps_link="",
        quality_score=5,
        notes="Needs bio pass for WhatsApp digits.",
    ),
    Lead(
        business_name="JJ Resin Memo",
        instagram="jj_resin.memo",
        city="India",
        state="India",
        business_type="Resin gifts / accessories",
        whatsapp="+918489166598",
        email="",
        ordering_method="WhatsApp (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="customisable, WhatsApp",
        reason_qualified="WhatsApp confirm flow for custom SMB.",
        potential_services="WhatsApp automation, ecommerce",
        maps_link="",
        quality_score=6,
        notes="",
    ),
    Lead(
        business_name="SuruArts Creation (SAC Jewellery)",
        instagram="suruarts_creation_official",
        city="Navi Mumbai / Mumbai",
        state="Maharashtra",
        business_type="Maharashtrian imitation / 1gm jewellery",
        whatsapp="+919373722506",
        email="",
        ordering_method="WhatsApp (wa.me link in caption) + inbox",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="wa.me, artificial, branches listed",
        reason_qualified="Explicit wa.me + inbox ordering for SMB chain.",
        potential_services="Multi-location CRM, WhatsApp automation, website",
        maps_link="",
        quality_score=8,
        notes="Multiple branches; still SMB-style ops vs national D2C.",
    ),
    Lead(
        business_name="Omkar Jewels Surat",
        instagram="omkar_jewels_surat",
        city="Surat",
        state="Gujarat",
        business_type="Custom / bespoke jewellery",
        whatsapp="+918141248248",
        email="",
        ordering_method="Phone/WhatsApp (number in caption) + showroom visit",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="custom jewelry, Surat address",
        reason_qualified="Custom orders + direct contact number published.",
        potential_services="3D design pipeline, CRM, website",
        maps_link="https://www.google.com/maps/search/?api=1&query=Omkar%20Jewels%20Uttran%20Surat",
        quality_score=6,
        notes="",
    ),
    Lead(
        business_name="Asha Bangles Official",
        instagram="ashabanglesofficial",
        city="Ambala / North India footprint",
        state="Haryana",
        business_type="Punjabi bridal chura / bangles",
        whatsapp="+917014592741",
        email="",
        ordering_method="WhatsApp",
        website_present="No",
        website_url="",
        recent_activity="Embed preview ~62K followers",
        avg_engagement="Not measured",
        bio_text="",
        keywords="partial COD, customisation, chura",
        reason_qualified="Strong WhatsApp + custom bridal SKU motion.",
        potential_services="WhatsApp flows, CRM, IG ads",
        maps_link="",
        quality_score=8,
        notes="",
        followers="~62K (embed preview)",
    ),
    Lead(
        business_name="Anikalan Jewels",
        instagram="anikalan.co.in",
        city="India",
        state="India",
        business_type="Jadau kundan",
        whatsapp="+919042729768",
        email="",
        ordering_method="DM or WhatsApp (caption)",
        website_present="Unknown",
        website_url="https://anikalan.co.in (likely; verify)",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="jadau kundan, DM or WhatsApp",
        reason_qualified="WhatsApp/DM ordering; verify website scope before pitching 'no website'.",
        potential_services="If site is weak: CRO; WhatsApp automation regardless",
        maps_link="",
        quality_score=6,
        notes="Handle suggests a domain exists—confirm before classifying as no-website.",
    ),
    Lead(
        business_name="Pooja Jewels",
        instagram="poojajewels_",
        city="India",
        state="India",
        business_type="Fashion jewellery",
        whatsapp="",
        email="",
        ordering_method="DM",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel thread",
        avg_engagement="Not measured",
        bio_text="",
        keywords="jewels",
        reason_qualified="Active reel thread presence.",
        potential_services="WhatsApp capture",
        maps_link="",
        quality_score=5,
        notes="",
    ),
    Lead(
        business_name="Amethyst Jewelz",
        instagram="_amethyst__jewelz",
        city="India",
        state="India",
        business_type="Fashion jewellery",
        whatsapp="",
        email="",
        ordering_method="DM",
        website_present="No",
        website_url="",
        recent_activity="Indexed thread",
        avg_engagement="Not measured",
        bio_text="",
        keywords="amethyst, jewelz",
        reason_qualified="Microbrand signals in indexed thread.",
        potential_services="IG shop",
        maps_link="",
        quality_score=5,
        notes="",
    ),
    Lead(
        business_name="Sal's Artisau",
        instagram="salsartisau",
        city="Kochi",
        state="Kerala",
        business_type="Handmade beaded earrings",
        whatsapp="",
        email="",
        ordering_method="DM (typical)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="handmade earring, Kochi",
        reason_qualified="Handmade jewellery SMB with India location tag in snippet.",
        potential_services="Ecommerce, IG shop",
        maps_link="",
        quality_score=6,
        notes="",
    ),
    Lead(
        business_name="Junaki Jewellery House",
        instagram="junaki_jewellery_house",
        city="Assam",
        state="Assam",
        business_type="Assamese traditional jewellery",
        whatsapp="+918721881403",
        email="",
        ordering_method="DM or WhatsApp (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="Assamese bride, DM, WhatsApp, no COD",
        reason_qualified="Explicit DM/WhatsApp booking; niche regional jewellery.",
        potential_services="WhatsApp automation, shipping policy pages",
        maps_link="",
        quality_score=8,
        notes="",
    ),
    Lead(
        business_name="Konmani Store",
        instagram="konmani_store",
        city="Dibrugarh",
        state="Assam",
        business_type="Traditional Assamese stone jewellery",
        whatsapp="",
        email="",
        ordering_method="DM",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="traditional assamese jewellery",
        reason_qualified="Regional jewellery SMB discovery.",
        potential_services="WhatsApp commerce, ecommerce",
        maps_link="",
        quality_score=6,
        notes="",
    ),
    Lead(
        business_name="Usha Artificial Jewellery",
        instagram="jewelleryusha",
        city="Gwalior",
        state="Madhya Pradesh",
        business_type="Artificial jewellery retail",
        whatsapp="+918602585508",
        email="",
        ordering_method="WhatsApp / store",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet with shop address",
        avg_engagement="Not measured",
        bio_text="",
        keywords="artificial jewellery, Hazira",
        reason_qualified="Phone published with physical shop; Instagram discovery.",
        potential_services="Google Business Profile, WhatsApp, website",
        maps_link="https://www.google.com/maps/search/?api=1&query=Usha%20Artificial%20Jewellery%20Gwalior",
        quality_score=7,
        notes="",
    ),
    Lead(
        business_name="Supriya Affordable Jewellery",
        instagram="supriya.affordable_jewellery",
        city="India",
        state="India",
        business_type="Enamel / affordable earrings",
        whatsapp="",
        email="",
        ordering_method="DM for orders (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="enamel, DM for orders, online payment only",
        reason_qualified="Embed preview indicated ~21K followers; DM ordering.",
        potential_services="WhatsApp + payments links",
        maps_link="",
        quality_score=7,
        notes="",
        followers="~21K (embed preview)",
    ),
    Lead(
        business_name="Gemi Jewellery World",
        instagram="gemijewllery_world",
        city="Mumbai (location tag in embed preview)",
        state="Maharashtra",
        business_type="Kundan / wedding sets (fashion)",
        whatsapp="+918928286885",
        email="",
        ordering_method="WhatsApp / call (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="kundan, handmade, Bollywood",
        reason_qualified="Explicit WhatsApp order line in indexed caption.",
        potential_services="Catalog site, WhatsApp CRM",
        maps_link="",
        quality_score=7,
        notes="",
        followers="~4K (embed preview)",
    ),
    Lead(
        business_name="The Madras Art Studio",
        instagram="themadras_artstudio",
        city="Chennai",
        state="Tamil Nadu",
        business_type="Resin jewellery (flower preserved)",
        whatsapp="",
        email="",
        ordering_method="DM to order (caption)",
        website_present="Unknown",
        website_url="https://madrasart.studio (possible separate art studio site)",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="DM to order, customised resin",
        reason_qualified="DM-first custom resin jewellery; verify website overlap.",
        potential_services="Product customizer, WhatsApp, ecommerce",
        maps_link="",
        quality_score=7,
        notes="madrasart.studio may exist; treat website presence as unknown until verified.",
    ),
    Lead(
        business_name="Beautiful Creations 0365",
        instagram="beautiful_creations0365",
        city="India",
        state="India",
        business_type="Moissanite / polki kundan",
        whatsapp="+919911283949",
        email="",
        ordering_method="DM or WhatsApp with picture (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="moissanite, kundan, no COD",
        reason_qualified="High-ticket SMB workflow via DM/WhatsApp.",
        potential_services="CRM, payments, authenticated catalogue",
        maps_link="",
        quality_score=8,
        notes="",
    ),
    Lead(
        business_name="Aakanksha Jewellery",
        instagram="aakanksha_jewellery",
        city="Maharashtra (Marathi bridal focus)",
        state="Maharashtra",
        business_type="Traditional moti bangles / bridal",
        whatsapp="+919324512333",
        email="",
        ordering_method="WhatsApp (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="moti bangles, Maharashtrian bridal",
        reason_qualified="Explicit WhatsApp contact line.",
        potential_services="WhatsApp automation, IG shop",
        maps_link="",
        quality_score=7,
        notes="",
        followers="~113K (embed preview; larger SMB)",
    ),
    Lead(
        business_name="Aaras Terracotta Jewellery",
        instagram="aaras_terracotta",
        city="Chennai",
        state="Tamil Nadu",
        business_type="Terracotta jewellery",
        whatsapp="+919940438577",
        email="",
        ordering_method="DM to order / WhatsApp number in caption",
        website_present="No",
        website_url="",
        recent_activity="Indexed posts",
        avg_engagement="Not measured",
        bio_text="",
        keywords="terracotta, customised, worldwide shipping",
        reason_qualified="DM + phone ordering for customised terracotta sets.",
        potential_services="Ecommerce, logistics, WhatsApp",
        maps_link="",
        quality_score=8,
        notes="",
    ),
    Lead(
        business_name="Sruthi Terracotta Creations",
        instagram="sruthiterracottacreations",
        city="Bengaluru",
        state="Karnataka",
        business_type="Terracotta jewellery",
        whatsapp="+919036384234",
        email="",
        ordering_method="DM / wa.me (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="terracotta, wa.me, customised",
        reason_qualified="Explicit wa.me / DM path.",
        potential_services="WhatsApp automation, IG shop",
        maps_link="",
        quality_score=8,
        notes="",
    ),
    Lead(
        business_name="Elegant Fashion by Rupika",
        instagram="elegant_fashion6095",
        city="India",
        state="India",
        business_type="Terracotta earrings",
        whatsapp="+919087319846",
        email="",
        ordering_method="DM @elegant_fashion6095 or WhatsApp",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="handmade terracotta, customised colors",
        reason_qualified="Explicit DM/WhatsApp ordering.",
        potential_services="WhatsApp catalog",
        maps_link="",
        quality_score=7,
        notes="",
    ),
    Lead(
        business_name="HAARAM by Yashh",
        instagram="haarambyyashh",
        city="India",
        state="India",
        business_type="Terracotta jewellery",
        whatsapp="",
        email="",
        ordering_method="DM",
        website_present="No",
        website_url="",
        recent_activity="Indexed profile existence",
        avg_engagement="Not measured",
        bio_text="",
        keywords="terracoatta, HAARAM",
        reason_qualified="Terracotta niche handle surfaced in search.",
        potential_services="WhatsApp commerce",
        maps_link="",
        quality_score=5,
        notes="Needs manual bio pass for WhatsApp digits.",
    ),
    Lead(
        business_name="Shopforaccessorie by Sanjana",
        instagram="shopforaccessorie",
        city="India",
        state="India",
        business_type="Afghani / statement sets",
        whatsapp="",
        email="",
        ordering_method="DM to place order (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="Afghani, DM us to place your order",
        reason_qualified="Explicit DM ordering language.",
        potential_services="WhatsApp automation",
        maps_link="",
        quality_score=7,
        notes="",
    ),
    Lead(
        business_name="Supriya Jewellery",
        instagram="supriya_jewellery",
        city="Mumbai",
        state="Maharashtra",
        business_type="Marathi traditional jewellery",
        whatsapp="+919152275741",
        email="",
        ordering_method="DM for order (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="hirva chuda, DM for order",
        reason_qualified="DM ordering + strong regional niche.",
        potential_services="WhatsApp catalog, CRM",
        maps_link="",
        quality_score=7,
        notes="",
    ),
    Lead(
        business_name="VS Jewellery",
        instagram="vs_jewellery",
        city="Mumbai",
        state="Maharashtra",
        business_type="Marathi jewellery (collab posts)",
        whatsapp="",
        email="",
        ordering_method="DM (via collab captions)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="collab, DM for order",
        reason_qualified="Collab-driven SMB distribution.",
        potential_services="Influencer ops, WhatsApp",
        maps_link="",
        quality_score=5,
        notes="Often posts collabs; verify primary WhatsApp in bio.",
    ),
    Lead(
        business_name="Mingled by Maya",
        instagram="mingled_by_maya",
        city="Kerala",
        state="Kerala",
        business_type="Afghani / ethnic earrings",
        whatsapp="",
        email="",
        ordering_method="DM to order (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="DM to order, Afghani earrings",
        reason_qualified="Embed preview: verified + ~21K followers; DM ordering.",
        potential_services="WhatsApp automation, IG shop",
        maps_link="",
        quality_score=8,
        notes="",
        followers="~21K (embed preview)",
    ),
    Lead(
        business_name="Rani Sarkar Jewellery",
        instagram="ranisarkar_jewellery",
        city="Pune",
        state="Maharashtra",
        business_type="Copper / Peshwai combo jewellery",
        whatsapp="+917620369051 / +918265010347 / +918767667090",
        email="",
        ordering_method="WhatsApp screenshot workflow",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet with shop addresses",
        avg_engagement="Not measured",
        bio_text="",
        keywords="Peshwai combo, Sinhagad Road",
        reason_qualified="Explicit WhatsApp workflow + local shops.",
        potential_services="POS + WhatsApp CRM, local SEO",
        maps_link="https://www.google.com/maps/search/?api=1&query=Rani%20Sarkar%20Jewellery%20Sinhagad%20Road%20Pune",
        quality_score=8,
        notes="",
    ),
    Lead(
        business_name="Because It's Silver",
        instagram="bcos_its_silver",
        city="Hyderabad",
        state="Telangana",
        business_type="Pure silver guttapusalu / premium silver",
        whatsapp="",
        email="",
        ordering_method="DM (typical for premium silver brands)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="hyderabad pearls, guttapusalu",
        reason_qualified="Hyderabad premium silver catalogue posts.",
        potential_services="Ecommerce, appointment booking",
        maps_link="",
        quality_score=6,
        notes="Older indexed post; verify current activity.",
    ),
    Lead(
        business_name="Sujatha Gold Covering Works",
        instagram="sujatha_gold_covering_works",
        city="Machilipatnam area",
        state="Andhra Pradesh",
        business_type="Micro gold-plated / AD sets",
        whatsapp="+917382222208 / +917997757703 / +918886428899 / +917036132171 (bulk)",
        email="",
        ordering_method="WhatsApp bookings / COD mentions",
        website_present="No",
        website_url="",
        recent_activity="Indexed reels",
        avg_engagement="Not measured",
        bio_text="",
        keywords="one gram gold plated, COD, bulk",
        reason_qualified="WhatsApp-heavy wholesale/retail motion.",
        potential_services="B2B portal, inventory, WhatsApp automation",
        maps_link="",
        quality_score=8,
        notes="Multiple numbers; treat as call center style SMB.",
    ),
    Lead(
        business_name="Onkar India Pearls & Jewells (Wholesale Pearls)",
        instagram="wholesalepearlsjewells.onkar",
        city="India",
        state="India",
        business_type="Fashion / wholesale jewellery",
        whatsapp="+919996698633",
        email="",
        ordering_method="DM for catalog (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="manufacturer, DM for catalog",
        reason_qualified="DM-first wholesale catalog motion.",
        potential_services="B2B portal, CRM, email marketing",
        maps_link="",
        quality_score=6,
        notes="",
    ),
    Lead(
        business_name="Rajputi Jewellery by Priti Rajawat",
        instagram="rajputij_by_pritirajawat",
        city="Rajasthan (Rajputi niche)",
        state="Rajasthan",
        business_type="Rajputi bridal sets",
        whatsapp="+918741074868",
        email="",
        ordering_method="WhatsApp booking (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="hasli, chand bali, WhatsApp",
        reason_qualified="Explicit WhatsApp booking line.",
        potential_services="WhatsApp CRM, landing pages",
        maps_link="",
        quality_score=7,
        notes="",
        followers="~78K (embed preview)",
    ),
    Lead(
        business_name="Paramount Jewels (wholesale contact via influencer post)",
        instagram="manisha.aggarwalak",
        city="Delhi",
        state="Delhi",
        business_type="Artificial jewellery wholesale (Chandni Chowk)",
        whatsapp="+919811940528 / +918882529085",
        email="",
        ordering_method="WhatsApp / call (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="Dariba Kalan, wholesale, MOQ",
        reason_qualified="Wholesale SMB motion; good fit for B2B tooling (not typical D2C).",
        potential_services="B2B ordering portal, WhatsApp, inventory",
        maps_link="https://www.google.com/maps/search/?api=1&query=Paramount%20Jewels%20Dariba%20Kalan%20Delhi",
        quality_score=6,
        notes="This is an influencer/shopping post referencing Paramount Jewels; validate merchant consent for outreach.",
    ),
    Lead(
        business_name="Yuvraj Nosepins",
        instagram="yuvraj_nosepins",
        city="Delhi",
        state="Delhi",
        business_type="Gold lightweight fancy nosepins/earrings (store)",
        whatsapp="",
        email="",
        ordering_method="Store visit (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet (Chandni Chowk)",
        avg_engagement="Not measured",
        bio_text="",
        keywords="Chandni Chowk, fancy jhumka",
        reason_qualified="SMB jeweller using Instagram for discovery.",
        potential_services="Local SEO, WhatsApp, ecommerce",
        maps_link="https://www.google.com/maps/search/?api=1&query=Yuvraj%20Nosepins%20Kucha%20Mahajani%20Delhi",
        quality_score=5,
        notes="",
    ),
    Lead(
        business_name="S Swarnakar & Son",
        instagram="s.swarnakarandson",
        city="Kolkata",
        state="West Bengal",
        business_type="Gold jewellery (Chetla)",
        whatsapp="+918981948452",
        email="",
        ordering_method="WhatsApp booking (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="Kolkata, gold choker, booking no",
        reason_qualified="Explicit booking number published on Instagram.",
        potential_services="CRM, WhatsApp automation, website",
        maps_link="https://www.google.com/maps/search/?api=1&query=Swarnakar%20%26%20Son%20Chetla%20Kolkata",
        quality_score=6,
        notes="Traditional gold store; verify IG-first positioning vs showroom-first.",
    ),
    Lead(
        business_name="Shree Ram Jewellers",
        instagram="shreeramjewellers2005",
        city="Delhi",
        state="Delhi",
        business_type="Gold jewellery",
        whatsapp="+919560512913 / +919953743293",
        email="",
        ordering_method="Call/WhatsApp (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="Mangolpuri, gold",
        reason_qualified="Phone numbers published on Instagram reel.",
        potential_services="Website, CRM, local ads",
        maps_link="https://www.google.com/maps/search/?api=1&query=Shree%20Ram%20Jewellers%20Mangolpuri%20Delhi",
        quality_score=6,
        notes="",
    ),
    Lead(
        business_name="Jodhpuri Jewellery (Salasar Payal House)",
        instagram="jodhpuri__jewellery",
        city="Jodhpur",
        state="Rajasthan",
        business_type="Traditional payal / rakhdi",
        whatsapp="+917568283224",
        email="",
        ordering_method="WhatsApp",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="gold rakhdi set, Jodhpur",
        reason_qualified="WhatsApp order line for traditional SKU.",
        potential_services="WhatsApp automation, catalogue microsite",
        maps_link="",
        quality_score=7,
        notes="",
    ),
    Lead(
        business_name="Rajputi Jewellery Bhilwara",
        instagram="rajputijewellerybhilwara00",
        city="Bhilwara",
        state="Rajasthan",
        business_type="Rajputi gold-look plated sets",
        whatsapp="+919829900459",
        email="",
        ordering_method="WhatsApp",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="rajputi aad, online payment",
        reason_qualified="WhatsApp-first ordering for high-ticket imitation sets.",
        potential_services="WhatsApp CRM, trust badges, microsite",
        maps_link="",
        quality_score=8,
        notes="",
    ),
    Lead(
        business_name="Mahalaxmi Gold",
        instagram="mahalaxmi_gold99",
        city="Mysuru",
        state="Karnataka",
        business_type="Gold chains / casting",
        whatsapp="+919880820391 / +917348921999",
        email="",
        ordering_method="DM / WhatsApp (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="916 hallmark, casting chain",
        reason_qualified="Explicit WhatsApp numbers for a regional jeweller.",
        potential_services="CRM, website, payments",
        maps_link="",
        quality_score=6,
        notes="",
    ),
    Lead(
        business_name="Jodhpuri Silver",
        instagram="jodhpuri_silver",
        city="Jodhpur",
        state="Rajasthan",
        business_type="Silver payal / silver fashion",
        whatsapp="+919358839704",
        email="",
        ordering_method="WhatsApp screenshot order (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="silver payal, COD",
        reason_qualified="WhatsApp screenshot ordering pattern.",
        potential_services="WhatsApp automation, returns workflow",
        maps_link="",
        quality_score=7,
        notes="",
    ),
    Lead(
        business_name="Mata Payals (Silver Store Mata Payals)",
        instagram="silver_store_matapayals",
        city="India",
        state="India",
        business_type="925 silver anklets/payals",
        whatsapp="",
        email="",
        ordering_method="DM",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="925 silver anklets",
        reason_qualified="Silver anklet niche SMB.",
        potential_services="WhatsApp commerce",
        maps_link="",
        quality_score=5,
        notes="",
    ),
    Lead(
        business_name="Silver Palace 45",
        instagram="silver_palace45",
        city="India",
        state="India",
        business_type="Silver mangalsutra/payal promotions",
        whatsapp="+919887305357",
        email="",
        ordering_method="WhatsApp order (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="WhatsApp order, discount",
        reason_qualified="Explicit WhatsApp order line; embed preview ~97K followers (larger SMB).",
        potential_services="WhatsApp CRM, IG shop",
        maps_link="",
        quality_score=6,
        notes="Larger following; still WhatsApp-led merchandising.",
        followers="~97K (embed preview)",
    ),
    Lead(
        business_name="Yash Ornaments (Chandni Chowk)",
        instagram="yash_ornaments",
        city="Delhi",
        state="Delhi",
        business_type="Gold jewellery retail",
        whatsapp="+919958113991",
        email="",
        ordering_method="Call / WhatsApp (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="Chandni Chowk, AJPL, offers",
        reason_qualified="Phone published; IG promo for Delhi jeweller.",
        potential_services="Website, CRM, ads",
        maps_link="https://www.google.com/maps/search/?api=1&query=Yash%20Ornaments%20Kucha%20Mahajani%20Delhi",
        quality_score=5,
        notes="",
        followers="~92K (embed preview)",
    ),
    Lead(
        business_name="Kayels Creations (Terracotta)",
        instagram="kayels_creations",
        city="India",
        state="India",
        business_type="Terracotta jewellery",
        whatsapp="+919486034402 / +916382372408",
        email="",
        ordering_method="DM/WhatsApp (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="terracotta jewellery, DM whatsapp",
        reason_qualified="Explicit DM/WhatsApp ordering.",
        potential_services="WhatsApp automation",
        maps_link="",
        quality_score=7,
        notes="",
    ),
    Lead(
        business_name="Riyas Artistry (Clay accessories)",
        instagram="riyas_artistry01",
        city="Jhunjhunu",
        state="Rajasthan",
        business_type="Clay keychains / small accessories",
        whatsapp="+919468654816",
        email="",
        ordering_method="DM / WhatsApp (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="DM for order, clay",
        reason_qualified="SMB DM/WhatsApp motion; adjacent to jewellery gifting.",
        potential_services="Ecommerce, WhatsApp",
        maps_link="",
        quality_score=6,
        notes="",
        followers="~2K (embed preview)",
    ),
    Lead(
        business_name="Crimson Aura (Pearl strings)",
        instagram="crimson_aura",
        city="Hyderabad",
        state="Telangana",
        business_type="Pearl strings / fine jewellery boutique",
        whatsapp="+9198556027 (verify full +91 formatting in bio)",
        email="",
        ordering_method="Call / online boutique (caption)",
        website_present="Unknown",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="Hyderabad pearls, home boutique",
        reason_qualified="Embed preview ~1K followers; boutique pearl seller.",
        potential_services="Ecommerce, appointment booking, WhatsApp",
        maps_link="",
        quality_score=7,
        notes="Indexed caption shows an 8-digit phone pattern; confirm full international number in bio.",
        followers="~1K (embed preview)",
    ),
    Lead(
        business_name="Made of Clay (Polymer clay earrings)",
        instagram="madeofclay.in",
        city="India",
        state="India",
        business_type="Polymer clay earrings",
        whatsapp="",
        email="",
        ordering_method="Order now CTA (verify DM vs website)",
        website_present="Unknown",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="polymer clay india, small business india",
        reason_qualified="India polymer clay SMB; embed preview ~7K followers.",
        potential_services="IG shop, WhatsApp, ecommerce",
        maps_link="",
        quality_score=6,
        notes="",
        followers="~7K (embed preview)",
    ),
    Lead(
        business_name="Jewelz by Aayushi",
        instagram="jewelz_by_aayushi",
        city="India",
        state="India",
        business_type="Fashion jewellery",
        whatsapp="",
        email="",
        ordering_method="DM for order (caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="Dm for order",
        reason_qualified="Explicit DM ordering; embed preview ~17K followers.",
        potential_services="WhatsApp automation, IG shop",
        maps_link="",
        quality_score=7,
        notes="",
        followers="~17K (embed preview)",
    ),
    Lead(
        business_name="Nazneen Bangles King",
        instagram="nazneen_bangles_king_786",
        city="India",
        state="India",
        business_type="Glossy glass bangles wholesale/retail",
        whatsapp="+917778844675",
        email="",
        ordering_method="WhatsApp or website (caption mentions banglesking.com)",
        website_present="Yes",
        website_url="https://www.banglesking.com",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="bangles wholesale, glossy bangles",
        reason_qualified="WhatsApp + web hybrid; still strong IG distribution.",
        potential_services="Shopify optimization, WhatsApp automation, ads",
        maps_link="",
        quality_score=6,
        notes="Included despite website because IG caption still pushes WhatsApp; may not match strict 'no website' filter.",
    ),
    Lead(
        business_name="Ayush Bangles",
        instagram="ayushbangles",
        city="India",
        state="India",
        business_type="Bridal chuda / bangles",
        whatsapp="+919772923196",
        email="",
        ordering_method="WhatsApp",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="chudaa, sizes, guarantee policy text",
        reason_qualified="Explicit WhatsApp ordering for bridal bangles.",
        potential_services="WhatsApp CRM, warranty workflow automation",
        maps_link="",
        quality_score=7,
        notes="",
    ),
    Lead(
        business_name="Saubhagya Mangalsutra",
        instagram="saubhagya_mangalsutra",
        city="India",
        state="India",
        business_type="Mangalsutra collection",
        whatsapp="+919421304179",
        email="",
        ordering_method="WhatsApp booking hashtag in caption",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="mangalsutra, whatsapp booking",
        reason_qualified="Explicit WhatsApp booking number in caption; embed preview ~27K followers.",
        potential_services="WhatsApp automation, ecommerce",
        maps_link="",
        quality_score=7,
        notes="",
        followers="~27K (embed preview)",
    ),
    Lead(
        business_name="Lakshmi Jewellers Khairtabad",
        instagram="lakshmi_jewellers_khairthabd",
        city="Hyderabad",
        state="Telangana",
        business_type="Gold jewellery showcase",
        whatsapp="",
        email="",
        ordering_method="DM (typical)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="chandbali, Khairtabad",
        reason_qualified="Regional jeweller IG presence; embed preview ~21K followers.",
        potential_services="Website, WhatsApp, local SEO",
        maps_link="https://www.google.com/maps/search/?api=1&query=Lakshmi%20Jewellers%20Khairtabad%20Hyderabad",
        quality_score=5,
        notes="",
        followers="~21K (embed preview)",
    ),
    Lead(
        business_name="ShivShakti Jewellers",
        instagram="shivshakti_jewelers",
        city="India",
        state="India",
        business_type="Handmade gold choker / custom",
        whatsapp="",
        email="",
        ordering_method="DM (verify)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="custom design, gold choker",
        reason_qualified="Custom handmade story content; embed preview ~23K followers.",
        potential_services="3D renders, CRM, WhatsApp",
        maps_link="",
        quality_score=6,
        notes="WhatsApp not visible in indexed snippet; verify bio.",
        followers="~23K (embed preview)",
    ),
    Lead(
        business_name="Wholesale Kundan Jewelery (IDK Wholesale)",
        instagram="wholesalekundanjewelery",
        city="Chandigarh / North India (caption tags)",
        state="Punjab",
        business_type="Polki / wholesale sets",
        whatsapp="",
        email="",
        ordering_method="DM",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="uncut polki, wholesale",
        reason_qualified="Wholesale catalogue posts; embed preview ~126K followers (larger SMB).",
        potential_services="B2B portal, CRM, ads",
        maps_link="",
        quality_score=5,
        notes="Larger account; still SMB-style wholesale merchandising on IG.",
        followers="~126K (embed preview)",
    ),
    Lead(
        business_name="Kolhapuri Thushi (Rishabh Gold)",
        instagram="kolhapurithushi",
        city="Kolhapur",
        state="Maharashtra",
        business_type="Thushi / mangalsutra (gold-plated / regional)",
        whatsapp="+919373483734",
        email="",
        ordering_method="WhatsApp + link in bio (caption)",
        website_present="Unknown",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="thushi, WhatsApp, link in bio",
        reason_qualified="Explicit WhatsApp line; embed preview ~38K followers.",
        potential_services="WhatsApp automation, ecommerce",
        maps_link="",
        quality_score=7,
        notes="",
        followers="~38K (embed preview)",
    ),
    Lead(
        business_name="Maharashtrian Jewelry",
        instagram="maharashtrian_jewelry",
        city="Maharashtra",
        state="Maharashtra",
        business_type="Maharashtrian fashion jewellery",
        whatsapp="",
        email="",
        ordering_method="DM",
        website_present="No",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="thushi, colour thushi",
        reason_qualified="Niche regional catalogue SMB; embed preview ~3K followers.",
        potential_services="WhatsApp commerce, IG shop",
        maps_link="",
        quality_score=6,
        notes="",
        followers="~3K (embed preview)",
    ),
    Lead(
        business_name="Ahilya Fine Silver Jewels",
        instagram="ahilyafinesilverjewels",
        city="India",
        state="India",
        business_type="925 silver thushi / kolhapuri styles",
        whatsapp="",
        email="",
        ordering_method="DM",
        website_present="Unknown",
        website_url="",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="92.5 sterling silver, thushi",
        reason_qualified="Silver thushi collection marketing; embed preview ~13K followers.",
        potential_services="Ecommerce, WhatsApp",
        maps_link="",
        quality_score=6,
        notes="",
        followers="~13K (embed preview)",
    ),
    Lead(
        business_name="D9creation Jewellery (oxidised manufacturer)",
        instagram="d9creation_jewellery",
        city="Jaipur",
        state="Rajasthan",
        business_type="Oxidised / German silver",
        whatsapp="",
        email="",
        ordering_method="Website checkout (caption)",
        website_present="Yes",
        website_url="https://d9creation.com",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="oxidised, manufacturer",
        reason_qualified="Included as counterexample: IG-led discovery but website checkout; likely NOT ideal for strict no-website outbound.",
        potential_services="CRO, ads, wholesale portal",
        maps_link="",
        quality_score=4,
        notes="Fails strict 'no professional website' filter; kept for completeness of indexed SMB manufacturers.",
    ),
    Lead(
        business_name="Khushbu Jewellers Dot Com (web+WhatsApp hybrid)",
        instagram="khushbujewellers.com_",
        city="India",
        state="India",
        business_type="Silver / rajputi silver",
        whatsapp="+919875791031 / +918233445357 / +918905291031 / +918829951030 (multiple posts)",
        email="",
        ordering_method="WhatsApp screenshot ordering + website discounts",
        website_present="Yes",
        website_url="https://khushbujewellers.com",
        recent_activity="Indexed posts/reels",
        avg_engagement="Not measured",
        bio_text="",
        keywords="COD, website order, silver",
        reason_qualified="Strong WhatsApp motion but explicit ecommerce domain in captions; likely NOT ideal for strict no-website outbound.",
        potential_services="Shopify optimization, WhatsApp CRM, returns automation",
        maps_link="",
        quality_score=5,
        notes="Fails strict 'no professional website' filter; kept because IG remains primary acquisition in many posts.",
    ),
    Lead(
        business_name="Seema Clay Jewelry (classes + shop)",
        instagram="seemaclayjewelry",
        city="Bengaluru",
        state="Karnataka",
        business_type="Polymer clay jewellery + classes",
        whatsapp="+919980472151",
        email="",
        ordering_method="WhatsApp for class details; purchase via link in bio",
        website_present="Yes",
        website_url="https://www.seemaclay.com",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="Bangalore class, polymer clay",
        reason_qualified="India SMB with WhatsApp for education funnel + ecommerce site.",
        potential_services="Course checkout, CRM, ads",
        maps_link="",
        quality_score=5,
        notes="Fails strict no-website filter; strong WhatsApp usage for classes.",
    ),
    Lead(
        business_name="Resin With Pallavi",
        instagram="resinwithpallavi",
        city="India",
        state="India",
        business_type="Wedding resin trays + jewellery dishes",
        whatsapp="",
        email="",
        ordering_method="DM / Etsy (caption mentions Etsy seller)",
        website_present="Yes",
        website_url="https://www.etsy.com (platform; verify exact shop URL)",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="wedding flower preservation, etsy seller",
        reason_qualified="Very small SMB (embed preview ~500 followers) but marketplace presence.",
        potential_services="D2C site, WhatsApp, CRM",
        maps_link="",
        quality_score=5,
        notes="Marketplace presence may violate strict no-website filter; included as micro-SMB resin/jewellery hybrid.",
        followers="~500 (embed preview)",
    ),
    Lead(
        business_name="Jewellery Shopper",
        instagram="jewellery_shopper_",
        city="India (shipping)",
        state="India",
        business_type="Silver / fashion rings and bracelets",
        whatsapp="+918905291031 / +919257024692 (multiple indexed posts)",
        email="",
        ordering_method="WhatsApp screenshot order; captions also mention website-order discounts",
        website_present="Yes",
        website_url="Indexed captions reference website checkout discounts (URL not consistently indexed)",
        recent_activity="Indexed reels/posts (2025)",
        avg_engagement="Not measured",
        bio_text="",
        keywords="WhatsApp screenshot, COD, silver, Radha Krishna ring",
        reason_qualified="Strong WhatsApp-first ordering motion on Instagram; included despite website upsell in captions.",
        potential_services="WhatsApp CRM, catalog microsite, abandoned-cart recovery",
        maps_link="",
        quality_score=7,
        notes="Fails strict 'no website' filter if a live storefront exists; verify current bio links.",
        followers="Not captured",
    ),
    Lead(
        business_name="Creative Zeal (Sapna Wadhwani)",
        instagram="creative_zeal_",
        city="Chennai",
        state="Tamil Nadu",
        business_type="German silver / oxidised earrings and sets",
        whatsapp="",
        email="",
        ordering_method="DM to place an order (indexed reel caption)",
        website_present="No",
        website_url="",
        recent_activity="Indexed reel (embed preview)",
        avg_engagement="Not measured",
        bio_text="",
        keywords="DM to place an order, oxidised, jhumka, Chennai",
        reason_qualified="Explicit DM ordering on oxidised fashion SKUs; large following but still creator-led SMB motion.",
        potential_services="WhatsApp capture, IG shop, lightweight checkout",
        maps_link="",
        quality_score=7,
        notes="Embed preview showed ~164K followers; confirm WhatsApp digit in bio if any.",
        followers="~164K (embed preview)",
    ),
    Lead(
        business_name="Fashion Mantra Jewellery",
        instagram="fashionmantrajewellary",
        city="India",
        state="India",
        business_type="Fashion / artificial jewellery",
        whatsapp="",
        email="",
        ordering_method="DM (indexed comment thread notes high DM volume)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post comments",
        avg_engagement="Not measured",
        bio_text="",
        keywords="fashion mantra, DM backlog, out of stock messaging",
        reason_qualified="Instagram-native fulfilment pattern; seller mentions missed DMs due to volume—WhatsApp automation fit.",
        potential_services="WhatsApp deflection, auto-replies, CRM, catalog site",
        maps_link="",
        quality_score=6,
        notes="Low public signal on exact SKU line; verify category mix in profile grid.",
        followers="Not captured",
    ),
    Lead(
        business_name="RVK Indian Jewellery",
        instagram="indianjewellery_rvk",
        city="Kolkata (location tag in embed preview)",
        state="West Bengal",
        business_type="Meenakari / kundan-style affordable chokers",
        whatsapp="",
        email="",
        ordering_method="DM / comment-to-order (typical for coded listings)",
        website_present="No",
        website_url="",
        recent_activity="Indexed post + embed preview",
        avg_engagement="Not measured",
        bio_text="",
        keywords="free shipping India, product code, kundan choker, rvk_necklace",
        reason_qualified="High-volume posting (~2.9K posts) with coded drops and India shipping language.",
        potential_services="WhatsApp order desk, payments links, simple storefront",
        maps_link="https://www.google.com/maps/search/?api=1&query=Kolkata%20imitation%20jewellery%20shop",
        quality_score=7,
        notes="Embed preview ~52K followers; confirm WhatsApp in bio.",
        followers="~52K (embed preview)",
    ),
    Lead(
        business_name="Amora Arts and Jewels",
        instagram="amoraartsandjewels",
        city="Chennai / Bengaluru (caption tags in indexed posts)",
        state="Tamil Nadu",
        business_type="Antique polished brass / wedding jhumkas",
        whatsapp="+919962432802",
        email="",
        ordering_method="WhatsApp for orders and enquiry (caption)",
        website_present="Yes",
        website_url="https://www.amoraartsandjewels.com",
        recent_activity="Indexed product posts",
        avg_engagement="Not measured",
        bio_text="",
        keywords="WhatsApp enquiry, antique jhumka, south Indian weddings",
        reason_qualified="WhatsApp-led fulfilment with parallel Shopify-style site; good for automation upsell.",
        potential_services="WhatsApp automation, CRO, ads, inventory sync",
        maps_link="",
        quality_score=6,
        notes="Has a dedicated domain; not ideal for strict no-website outbound without positioning as optimisation work.",
        followers="Not captured",
    ),
    Lead(
        business_name="Divanka",
        instagram="divanka.in",
        city="India",
        state="India",
        business_type="Rajwada jhumar / fashion earrings",
        whatsapp="+919207376139",
        email="",
        ordering_method="WhatsApp or shop on www.divanka.in (indexed caption)",
        website_present="Yes",
        website_url="https://www.divanka.in",
        recent_activity="Indexed post snippet",
        avg_engagement="Not measured",
        bio_text="",
        keywords="jhumar, shop online, WhatsApp",
        reason_qualified="Hybrid IG discovery + WhatsApp path; still SMB-style merchandising.",
        potential_services="WhatsApp flows, retention CRM, performance ads",
        maps_link="",
        quality_score=6,
        notes="Dedicated ecommerce domain present.",
        followers="Not captured",
    ),
    Lead(
        business_name="Rohika (Jewellery by Rohika)",
        instagram="jewellery_by_rohika",
        city="India (ships worldwide per captions)",
        state="India",
        business_type="Polki kundan / moissanite bridal sets",
        whatsapp="+916280926290",
        email="",
        ordering_method="DM or WhatsApp; bank/UPI payments (caption)",
        website_present="Yes",
        website_url="https://www.rohikastore.com",
        recent_activity="Indexed bridal set posts",
        avg_engagement="Not measured",
        bio_text="",
        keywords="DM for prices, no COD, rohikastore, polki kundan",
        reason_qualified="Strong WhatsApp/DM ordering workflow on high-ticket bridal SKUs.",
        potential_services="CRM, payments automation, catalogue pages, IG ads",
        maps_link="",
        quality_score=7,
        notes="Has rohikastore.com; strong WhatsApp motion still makes automation relevant.",
        followers="Not captured",
    ),
]


def render_lead(idx: int, lead: Lead) -> str:
    url = f"https://www.instagram.com/{lead.instagram}/"
    lines = [
        "",
        "=" * 50,
        f"LEAD #{idx}",
        "=" * 50,
        f"Business Name: {lead.business_name}",
        f"Instagram Handle: @{lead.instagram}",
        f"Instagram URL: {url}",
        f"Followers Count: {lead.followers}",
        f"City: {lead.city}",
        f"State: {lead.state}",
        f"Business Type: {lead.business_type}",
        f"WhatsApp Number: {lead.whatsapp}",
        f"Email: {lead.email}",
        f"Ordering Method: {lead.ordering_method}",
        f"Website Present: {lead.website_present}",
        f"Website URL: {lead.website_url}",
        f"Recent Activity Date: {lead.recent_activity}",
        f"Average Engagement: {lead.avg_engagement}",
        f"Bio Text: {lead.bio_text}",
        f"Keywords: {lead.keywords}",
        f"Reason Qualified: {lead.reason_qualified}",
        f"Potential Services Needed: {lead.potential_services}",
        f"Google Maps Link: {lead.maps_link}",
        f"Lead Quality Score: {lead.quality_score}/10",
        f"Notes: {lead.notes}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    if len({l.instagram for l in LEADS}) != len(LEADS):
        dupes = sorted({l.instagram for l in LEADS})
        raise SystemExit(f"Duplicate instagram handles in LEADS: {dupes}")

    if len(LEADS) != 100:
        raise SystemExit(f"Expected 100 leads, got {len(LEADS)}")

    out = Path("/workspace/india_jewellery_instagram_leads.txt")
    header = "\n".join(
        [
            "INDIA JEWELLERY - INSTAGRAM / WHATSAPP LEAD EXPORT",
            "Generated by Cursor automation (web research + Instagram embed previews).",
            "IMPORTANT:",
            "- Treat phone numbers, addresses, and follower counts as UNVERIFIED until manually confirmed on the live profile.",
            "- Some entries intentionally include borderline 'website present' cases for transparency (see Notes).",
            "",
        ]
    )
    body = "".join(render_lead(i + 1, lead) for i, lead in enumerate(LEADS))
    out.write_text(header + body, encoding="utf-8")


if __name__ == "__main__":
    main()
