#!/usr/bin/env python3
"""Generate india_jewellery_instagram_leads.txt from curated public-web research metadata."""

from __future__ import annotations

from pathlib import Path

LEADS: list[dict[str, str]] = [
    {
        "business": "Jewellery Palace (BJS)",
        "handle": "_jewellery_palace_bjs",
        "followers": "Not scraped (login wall)",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Imitation / fashion jewellery",
        "whatsapp": "+918440038551",
        "email": "Not disclosed",
        "ordering": "WhatsApp (post: order on WhatsApp)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post activity (public SERP)",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "nath, order on WhatsApp, code pricing",
        "reason": "Explicit WhatsApp ordering on Instagram; SMB-style listing.",
        "services": "WhatsApp automation, lightweight ecommerce, CRM",
        "maps": "Not found",
        "score": "8",
        "notes": "Source: Instagram post snippet (Google indexed).",
    },
    {
        "business": "Jewellery Shopper",
        "handle": "jewellery_shopper_",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Silver / religious silver pieces",
        "whatsapp": "+918905291031",
        "email": "Not disclosed",
        "ordering": "WhatsApp screenshot-to-order; mentions COD in posts",
        "website_yn": "Unclear",
        "website_url": "Posts mention website discount text; verify before outreach",
        "recent": "Indexed reels/posts",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "silver, COD, WhatsApp screenshot",
        "reason": "Strong WhatsApp-led fulfillment signals in indexed captions.",
        "services": "WhatsApp automation, payments/checkout clarity, website simplification",
        "maps": "Not found",
        "score": "7",
        "notes": "Some posts reference website ordering; treat as mixed-channel SMB.",
    },
    {
        "business": "Chudiwale Fashion Jewellery",
        "handle": "chudiwale_",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Bangles / bridal bangles",
        "whatsapp": "+917972380643",
        "email": "Not disclosed",
        "ordering": "WhatsApp booking + custom bangles",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "customized bangles, bridal, velvet bangles",
        "reason": "Custom orders + WhatsApp booking; strong SMB signal.",
        "services": "WhatsApp automation, custom-order workflows, CRM",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Unique Jewelryys (Pooja Jewels reel branding)",
        "handle": "unique_jewelryys",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Silver payal / silver fashion",
        "whatsapp": "+917597344552",
        "email": "Not disclosed",
        "ordering": "WhatsApp + stories offers",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "silver payal, COD mentioned, handmade",
        "reason": "WhatsApp-first ordering and COD mention in indexed caption.",
        "services": "WhatsApp automation, ecommerce basics, ads",
        "maps": "Not found",
        "score": "7",
        "notes": "Brand naming in snippet may differ from handle; verify on profile.",
    },
    {
        "business": "Biswakarma Jewellery Shilpalaya",
        "handle": "bjs2k",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Diamond / fine jewellery (SMB-style IG sales)",
        "whatsapp": "+919874085669",
        "email": "Not disclosed",
        "ordering": "WhatsApp inquiries",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed posts",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "WhatsApp for details, nosepin, earrings",
        "reason": "Repeated WhatsApp CTAs in indexed posts.",
        "services": "CRM, WhatsApp automation, appointment booking",
        "maps": "Not found",
        "score": "6",
        "notes": "Higher-ticket category; still IG/WhatsApp-led in indexed snippets.",
    },
    {
        "business": "Khushbu Jewellers (Tinwari)",
        "handle": "khushbu_jewellers_tinwari",
        "followers": "Not scraped",
        "city": "Tinwari area (confirm)",
        "state": "Rajasthan",
        "type": "Silver / traditional",
        "whatsapp": "+919929595357",
        "email": "Not disclosed",
        "ordering": "WhatsApp screenshot-to-order; COD mentioned",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed posts/reels",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "silver, COD, customize",
        "reason": "WhatsApp-led ordering with customization mentions.",
        "services": "WhatsApp automation, CRM, COD ops tooling",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Lakshmi Creations (Lakshmi imitation jewellery)",
        "handle": "lakshmi_creations_9",
        "followers": "Not scraped",
        "city": "Mumbai (frequently referenced in wholesale context; confirm)",
        "state": "Maharashtra",
        "type": "Imitation jewellery / wholesale",
        "whatsapp": "+919849567353",
        "email": "Not disclosed",
        "ordering": "WhatsApp for collections/prices",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "imitation, wholesale, jhumkas",
        "reason": "Classic IG + WhatsApp wholesale pattern.",
        "services": "Catalog automation, B2B ordering portal, WhatsApp bots",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Radha Rani Imitation",
        "handle": "radha_rani_imitation_7",
        "followers": "Not scraped",
        "city": "Mumbai",
        "state": "Maharashtra",
        "type": "Imitation jewellery (Bhuleshwar wholesale context)",
        "whatsapp": "+917023725950",
        "email": "Not disclosed",
        "ordering": "Phone/WhatsApp + market address in caption",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "Bhuleshwar, wholesale, Mumbai",
        "reason": "Offline wholesale shop using Instagram discovery; no website in snippet.",
        "services": "Local SEO, Google Business Profile, simple catalog site",
        "maps": "Not found",
        "score": "7",
        "notes": "Good candidate for maps + landing page.",
    },
    {
        "business": "Those Little Bling",
        "handle": "thoselittleblinggss",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Oxidised / moissanite / fashion sets",
        "whatsapp": "Not disclosed in indexed snippet",
        "email": "Not disclosed",
        "ordering": "DM to order (explicit in indexed captions)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed posts",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "dm to order, oxidised, moissanite, free shipping",
        "reason": "DM-first selling; fits Instagram-native SMB.",
        "services": "DM automation, IG shopping setup, checkout links",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Oxidised Jewellery Wholesaler",
        "handle": "oxidised_jewellery_wholesaler",
        "followers": "Not scraped",
        "city": "Kolkata (search intent; confirm)",
        "state": "West Bengal",
        "type": "Oxidised / wholesale",
        "whatsapp": "Not disclosed in indexed snippet",
        "email": "Not disclosed",
        "ordering": "Likely DM/WhatsApp (verify)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "oxidised, wholesaler",
        "reason": "Niche wholesaler handle surfaced repeatedly in India oxidised searches.",
        "services": "B2B catalog, WhatsApp order desk, lead capture site",
        "maps": "Not found",
        "score": "6",
        "notes": "Contact details not visible in snippet used; verify on profile.",
    },
    {
        "business": "Jewels of Karnataka",
        "handle": "jewelsofkarnataka",
        "followers": "Not scraped",
        "city": "Karnataka (statewide shipping; confirm base city)",
        "state": "Karnataka",
        "type": "One-gram gold fashion jewellery",
        "whatsapp": "+919740234813",
        "email": "Not disclosed",
        "ordering": "WhatsApp",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed posts",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "one gram gold, mangalyam chains, shipping",
        "reason": "WhatsApp-first ordering for fast-moving SKUs.",
        "services": "WhatsApp automation, product catalog, UPI payment flows",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Vernika Silver Jewellery",
        "handle": "vernika.silver.jewellery",
        "followers": "Not scraped",
        "city": "Bengaluru",
        "state": "Karnataka",
        "type": "92.5 silver jewellery",
        "whatsapp": "+917406810666",
        "email": "Not disclosed",
        "ordering": "Call / WhatsApp bookings + video call shopping (per indexed caption)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "925, Chikpete, Raja market, video call",
        "reason": "Hybrid retail + remote selling via phone/video; IG presence.",
        "services": "Appointment booking, WhatsApp commerce, local landing pages",
        "maps": "Not found",
        "score": "7",
        "notes": "Physical shop addresses mentioned in indexed reel text.",
    },
    {
        "business": "WeddingAnswers (bridal boxes / accessories)",
        "handle": "weddinganswers",
        "followers": "Not scraped",
        "city": "Delhi (tagged in caption; confirm)",
        "state": "India",
        "type": "Bridal accessories / wedding gifting",
        "whatsapp": "+918368213149",
        "email": "Not disclosed",
        "ordering": "WhatsApp or DM; advance payment",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "chooda box, DM, weddings",
        "reason": "Strong DM/WhatsApp ordering workflow for bespoke bridal items.",
        "services": "CRM, WhatsApp automation, checkout links",
        "maps": "Not found",
        "score": "7",
        "notes": "Adjacent to core jewellery but high overlap in buyer intent.",
    },
    {
        "business": "Aayush Bangles",
        "handle": "ayushbangles",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Bridal chuda / bangles",
        "whatsapp": "+919772923196",
        "email": "Not disclosed",
        "ordering": "WhatsApp (reel text)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "bridal chudaa, sizes, guarantee",
        "reason": "Clear phone-led ordering on Instagram reels.",
        "services": "WhatsApp automation, size guide pages, CRM",
        "maps": "Not found",
        "score": "7",
        "notes": "",
    },
    {
        "business": "Trend Jewelryys",
        "handle": "trend_jewelryys",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Fashion jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Likely DM (verify)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed posts",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "trending, reels",
        "reason": "Appears in multiple indexed jewellery SERP threads; SMB handle pattern.",
        "services": "IG growth, content ops, DM automation",
        "maps": "Not found",
        "score": "5",
        "notes": "Low confidence on ordering channel; verify before outreach.",
    },
    {
        "business": "Wear N Shine Jewelry",
        "handle": "wear_nd_shine_jewelry",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Fashion jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "DM (verify)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed posts",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "fashion jewellery",
        "reason": "Surfaced in jewellery India SERPs; SMB-style handle.",
        "services": "IG content, DM automation",
        "maps": "Not found",
        "score": "5",
        "notes": "Verify contact + niche on profile.",
    },
    {
        "business": "Rajputi Jewellery (Rajputii)",
        "handle": "rajputii_jewellery_",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Rajputi / traditional fashion jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "DM/WhatsApp (verify)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed posts",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "rajputi, traditional",
        "reason": "Traditional niche with IG-native distribution.",
        "services": "WhatsApp catalog, landing pages, ads",
        "maps": "Not found",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Asha Bangles Official",
        "handle": "ashabanglesofficial",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Bangles / bridal bangles",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "DM (verify)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed posts",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "bangles, bridal",
        "reason": "Bangle-focused SMB surfaced in bridal jewellery searches.",
        "services": "WhatsApp automation, IG reels strategy",
        "maps": "Not found",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Sai Jewellers Rajat (Ujjain)",
        "handle": "sai_jewellers_rajat_ujjain",
        "followers": "Not scraped",
        "city": "Ujjain",
        "state": "Madhya Pradesh",
        "type": "Gold-plated / 1gm gold fashion jewellery",
        "whatsapp": "+917024274632",
        "email": "Not disclosed",
        "ordering": "WhatsApp / DM",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed posts/reels",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "dm only, gold plated, MP",
        "reason": "Explicit DM/WhatsApp ordering tied to a city.",
        "services": "WhatsApp automation, local SEO, simple ecommerce",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Jaipur Jewellery Damoh",
        "handle": "jaipur_jewellary_damoh",
        "followers": "Not scraped",
        "city": "Damoh",
        "state": "Madhya Pradesh",
        "type": "Fashion / designer earrings",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Likely in-store/DM (verify)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "Jaipur jewellery, earrings",
        "reason": "Local retailer using Instagram for discovery.",
        "services": "GBP + maps, IG ads, WhatsApp click-to-chat",
        "maps": "Not found",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Rajputi Jewellery Manufacturer (SC)",
        "handle": "rajputi_jewelery_wholsaler_s.c",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Rajputi wholesale sets",
        "whatsapp": "+917877634674",
        "email": "Not disclosed",
        "ordering": "WhatsApp + WhatsApp groups (caption)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "wholesale, join group",
        "reason": "WhatsApp-first wholesale motion.",
        "services": "WhatsApp community tooling, catalog, CRM",
        "maps": "Not found",
        "score": "7",
        "notes": "",
    },
    {
        "business": "Vari Artificial Jewellery by Ritu Soni",
        "handle": "vari_artificials_jewellery",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Temple / artificial bangles",
        "whatsapp": "+918769988299",
        "email": "Not disclosed",
        "ordering": "DM or phone; same-day local delivery mentioned",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "temple jewellery bangles, all India delivery",
        "reason": "DM + phone + delivery messaging; SMB.",
        "services": "WhatsApp automation, delivery ops, CRM",
        "maps": "Not found",
        "score": "8",
        "notes": "Second number +919461488299 also appears in snippet.",
    },
    {
        "business": "Chandana Fashion Jewellery",
        "handle": "chandana_fashion_jewellery",
        "followers": "Not scraped",
        "city": "Chennai (implied by imitation jewellery SERP; confirm)",
        "state": "Tamil Nadu",
        "type": "Imitation jewellery",
        "whatsapp": "+919741030474",
        "email": "Not disclosed",
        "ordering": "DM or WhatsApp (explicit how-to-order caption)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "mangalsutra, imitation, waterproof",
        "reason": "Very explicit DM/WhatsApp ordering instructions.",
        "services": "WhatsApp automation, product FAQ pages",
        "maps": "Not found",
        "score": "9",
        "notes": "",
    },
    {
        "business": "The Madras Art Studio (Dhanu Ravi)",
        "handle": "themadras_artstudio",
        "followers": "Not scraped",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "type": "Resin / preserved flower jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "DM to order + customization",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "resin, customized, DM",
        "reason": "Handmade/resin niche with DM-led sales.",
        "services": "Ecommerce for custom SKUs, CRM, DM automation",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Gohar Jewels Official",
        "handle": "goharjewelsofficial",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Resin jhumkas / handmade",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "DM (verify)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "resin jhumkas, dried flowers",
        "reason": "Resin handmade niche; IG-native.",
        "services": "Shopify-lite, DM automation, content",
        "maps": "Not found",
        "score": "7",
        "notes": "",
    },
    {
        "business": "Aashu's Pearl Creation",
        "handle": "aashus_pearl_creation",
        "followers": "Not scraped",
        "city": "Maharashtra (Marathi captions; confirm)",
        "state": "Maharashtra",
        "type": "Handmade pearl / traditional sets",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "DM for order (caption)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "handmade, DM, small business",
        "reason": "Explicit DM ordering + customization mention.",
        "services": "DM automation, checkout links, CRM",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Floral Art by Srishti (floral jewellery)",
        "handle": "floralartbysrishti",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Floral jewellery / wedding accessories",
        "whatsapp": "+919833989613",
        "email": "Not disclosed",
        "ordering": "DM + WhatsApp + customization",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "haldi, mehendi, pan-India shipping",
        "reason": "Strong WhatsApp + DM + customization for events.",
        "services": "WhatsApp automation, booking CRM, landing pages",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "NR Silver Jewels",
        "handle": "nr_silver_jewels",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Silver jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify on profile",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "silver",
        "reason": "Surfaced in silver jewellery SERPs.",
        "services": "WhatsApp commerce, catalog",
        "maps": "Not found",
        "score": "5",
        "notes": "Low detail in snippet; verify.",
    },
    {
        "business": "Lakshmi Jewells (Sree Wholesale Jewellery)",
        "handle": "lakshmijewells",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Handmade / matte / bridal imitation",
        "whatsapp": "+919390483697",
        "email": "Not disclosed",
        "ordering": "WhatsApp order & enquiry (caption)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "no COD, opening video must, bridal",
        "reason": "Clear operational rules via WhatsApp-led sales.",
        "services": "WhatsApp automation, policy pages, CRM",
        "maps": "Not found",
        "score": "7",
        "notes": "Number parsed from indexed caption: 93904 83697.",
    },
    {
        "business": "Mahavir Imitation Jewelle",
        "handle": "mahavirimitationjewelle",
        "followers": "Not scraped",
        "city": "Nagpur (search thread; confirm)",
        "state": "Maharashtra",
        "type": "Imitation jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "imitation",
        "reason": "Imitation retailer handle surfaced in Nagpur market searches.",
        "services": "GBP, WhatsApp click-to-chat, catalog",
        "maps": "Not found",
        "score": "5",
        "notes": "Verify contacts on profile.",
    },
    {
        "business": "Omkar Jewels Surat",
        "handle": "omkar_jewels_surat",
        "followers": "Not scraped",
        "city": "Surat",
        "state": "Gujarat",
        "type": "Custom / personalized jewellery",
        "whatsapp": "+918141248248",
        "email": "Not disclosed",
        "ordering": "Phone/WhatsApp + visit studio",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "custom jewelry, Surat",
        "reason": "Custom orders + direct phone contact; SMB.",
        "services": "CRM, appointment booking, portfolio site",
        "maps": "Not found",
        "score": "7",
        "notes": "Address appears in indexed reel text.",
    },
    {
        "business": "Varudi Jewellers",
        "handle": "varudijewellers",
        "followers": "Not scraped",
        "city": "Surat",
        "state": "Gujarat",
        "type": "Gold jewellery (SMB IG)",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "DM (caption: instant buy / DM)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "DM, safe delivery, BIS mention",
        "reason": "DM-led buying motion on IG reel snippet.",
        "services": "Trust/compliance pages, WhatsApp bridge, CRM",
        "maps": "Not found",
        "score": "6",
        "notes": "Verify whether this is a larger showroom; still DM-led in snippet.",
    },
    {
        "business": "STYLIKA",
        "handle": "stylika_",
        "followers": "Not scraped",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "type": "Oxidised / festive jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "DM / in-person discovery (verify)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "Navratri, oxidised earrings",
        "reason": "Local hidden-gem positioning via IG reels.",
        "services": "GBP, IG ads, WhatsApp link-in-bio",
        "maps": "Not found",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Gahane Jewellery",
        "handle": "gahanejewellery",
        "followers": "Not scraped",
        "city": "Kolkata (Bengali bridal context; confirm)",
        "state": "West Bengal",
        "type": "Gold bangles / handcrafted",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "916 hallmark, kon-kon bangles, bridal",
        "reason": "Handcrafted bridal gold pieces marketed on IG.",
        "services": "Catalog, appointment booking, CRM",
        "maps": "Not found",
        "score": "6",
        "notes": "Higher ticket; confirm IG-led vs showroom-led mix.",
    },
    {
        "business": "Wholesale Pearls Jewells Onkar",
        "handle": "wholesalepearlsjewells.onkar",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Fashion / wholesale jewellery",
        "whatsapp": "+919996698633",
        "email": "Not disclosed",
        "ordering": "DM for catalog + phone line",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "wholesale, manufacturer, DM catalog",
        "reason": "B2B catalog motion via DM/WhatsApp.",
        "services": "B2B portal, WhatsApp automation, CRM",
        "maps": "Not found",
        "score": "7",
        "notes": "",
    },
    {
        "business": "Jewel Indukuri's",
        "handle": "indukurisjewel",
        "followers": "Not scraped",
        "city": "Hyderabad (implied; confirm)",
        "state": "Telangana",
        "type": "Lab-grown diamond jewellery",
        "whatsapp": "+916302720676",
        "email": "Not disclosed",
        "ordering": "WhatsApp for details/customization",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "labgrown, customize",
        "reason": "WhatsApp-led consult selling.",
        "services": "CRM, appointment booking, content",
        "maps": "Not found",
        "score": "6",
        "notes": "Higher ticket; confirm SMB positioning vs showroom.",
    },
    {
        "business": "Janvish One Gram Gold & Boutique",
        "handle": "janvish_onegramgold_and_boutiq",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "One gram gold fashion jewellery",
        "whatsapp": "+918121769801",
        "email": "Not disclosed",
        "ordering": "Screenshot + WhatsApp + WhatsApp groups",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "one gram gold, free ship, WA group",
        "reason": "Classic IG + WhatsApp community distribution.",
        "services": "WhatsApp automation, catalog, retargeting",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Lucknow Artificial Jewellery",
        "handle": "lucknow_artificial_jewellery_",
        "followers": "Not scraped",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "type": "Artificial / one gram gold polish",
        "whatsapp": "+918957754721",
        "email": "Not disclosed",
        "ordering": "Booking number / WhatsApp",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "COD, all India shipping, Lucknow",
        "reason": "City-tagged SMB with phone-led ordering.",
        "services": "WhatsApp automation, local ads, simple site",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "KR Jewellers Goa",
        "handle": "krjewellersgoa",
        "followers": "Not scraped",
        "city": "Ponda",
        "state": "Goa",
        "type": "Traditional gold bangles (Goan patli)",
        "whatsapp": "+919511641757",
        "email": "Not disclosed",
        "ordering": "DM for order + phone",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "hallmark, wedding jewellery, DM",
        "reason": "DM + phone for a localized traditional niche.",
        "services": "WhatsApp automation, GBP, appointment booking",
        "maps": "Not found",
        "score": "6",
        "notes": "Physical jeweller; confirm IG-led share of revenue.",
    },
    {
        "business": "Rajputi Jewellery Bhilwara",
        "handle": "rajputijewellerybhilwara00",
        "followers": "Not scraped",
        "city": "Bhilwara",
        "state": "Rajasthan",
        "type": "Rajputi / gold-look plated sets",
        "whatsapp": "+919829900459",
        "email": "Not disclosed",
        "ordering": "WhatsApp orders; online prepayment",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "whatsapp order, no COD, handmade look",
        "reason": "WhatsApp-first with strong SMB ops language.",
        "services": "WhatsApp automation, payments, CRM",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Jewellery Rajasthan",
        "handle": "jewellery_rajasthan",
        "followers": "Not scraped",
        "city": "Rajasthan (broad; confirm)",
        "state": "Rajasthan",
        "type": "Rajputi / traditional",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "rajasthan, earrings",
        "reason": "Regional SMB handle pattern.",
        "services": "WhatsApp link, catalog microsite",
        "maps": "Not found",
        "score": "5",
        "notes": "Verify contact + positioning.",
    },
    {
        "business": "Pratha The Jewellery Studio",
        "handle": "prathathejewellerystudio",
        "followers": "Not scraped",
        "city": "Patna (often associated; confirm)",
        "state": "Bihar",
        "type": "Pure silver kundan / bridal accessories",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "pure silver, handcrafted, maang tikka",
        "reason": "Studio-style silver bridal pieces on IG.",
        "services": "Portfolio site, bookings, CRM",
        "maps": "Not found",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Dream Jewellery 2023",
        "handle": "dream.jewellery2023",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Fashion jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "bracelet, silver",
        "reason": "SMB handle from silver SERP threads.",
        "services": "IG content, WhatsApp commerce",
        "maps": "Not found",
        "score": "5",
        "notes": "",
    },
    {
        "business": "Shree Silver (Pune)",
        "handle": "silver_jewels_pune",
        "followers": "Not scraped",
        "city": "Pune",
        "state": "Maharashtra",
        "type": "925 silver retail",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Shop visit + online ordering mention (verify)",
        "website_yn": "Unclear",
        "website_url": "Verify",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "925, Raviwar Peth, Pune",
        "reason": "Hybrid retail + online; IG discovery.",
        "services": "Local SEO, WhatsApp, simple ecommerce",
        "maps": "Not found",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Jodhpuri Silver",
        "handle": "jodhpuri_silver",
        "followers": "Not scraped",
        "city": "Jodhpur (implied; confirm)",
        "state": "Rajasthan",
        "type": "Silver jewellery",
        "whatsapp": "+919358839704",
        "email": "Not disclosed",
        "ordering": "WhatsApp screenshot-to-order (caption in SERP thread)",
        "website_yn": "Unclear",
        "website_url": "Posts mention website discount text in network posts; verify",
        "recent": "Indexed reels",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "silver, payal, COD",
        "reason": "WhatsApp-led ordering pattern surfaced on this handle.",
        "services": "WhatsApp automation, UPI receipts, CRM",
        "maps": "Not found",
        "score": "7",
        "notes": "Disambiguate from similarly named pages; verify bio.",
    },
    {
        "business": "Silver Palace 45",
        "handle": "silver_palace45",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Silver jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "silver",
        "reason": "Silver SMB surfaced in Pune silver SERP comments.",
        "services": "WhatsApp commerce, catalog",
        "maps": "Not found",
        "score": "5",
        "notes": "",
    },
    {
        "business": "Samskruthi Jewellers",
        "handle": "samskruthijewellers",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "CZ / bridal necklace sets",
        "whatsapp": "+918790112233",
        "email": "Not disclosed",
        "ordering": "WhatsApp to place order (caption)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "south indian jewelry, bride, layered necklace",
        "reason": "Explicit WhatsApp order CTA.",
        "services": "WhatsApp automation, catalog, ads",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Ridhi Sidhi Jewellers",
        "handle": "ridhi_sidhi_jewellers",
        "followers": "Not scraped",
        "city": "Barmer",
        "state": "Rajasthan",
        "type": "Silver bangles / traditional silver",
        "whatsapp": "+917849810107",
        "email": "Not disclosed",
        "ordering": "WhatsApp enquiry + screenshot ordering",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "COD, all India shipping, silver bangles",
        "reason": "Strong WhatsApp ops + COD mention.",
        "services": "WhatsApp automation, CRM, fulfillment pages",
        "maps": "Not found",
        "score": "8",
        "notes": "Alternate numbers appear in other posts; dedupe outreach carefully.",
    },
    {
        "business": "R K Jewellers",
        "handle": "r_k__jewellers",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Gold / hallmark jewellery (IG marketing)",
        "whatsapp": "+918106852097",
        "email": "Not disclosed",
        "ordering": "WhatsApp for requirements (caption)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "916 hallmark, free shipping, WhatsApp",
        "reason": "WhatsApp-led enquiries on high-engagement reels.",
        "services": "CRM, WhatsApp automation, compliance content",
        "maps": "Not found",
        "score": "6",
        "notes": "Could be more established retail; validate SMB fit.",
    },
    {
        "business": "Cenora Jewels",
        "handle": "cenorajewels",
        "followers": "Not scraped",
        "city": "Kerala (implied by SERP; confirm)",
        "state": "Kerala",
        "type": "Fashion / promo jewellery",
        "whatsapp": "+917021923226",
        "email": "Not disclosed",
        "ordering": "DM / WhatsApp (caption)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "buy 1 get 1, DM to order",
        "reason": "Explicit DM/WhatsApp promo ordering.",
        "services": "WhatsApp automation, offers workflow, ads",
        "maps": "Not found",
        "score": "7",
        "notes": "",
    },
    {
        "business": "KPR Jewellery",
        "handle": "kpr_jewellery",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Jewellery (verify niche)",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "jewellery",
        "reason": "Handle surfaced in Kerala jewellery SERP thread.",
        "services": "IG audit, WhatsApp link, catalog",
        "maps": "Not found",
        "score": "5",
        "notes": "",
    },
    {
        "business": "Samasha Jewellery",
        "handle": "samashajewellery",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Fashion jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "jewellery reels",
        "reason": "SMB reel account in jewellery SERPs.",
        "services": "Content, DM automation",
        "maps": "Not found",
        "score": "5",
        "notes": "",
    },
    {
        "business": "Lavanya Jewellers SLJ",
        "handle": "lavanyajewellers_slj",
        "followers": "Not scraped",
        "city": "Vijayawada",
        "state": "Andhra Pradesh",
        "type": "Handmade gold bangles / gold jewellery",
        "whatsapp": "+919441176530",
        "email": "Not disclosed",
        "ordering": "DM or WhatsApp (caption)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "916 gold, handmade bangles, Andhra",
        "reason": "DM/WhatsApp consult pattern for bespoke gold pieces.",
        "services": "CRM, appointment booking, content",
        "maps": "Not found",
        "score": "6",
        "notes": "Higher ticket; confirm IG-led vs store-led mix.",
    },
    {
        "business": "Rohit Bhai Jewellers",
        "handle": "rohitbhaijewellers",
        "followers": "Not scraped",
        "city": "Delhi",
        "state": "Delhi",
        "type": "Gold / antique bridal sets (Chandni Chowk)",
        "whatsapp": "+919953916916",
        "email": "Not disclosed",
        "ordering": "WhatsApp + store visit",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "Chandni Chowk, hallmark, bridal",
        "reason": "Very active IG + WhatsApp for a dense retail market.",
        "services": "WhatsApp automation, inventory microsites, CRM",
        "maps": "Not found",
        "score": "6",
        "notes": "Also lists second number +919953916903 in indexed caption.",
    },
    {
        "business": "Jewels By Nitin",
        "handle": "jewelsbynitin",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Punjabi traditional groom jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "kantha, punjabi wedding",
        "reason": "Niche wedding jewellery content on IG.",
        "services": "Portfolio site, lead capture, ads",
        "maps": "Not found",
        "score": "5",
        "notes": "",
    },
    {
        "business": "My Create Resinart",
        "handle": "my_create_resinart",
        "followers": "Not scraped",
        "city": "Tamil Nadu (artist positioning; confirm)",
        "state": "Tamil Nadu",
        "type": "Resin art / gifts (some jewellery-adjacent)",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "DM for order",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "DM for order, resin",
        "reason": "DM-led maker; useful for cross-sell into jewellery ops tooling.",
        "services": "Ecommerce, DM automation",
        "maps": "Not found",
        "score": "6",
        "notes": "Jewellery-adjacent; verify product mix.",
    },
    {
        "business": "Resin by Pallavi",
        "handle": "resinbypallavi",
        "followers": "Not scraped",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "type": "Resin keepsakes / jewellery-adjacent",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Customization (verify)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "resin, customization, Chennai",
        "reason": "Custom resin maker in Chennai surfaced in resin jewellery searches.",
        "services": "Checkout, CRM, DM automation",
        "maps": "Not found",
        "score": "6",
        "notes": "",
    },
    {
        "business": "South Indian Temple Jewellery",
        "handle": "southindian__templejewellery",
        "followers": "Not scraped",
        "city": "Chennai seller tag (confirm)",
        "state": "Tamil Nadu",
        "type": "Temple / matt finish imitation",
        "whatsapp": "+917904076978",
        "email": "Not disclosed",
        "ordering": "DM or WhatsApp + WhatsApp group link",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "no COD, GPay/PhonePe, temple collections",
        "reason": "Very explicit online payment + WhatsApp community motion.",
        "services": "WhatsApp automation, community management, catalog",
        "maps": "Not found",
        "score": "8",
        "notes": "Second number +918610765751 appears in indexed caption.",
    },
    {
        "business": "Satya Jewels Official",
        "handle": "satyajewelsofficial",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Temple gold jewellery wholesale marketing",
        "whatsapp": "+919999155985",
        "email": "Not disclosed",
        "ordering": "Call/WhatsApp (caption)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "temple jewellery, wholesale",
        "reason": "Phone-led wholesale enquiries via IG.",
        "services": "B2B portal, WhatsApp automation, CRM",
        "maps": "Not found",
        "score": "6",
        "notes": "Validate SMB vs larger distributor.",
    },
    {
        "business": "Emmadi Silver Jewellery",
        "handle": "emmadi_silver_jewellery",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Silver jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "silver",
        "reason": "Surfaced in Ridhima-adjacent silver SERP noise; still a distinct handle.",
        "services": "WhatsApp commerce, catalog",
        "maps": "Not found",
        "score": "5",
        "notes": "",
    },
    {
        "business": "Kaurz Crown Jewellery",
        "handle": "kaurzcrownjewellery",
        "followers": "Not scraped",
        "city": "Patiala context in posts (confirm)",
        "state": "Punjab",
        "type": "925 silver with gold plating / Punjabi traditional",
        "whatsapp": "+919888298050",
        "email": "Not disclosed",
        "ordering": "WhatsApp or DM; mentions online + store",
        "website_yn": "Unclear",
        "website_url": "Verify (posts say online; may use third-party checkout)",
        "recent": "Indexed reels",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "Punjabi culture, customization, worldwide shipping",
        "reason": "Strong IG + WhatsApp + customization signals.",
        "services": "CRM, ecommerce, WhatsApp automation",
        "maps": "Not found",
        "score": "7",
        "notes": "",
    },
    {
        "business": "Nikhil Jewellery Hyderabad",
        "handle": "nikhiljewelleryhyderabad",
        "followers": "Not scraped",
        "city": "Hyderabad",
        "state": "Telangana",
        "type": "916 gold traditional / puligoru lockets",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "916 gold, Hyderabad, LB Nagar",
        "reason": "Local IG-first gold jeweller content.",
        "services": "GBP, WhatsApp, inventory microsite",
        "maps": "Not found",
        "score": "6",
        "notes": "May be more retail-heavy; validate SMB services fit.",
    },
    {
        "business": "S Swarnakar And Son",
        "handle": "s.swarnakarandson",
        "followers": "Not scraped",
        "city": "Kolkata",
        "state": "West Bengal",
        "type": "Hallmarked gold/silver collections (Chetla)",
        "whatsapp": "+918981948452",
        "email": "Not disclosed",
        "ordering": "Booking number / call",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "Kolkata, Chetla, wedding jewellery",
        "reason": "IG used for showroom marketing + bookings.",
        "services": "Appointment WhatsApp, CRM, local SEO",
        "maps": "Not found",
        "score": "6",
        "notes": "Physical store; still IG-active.",
    },
    {
        "business": "Raji Jewels",
        "handle": "rajijewels",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Jewellery (verify niche)",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "jewels",
        "reason": "Handle surfaced in DM-for-price jewellery searches.",
        "services": "IG audit, lead capture",
        "maps": "Not found",
        "score": "5",
        "notes": "",
    },
    {
        "business": "Begumbazar Wholesale Jewelry",
        "handle": "begumbazar_wholesale_jewelry",
        "followers": "Not scraped",
        "city": "Hyderabad / Begum Bazar context (confirm)",
        "state": "Telangana",
        "type": "Imitation / guttapusalu sets (wholesale)",
        "whatsapp": "+919618136342",
        "email": "Not disclosed",
        "ordering": "DM or WhatsApp; screenshot ordering",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reels",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "Begum bazar, wholesale, free shipping",
        "reason": "Very strong WhatsApp + wholesale motion.",
        "services": "WhatsApp automation, B2B ordering, CRM",
        "maps": "Not found",
        "score": "8",
        "notes": "Some posts show alternate numbers; standardize on latest bio when outreach.",
    },
    {
        "business": "Sai Brindavan Jewellers",
        "handle": "saibrindavan_jewellers",
        "followers": "Not scraped",
        "city": "Hyderabad (Begum Bazar; confirm)",
        "state": "Telangana",
        "type": "Wholesale/retail jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "Begum Bazar market",
        "reason": "Market-adjacent IG wholesaler/retailer presence.",
        "services": "WhatsApp, catalog, maps",
        "maps": "Not found",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Pooja Jewels",
        "handle": "poojajewels_",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Jewellery reels (verify niche)",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reels",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "jewels",
        "reason": "High engagement reels surfaced in searches.",
        "services": "Content ops, DM automation",
        "maps": "Not found",
        "score": "5",
        "notes": "",
    },
    {
        "business": "Khushbu Jewellers 1",
        "handle": "khushbu_jewellers_1",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Silver / related SKUs (disambiguate from other Khushbu pages)",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "khushbu, silver",
        "reason": "Separate handle in same ecosystem; worth deduping operationally before outreach.",
        "services": "Brand consolidation consulting, WhatsApp",
        "maps": "Not found",
        "score": "5",
        "notes": "Likely related network; verify ownership.",
    },
    {
        "business": "Jodhpuri Jewellery (Salasar Payal House reel branding)",
        "handle": "jodhpuri__jewellery",
        "followers": "Not scraped",
        "city": "Jodhpur (implied; confirm)",
        "state": "Rajasthan",
        "type": "Traditional gold-look sets / payal house",
        "whatsapp": "+917568283224",
        "email": "Not disclosed",
        "ordering": "WhatsApp (caption)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "gold rakhdi set, WhatsApp",
        "reason": "WhatsApp-led custom order language.",
        "services": "WhatsApp automation, CRM",
        "maps": "Not found",
        "score": "7",
        "notes": "",
    },
    {
        "business": "JCS Jewel Creations",
        "handle": "jcsjewelcreations",
        "followers": "Not scraped",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "type": "Temple jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "temple jewelry, Chennai",
        "reason": "Temple jewellery creator brand on IG.",
        "services": "Catalog, WhatsApp, content",
        "maps": "Not found",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Petals by Swathi",
        "handle": "petalsbyswathi",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Jadau / kundan bridal jewellery",
        "whatsapp": "+917013645835",
        "email": "Not disclosed",
        "ordering": "Comment-to-DM link flow + vendor coordination",
        "website_yn": "Unclear",
        "website_url": "Verify (may use external checkout links)",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "pp comment, jadau, bridal",
        "reason": "IG-native selling mechanics; phone listed on aggregator posts.",
        "services": "Funnel optimization, WhatsApp automation, ecommerce",
        "maps": "Not found",
        "score": "7",
        "notes": "Phone sourced from South India Jewels imitation vendor listing.",
    },
    {
        "business": "Sahiba’s Jewellery Box",
        "handle": "sahibasjewellerybox",
        "followers": "Not scraped",
        "city": "Toronto / diaspora + India shipping (caption)",
        "state": "India (ships to India)",
        "type": "Indian jewellery + suits crossover",
        "whatsapp": "+12364129082",
        "email": "sahibasjewellerybox@gmail.com",
        "ordering": "DM or WhatsApp",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "Punjabi wedding, gold plated, small jewelry business",
        "reason": "Small business positioning with explicit DM/WhatsApp ordering.",
        "services": "CRM, WhatsApp automation, international shipping ops",
        "maps": "Not found",
        "score": "6",
        "notes": "Non-India phone; still sells Indian wedding jewellery to India buyers.",
    },
    {
        "business": "I Imitation Jewellery",
        "handle": "i_imitation_jewellery",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Imitation necklace & bangles",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "DM for order",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "DM for order, imitation",
        "reason": "Pure DM ordering motion.",
        "services": "DM automation, checkout links",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Flabel Creations",
        "handle": "flabelcreations",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Fashion / diamond-look sets",
        "whatsapp": "+917711990044",
        "email": "Not disclosed",
        "ordering": "WhatsApp + link in bio mention",
        "website_yn": "Unclear",
        "website_url": "Verify (link-in-bio)",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "same day dispatch, free shipping, WhatsApp",
        "reason": "WhatsApp-first + dispatch claims in indexed caption.",
        "services": "WhatsApp automation, ops tooling, lightweight site",
        "maps": "Not found",
        "score": "7",
        "notes": "",
    },
    {
        "business": "JYG Diamond 4 Less",
        "handle": "jygdiamond4less",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Diamond-look / fashion sets",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "factory price, nationwide shipping",
        "reason": "SMB-style IG promo account.",
        "services": "Ads, WhatsApp, catalog",
        "maps": "Not found",
        "score": "5",
        "notes": "",
    },
    {
        "business": "Lakshi S Jewellery",
        "handle": "lakshi_s_jewellery",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Bangles / raindrop bangles (tagged seller)",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "bangles, budget friendly",
        "reason": "Tagged seller surfaced in budget jewellery SERPs.",
        "services": "IG shop, WhatsApp",
        "maps": "Not found",
        "score": "5",
        "notes": "",
    },
    {
        "business": "Chettinad Creations",
        "handle": "chettinad_creations",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "Tamil Nadu",
        "type": "Kemp / temple imitation sets",
        "whatsapp": "+917904114988",
        "email": "Not disclosed",
        "ordering": "DM or WhatsApp; GPay/PhonePe/bank; no COD",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reels",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "dispatch SLA, opening video policy, kemp",
        "reason": "Very strong SMB ops + WhatsApp ordering.",
        "services": "WhatsApp automation, policy pages, CRM",
        "maps": "Not found",
        "score": "9",
        "notes": "Confusable with similarly named accounts; use exact handle.",
    },
    {
        "business": "Colors Bangles & Imitation",
        "handle": "colorsbangles",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "AD bangles / glass bangles",
        "whatsapp": "+918264130483",
        "email": "Not disclosed",
        "ordering": "Phone + DM customizations",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "DM for orders, sizes, bridal bangles",
        "reason": "Explicit DM + phone ordering.",
        "services": "WhatsApp automation, size guide, CRM",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "RP Bangles Jaipur",
        "handle": "rp__bangles__41",
        "followers": "Not scraped",
        "city": "Jaipur",
        "state": "Rajasthan",
        "type": "Rajasthani bangles",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "chuda, bangles",
        "reason": "Jaipur bangle SMB on IG.",
        "services": "WhatsApp, reels ads, GBP",
        "maps": "Not found",
        "score": "6",
        "notes": "",
    },
    {
        "business": "SKJ Sri Krishna Jewellers",
        "handle": "skj_sri_krishna_jewellers",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Pearl / traditional jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "pearls, south india jewels",
        "reason": "Vendor account surfaced via aggregator posts.",
        "services": "Catalog, WhatsApp, CRM",
        "maps": "Not found",
        "score": "5",
        "notes": "",
    },
    {
        "business": "Sujatha Gold Covering Works",
        "handle": "sujatha_gold_covering_works",
        "followers": "Not scraped",
        "city": "Machilipatnam",
        "state": "Andhra Pradesh",
        "type": "Micro-plated / one-gram gold imitation",
        "whatsapp": "+917036132171",
        "email": "Not disclosed",
        "ordering": "WhatsApp bookings + COD mentions + bulk video calls",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "bulk, COD, Machilipatnam, diamond replica",
        "reason": "Multiple WhatsApp lines + wholesale motion.",
        "services": "WhatsApp automation, B2B portal, CRM",
        "maps": "Not found",
        "score": "8",
        "notes": "Additional numbers appear in indexed caption; dedupe carefully.",
    },
    {
        "business": "Swarnam Varnam",
        "handle": "swarnam_varnam",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Jewellery (verify niche)",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "jewellery",
        "reason": "Handle surfaced in imitation SERP threads.",
        "services": "IG audit",
        "maps": "Not found",
        "score": "5",
        "notes": "",
    },
    {
        "business": "925 Silver Jaipur",
        "handle": "925silverjpr",
        "followers": "Not scraped",
        "city": "Jaipur",
        "state": "Rajasthan",
        "type": "925 silver traditional",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "925, traditional, weight priced",
        "reason": "Silver SMB with explicit pricing style in snippet.",
        "services": "WhatsApp quoting automation, catalog",
        "maps": "Not found",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Silver Jewellery Indian",
        "handle": "silver_jewellery_indian",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "925 silver",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "925 silver",
        "reason": "SMB silver marketing account.",
        "services": "WhatsApp, ecommerce",
        "maps": "Not found",
        "score": "5",
        "notes": "",
    },
    {
        "business": "Krupanidhi 925 Silver",
        "handle": "krupanidhi_925_silver",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "925 silver rings/necklaces",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "925, engraving",
        "reason": "925-focused IG seller.",
        "services": "Ecommerce, personalization tooling",
        "maps": "Not found",
        "score": "5",
        "notes": "",
    },
    {
        "business": "SuruArts Creation (SAC Jewellery)",
        "handle": "suruarts_creation_official",
        "followers": "Not scraped",
        "city": "Navi Mumbai / Mumbai",
        "state": "Maharashtra",
        "type": "Maharashtrian imitation / 1gm jewellery",
        "whatsapp": "+919373722506",
        "email": "Not disclosed",
        "ordering": "WhatsApp + inbox with product picture",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "Nerul, Panvel, Ghatkopar, wa.me link",
        "reason": "Multi-branch SMB with explicit WhatsApp motion.",
        "services": "WhatsApp automation, multi-location CRM, reviews",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Stree Jewels By Surbhi",
        "handle": "streejewelsbysurbhi",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Amrapali-inspired statement sets",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "DM to book",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "DM to book, wedding jewellery",
        "reason": "DM-first booking for limited drops.",
        "services": "DM automation, checkout links, CRM",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Payal Jewelry",
        "handle": "payal_jewelry_",
        "followers": "Not scraped",
        "city": "Naroda (hashtag in indexed reel; confirm)",
        "state": "Gujarat",
        "type": "Mangalsutra / short necklace imitation",
        "whatsapp": "+919054250580",
        "email": "Not disclosed",
        "ordering": "WhatsApp (Wsp) + reels catalog",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "mangalsutra, one gram gold plated",
        "reason": "Imitation mangalsutra niche on IG.",
        "services": "WhatsApp commerce, SEO landing pages",
        "maps": "Not found",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Shivay Imitation",
        "handle": "shivay.imitation",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Imitation jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "imitation",
        "reason": "Imitation-focused handle surfaced in mangalsutra SERPs.",
        "services": "Catalog, WhatsApp",
        "maps": "Not found",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Digital Dress Room",
        "handle": "digitaldressroom",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Mangalsutra / online-first jewellery listings",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify (likely external shop)",
        "website_yn": "Unclear",
        "website_url": "Verify",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "mangalsutra, item code",
        "reason": "SKU-coded listings typical of SMB ecommerce; confirm channel mix.",
        "services": "Ecommerce optimization, IG shopping",
        "maps": "Not found",
        "score": "5",
        "notes": "May be mixed apparel+jewellery; validate before outreach.",
    },
    {
        "business": "Beautiful Creations 0365",
        "handle": "beautiful_creations0365",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Moissanite / polki kundan sets",
        "whatsapp": "+919911283949",
        "email": "Not disclosed",
        "ordering": "DM or WhatsApp with picture; UPI payments",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "no COD, moissanite, kundan",
        "reason": "Strong WhatsApp booking + policy clarity in indexed caption.",
        "services": "WhatsApp automation, CRM, returns workflow tooling",
        "maps": "Not found",
        "score": "8",
        "notes": "Linked from Indian Kundan Jewellery style posts; treat as primary booking contact.",
    },
    {
        "business": "Just Kundan",
        "handle": "just_kundan",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Kundan jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "kundan",
        "reason": "Kundan niche handle surfaced in kundan SERPs.",
        "services": "Catalog, ads, WhatsApp",
        "maps": "Not found",
        "score": "5",
        "notes": "",
    },
    {
        "business": "KSB Gold and Diamonds",
        "handle": "ksb_gold_and_diamonds",
        "followers": "Not scraped",
        "city": "Visakhapatnam",
        "state": "Andhra Pradesh",
        "type": "Gold / diamond jewellery (retail IG)",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Verify (likely showroom DMs)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "Vizag, Eluru, bracelets, bangles",
        "reason": "Regional jeweller using reels for discovery; validate SMB vs chain.",
        "services": "WhatsApp enquiries, GBP, content",
        "maps": "Not found",
        "score": "5",
        "notes": "Confirm ordering channel on profile; may be showroom-first.",
    },
    {
        "business": "Nakshatra Jewels",
        "handle": "nakshatra_jewels",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Antique / south Indian fashion sets",
        "whatsapp": "+918977605305",
        "email": "Not disclosed",
        "ordering": "DM for order + WhatsApp number in caption",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "DM for order, kemp, guttapusalu, Sneha inspired",
        "reason": "Explicit DM + phone ordering for priced sets.",
        "services": "WhatsApp automation, catalog pages, CRM",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Shainaz Khatik (Haldi jewellery maker)",
        "handle": "kahatiksahainaz",
        "followers": "Not scraped",
        "city": "Pimpalgaon Baswant (caption)",
        "state": "Maharashtra",
        "type": "Haldi / floral-style jewellery (bulk dispatch)",
        "whatsapp": "+918766917135",
        "email": "Not disclosed",
        "ordering": "DM / phone for bulk orders",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "haldi jewellery, bulk order, dispatch",
        "reason": "Event-jewellery SMB with DM-led sales.",
        "services": "CRM, WhatsApp automation, invoicing",
        "maps": "Not found",
        "score": "7",
        "notes": "Phone parsed from caption text 'Dm8766917135'.",
    },
    {
        "business": "Resin with Pallavi",
        "handle": "resinwithpallavi",
        "followers": "Not scraped",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "type": "Resin / flower preservation keepsakes",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "Customization via DM (verify)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "resin, Chennai, moon phase",
        "reason": "Maker brand surfaced in resin jewellery discovery searches.",
        "services": "Ecommerce, DM automation, CRM",
        "maps": "Not found",
        "score": "6",
        "notes": "Jewellery-adjacent; confirm SKU mix.",
    },
    {
        "business": "Samskriti 2023 (hand-painted jewelry)",
        "handle": "samskriti_2023",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Hand-painted / custom jewelry",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "DM for order (caption)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed reel",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "custom hand-painted jewelry, DM for order",
        "reason": "DM-led custom maker; strong services upsell fit.",
        "services": "Custom ecommerce, DM automation, CRM",
        "maps": "Not found",
        "score": "7",
        "notes": "",
    },
    {
        "business": "Wed With Gul (floral jewellery)",
        "handle": "wedwithgul",
        "followers": "Not scraped",
        "city": "Unknown (confirm)",
        "state": "India",
        "type": "Floral / haldi jewellery (made to order)",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "DM with outfit + date (caption)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "haldi jewellery, destination wedding, customization",
        "reason": "Made-to-order floral sets sold via DM workflow.",
        "services": "CRM, scheduling, deposits/checkout, WhatsApp automation",
        "maps": "Not found",
        "score": "8",
        "notes": "",
    },
    {
        "business": "RADHEE Imitation Rajkot",
        "handle": "radhee_imitation_rajkot",
        "followers": "Not scraped",
        "city": "Rajkot",
        "state": "Gujarat",
        "type": "Imitation jewellery retail",
        "whatsapp": "+917383704729",
        "email": "Not disclosed",
        "ordering": "WhatsApp booking + worldwide shipping claims",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "kundan, AD jewellery, Rajkot address",
        "reason": "Shop-forward imitation retailer with explicit WhatsApp lines.",
        "services": "WhatsApp automation, maps/GBP, catalog microsite",
        "maps": "Not found",
        "score": "8",
        "notes": "Indexed caption also references another WhatsApp segment (+919725347257-58); verify active numbers on profile.",
    },
    {
        "business": "Rajaveer Imitation Ahmedabad",
        "handle": "rajaveer_imitation_ahemadabad",
        "followers": "Not scraped",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "type": "Imitation jewellery",
        "whatsapp": "Not disclosed in snippet",
        "email": "Not disclosed",
        "ordering": "DM/comment price checks (verify)",
        "website_yn": "No",
        "website_url": "—",
        "recent": "Indexed post",
        "engagement": "Not scraped",
        "bio": "Not scraped",
        "keywords": "imitation, Ahmedabad, Gujarati comments",
        "reason": "Local imitation seller surfaced in classic/imitation SERPs.",
        "services": "WhatsApp click-to-chat, catalog, ads",
        "maps": "Not found",
        "score": "6",
        "notes": "Pricing/contact not visible in snippet; verify on profile.",
    },
]


def render_leads(leads: list[dict[str, str]]) -> str:
    blocks: list[str] = []
    for idx, lead in enumerate(leads, start=1):
        handle = lead["handle"]
        url = f"https://www.instagram.com/{handle.strip('@')}/"
        blocks.append(
            "\n".join(
                [
                    "",
                    "=" * 50,
                    f"LEAD #{idx}",
                    "=" * 50,
                    f"Business Name: {lead['business']}",
                    f"Instagram Handle: @{handle.strip('@')}",
                    f"Instagram URL: {url}",
                    f"Followers Count: {lead['followers']}",
                    f"City: {lead['city']}",
                    f"State: {lead['state']}",
                    f"Business Type: {lead['type']}",
                    f"WhatsApp Number: {lead['whatsapp']}",
                    f"Email: {lead['email']}",
                    f"Ordering Method: {lead['ordering']}",
                    f"Website Present: {lead['website_yn']}",
                    f"Website URL: {lead['website_url']}",
                    f"Recent Activity Date: {lead['recent']}",
                    f"Average Engagement: {lead['engagement']}",
                    f"Bio Text: {lead['bio']}",
                    f"Keywords: {lead['keywords']}",
                    f"Reason Qualified: {lead['reason']}",
                    f"Potential Services Needed: {lead['services']}",
                    f"Google Maps Link: {lead['maps']}",
                    f"Lead Quality Score: {lead['score']}/10",
                    f"Notes: {lead['notes']}",
                ]
            )
        )
    header = "\n".join(
        [
            "India Jewellery Instagram / WhatsApp Lead Export",
            "Generated from public web search snippets (not logged-in Instagram scraping).",
            "Deduped on Instagram handle. Verify phone, city, and website presence on the live profile before outreach.",
            f"Total leads: {len(leads)}",
        ]
    )
    return header + "\n" + "\n".join(blocks) + "\n"


def main() -> None:
    out = Path("/workspace/india_jewellery_instagram_leads.txt")
    if len(LEADS) != 100:
        raise SystemExit(f"Expected 100 leads, got {len(LEADS)}")
    out.write_text(render_leads(LEADS), encoding="utf-8")


if __name__ == "__main__":
    main()
