#!/usr/bin/env python3
"""Generate india_jewellery_instagram_leads.txt from curated public-index research (May 2026)."""
from __future__ import annotations

import textwrap
from pathlib import Path

# Each tuple: (handle, business_name, city, state, biz_type, wa, email, ordering, website_yn,
#             website_url, bio, keywords, reason, services, maps_hint, score, notes)
# Followers/activity/engagement: not verifiable from search index alone.

LEADS: list[tuple] = [
    ("_jewellery_palace_bjs", "Jewellery Palace (BJS)", "Unspecified", "India", "Imitation / Nath", "+918440038551", "Not found in public index", "WhatsApp order on posts", "No", "", "Order on WhatsApp; code-based listings", "WhatsApp, nath, imitation", "Caption lists WhatsApp for orders; SMB-style posts", "WhatsApp automation, ecommerce, CRM", "https://www.google.com/maps/search/jewellery%20shop%20India", "8", "Franchise chain rule: appears independent local-style; verify."),
    ("wear_nd_shine_jewelry", "Wear N Shine Jewelry", "Unspecified", "India", "Fashion / artificial", "Not in snippet", "Not found", "DM / comments", "No", "", "Active reel-style posts in index", "fashion jewellery, DM", "Small seller signals from indexed reels", "Instagram growth, DM automation", "https://www.google.com/maps/search/fashion%20jewellery%20India", "6", "Verify phone from profile; enrich metrics via IG."),
    ("trend_jewelryys", "Trend Jewelryys", "Unspecified", "India", "Fashion jewellery", "Not in snippet", "Not found", "DM", "No", "", "Indexed posts with low comment counts", "trending, reels", "SMB reel account pattern", "Content studio, ads", "https://www.google.com/maps/search/jewellery%20India", "5", "Needs manual bio scrape."),
    ("aakanksha_jewellery", "Aakanksha Jewellery", "Unspecified", "India", "Fashion / artificial", "Not in snippet", "Not found", "DM (price queries in comments)", "No", "", "Commenters ask price/PP", "PP, price on DM", "Classic DM-for-price behaviour", "DM automation, chatbot", "https://www.google.com/maps/search/jewellery%20India", "6", "High comment engagement pattern in index."),
    ("s.swarnakarandson", "S. Swarnakar & Son", "Kolkata", "West Bengal", "Silver / traditional", "+918981948452", "Not found", "Call / booking number on posts", "No", "", "Kolkata Chetla; silver gach kouto collection", "Kolkata, silver, bridal", "Phone booking; strong local hashtags", "Website, local SEO, WA booking", "https://www.google.com/maps/search/Chetla%20jewellery%20Kolkata", "7", "Physical jeweller; confirm if ecommerce site exists."),
    ("hirapannajewels", "Hira Panna Jewels", "Kolkata", "West Bengal", "925 silver", "Not in snippet", "Not found", "Store + Instagram discovery", "No", "", "92.5 silver Kolkata Elgin area (influencer mention)", "Kolkata, sterling silver", "SMB silver boutique positioning", "Ecommerce, appointment booking", "https://www.google.com/maps/search/Hira%20Panna%20jewels%20Kolkata", "7", "Address surfaced via third-party reel; verify."),
    ("lakshmi_creations_9", "Lakshmi Creations (Imitation)", "Unspecified", "India", "Imitation wholesale", "+919849567353", "Not found", "WhatsApp for orders", "No", "", "Wholesale imitation; WhatsApp in captions", "imitation, wholesale, WhatsApp", "Explicit WhatsApp ordering", "WA automation, catalogue site", "https://www.google.com/maps/search/imitation%20jewellery%20India", "8", "Strong WhatsApp-led distribution signals."),
    ("mahavirimitationjewelle", "Mahavir Imitation Jewellery", "Unspecified", "India", "Imitation / oxidised bangles", "+918320499102", "Not found", "Call / WhatsApp for designs", "No", "", "Manufacturer hashtags; call for details", "imitation, oxidised, wholesale", "Manufacturer + call-to-order", "B2B portal, CRM, WA catalog", "https://www.google.com/maps/search/imitation%20jewellery%20wholesale%20India", "8", "Wholesale orientation; verify MOQ."),
    ("rajaveer_imitation_ahemadabad", "Raja Veer Imitation (Ahmedabad)", "Ahmedabad", "Gujarat", "One-gram / imitation", "+918511513997", "Not found", "Mobile number on reels", "No", "", "Ahmedabad-focused imitation reels", "Ahmedabad, one gram, imitation", "City tag + phone in creative", "WA commerce, IG ads", "https://www.google.com/maps/search/imitation%20jewellery%20Ahmedabad", "7", "Verify business registration name."),
    ("chudiwale_", "Chudiwale Fashion Jewellery", "Unspecified", "India", "Custom bangles / fashion", "+917972380643", "Not found", "WhatsApp booking", "No", "", "Customized bangles; WhatsApp booking", "custom bangles, bridal", "Custom orders + WhatsApp", "Custom order CRM, WA flows", "https://www.google.com/maps/search/bangles%20jewellery%20India", "8", "Strong custom + WA signals."),
    ("oxidised_jewellery_wholesaler", "Oxidised Jewellery Wholesaler", "Unspecified", "India", "Oxidised wholesale", "Not in snippet", "Not found", "DM / wholesale DMs", "No", "", "Wholesaler account in index", "oxidised, wholesale", "SMB wholesaler niche", "Catalogue website, B2B CRM", "https://www.google.com/maps/search/oxidised%20jewellery%20wholesale%20India", "6", "Needs phone extraction from profile."),
    ("rajputii_jewellery_", "Rajputii Jewellery", "Unspecified", "India", "Rajputi / traditional fashion", "Not in snippet", "Not found", "DM / community comments", "No", "", "Comment threads on reels", "rajputi, traditional", "Community-heavy SMB", "UGC, influencer collabs", "https://www.google.com/maps/search/rajputi%20jewellery%20India", "6", "Enrich with exact SKU workflow."),
    ("southindian__templejewellery", "South Indian Temple Jewellery", "Chennai (seller tag)", "Tamil Nadu", "Temple / matt finish", "+917904076978 / +918610765751", "Not found", "DM or WhatsApp; UPI payments", "No", "", "WhatsApp group link in posts; no COD", "temple, south indian, matt finish", "Dual WhatsApp lines + group selling", "WA groups automation, payments stack", "https://www.google.com/maps/search/temple%20jewellery%20Chennai", "9", "Very strong IG+WA stack; verify legal entity."),
    ("templejewelleryhub_bypriya", "Temple Jewellery Hub by Priya", "Unspecified", "India", "Temple jewellery", "Not in snippet", "Not found", "DM / price in caption", "No", "", "Price-point posts (indexed)", "temple, budget sets", "Caption-led selling", "Ecommerce + logistics", "https://www.google.com/maps/search/temple%20jewellery%20India", "7", "Add WhatsApp if present in bio."),
    ("bcos_its_silver", "Because It's Silver", "Hyderabad", "Telangana", "925 silver / guttapusalu", "Not in snippet", "Not found", "DM / enquiries", "No", "", "Hyderabad pearls hashtags; premium silver sets", "silver, pearls, Hyderabad", "Silver-specialist IG brand", "Shopify-lite site or booking", "https://www.google.com/maps/search/silver%20jewellery%20Hyderabad", "7", "Verify if separate storefront site."),
    ("flicker_colors", "Flicker Colors (Resin Artist Simran)", "Bangalore", "Karnataka", "Resin / preserved flowers", "Not in snippet", "Not found", "DM to order", "No", "", "Bangalore resin artist; DM ordering", "resin, Bangalore, preserved flowers", "DM-native custom product", "DM automation, ecommerce", "https://www.google.com/maps/search/resin%20jewellery%20Bangalore", "8", "Cross-sell: wedding flower preservation."),
    ("vernika.silver.jewellery", "Vernika Silver", "Bangalore", "Karnataka", "925 silver retail", "+917406810666", "Not found", "Call / video call shopping", "No", "", "Chickpet / Avenue Road address cues", "925 silver, Bangalore", "Phone + physical market SMB", "Local SEO, WA catalog", "https://www.google.com/maps/search/Avenue%20Road%20silver%20Bangalore", "7", "Physical shop + IG; verify site."),
    ("jewelsofkarnataka", "Jewels of Karnataka", "Karnataka", "Karnataka", "One-gram gold fashion", "+919740234813", "Not found", "WhatsApp orders", "No", "", "One gram gold pieces; WhatsApp contact", "one gram gold, Karnataka", "WhatsApp-first SKU selling", "WA automation, UPI flows", "https://www.google.com/maps/search/one%20gram%20gold%20jewellery%20Karnataka", "8", "Strong SMB SKU + WA pattern."),
    ("rajputijewellerybhilwara00", "Rajputi Jewellery Bhilwara", "Bhilwara", "Rajasthan", "Rajputi / plated sets", "+919829900459", "Not found", "WhatsApp order text", "No", "", "WhatsApp payment instructions; online transfer", "rajputi, plated, handmade look", "WhatsApp-led high-ticket sets", "CRM, fraud-prevention UX", "https://www.google.com/maps/search/jewellery%20Bhilwara", "7", "Claims COD rules in post; verify."),
    ("jhoolylalartificial", "Jhooly Lal Artificial Jewellery", "Delhi", "Delhi", "Artificial jewellery", "Not in snippet", "Not found", "DM / store discovery", "No", "", "Delhi artificial jewellery page indexed", "artificial, Delhi", "Chandni Chowk-type SMB cluster", "Website + inventory", "https://www.google.com/maps/search/artificial%20jewellery%20Delhi", "6", "Enrich address from profile."),
    ("radha_rani_imitation_7", "Radha Rani Imitation", "Mumbai", "Maharashtra", "Imitation wholesale", "+917023725950", "Not found", "Phone on reel; Bhoiwada market", "No", "", "Bhuleshwar / Bhoiwada wholesale cues", "Mumbai, wholesale, imitation", "Classic wholesale SMB", "B2B ordering portal", "https://www.google.com/maps/search/Bhuleshwar%20imitation%20jewellery%20Mumbai", "8", "Strong market-location selling."),
    ("flabelcreations", "Flabel Creations", "Unspecified", "India", "Diamond-look fashion sets", "+917711990044", "Not found", "WhatsApp + DM", "No", "", "Free shipping; link-in-bio WhatsApp pattern", "AD jewellery, same-day dispatch", "WhatsApp + DM dual channel", "WA automation, IG ads", "https://www.google.com/maps/search/fashion%20jewellery%20India", "8", "Explicit WA + DM in indexed caption."),
    ("creative_zeal_", "CreativeZeal by Sapna Wadhwani", "Chennai", "Tamil Nadu", "Oxidised / German silver", "Not in snippet (DM-first)", "Not found", "DM to place order", "No", "", "DM-led oxidised earrings; Chennai tags", "oxidised, jhumka, DM order", "Pure DM commerce pattern", "DM automation, checkout links", "https://www.google.com/maps/search/oxidised%20jewellery%20Chennai", "8", "Handle confirmed via third-party index."),
    ("cenorajewels", "Cenora Jewels", "Chennai", "Tamil Nadu", "Fashion / promo jewellery", "+917021923226", "Not found", "DM + WhatsApp", "No", "", "Buy-1-get-1 style promo posts", "promo, DM, WhatsApp", "Offer-led WhatsApp/DM stack", "Promo automation, CRM", "https://www.google.com/maps/search/jewellery%20Chennai", "7", "Verify legitimacy of promos."),
    ("silver_jewels_pune", "Shree Silver (Silver Jewels Pune)", "Pune", "Maharashtra", "925 silver retail", "Not in snippet", "Not found", "Shop visit + online", "No", "", "Raviwar Peth address; hallmarked rings", "Pune, 925 silver", "Local shop + IG", "Click-collect, WA", "https://www.google.com/maps/search/silver%20jewellery%20Pune", "7", "Post mentions order online; verify channel."),
    ("shrisilverjewellery_28", "Shri Silver Jewellery", "Unspecified", "India", "925 silver studs", "Not in snippet", "Not found", "DM", "No", "", "Ready-to-ship style captions", "925 silver, studs", "SKU posting pattern", "Inventory microsite", "https://www.google.com/maps/search/925%20silver%20jewellery%20India", "6", "Limited public contact in index."),
    ("lakshmijewells", "Lakshmi Jewells / Sree Wholesale Jewellery", "Hyderabad / South India", "Telangana", "Handmade / matte bridal", "+919390483697", "Not found", "WhatsApp order & enquiry", "No", "", "No COD; opening video policy", "bridal, matte, wholesale", "Strict policies = operational maturity", "Policy pages, helpdesk bot", "https://www.google.com/maps/search/wholesale%20jewellery%20Hyderabad", "8", "Operational rules indicate volume."),
    ("roshi.collections", "Roshi Collections", "Tamil Nadu (ships TN)", "Tamil Nadu", "One-gram gold forming", "+919092327836", "Not found", "WhatsApp + screenshot order", "No", "", "Online payment only; screenshot workflow", "one gram gold, forming", "Screenshot-to-WhatsApp pipeline", "WA automation + OMS", "https://www.google.com/maps/search/one%20gram%20gold%20Tamil%20Nadu", "8", "No COD; clear ops text."),
    ("sakhi_1_gram_gold_jewellery", "Sakhi 1 Gram Gold Jewellery", "Unspecified", "India", "One-gram gold fashion", "+919652417754", "Not found", "WhatsApp orders", "No", "", "Simple price + WhatsApp caption", "one gram gold, necklace", "Classic SMB caption selling", "Catalog automation", "https://www.google.com/maps/search/one%20gram%20gold%20India", "7", "Verify state/city from bio."),
    ("janvish_onegramgold_and_boutiq", "Janvish One Gram Gold & Boutique", "Unspecified", "India", "One-gram gold + boutique", "+918121769801", "Not found", "Screenshot WhatsApp + groups", "No", "", "WhatsApp group for updates", "one gram gold, boutique", "Group + WA commerce", "Community marketing automation", "https://www.google.com/maps/search/one%20gram%20gold%20India", "8", "Group link pattern is strong signal."),
    ("dreams.jewellery2023", "Dreams Jewellery 2023", "Unspecified", "India", "Fashion / bracelets", "Not in snippet", "Not found", "DM price", "No", "", "Commenters ask price", "bracelet, DM price", "Comment-led DM funnel", "DM routing automation", "https://www.google.com/maps/search/fashion%20jewellery%20India", "6", "Lightweight SMB."),
    ("begumbazar_wholesale_jewelry", "Begum Bazar Wholesale Jewelry", "Hyderabad", "Telangana", "Wholesale sets / guttapusalu", "+919908136342", "Not found", "DM or WhatsApp; screenshot order", "No", "", "Begum Bazar wholesale context", "Begum Bazar, wholesale, DM", "Named wholesale market SMB", "B2B portal, WA catalog", "https://www.google.com/maps/search/Begum%20Bazar%20wholesale%20jewellery%20Hyderabad", "8", "Multiple numbers appear across promos; dedupe ongoing."),
    ("saibrindavan_jewellers", "Sai Brindavan Jewellers (SB Code)", "Hyderabad", "Telangana", "Begum Bazar wholesale/retail", "Not in snippet", "Not found", "Store + market positioning", "No", "", "Wholesale/retail Begum Bazar", "Begum Bazar, wholesale", "Market-native seller", "Inventory + WA", "https://www.google.com/maps/search/Begum%20Bazar%20jewellers%20Hyderabad", "6", "Enrich phone from profile."),
    ("fashion_darbar_hub_", "Fashion Darbar Hub", "Unspecified", "India", "Couple bracelets / fashion", "+919887305357", "Not found", "WhatsApp screenshot", "No", "", "Screenshot-to-WhatsApp ordering", "couple bracelets, viral reels", "Viral SKU + WA", "Ads + landing", "https://www.google.com/maps/search/fashion%20jewellery%20India", "7", "Gift-market positioning."),
    ("indukurisjewel", "Jewel Indukuri's", "Hyderabad", "Telangana", "Lab-grown diamond custom", "+916302720676", "Not found", "WhatsApp for details", "No", "", "Customization via WhatsApp", "lab grown, customize", "High-trust DM/WA sales", "Appointment scheduling", "https://www.google.com/maps/search/lab%20grown%20diamond%20Hyderabad", "7", "Premium SMB; verify disclosures."),
    ("sampati_official", "Sampati (Sampat Jewellers Inc.)", "Chennai", "Tamil Nadu", "Custom gold mangalsutra", "Not in snippet", "Not found", "DM keyword CUSTOM", "No", "", "Custom Thali mangalsutra storytelling", "custom mangalsutra, Tamil", "DM workflow for bespoke gold", "CRM for bespoke orders", "https://www.google.com/maps/search/custom%20mangalsutra%20Chennai", "8", "Custom gold = high service load."),
    ("just_kundan", "Just Kundan", "Unspecified", "India", "Kundan fashion", "Not in snippet", "Not found", "DM", "No", "", "Kundan niche handle", "kundan, fashion", "Niche SMB", "Catalog + WA", "https://www.google.com/maps/search/kundan%20jewellery%20India", "6", "Enrich contacts from bio."),
    ("lucknow_artificial_jewellery_", "Lucknow Artificial Jewellery", "Lucknow", "Uttar Pradesh", "One-gram / artificial", "+918957754721", "Not found", "Booking number on reels", "No", "", "COD + India shipping claims", "Lucknow, artificial, COD", "COD-led SMB acquisition", "COD risk tools, CRM", "https://www.google.com/maps/search/artificial%20jewellery%20Lucknow", "8", "COD claims need verification."),
    ("sujatha_gold_covering_works", "Sujatha Gold Covering Works", "Machilipatnam", "Andhra Pradesh", "Micro gold plated / AD", "+917382222208", "Not found", "WhatsApp bookings; bulk line", "No", "", "Multiple WA numbers; COD mentions", "Machilipatnam, micro plated", "Manufacturer-distributor pattern", "B2B portal, CRM", "https://www.google.com/maps/search/Machilipatnam%20jewellery", "8", "Several numbers; keep primary."),
    ("rajputi_jewelery_wholsaler_s.c", "Rajputi Jewellery Wholesaler", "Unspecified", "India", "Rajputi sets", "+917877634674", "Not found", "WhatsApp + join group", "No", "", "Group link selling pattern", "rajputi, wholesale", "Group commerce", "Group automation compliance", "https://www.google.com/maps/search/rajputi%20jewellery%20wholesale%20India", "7", "Group link requires policy review."),
    ("bjs2k", "Biswakarma Jewellery Shilpaya (BJS)", "Kolkata", "West Bengal", "Diamond-look / nosepins", "+919874085669", "Not found", "WhatsApp for orders", "No", "", "WhatsApp repeated in posts", "diamond look, nosepin", "WhatsApp-led SMB in Kolkata cluster", "WA catalog, CRM", "https://www.google.com/maps/search/Biswakarma%20jewellery%20Kolkata", "7", "Multiple numbers historically; use latest post."),
    ("poojajewels_", "Pooja Jewels", "Unspecified", "India", "Fashion / reels commerce", "Not in snippet", "Not found", "DM", "No", "", "Reels engagement in index", "reels, jewellery", "Creator-commerce vibe", "Affiliate tooling", "https://www.google.com/maps/search/jewellery%20India", "5", "Light evidence; low priority until enriched."),
    ("khushbu_jewellers_tinwari", "Khushbu Jewellers Tinwari", "Unspecified", "India", "Silver / rajputi silver", "+919929595357", "Not found", "WhatsApp screenshot orders", "No", "", "COD available on many silver reels", "silver, COD, screenshot order", "Screenshot order pipeline", "OMS + WA automation", "https://www.google.com/maps/search/silver%20jewellery%20India", "8", "Same phone appears on sibling pages; treat as network hub."),
    ("jewellryjunction", "Jewellery Junction", "Nagpur", "Maharashtra", "Imitation retail", "+919730162779", "Not found", "Call / store", "No", "", "Teen Nal Chowk Nagpur", "Nagpur, imitation", "Local shop + IG discovery", "Local SEO, WA", "https://www.google.com/maps/search/jewellery%20Teen%20Nal%20Chowk%20Nagpur", "7", "Influencer map pin posts."),
    ("asarejewellers_bhimchowk", "Asare Jewellers (Bhim Chowk)", "Nagpur", "Maharashtra", "Gold / silver / artificial mix", "Not in snippet", "Not found", "Store-first", "No", "", "Nagpur locality tags", "Nagpur, gold, silver", "Local jeweller IG", "Website + inventory", "https://www.google.com/maps/search/Bhim%20Chowk%20jewellers%20Nagpur", "6", "Enterprise filter: appears local."),
    ("khushbu_jewellers_1", "Khushbu Jewellers (Alt handle)", "Unspecified", "India", "Silver fashion", "Not in snippet", "Not found", "DM / reels", "No", "", "Sibling network handle in index", "silver, reels", "Network SMB", "WA automation", "https://www.google.com/maps/search/silver%20jewellery%20India", "6", "Do not merge with Tinwari without ops confirmation."),
    ("jj_resin.memo", "JJ Resin Memo (Jeyavindhiya Jegadish)", "Unspecified", "India", "Resin keychains / custom", "+918489166598", "Not found", "WhatsApp orders", "No", "", "Custom resin memo products", "resin, customised", "Custom SKU WhatsApp", "Ecommerce + upsells", "https://www.google.com/maps/search/resin%20gifts%20India", "7", "Adjacent to jewellery; still accessory SMB."),
    ("themadras_artstudio", "The Madras Art Studio (Dhanu Ravi)", "Chennai", "Tamil Nadu", "Resin flower jewellery", "Not in snippet", "Not found", "DM to order", "No", "", "Custom resin flower sets", "resin, preserved flowers, Chennai", "DM custom product", "DM automation", "https://www.google.com/maps/search/resin%20jewellery%20Chennai", "8", "Strong DM ordering language."),
    ("suhasjewellers", "Suhas Jewellers", "Khammam", "Telangana", "Gold bridal video commerce", "+918121924779", "Not found", "Video call booking", "No", "", "Video call shopping for bridal harams", "bridal, video call, gold", "Video-commerce jeweller", "Scheduling + CRM", "https://www.google.com/maps/search/Suhas%20Jewellers%20Khammam", "7", "Also uses alternate numbers in posts."),
    ("seriously.kreative", "Seriously Kreative (Kusum C Bala)", "Unspecified", "India", "Handmade jhumka / fashion", "Not in snippet", "Not found", "DM / enquiries", "No", "", "Handmade jhumka positioning", "handmade, jhumka", "Creator-led SMB", "Shopify starter", "https://www.google.com/maps/search/handmade%20jhumka%20India", "6", "Enrich WhatsApp from bio."),
    ("talai.jewels", "Talai Jewels", "Unspecified", "India", "Mangalsutra fashion", "See profile (index formatting)", "Not found", "WhatsApp in caption", "No", "", "Black beaded mangalsutra sets", "mangalsutra, black beads", "Caption phone formatting odd in index", "WA automation", "https://www.google.com/maps/search/mangalsutra%20jewellery%20India", "5", "Re-verify WhatsApp digits from IG."),
    ("weddinganswers", "Wedding Answers (bridal accessories)", "Patna", "Bihar", "Bridal kalire / floral jewellery", "+918368213149", "Not found", "WhatsApp or DM @weddinganswers", "No", "", "Patna shipping mention", "Patna, bridal, kalire", "Bridal accessory SMB", "Ecommerce bundles", "https://www.google.com/maps/search/bridal%20jewellery%20Patna", "7", "Adjacent category; still wedding commerce."),
    ("shubh_jewellerss", "Shubh Jewellers", "Kanpur", "Uttar Pradesh", "925 silver / gold", "+918318759607", "Not found", "Call", "No", "", "Lal Bangla Kanpur address", "Kanpur, 925 silver", "Local shop IG", "Local SEO", "https://www.google.com/maps/search/Shubh%20Jewellers%20Kanpur", "6", "Primarily call-based."),
    ("pukhraj.jewellers1", "Pukhraj Jewellers", "Ahmedabad", "Gujarat", "22k gold custom", "+919409151772", "Not found", "DM + WhatsApp + call", "No", "", "Satellite area address; hallmark claims", "Ahmedabad, custom gold", "Custom orders via DM/WA", "CRM, appointment booking", "https://www.google.com/maps/search/Pukhraj%20Jewellers%20Ahmedabad", "7", "Physical store; verify site."),
    ("sai_jewellers_rajat_ujjain", "Sai Jewellers Rajat", "Ujjain", "Madhya Pradesh", "Gold-plated short necklace", "+917024274632", "Not found", "DM + WhatsApp", "No", "", "Ujjain location in comments", "Ujjain, gold plated", "Temple-town SMB", "WA automation", "https://www.google.com/maps/search/jewellery%20Ujjain", "7", "Religious-tourism retail angle."),
    ("silver_palace45", "Silver Palace 45", "Unspecified", "India", "925 silver", "Not in snippet", "Not found", "DM", "No", "", "Stud SKUs", "925 silver, studs", "SKU posting", "Micro-catalog", "https://www.google.com/maps/search/925%20silver%20India", "6", "Needs phone from bio."),
    ("emmadi_silver_jewellery", "Emmadi Silver Jewellery", "Unspecified", "South India", "Silver", "Not in snippet", "Not found", "DM", "No", "", "Silver reels in index", "silver, south", "Regional silver SMB", "WA + shipping policy pages", "https://www.google.com/maps/search/silver%20jewellery%20India", "6", "Enrich city from bio."),
    ("ridhi_sidhi_jewellers", "Ridhi Sidhi Jewellers", "Barmer", "Rajasthan", "Silver gifts / sindoor box", "+917849810107", "Not found", "WhatsApp screenshot orders", "No", "", "COD claims; Rajasthan location", "Barmer, silver, COD", "Screenshot order + COD", "Risk ops + CRM", "https://www.google.com/maps/search/silver%20jewellery%20Barmer", "8", "Multiple numbers on posts; pick primary."),
    ("samskruthijewellers", "Samskruthi Jewellers", "Unspecified", "India", "925 silver / CZ bridal", "+918790112233", "Not found", "WhatsApp order", "No", "", "Layered necklaces; WhatsApp in reels", "CZ, bridal, silver", "WhatsApp-first silver bridal", "Catalog automation", "https://www.google.com/maps/search/samskruthi%20jewellers", "8", "Handle inferred from branded hashtag."),
    ("_sumangali_jewellers", "Sumangali Jewellers Veppampattu", "Veppampattu", "Tamil Nadu", "916 gold jewellery", "Not in snippet", "Not found", "DM / store", "No", "", "Traditional jeweller reel tone", "916 gold, Tamil Nadu", "Local jeweller IG", "Appointment + CRM", "https://www.google.com/maps/search/jewellery%20Veppampattu", "6", "Light ordering detail in index."),
    ("jodhpuri_silver", "Jodhpuri Silver", "Unspecified", "India", "Silver payal / rajasthani", "+919358839704", "Not found", "WhatsApp screenshot order", "No", "", "Website-order discount mentions in network posts", "silver, payal, jodhpuri", "Network SMB with WA screenshot flow", "WA automation", "https://www.google.com/maps/search/jodhpuri%20silver%20jewellery", "7", "Cross-check for ecommerce site."),
    ("resinbypallavi", "Resin by Pallavi", "Chennai", "Tamil Nadu", "Resin / moon keychains", "Not in snippet", "Not found", "DM", "No", "", "Chennai resin artist", "resin, Chennai, custom", "DM-led custom", "Ecommerce", "https://www.google.com/maps/search/resin%20artist%20Chennai", "7", "Jewellery-adjacent."),
    ("deccan.jewels1", "Deccan Jewels", "Hyderabad", "Telangana", "Hyderabadi vintage fashion", "+918919578539", "Not found", "DM + WhatsApp screenshot", "No", "", "Nizami / Hyderabadi positioning", "Hyderabad, nizami, vintage", "Geo-style IG brand", "WA automation, logistics", "https://www.google.com/maps/search/Hyderabadi%20jewellery%20Hyderabad", "8", "Unicode digits in source; normalized here."),
    ("gobindjewellers", "Gobind Jewellers", "Durgapur", "West Bengal", "Gold / silver traditional", "+919593222111", "Not found", "Call / WhatsApp", "No", "", "Chandidas Market; home delivery WB/JH", "Durgapur, gold, silver", "Traditional store + WA", "Local delivery tech", "https://www.google.com/maps/search/Gobind%20Jewellers%20Durgapur", "7", "Multiple numbers on posts."),
    ("thoselittleblinggss", "Those Little Blinggss", "Unspecified", "India", "Moissanite / oxidised fashion", "Not in snippet", "Not found", "DM to order", "No", "", "Free shipping + DM order captions", "moissanite, oxidised, DM", "DM-native SKU selling", "Checkout links", "https://www.google.com/maps/search/moissanite%20jewellery%20India", "8", "Strong DM order phrasing."),
    ("beautiful_creations0365", "Beautiful Creations (Indian Kundan Jewellery)", "Unspecified", "India", "Moissanite / kundan fashion", "+919911283949", "Not found", "DM or WhatsApp with picture", "No", "", "No COD; opening video policy", "kundan, moissanite, DM", "High-trust remote selling", "CRM + ticketing", "https://www.google.com/maps/search/kundan%20jewellery%20India", "8", "Claims large client count; verify."),
    ("chithus_jewel_world", "Chithu's Jewel World", "Perundurai", "Tamil Nadu", "Rent + sale jewellery", "+919865299960", "Not found", "Call / stall", "No", "", "Erode/Perundurai stall promos", "rent jewellery, Tamil Nadu", "Hybrid rent/sale SMB", "Rental inventory software", "https://www.google.com/maps/search/jewellery%20rental%20Tamil%20Nadu", "6", "Offer mechanics in reel."),
    ("omkar_jewels_surat", "Omkar Jewels Surat", "Surat", "Gujarat", "Custom jewellery studio", "+918141248248", "Not found", "Phone + showroom visit", "No", "", "Custom jewellery in Surat", "Surat, custom, bespoke", "Studio model SMB", "3D configurator, CRM", "https://www.google.com/maps/search/custom%20jewellery%20Surat", "7", "Showroom-first; still IG-led discovery."),
    ("suvarnashilpijewellerspvtltd", "Suvarna Shilpi Jewellers", "Ahmedabad", "Gujarat", "Wedding gold / diamond", "+919725816464", "Not found", "DM + WhatsApp + store", "No", "", "CG Road Ahmedabad store", "Ahmedabad, wedding, diamond", "Pvt Ltd but IG DM/WA present", "CRM, marketing automation", "https://www.google.com/maps/search/Suvarna%20Shilpi%20Jewellers%20Ahmedabad", "6", "Larger SMB; still service-heavy."),
    ("jewellery_shopper_", "Jewellery Shopper", "Unspecified", "India", "Silver idols / rings", "+918905291031", "Not found", "WhatsApp screenshot order", "No", "", "Different WA line than 992959... network posts", "silver, COD, screenshot", "Parallel ops number in posts", "WA automation", "https://www.google.com/maps/search/silver%20jewellery%20India", "7", "Do not dedupe with other network lines without ops proof."),
    ("rkjewellerypdy", "Radhakrishna Jewellery Pondicherry", "Puducherry", "Puducherry", "916 gold symbolic", "Not in snippet", "Not found", "Store + IG", "No", "", "Aurobindo motif pieces", "Pondicherry, gold", "Local heritage jeweller", "Website + storytelling", "https://www.google.com/maps/search/jewellery%20Pondicherry", "6", "More store-led than DM-first."),
    ("creativebhel", "Creativeभेल (Creative Bhel)", "Unspecified", "India", "Quirky bangle stacks / fashion", "Not in snippet", "Not found", "DM", "No", "", "Customised festive bangles", "bangles, customised, handmade", "Handmade fashion SMB", "Ecommerce", "https://www.google.com/maps/search/handmade%20bangles%20India", "7", "Fashion accessory overlap."),
    ("zevar_nawabi", "Zevar Nawabi", "Hyderabad", "Telangana", "Hyderabadi heritage fashion", "Not in snippet", "Not found", "DM (typical for this niche)", "No", "", "Heritage jadau-style positioning", "Hyderabad, jadau, heritage", "Premium niche IG brand", "Catalog + appointments", "https://www.google.com/maps/search/Hyderabadi%20jewellery%20Hyderabad", "6", "Phone not captured in index snippet."),
    ("yuvraj_nosepins", "Yuvraj Nosepins (Yuv Raj Kumar Jewellers)", "Delhi", "Delhi", "Lightweight gold nosepins/earrings", "Not in snippet", "Not found", "Store (Chandni Chowk)", "No", "", "Kucha Mahajani Chandni Chowk cues", "Delhi, gold earrings, lightweight", "Old Delhi jewellery SMB", "Ecommerce + inventory", "https://www.google.com/maps/search/Chandni%20Chowk%20jewellery%20Delhi", "6", "Pvt Ltd; still traditional market SMB."),
    ("aartijewellers.surat", "Aarti Jewellers Surat", "Surat", "Gujarat", "Gold jewellery retail", "Not in snippet", "Not found", "Store offers", "No", "", "Surat showroom promos", "Surat, gold, offers", "Retail jeweller IG", "Omnichannel", "https://www.google.com/maps/search/Aarti%20Jewellers%20Surat", "6", "Store-led."),
    ("jyoti.jewellers.surat", "Jyoti Jewellers Surat", "Surat", "Gujarat", "Mangalsutra / trendy gold", "Not in snippet", "Not found", "Showroom", "No", "", "Adajan showroom address posts", "Surat, mangalsutra", "Showroom IG", "Appointments + CRM", "https://www.google.com/maps/search/Jyoti%20Jewellers%20Surat", "6", "Store-led."),
    ("tp_jwellers_official", "TP Jewellers Official", "Unspecified", "India", "Gold earrings / shorts content", "Not in snippet", "Not found", "DM / call unclear", "No", "", "Shorts-heavy gold earring promos", "gold earrings, shorts", "Content-first jeweller SMB", "YouTube + IG funnel", "https://www.google.com/maps/search/gold%20earrings%20India", "5", "Light evidence; enrich contacts."),
    ("aabhushan_kriti", "Aabhushan Kriti", "Kochi", "Kerala", "Thread / one-gram fashion", "+919633032800", "Not found", "DM or WhatsApp (link in bio)", "No", "", "Kochi tags; choker/thread necklace", "Kochi, one gram, thread necklace", "Link-in-bio commerce pattern", "Link-in-bio landing builder", "https://www.google.com/maps/search/jewellery%20Kochi", "8", "Explicit DM/WA + LIOB pattern."),
    ("the.tassel.story", "The Tassel Story by Kriti", "Raipur (founder story) / India-wide", "Chhattisgarh", "Bridal tassel / floral jewellery", "Not in snippet", "Not found", "DM to order", "No", "", "Floral dupatta + bridal accessories", "bridal, tassel, floral", "DM-first bridal accessory brand", "Ecommerce + production ERP", "https://www.google.com/maps/search/bridal%20jewellery%20Raipur", "8", "Press mentions Raipur origin; verify current ops city."),
    ("krixtals", "Krixtals by Kripii", "Unspecified", "India", "Handmade rhinestone / resin", "Not found in IG index", "Not found", "DM (Threads crossposts)", "No", "", "Handmade to order; India shipping claims (Threads)", "handmade, rhinestone, resin", "Creator commerce", "Ecommerce + DM automation", "https://www.google.com/maps/search/handmade%20jewellery%20India", "6", "Primary discovery may be Threads; verify IG handle."),
    ("lavanyajewellers_slj", "Lavanya Jewellers (Gold)", "Vijayawada", "Andhra Pradesh", "Gold kasu / temple styles", "+919441176530", "Not found", "DM + WhatsApp + customised orders", "No", "", "PAN India shipping claims; customised orders", "Vijayawada, gold, kasu, temple", "DM/WA + custom gold SMB", "CRM + video consult", "https://www.google.com/maps/search/Lavanya%20Jewellers%20Vijayawada", "6", "More gold-forward than imitation; still IG-led."),
    ("manepallyjewellers_", "Manepally Jewellers", "Hyderabad", "Telangana", "Temple gold / bridal", "+918712690025", "Not found", "Appointment / video call", "No", "", "Large Hyderabad jeweller; IG appointments", "Hyderabad, temple, bridal", "Enterprise-y; included only for geo coverage", "Enterprise digital", "https://www.google.com/maps/search/Manepally%20Jewellers%20Hyderabad", "4", "Likely exceeds SMB filter; mark low score."),
    ("bhagyashree.jewellers.hyd", "Bhagyashree Jewellers HYD", "Hyderabad", "Telangana", "Gold kasu / nakshi", "+918121118307", "Not found", "Call / WhatsApp", "No", "", "Jubilee Hills tags; heavy gold sets", "Hyderabad, kasu, nakshi", "Premium SMB/large store", "CRM + marketing automation", "https://www.google.com/maps/search/Bhagyashree%20Jewellers%20Hyderabad", "5", "May be larger; verify SMB fit."),
    ("virkanyajewels_chennai", "Vir Kanya Jewels Chennai", "Chennai", "Tamil Nadu", "Fine gold jewellery", "Not in snippet", "Not found", "Store / IG", "No", "", "Pvt Ltd fine jewellery posts", "Chennai, fine gold", "Larger SMB", "Enterprise tooling", "https://www.google.com/maps/search/jewellery%20Chennai", "4", "Pvt Ltd; likely above target SMB."),
    ("newhyderabadpearlscbe", "New Hyderabad Pearls (Coimbatore)", "Coimbatore", "Tamil Nadu", "Pearl / moissanite retail", "+919629511193", "Not found", "Call + website shop", "Yes", "https://www.newhyderabadpearls.com/", "Coimbatore showroom + shop now", "pearls, moissanite, Coimbatore", "Has ecommerce site", "Migrate to headless commerce", "https://www.google.com/maps/search/New%20Hyderabad%20Pearls%20Coimbatore", "3", "Included only to document 'has site' contrast; usually EXCLUDE for outreach."),
    ("attrangi_designs", "Attrangi Designs", "Mumbai / Chennai / Surat", "India", "Fashion / polki / CNC bangles", "Not in snippet", "Not found", "Boutique visits", "No", "", "Multi-city boutiques", "polki, CNC bangles, boutiques", "Multi-city brand", "Enterprise retail systems", "https://www.google.com/maps/search/Attrangi%20Surat", "3", "Likely too large for ideal SMB lead."),
    ("divanka.in", "Divanka (fashion jewellery)", "Unspecified", "India", "Imitation / jhumka ecommerce", "+919207376139", "Not found", "WhatsApp + website shop", "Yes", "https://www.divanka.in/", "WhatsApp + web shop in captions", "jhumka, ecommerce", "Has dedicated ecommerce site", "Ads + retention", "https://www.google.com/maps/search/online%20jewellery%20India", "3", "Contrast lead: has site; usually EXCLUDE."),
    ("d9creation_jewellery", "D9creation Jewellery", "Jaipur", "Rajasthan", "Oxidised / German silver", "Not in snippet", "Not found", "Website purchase", "Yes", "https://www.d9creation.com/", "Manufacturer pushes D9Creation.com", "Jaipur, oxidised, manufacturer", "Has ecommerce site", "B2B portal", "https://www.google.com/maps/search/D9creation%20Jaipur", "3", "Contrast lead: has site; usually EXCLUDE."),
    ("khushbujewellers.com_", "Khushbu Jewellers (dot com handle)", "Unspecified", "India", "Silver SKUs", "+919875791031", "Not found", "WhatsApp screenshot + website order", "Yes", "https://khushbujewellers.com/ (inferred from handle)", "Explicit website-order promos in captions", "silver, website order", "Network with ecommerce", "Migrate checkout UX", "https://www.google.com/maps/search/silver%20jewellery%20India", "3", "Contrast lead: likely violates 'no website' ideal."),
    ("jewellery_by_rohika", "Jewellery by Rohika / Rohika", "Unspecified", "India", "Polki kundan bridal", "+916280926290", "Not found", "DM + WhatsApp + website", "Yes", "https://www.rohikastore.com/", "DM/WA but also ecommerce site", "polki, kundan, bridal", "Has professional ecommerce", "Retention marketing", "https://www.google.com/maps/search/Rohika%20jewellery", "3", "Contrast lead: has site; EXCLUDE for ideal ICP."),
    ("varudijewellers", "Varudi Jewellers", "Surat", "Gujarat", "Bridal / jadau / hallmark gold", "+919537102021", "Not found", "DM + phone + website", "Yes", "https://www.varudijewellers.com/", "DM + website in reels", "Surat, jadau, bridal", "Has ecommerce site", "Omnichannel", "https://www.google.com/maps/search/Varudi%20Jewellers%20Surat", "3", "Contrast lead: has site; EXCLUDE for ideal ICP."),
    ("wholesalepearlsjewells.onkar", "Pearls & Jewells Design Studio (Onkar)", "Unspecified", "India", "Fashion pearls / wholesale catalog", "+919996698633", "Not found", "DM for catalog; contact line on indexed reel", "No", "", "onkarindia-style reels; contact line + DM for full catalog", "pearls, wholesale, DM catalog", "Indexed caption lists contact line", "WA automation, B2B catalog", "https://www.google.com/maps/search/pearl%20jewellery%20wholesale%20India", "8", "Confirm legal entity vs other Onkar-named accounts."),
    ("r_k__jewellers", "R.K Jewellers (IG reel account)", "Unspecified", "India", "Gold / fashion jewellery reels", "+918106852097", "Not found", "WhatsApp for requirements (indexed reel text)", "No", "", "Public search snippet: WhatsApp for requirements", "reels, WhatsApp enquiries", "Explicit WhatsApp line on indexed reel", "WA lead routing", "https://www.google.com/maps/search/jewellery%20India", "7", "Store name/city not in snippet; validate before outreach."),
    ("hanumantjewels", "Hanumant Jewels", "New Delhi", "Delhi", "Diamond / mangalsutra retail", "Not in snippet", "Not found", "DM + Karol Bagh store (hashtags/captions)", "No", "", "Karol Bagh diamond posts; price grids in feed", "diamond, mangalsutra, Karol Bagh", "IG retail with DM workflow", "CRM, showroom scheduling", "https://www.google.com/maps/search/Hanumant%20Jewels%20Karol%20Bagh", "6", "Showroom-scale; WhatsApp not in sampled snippet."),
    ("bjhjewels_karolbagh", "BJH Jewels (BJH Jewels Pvt Ltd)", "New Delhi", "Delhi", "Diamond wholesale / retail", "+919354357066", "Not found", "DM + phone on reel; Bank Street Karol Bagh", "No", "", "Bank Street Karol Bagh address on wholesale reel", "diamond, Karol Bagh, HUID", "Phone + DM on caption", "B2B portal, CRM", "https://www.google.com/maps/search/BJH%20Jewels%20Karol%20Bagh", "8", "Pvt Ltd; caption-led ordering."),
    ("ashokjewellers_karolbagh", "Ashok Jewellers", "New Delhi", "Delhi", "Diamond / luxury rings", "Not in snippet", "Not found", "DM or visit Karol Bagh store", "No", "", "DM for prices; visit Ashok Jewellers Karol Bagh", "diamond, engagement rings, Karol Bagh", "Store + DM path", "DM automation, appointments", "https://www.google.com/maps/search/Ashok%20Jewellers%20Karol%20Bagh", "6", "No WhatsApp in sampled indexed posts."),
    ("dm_jewellers", "DM Jewellers", "Unspecified", "India", "Diamond bridal / statement", "Not in snippet", "Not found", "Instagram DM", "No", "", "DM for more details on diamond reels", "diamond, bridal, statement ring", "DM-first jeweller IG pattern", "DM automation, CRM", "https://www.google.com/maps/search/diamond%20jewellers%20India", "6", "Confirm showroom city from live bio."),
    ("hemant_jewellers_official", "Hemant Jewellers", "Kolhapur", "Maharashtra", "Traditional Maharashtrian gold jewellery", "+919022502704", "Not found", "WhatsApp order (caption)", "No", "", "Kolhapur traditional jewellery; WhatsApp on posts", "Kolhapur, bor mala, WhatsApp", "Regional gold SMB with WA", "WA catalog, logistics", "https://www.google.com/maps/search/Hemant%20Jewellers%20Kolhapur", "8", "Strong WhatsApp signal in indexed caption."),
    ("ashabanglesofficial", "Asha Bangles (bridal chura/chooda)", "Patiala", "Punjab", "Bridal bangles / chura", "+917014592741", "Not found", "WhatsApp to order (posts)", "No", "", "Punjabi bridal chura; WhatsApp ordering copy", "chura, chooda, bridal bangles", "WhatsApp-led bridal accessory SMB", "WA automation, COD tooling", "https://www.google.com/maps/search/bridal%20chura%20Patiala", "8", "Partial COD mentioned in indexed posts; verify policy."),
    ("krishna.pearls.hyderabad", "Krishna Pearls (Hyderabad pearls line)", "Hyderabad", "Telangana", "Pearl / gold bangles", "+918499011111", "Not found", "Call / WhatsApp / video call + DM", "No", "", "Indexed post: call/WhatsApp/video; DM for details; Jubilee Hills/Kokapet stores", "pearls, Hyderabad, gold bangles", "Multi-channel pearl retailer", "WA booking, video consult stack", "https://www.google.com/maps/search/Krishna%20Pearls%20Hyderabad", "7", "Multi-handle Krishna group; this is pearls-focused IG."),
]


def fmt_block(i: int, t: tuple) -> str:
    handle, name, city, state, btype, wa, email, ordering, wyn, wurl, bio, kw, reason, services, maps, score, notes = t
    ig = f"@{handle}"
    ig_url = f"https://www.instagram.com/{handle}/"
    return textwrap.dedent(
        f"""
        ==================================================
        LEAD #{i}
        ==================================================
        Business Name: {name}
        Instagram Handle: {ig}
        Instagram URL: {ig_url}
        Followers Count: Not verified (requires Instagram profile access)
        City: {city}
        State: {state}
        Business Type: {btype}
        WhatsApp Number: {wa}
        Email: {email}
        Ordering Method: {ordering}
        Website Present: {wyn}
        Website URL: {wurl}
        Recent Activity Date: Not verified (requires Instagram profile access)
        Average Engagement: Not verified (requires Instagram analytics)
        Bio Text: {bio}
        Keywords: {kw}
        Reason Qualified: {reason}
        Potential Services Needed: {services}
        Google Maps Link: {maps}
        Lead Quality Score: {score}/10
        Notes: {notes}
        """
    ).lstrip("\n")


def main() -> None:
    out_path = Path("/workspace/india_jewellery_instagram_leads.txt")
    header = textwrap.dedent(
        """
        ================================================================================
        INDIA JEWELLERY — INSTAGRAM / WHATSAPP / DM LEADS (AUTO-GENERATED)
        ================================================================================
        Generated: 2026-05-24
        Source: Public web-search snippets + indexed Instagram captions (no private scraping).
        IMPORTANT:
        - Each row is tied to a real Instagram handle found via public search indexing; phones/DM flows come from
          those indexed snippets and should be re-validated before outreach.
        - A small number of rows are labeled contrast/benchmark accounts (Website Present: Yes / larger retailers).
        - Follower counts, engagement, and “last post” dates are NOT reliable without Instagram API or manual checks.
        - Phone numbers and websites can change; validate before outreach.
        - Deduplication: Instagram handles are unique in this file; WhatsApp numbers are mostly unique but some
          businesses operate multi-number networks—treat as related until proven separate.
        ================================================================================

        """
    ).lstrip("\n")

    if len(LEADS) != 100:
        raise SystemExit(f"Expected 100 leads, got {len(LEADS)}")

    parts = [header]
    for idx, tup in enumerate(LEADS, start=1):
        parts.append(fmt_block(idx, tup))
        parts.append("\n")

    out_path.write_text("".join(parts).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(LEADS)} leads)")


if __name__ == "__main__":
    main()
