#!/usr/bin/env python3
"""Generate india_jewellery_instagram_leads.txt with 100 unique Instagram-based leads.

Data compiled from public web search snippets and limited Instagram page fetches
(May 2026). Some fields require manual verification on Instagram (followers,
exact bio, last post date).
"""

from __future__ import annotations

import textwrap
from pathlib import Path

# Each tuple: (handle, business_name, city, state, business_type, whatsapp, email,
# ordering_method, website_present, website_url, recent_activity, engagement_note,
# bio_text, keywords_csv, reason, services_csv, maps_link, score, notes)
LEADS: list[tuple[str, ...]] = [
    ("poddarjewels", "Poddar Jewels", "Delhi", "Delhi", "Artificial / Kundan / Polki", "+919899134124", "", "WhatsApp (wholesale/retail caption)", "No", "", "Verify on profile", "Caption-led ordering", "Premium budget-friendly kundan/polki sets; wholesale enquiries via WhatsApp", "kundan,polki,choker,bridal", "WhatsApp number in posts; strong bridal keywords", "WhatsApp automation, ecommerce, CRM", "", "8", "Public posts show WhatsApp ordering."),
    ("s.swarnakarandson", "S. Swarnakar And-Son", "Kolkata", "West Bengal", "Gold / traditional showroom + IG", "+918981948452", "", "Phone / booking numbers in posts", "No", "", "Verify on profile", "Local showroom engagement", "Kolkata Chetla area; hallmarked gold and silver collections", "kolkata,gold,bridal", "Kolkata-local SMB active on Instagram", "Website, WhatsApp booking system", "https://www.google.com/maps/search/S.+Swarnakar+And+Son+Kolkata", "7", "Also lists alternate booking numbers in posts."),
    ("bjs2k", "Biswakarma Jewellery Shilpaya", "Barasat", "West Bengal", "Diamond nosepins / fine jewellery", "+919874085669", "", "WhatsApp + online delivery captions", "No", "", "Verify on profile", "WhatsApp-led inquiries", "Barasat showroom; captions push WhatsApp for details/orders", "diamond,nosepin,whatsapp", "Explicit WhatsApp CTAs and local showroom", "WhatsApp automation, local SEO, CRM", "https://www.google.com/maps/search/Biswakarma+Jewellery+Shilpaya+Barasat", "8", "Multiple posts reference WhatsApp and Barasat/Kolkata region."),
    ("_jewellery_palace_bjs", "Jewellery Palace (BJS)", "Unknown", "India", "Artificial / silver pieces", "+918440038551", "", "WhatsApp order with product code", "No", "", "Verify on profile", "Screenshot-to-order pattern", "Posts show 'order on WhatsApp' with numeric codes", "whatsapp,code,silver", "Clear WhatsApp ordering workflow in captions", "WhatsApp catalog automation, ecommerce", "", "7", "City not stated in indexed snippet."),
    ("flabelcreations", "Flabel Creations", "India", "India", "Imitation / diamond-look jewellery", "+917711990044", "", "WhatsApp + DM (caption)", "No", "", "Verify on profile", "Same-day dispatch messaging", "Diamond-look necklace sets; free shipping claims in snippet", "dm,whatsapp,shipping", "WhatsApp + DM ordering; fast dispatch claim", "Instagram shop integration, CRM", "", "8", "Snippet referenced link-in-bio style WhatsApp."),
    ("i_imitation_jewellery", "I Imitation Jewellery", "India", "India", "Imitation jewellery", "", "", "DM for order", "No", "", "Verify on profile", "Low comment threads in index", "Necklace and bangle sets; explicit DM-for-order CTA", "imitation,dm,necklace", "Strong fit: DM-only ordering language", "Ecommerce, DM automation", "", "7", "No public phone in indexed snippet."),
    ("southindian__templejewellery", "South Indian Temple Jewellery", "Chennai", "Tamil Nadu", "Temple / matt finish jewellery", "+917904076978", "", "DM or WhatsApp (two numbers in post)", "No", "", "Verify on profile", "WhatsApp group link in post", "South India temple collections; UPI/GPay style payment notes", "temple,southindian,chennai", "Temple niche + WhatsApp/DM + group community", "WhatsApp CRM, community groups, ecommerce", "", "8", "Also references second number +91 8610765751 in indexed post."),
    ("bcos_its_silver", "Because It's Silver (Bcos Its Silver)", "Hyderabad", "Telangana", "925 silver / guttapusalu", "", "", "DM / visit-oriented posts", "Unclear", "", "Verify on profile", "Premium silver positioning", "Hyderabad pearls hashtags; high-ticket silver sets in snippets", "hyderabad,silver,guttapusalu", "Hyderabad silver specialty; likely showroom-led", "Ecommerce, appointment booking", "https://www.google.com/maps/search/silver+jewellery+Hyderabad", "6", "Verify whether separate ecommerce site exists."),
    ("jaipur_jewellary_damoh", "Jaipur Jewellery Damoh", "Damoh", "Madhya Pradesh", "Fashion / designer earrings", "", "", "DM / local pickup implied", "No", "", "Verify on profile", "Reels engagement varies", "Bundabahu complex location referenced in reel text", "jaipur,fashion,earrings", "Small-city retail with Instagram promo", "Website, online payments", "https://www.google.com/maps/search/Bundabahu+complex+Damoh+jewellery", "6", "Name references Jaipur branding; verify exact legal business name."),
    ("vernika.silver.jewellery", "Vernika Silver / Sri Lakshmi Venkateshwara Jewellers", "Bengaluru", "Karnataka", "925 silver", "+917406810666", "", "Call / WhatsApp for bookings (caption)", "No", "", "Verify on profile", "Video call shopping mentioned", "Chickpet / Avenue Road locations referenced in reel", "925silver,bengaluru,chickpet", "Strong omnichannel: IG + phone + physical shops", "WhatsApp automation, ecommerce", "https://www.google.com/maps/search/Avenue+Road+Bengaluru+silver+jewellery", "7", "Physical stores present; still IG-led discovery."),
    ("krishna.house.of.silver", "Krishna House of Silver (Silver Artifacts)", "Hyderabad", "Telangana", "925 silver articles / temple silver", "+918499011111", "", "Call / WhatsApp / video call + DM", "No", "", "Verify on profile", "Multi-account Krishna ecosystem", "Jubilee Hills store references; wa.link in posts", "silver925,temple,hyderabad", "Enterprise-adjacent but IG posts still DM/WhatsApp heavy", "WhatsApp deep links, CRM", "https://www.google.com/maps/search/Krishna+House+of+Silver+Jubilee+Hills", "6", "Related luxury brand accounts exist; verify SMB fit."),
    ("silver_palace45", "Silver Palace 45", "India", "India", "Silver jewellery", "", "", "Verify DM/WhatsApp in bio", "No", "", "Verify on profile", "Snippet limited", "Low-comment indexed post; needs profile review", "silver", "Handle discovered via search index", "Profile audit recommended", "", "5", "Sparse public data; verify activity before outreach."),
    ("lakshmi_creations_9", "Lakshmi Creations (Imitation)", "Surat", "Gujarat", "Imitation / wholesale", "+919849567353", "", "WhatsApp for orders/collections", "No", "", "Verify on profile", "Wholesale-oriented captions", "Wholesale pricing language in indexed posts", "surat,wholesale,jhumka", "WhatsApp-first wholesale imitation seller", "B2B portal, WhatsApp catalog", "https://www.google.com/maps/search/imitation+jewellery+Surat", "8", "Surat wholesale cluster fit."),
    ("varudijewellers", "Varudi Jeweller", "Surat", "Gujarat", "Gold certified jewellery (DM instant buy)", "", "", "DM instant buy (caption)", "No", "", "Verify on profile", "DM-led purchase messaging", "BIS gold messaging in snippet; 'just DM us' tone", "surat,gold,dm", "DM commerce without site in snippet", "Ecommerce + trust/compliance pages", "https://www.google.com/maps/search/Varudi+Jeweller+Surat", "7", "Verify if physical shop is primary channel."),
    ("sujatha_gold_covering_works", "Sujatha Gold Covering Works", "Machilipatnam", "Andhra Pradesh", "Micro gold plated / AD replica", "+917386222208", "", "WhatsApp (+ alternates in posts)", "No", "", "Verify on profile", "COD mentioned in posts", "Multiple WhatsApp lines for retail/bulk; COD claims", "ad,microgold,cod", "High-intent WhatsApp + COD combo", "CRM, inventory, fraud controls", "https://www.google.com/maps/search/Machilipatnam+jewellery", "8", "Also lists additional numbers in same post family."),
    ("vari_artificials_jewellery", "Vari Artificial Jewellery by Ritu Soni", "India", "India", "Temple bangles / gold-tone artificial", "+918769988299", "", "DM or call/WhatsApp", "No", "", "Verify on profile", "Same-day local delivery claim", "Temple jewellery bangle pair pricing in caption", "temple,bangles,dm", "DM + phone + local delivery promise", "Hyperlocal logistics integration", "", "8", "Second contact +919461488299 appears in indexed post."),
    ("rajputi_jewelery_wholsaler_s.c", "Rajputi Jewellery Wholesaler", "India", "India", "Rajputi / wholesale sets", "+917877634674", "", "WhatsApp + group link", "No", "", "Verify on profile", "Group selling motion", "Very low price language; WhatsApp group growth", "rajputi,wholesale,whatsapp", "WhatsApp group + wholesale SMB pattern", "WhatsApp community tooling", "", "7", "Spelling variants in handle; verify brand stability."),
    ("chezian_velli_maaligai", "Chezhiyan Velli Maaligai", "Chennai", "Tamil Nadu", "925 silver / laser name rings", "+917010078402", "", "DM or WhatsApp", "No", "", "Verify on profile", "Customization emphasis", "Customized silver wedding rings; bilingual CTAs", "silver925,custom,chennai", "Custom orders + WhatsApp/DM", "Product configurator, ecommerce", "https://www.google.com/maps/search/Chezhiyan+Velli+Maaligai+Chennai", "8", "Strong custom-order signal."),
    ("cenorajewels", "Cenora Jewels", "India", "India", "Fashion jewellery", "+917021923226", "", "DM to order / WhatsApp", "No", "", "Verify on profile", "Offer-style captions", "Buy 1 get 1 style promo language in index", "dm,offer,fashion", "Promo-led DM commerce", "Promo automation, CRM", "", "7", "City not confirmed in snippet."),
    ("wear_nd_shine_jewelry", "Wear N Shine Jewelry", "India", "India", "Fashion jewellery", "", "", "Verify ordering channel", "No", "", "Verify on profile", "Indexed post low data", "Discovered via search index comments", "fashion", "Needs profile confirmation", "Audit first", "", "5", "Minimal indexed evidence."),
    ("indranibiswas_", "Indrani's Collection", "Kolkata", "West Bengal", "Handmade clay / oxidised", "", "", "DM to buy", "No", "", "Verify on profile", "Reels + small business tags", "Clay chokers; customization notes", "clay,handmade,kolkata", "Creator-led jewellery SMB", "Branded site, subscriptions", "", "8", "Strong Kolkata + handmade signals."),
    ("gobindjewellers", "Gobind Jewellers", "Durgapur", "West Bengal", "Gold / traditional", "+919593222111", "", "Call / visit + Instagram promos", "No", "", "Verify on profile", "Local market shop", "Chandidas Market address in captions", "gold,durgapur,bridal", "Local jeweller using IG for reach", "Website + inventory", "https://www.google.com/maps/search/Gobind+Jewellers+Durgapur", "6", "Physical store first; verify IG-only sales."),
    ("goharjewelsofficial", "Gohar Jewels", "India", "India", "Handmade resin jhumkas", "", "", "DM / WhatsApp likely", "No", "", "Verify on profile", "Custom resin niche", "Pressed flower resin jhumkas in indexed description", "resin,handmade,jhumka", "Niche handmade; Instagram-native", "Ecommerce, international shipping pages", "", "7", "Verify contact in bio."),
    ("indukurisjewel", "Jewel Indukuri's", "Hyderabad", "Telangana", "Lab-grown diamond / custom", "+916302720676", "", "WhatsApp for details", "Unclear", "", "Verify on profile", "Customization language", "Custom pendant + chain options in caption", "labgrown,custom,hyderabad", "WhatsApp-led customization", "CRM, 3D visualization", "https://www.google.com/maps/search/Hyderabad+jewellery+labgrown", "7", "Higher ticket; still SMB-style WhatsApp."),
    ("aakankshajewellery", "Aakanksha Jewellery", "Mumbai", "Maharashtra", "Maharashtrian bridal / moti", "+919324512333", "", "WhatsApp for details", "No", "", "Verify on profile", "Bridal niche", "Maharashtrian bride sets; WhatsApp in caption", "bridal,maharashtra,whatsapp", "WhatsApp-first bridal niche", "Content + DM automation", "https://www.google.com/maps/search/Mumbai+Maharashtrian+jewellery", "8", "Strong regional bridal positioning."),
    ("chudiwale_", "Chudiwale Fashion Jewellery", "India", "India", "Custom bangles / bridal bangles", "+917972380643", "", "WhatsApp booking", "No", "", "Verify on profile", "Customization CTA", "Velvet bangle customization language", "bangles,custom,bridal", "Custom orders via WhatsApp", "Configurator, CRM", "", "8", "Good services upsell candidate."),
    ("ashabanglesofficial", "Asha Bangles / Punjabi Bridal Chura", "Patiala", "Punjab", "Bridal chura / bangles", "+917014592741", "", "WhatsApp", "No", "", "Verify on profile", "Long-running brand cues in caption", "Partial COD claims; customization available", "chura,punjabi,whatsapp", "WhatsApp + customization + COD options", "WhatsApp flows, logistics", "https://www.google.com/maps/search/Patiala+bridal+chura", "8", "Multi-city hashtags; HQ verify."),
    ("khushbu_jewellers_tinwari", "Khushbu Jewellers (Tinwari)", "India", "India", "Silver / gold-polish fashion", "+919929595357", "", "WhatsApp screenshot ordering", "Unclear", "", "Verify on profile", "High-volume posting pattern", "COD + screenshot-to-order language across reels", "silver,cod,whatsapp", "Screenshot ordering is automation-ready", "WhatsApp commerce automation", "", "8", "Family network uses multiple handles; dedupe carefully."),
    ("thoselittleblinggss", "Those Little Bling", "India", "India", "Moissanite / oxidised fashion", "", "", "DM to order", "No", "", "Verify on profile", "Free shipping DM offers", "German silver sets; DM ordering in captions", "moissanite,oxidised,dm", "Pure DM commerce pattern", "Instagram checkout, ecommerce", "", "8", "No public phone in indexed moissanite posts."),
    ("jewelsofkarnataka", "Jewels of Karnataka", "Karnataka", "Karnataka", "One-gram gold fashion", "+919740234813", "", "WhatsApp", "No", "", "Verify on profile", "Low ticket high volume", "One gram gold earrings; free shipping language", "onegramgold,karnataka", "WhatsApp-first low ticket model", "Catalog automation", "", "8", "Good fit for WhatsApp catalog."),
    ("silver.attractions", "Silver Attractions", "India", "India", "Silver jewellery", "", "", "DM price inquiries", "No", "", "Verify on profile", "Commenters ask price", "Typical IG silver seller comment pattern", "silver,price,dm", "Engagement shows DM price workflow", "DM automation", "", "6", "Limited snippet; verify bio."),
    ("naresh_choudhary916", "Naresh Choudhary Jewellery", "Ujjain", "Madhya Pradesh", "Gold-plated / short necklaces", "", "", "DM / WhatsApp (7024274632 referenced in ecosystem)", "No", "", "Verify on profile", "Devotional comment threads", "Often cross-linked with Sai Jewellers posts in index", "ujjain,goldplated", "Regional SMB cluster", "Unified WhatsApp line", "https://www.google.com/maps/search/Ujjain+jewellery", "6", "Phone dedupe with Sai Jewellers content."),
    ("begumbazar_wholesale_jewelry", "Begum Bazar Wholesale Jewelry", "Hyderabad", "Telangana", "One-gram / necksets wholesale", "+919618136342", "", "DM or WhatsApp screenshot", "No", "", "Verify on profile", "Screenshot ordering instructions", "Screenshot + DM/WhatsApp workflow; no COD note", "begumbazar,wholesale,onegram", "Classic wholesale IG playbook", "B2B portal, payments", "https://www.google.com/maps/search/Begum+Bazar+jewellery+Hyderabad", "8", "Wholesale minimums may apply."),
    ("janvish_onegramgold_and_boutiq", "Janvish One Gram Gold & Boutique", "India", "India", "One-gram gold + boutique", "+918121769801", "", "WhatsApp screenshot + groups", "No", "", "Verify on profile", "WhatsApp group updates", "Free shipping + WhatsApp group for updates", "onegramgold,boutique", "Group + WhatsApp commerce", "Community + CRM", "", "8", "Good automation candidate."),
    ("lucknow_artificial_jewellery_", "Lucknow Artificial Jewellery", "Lucknow", "Uttar Pradesh", "One-gram polish / imitation", "+918957754721", "", "WhatsApp booking", "No", "", "Verify on profile", "COD mentioned", "COD available + India shipping claims", "lucknow,cod,onegram", "City-specific SMB with COD", "Ecommerce + payments risk tooling", "https://www.google.com/maps/search/Lucknow+artificial+jewellery", "8", "Strong COD signal."),
    ("sai_jewellers_rajat_ujjain", "Sai Jewellers Rajat", "Ujjain", "Madhya Pradesh", "Gold-plated chains / short necklaces", "+917024274632", "", "WhatsApp / DM", "No", "", "Verify on profile", "Regional devotional reels", "Madhya Pradesh location references in comments", "ujjain,goldplated,whatsapp", "WhatsApp-first regional seller", "Unified catalog", "https://www.google.com/maps/search/Ujjain+jewellery+Sai", "7", "Verify overlap with other local pages."),
    ("rajaveer_imitation_ahemadabad", "Rajaveer Imitation Ahmedabad", "Ahmedabad", "Gujarat", "Imitation jewellery", "", "", "DM price / order", "No", "", "Verify on profile", "Gujarati comment engagement", "Imitation sets; price questions in comments", "ahmedabad,imitation", "Regional imitation seller", "WhatsApp price bot", "https://www.google.com/maps/search/Ahmedabad+imitation+jewellery", "7", "Good Ahmedabad cluster lead."),
    ("_nakshjewels_", "Naksh Jewels (Kochi collab)", "Kochi", "Kerala", "Silver diamond jewellery retail", "", "", "Visit / DM (verify)", "Unclear", "", "Verify on profile", "Influencer collab posts", "Featured in local city reel; verify ordering", "kochi,silver,diamond", "Retail discovery via local IG", "Local ads + booking", "https://www.google.com/maps/search/Rajaji+Road+Kochi+jewellery", "6", "Verify WhatsApp presence."),
    ("_amethyst__jewelz", "Amethyst Jewelz", "India", "India", "Fashion / crystal jewellery", "", "", "Verify DM", "No", "", "Verify on profile", "Low-data index", "Discovered via search index", "crystal,fashion", "Needs verification", "Audit", "", "5", "Sparse public data."),
    ("kpr_jewellery", "KPR Jewellery", "India", "India", "Unknown subtype", "", "", "Verify", "No", "", "Verify on profile", "Low-data index", "Discovered via search index", "jewellery", "Needs verification", "Audit", "", "5", "Sparse public data."),
    ("oxidised_jewellery_wholesaler", "Oxidised Jewellery Wholesaler", "India", "India", "Oxidised wholesale", "", "", "WhatsApp likely", "No", "", "Verify on profile", "Wholesale handle naming", "Handle implies wholesale oxidised inventory", "oxidised,wholesale", "Wholesale IG distributor pattern", "B2B portal", "", "6", "Verify location and MOQ."),
    ("rajputii_jewellery_", "Rajputii Jewellery", "India", "India", "Rajputi / traditional", "", "", "DM / comments", "No", "", "Verify on profile", "Devotional engagement posts", "Traditional aesthetic; comment-heavy posts", "rajputi,traditional", "Community-heavy SMB", "CRM + moderation tools", "", "6", "Verify WhatsApp in bio."),
    ("trend_jewelryys", "Trend Jewelryys", "India", "India", "Trend fashion jewellery", "", "", "Verify", "No", "", "Verify on profile", "Low-data index", "Discovered via search index", "trending", "Needs verification", "Audit", "", "5", "Sparse public data."),
    ("samskruthijewellers", "Samskruthi Jewellers", "Bengaluru", "Karnataka", "925 silver layered bridal necklace", "+918790112233", "", "WhatsApp", "No", "", "Verify on profile", "Bridal keywords", "Pearls + moissanite pendants; silver 925 focus", "925silver,bridal,bengaluru", "WhatsApp order on silver bridal SKU", "Ecommerce + CAD renders", "https://www.google.com/maps/search/Bengaluru+925+silver+jewellery", "8", "Strong WhatsApp CTA in indexed reel."),
    ("beautiful_creations0365", "Beautiful Creations 0365", "India", "India", "Kundan / moissanite / polki", "+919911283949", "", "DM or WhatsApp with picture", "No", "", "Verify on profile", "Long-running client claims", "No COD / no returns policy language; bank/UPI payments", "kundan,moissanite,polki", "Mature WhatsApp/DM sales process", "Policy pages, CRM, returns workflow", "", "9", "High score: explicit ops playbook in posts."),
    ("kundan_meena_by_sunar", "Kundan Meena by Sunar / Deendayal Soni", "Mumbai", "Maharashtra", "High-karat kundan meena", "+918078696056", "", "DM or call/WhatsApp", "No", "", "Verify on profile", "Luxury craft positioning", "18kt panch lada polki language in snippet", "kundanmeena,mumbai", "DM + WhatsApp for bespoke pieces", "Appointment booking, CRM", "https://www.google.com/maps/search/Mumbai+kundan+jewellery", "7", "Higher ticket; verify SMB vs atelier size."),
    ("swarnam_varnam", "Swarnam Varnam", "India", "India", "Jadau kundan sets", "", "", "DM price", "No", "", "Verify on profile", "Comment price requests", "Jadau kundan 3-lada style posts in index", "jadau,kundan", "Comment-driven selling motion", "DM automation", "", "6", "Limited contact in snippet."),
    ("finesilverjewels_rj", "Fine Silver Jewels", "Jaipur", "Rajasthan", "925 silver / kumud necklace", "+919829314701", "", "WhatsApp customization + shop mention", "Yes", "https://finesilverjewels.com/ (verify)", "Verify on profile", "Store appointment + online shop language", "Jaipur Bani Park appointments referenced", "jaipur,silver925,custom", "Has shop/web mentions; still WhatsApp heavy", "Shopify optimization, WhatsApp", "https://www.google.com/maps/search/Bani+Park+Jaipur+silver", "6", "Website likely exists; included because WhatsApp customization is strong."),
    ("elegant_fashion6095", "Elegant Fashion by Rupika", "India", "India", "Terracotta handmade earrings", "+919087319846", "", "DM or WhatsApp", "No", "", "Verify on profile", "Customization of colors", "Handmade terracotta; color customization", "terracotta,handmade", "Artisan SMB; dual DM/WhatsApp", "Ecommerce, studio booking", "", "8", "Cross-craft jewellery seller."),
    ("andmade_byhand", "AND-MADE by Hand", "India", "India", "Handmade earrings / accessories", "", "", "DM after live shopping", "No", "", "Verify on profile", "Live commerce motion", "Reel instructs DM with items after live", "handmade,live", "Live selling + DMs", "Live commerce tooling", "", "7", "Verify jewellery vs mixed accessories ratio."),
    ("ra_jewellers", "RA Jewellers", "India", "India", "Custom bridal sets", "", "", "DM custom orders", "No", "", "Verify on profile", "Custom matching outfit language", "Earrings/tika/jhoomer custom sets", "custom,bridal,dm", "Explicit custom design via DM", "3D design, CRM", "", "8", "Strong custom-order positioning."),
    ("_antique_jwellery", "Antique Jewellery by Ishwari", "Kolkata", "West Bengal", "Madhubani laah bangles / antique fashion", "", "", "DM orders", "No", "", "Verify on profile", "WB shipping note", "Madhubani-made bangles; DM for orders", "madhubani,bangles,kolkata", "Niche craft + DM", "Ecommerce storytelling", "https://www.google.com/maps/search/Kolkata+antique+jewellery", "7", "Cross-state craft story."),
    ("jewellery_by_lalitha", "Jewellery by Lalitha", "India", "India", "Lalitha imitation jewellery", "+917672044475", "", "Screenshot + DM or WhatsApp", "No", "", "Verify on profile", "Strict payment rules", "No COD; parcel video rules in caption", "imitation,paymentrules", "Operations-heavy SMB", "Policy automation + CRM", "", "8", "Good candidate for compliance tooling."),
    ("dreams.jewellery2023", "Dreams Jewellery 2023", "India", "India", "One-gram gold plated", "+919099003670", "", "WhatsApp price details", "No", "", "Verify on profile", "Worldwide shipping claims", "Online payment only; replacement policy language", "onegramgold,shipping", "WhatsApp-first with strict policies", "Checkout + support automation", "", "8", "Alternate number +919106503944 referenced in posts."),
    ("mmprincetrivandrum", "MM Prince Jewellery", "Thiruvananthapuram", "Kerala", "916 gold hipchains / custom lengths", "+918714145111", "", "Call / WhatsApp customize", "No", "", "Verify on profile", "Customization by length", "Free India delivery language", "gold,916,custom", "Custom sizing via phone", "Ecommerce size selectors", "https://www.google.com/maps/search/Thiruvananthapuram+jewellery", "7", "Gold-weight based SKUs."),
    ("dulhanjewels", "Dulhan Jewels", "India", "India", "One-gram gold watches / bridal accessories", "", "", "Message for inquiry", "No", "", "Verify on profile", "Reels-heavy brand tag", "South Indian bride hashtags in reels", "onegramgold,bridal,reels", "Reels-first product marketing", "Instagram ads + DM automation", "", "7", "Verify WhatsApp in bio."),
    ("dh_jewellers", "DH Silver and Gold", "India", "India", "Kids silver / gold-plated", "", "", "Verify", "No", "", "Verify on profile", "Kids niche reels", "Kids pochi / baby silver niche", "kids,silver", "Niche SKU Instagram seller", "Parent-focused ecommerce", "", "6", "Limited ordering data in snippet."),
    ("jodhpuri_silver", "Jodhpuri Silver", "Jodhpur", "Rajasthan", "Rajasthani silver fashion", "+919358839704", "", "WhatsApp screenshot ordering (Khushbu network posts)", "No", "", "Verify on profile", "Cross-posted catalogue style", "Silver payal posts indexed under this handle too", "silver,rajasthan,whatsapp", "Likely catalogue reseller network", "PIM + WhatsApp", "https://www.google.com/maps/search/Jodhpur+silver+jewellery", "7", "Verify independence from Khushbu network."),
    ("divi_jewellery", "DIVI Jewellery", "Mumbai", "Maharashtra", "One-gram gold look-alike", "+919174040704", "", "WhatsApp booking", "Unclear", "https://divijewl.com/ (possible related retail site)", "Verify on profile", "COD/prepaid pricing tiers", "COD surcharge pattern in captions", "onegramgold,mumbai,cod", "High-volume WhatsApp bookings", "WhatsApp CRM + payments", "https://www.google.com/maps/search/Mumbai+one+gram+gold+jewellery", "7", "Verify relationship to DiviJewl web retail."),
    ("riyas_artistry01", "Riya's Artistry / Riya Kumawat", "India", "India", "Clay miniatures / jewellery", "+919468654816", "", "DM + WhatsApp", "No", "", "Verify on profile", "Creator SMB", "Clay keychains; DM orders", "clay,handmade", "Creator commerce", "Ecommerce", "", "7", "Mixed jewellery + art products."),
    ("unique_jewelryys", "Unique Jewelryys", "India", "India", "Silver jewellery (Pooja Jewels branded reels)", "+917597344552", "", "WhatsApp + COD", "No", "", "Verify on profile", "COD available", "Silver payal / bracelets promos", "silver,cod,whatsapp", "COD + WhatsApp = logistics pain", "Ops automation", "", "8", "Branding overlap with 'Pooja Jewels' captions; verify store identity."),
    ("yuvraj_nosepins", "Yuvraj Nosepins", "Delhi", "Delhi", "Lightweight gold earrings / nosepins", "", "", "Visit Chandni Chowk + IG", "No", "", "Verify on profile", "Retail discovery", "Chandni Chowk shop references", "gold,chandnichowk", "Physical retail + IG", "Local inventory online", "https://www.google.com/maps/search/Kucha+Mahajani+Chandni+Chowk", "6", "Enterprise Pvt Ltd name appears; still local retail."),
    ("dreamsjewelleryandgifts", "Dreams Jewellery and Gifts", "India", "India", "One-gram / gifts", "", "", "Verify WhatsApp", "No", "", "Verify on profile", "Related brand reel", "Appears as adjacent Dreams brand reel", "onegram,gifts", "Sibling account to Dreams network", "Brand consolidation", "", "6", "May overlap with dreams.jewellery2023."),
    ("nikhiljewelleryhyderabad", "Nikhil Jewellery Hyderabad", "Hyderabad", "Telangana", "916 gold traditional", "", "", "Visit / DM (verify)", "No", "", "Verify on profile", "Physical store cues", "LB Nagar hashtags; gold locket reels", "916gold,hyderabad", "Store-led Instagram marketing", "O2O appointment booking", "https://www.google.com/maps/search/LB+Nagar+gold+jewellery", "6", "Larger gold retail; verify SMB positioning."),
    ("kalyani_jewellers_", "Kalyani Jewellers", "India", "India", "Gold-plated adjustable kada sets", "", "", "Link in bio + DM", "Unclear", "Link-in-bio commerce (verify)", "Verify on profile", "Shop via bio link", "Chowki diamond studded gold-plated kada promos", "goldplated,chowki,linkinbio", "Link-in-bio ordering; may be storefront", "Shopify/Meesho integration", "", "6", "Verify if off-IG checkout is professional site."),
    ("ar_gold_covering", "AR Gold Covering", "India", "India", "Gold-plated / thali / wedding rings", "+918606878555", "", "DM or WhatsApp; link-in-bio booking on some posts", "Unclear", "Posts mention website booking + link in bio (verify)", "Verify on profile", "Gold-covering wholesaler tone", "Custom thali/name pendants; DM/WhatsApp in reels", "goldplated,thali,whatsapp", "Strong WhatsApp + DM with catalogue-style posts", "WhatsApp automation, ecommerce", "", "8", "Some posts advertise website booking; still IG-first discovery."),
    ("navkar_boutique", "Navkar Boutique", "Guntur", "Andhra Pradesh", "Silver chains / Victorian accessories", "+917989751387", "", "WhatsApp order", "No", "", "Verify on profile", "Uses Prathik Bhansali style promos", "Back chains and mossonite SKUs in reels", "victoriansilver,guntur", "Regional boutique WhatsApp commerce", "Inventory + WhatsApp", "https://www.google.com/maps/search/Guntur+boutique+jewellery", "7", "Verify brand vs individual seller."),
    ("prathibha_collections_", "Prathibha Collections", "India", "India", "Uncut/AD earrings", "", "", "DM / WhatsApp (verify)", "No", "", "Verify on profile", "Low price SKU reels", "Uncut hangings ₹720 style posts", "uncut,ad,earrings", "Value SKU Instagram seller", "WhatsApp catalog", "", "7", "Limited contact in snippet."),
    ("ahantisilver", "Ahanti by Pratima", "Mumbai", "Maharashtra", "Maharashtrian silver + gold polish", "+919920085102", "", "WhatsApp or DM enquiries", "No", "", "Verify on profile", "Care instructions heavy", "Thushi sets; no refund policy clarity", "silver,maharashtrian,mumbai", "Heritage niche + WhatsApp", "Education content + ecommerce", "https://www.google.com/maps/search/Mumbai+Maharashtrian+silver+jewellery", "8", "Strong cultural niche."),
    ("olddelhijewellers", "Old Delhi Jewellers", "Delhi", "Delhi", "Vintage / kundan art pieces", "", "", "DM for details", "No", "", "Verify on profile", "Collectible positioning", "Jade pendant kundan stringing story", "vintage,kundan,olddelhi", "DM-led high-trust sales", "Authentication docs, ecommerce", "https://www.google.com/maps/search/Old+Delhi+jewellers", "7", "Good story-led ecommerce candidate."),
    ("dishaarts_fashionjewellery", "Disha Arts Fashion Jewellery", "India", "India", "Kundan AD brass necklaces wholesale", "", "", "DM bulk (verify)", "No", "", "Verify on profile", "Bulk orders accepted language", "Multi-color AD kundan bases", "kundan,ad,wholesale", "Bulk wholesale via IG", "B2B quoting tool", "", "7", "Indexed post mentions bulk."),
    ("shingaar_creations", "Shingaar Creations", "Ahmedabad", "Gujarat", "Pachi kundan / bridal sets", "", "", "DM / visit (verify)", "No", "", "Verify on profile", "Heavy bridal sets", "Ahmedabadi pachi kundan choker language", "pachi,kundan,ahmedabad", "Gujarat bridal craft niche", "Ecommerce lookbook", "https://www.google.com/maps/search/Ahmedabad+pachi+kundan", "7", "Verify WhatsApp presence."),
    ("savic_jewellery", "Savic Jewellery by KTJ", "India", "India", "Imitation kundan halo necklaces", "", "", "DM (verify)", "No", "", "Verify on profile", "Brand-style posts", "Royal radiance kundan marketing", "imitation,kundan", "Brand-building SMB", "Paid ads + site", "", "6", "Verify checkout channel."),
    ("swapna_jewels", "Swapna Jewels", "India", "India", "Jadau kundan sets", "", "", "DM price", "No", "", "Verify on profile", "Comment-driven pricing", "3-lada jadau posts in index", "jadau,kundan", "DM commerce", "Catalog + CRM", "", "6", "Limited public contact."),
    ("talkwithart_byrach", "Talk With Art by Rach", "India", "India", "Resin rose jewellery", "", "", "DM for orders/prices", "No", "", "Verify on profile", "Customization available", "Custom resin pendants; DM ordering", "resin,custom,dm", "Creator-led resin niche", "Ecommerce bundles", "", "7", "Seasonal gifting angle."),
    ("khushbujewellers.com_", "Khushbu Jewellers (Dot Com Account)", "India", "India", "Silver sindoor boxes / bridal silver", "+918233445357", "", "WhatsApp screenshot ordering", "Unclear", "Posts mention website order discounts", "Verify on profile", "COD + website upsell mentions", "Screenshot ordering with website cross-sell language", "silver,cod,whatsapp", "Hybrid IG + web promos", "Unify omnichannel", "", "7", "May conflict with 'no website' ideal; still SMB."),
    ("jewellery_shopper_", "Jewellery Shopper", "India", "India", "Silver idols / silver fashion", "+918905291031", "", "WhatsApp screenshot ordering", "No", "", "Verify on profile", "COD language", "Radha Krishna ring reels etc.", "silver,cod", "Screenshot ordering model", "WhatsApp automation", "", "7", "Also uses other numbers in some posts; keep unique primary."),
    ("poojajewels_", "Silver Jewellery by Pooja Jewels", "India", "India", "Silver bracelets / premium silver", "+919993284004", "", "WhatsApp (Threads snippet)", "No", "", "Verify on profile", "Threads cross-post", "Multiple WhatsApp lines appear across Threads/IG", "silver,premium", "Threads indicates active WhatsApp selling", "Omnichannel inbox", "", "7", "Cross-check number vs unique_jewelryys network."),
    ("panashejewellery", "Panashe Jewellery", "India", "India", "Silver / fine silver comments niche", "", "", "Verify", "No", "", "Verify on profile", "Comment engagement on fine silver reels", "Appeared in public comment threads on premium silver reels (bio not fully captured in index).", "silver,comments,instagram", "Discovered via indexed Instagram comment threads", "Profile audit + CRM", "", "5", "Minimal public bio data."),
    ("neenox_fashion", "Neenox Fashion", "Delhi", "Delhi", "Wholesale artificial Sadar Bazar", "", "", "Visit / DM (verify)", "No", "", "Verify on profile", "Ultra-low wholesale entry price promos", "Sadar Bazar wholesale positioning", "sadar,wholesale,artificial", "Offline wholesale + IG lead gen", "B2B lead forms", "https://www.google.com/maps/search/Sadar+Bazar+Delhi+jewellery+wholesale", "7", "Verify MOQ and contact."),
    ("wholesalepearlsjewells.onkar", "Pearls & Jewells Design Studio (Onkar India)", "India", "India", "Fashion jewellery manufacturing", "+919996698633", "", "DM for catalog", "No", "", "Verify on profile", "Manufacturer SEO spam captions", "DM for full catalog CTA", "manufacturer,wholesale,catalog", "B2B manufacturer lead gen via IG", "B2B portal + CRM", "", "7", "Heavy caption keyword stuffing; still SMB signal."),
    ("tyohaarsilverjewellery", "Tyohaar Silver Jewellery", "Hyderabad", "Telangana", "Large format silver retail", "", "", "Visit + IG", "Unclear", "", "Verify on profile", "Showroom marketing", "Jubilee Hills exclusive silver store language", "silver,hyderabad,jubileehills", "Retail-first with IG", "O2O appointments", "https://www.google.com/maps/search/Tyohaar+Silver+Jewellery+Hyderabad", "6", "Largest store claims; verify SMB vs chain."),
    ("mmsilverpalacetenali", "MM Silver Palace Tenali", "Tenali", "Andhra Pradesh", "925 silver wholesale / gifts", "", "", "DM price / visit", "No", "", "Verify on profile", "Wholesale hashtags", "Hyderabad wholesale mentions in captions", "925silver,wholesale,tenali", "Wholesale silver + IG discovery", "B2B quoting", "https://www.google.com/maps/search/Tenali+silver+jewellery", "7", "Verify WhatsApp in bio."),
    ("wholesalekundanjewelery", "IDK Wholesale Kundan Jewellery", "Chandigarh", "India", "Polki / wholesale kundan", "", "", "DM / wholesale (verify)", "No", "", "Verify on profile", "Wedding aesthetic reels", "Polki bridal set storytelling", "polki,wholesale,chandigarh", "Wholesale-style IG brand", "Catalog + CRM", "", "6", "Location inferred from hashtags; verify."),
    ("mangalmanijewellers", "Mangalmani Jewellers", "Mumbai", "Maharashtra", "Imitation polki payal / exporter", "+919867596599", "", "DM/Text/Call/WhatsApp/FaceTime", "Yes", "http://www.mangalmanijewellers.com/", "Verify on profile", "Exporter MOQ language", "Large stock + video call sales; USD MOQ", "exporter,polki,mumbai", "Exporter SMB (not tiny retail)", "B2B portal, ERP", "https://www.google.com/maps/search/Mangalmani+Jewellers+Mumbai", "5", "Has professional site; included as borderline exporter SMB."),
    ("bhartijewellersofficial", "Bharti Jewellers", "India", "India", "Bridal polki / luxury sets", "", "", "DM (verify)", "Unclear", "", "Verify on profile", "Luxury bridal creative", "Emerald polki bridal language", "polki,bridal,luxury", "Premium bridal marketing", "Lookbooks + appointments", "", "5", "May be larger; verify before SMB pitch."),
    ("silvermantraindia", "Silver Mantra India", "India", "India", "925 oxidised / gemstone earrings", "", "", "DM to place order (caption)", "No", "", "Verify on profile", "Handmade + wholesaler hashtags", "Rose quartz oxidised earrings; DM order CTA", "925silver,oxidised,gemstone", "DM-first handmade SKU pattern", "Ecommerce + DM automation", "", "7", "Handle confirmed via Instagram 'more posts' link on public post page."),
    ("jewels_and_you_", "Jewels And You", "India", "India", "Handmade oxidised earrings", "", "", "DM (typical for this account type)", "No", "", "Verify on profile", "Comment price requests", "Tags raw material supplier @_jewellery_raw_material in posts", "oxidised,handmade,earrings", "Creator-style oxidised drops", "Catalog + supplier integrations", "", "7", "Handle confirmed via Instagram 'more posts' link on public post page."),
    ("rajesh_silver_jewellery", "Rajesh Silver Jewellery / Rajesh Jewels", "India", "India", "925 oxidised silver studs", "", "", "DM or website (caption)", "Yes", "https://www.rajeshjewels.com/", "Verify on profile", "Website + DM hybrid", "Posts mention website OR DM ordering", "925silver,oxidised,studs", "Hybrid commerce; still SMB-feel in snippet", "Shopify optimization + WhatsApp", "", "6", "Website present; included due to strong DM path in indexed caption."),
    ("rajlakshmijewellersdgp", "Rajlakshmi Jewellers (Durgapur)", "Durgapur", "West Bengal", "Gold / silver showroom + IG", "+918653002140", "", "Call / visit + Instagram promos", "No", "", "Verify on profile", "Multi-branch phone numbers in posts", "Durgapur/Bardhaman area delivery language in captions", "gold,durgapur,showroom", "Regional chain-like SMB with IG promos", "O2O + CRM", "https://www.google.com/maps/search/Rajlakshmi+Jewellers+Durgapur", "5", "Larger than micro-SMB; verify fit vs enterprise criteria."),
    ("_jewellery_raw_material", "Jewellery Raw Material", "India", "India", "Jewellery components / raw materials", "", "", "DM (verify)", "No", "", "Verify on profile", "Supplier to creators", "Tagged by handmade sellers as material source", "rawmaterials,supply,wholesale", "B2B supplier adjacent to D2C creators", "B2B portal + invoicing", "", "6", "Not finished jewellery only; still jewellery-industry lead."),
    ("blingaffair", "Bling Affair", "India", "India", "Fashion / party jewellery", "", "", "Verify DM/WhatsApp in bio", "No", "", "Verify on profile", "Public profile exists", "Handle resolves on Instagram (public title)", "fashion,party", "Likely IG-native fashion jewellery seller", "Ecommerce + ads", "", "5", "Minimal indexed ops detail; verify ordering workflow."),
    ("chidambaramgoldcovering", "Chidambaram Gold Covering", "Chidambaram", "Tamil Nadu", "Gold-plated fashion / COD models", "+919500019491", "", "WhatsApp order + COD delivery", "Yes", "Handle references ChidambaramGoldCovering.com in indexed title", "Verify on profile", "COD + model codes", "WhatsApp wa.me links in indexed posts", "goldplated,cod,tamilnadu", "COD + WhatsApp ordering combo", "WhatsApp automation + COD reconciliation", "https://www.google.com/maps/search/Chidambaram+jewellery", "8", "Second WhatsApp line +918438114505 referenced in indexed post."),
    ("thebaublelove", "The Bauble Love", "India", "India", "Fashion / bauble jewellery", "", "", "Verify", "No", "", "Verify on profile", "Public profile exists", "Instagram handle resolves (minimal public metadata)", "bauble,fashion", "Potential IG-first brand", "Ecommerce", "", "5", "Sparse ops detail in automation fetch; verify."),
    ("zola_jewels", "Zola Jewels", "India", "India", "Fashion jewellery", "", "", "Verify", "No", "", "Verify on profile", "Public profile exists", "Instagram handle resolves (minimal public metadata)", "fashion", "Potential IG-first seller", "Ecommerce", "", "5", "Sparse ops detail; verify."),
    ("anayahjewellery", "Anayah Jewellery", "India", "India", "Fashion / fine (verify)", "", "", "Verify", "No", "", "Verify on profile", "Public profile exists", "Instagram handle resolves (minimal public metadata)", "fashion", "Potential IG-first seller", "Ecommerce", "", "5", "Sparse ops detail; verify."),
    ("rubansaccessories", "Rubans Accessories", "India", "India", "Fashion jewellery / accessories", "", "", "Verify", "Unclear", "May have external commerce (verify)", "Verify on profile", "Large catalog brand risk", "Well-known Indian accessories brand presence on IG", "fashion,accessories", "Could be larger brand; verify SMB pitch fit", "Enterprise integrations if large", "", "4", "Likely larger; keep only if SMB positioning confirmed."),
    ("priyaasi", "Priyaasi", "India", "India", "Bengali/ethnic fashion jewellery (verify)", "", "", "Verify", "Unclear", "", "Verify on profile", "Public profile exists", "Bengali title text in public profile metadata", "ethnic,fashion", "Potential regional brand", "Ecommerce + content", "", "5", "Verify WhatsApp/DM ordering and business size."),
    ("adornculture", "Adorn Culture", "India", "India", "Fashion jewellery (verify)", "", "", "Verify", "No", "", "Verify on profile", "Public profile exists", "Instagram handle resolves (public title)", "fashion", "Potential IG-first seller", "Influencer collabs", "", "5", "Sparse ops detail; verify."),
    ("blinggarden_", "Bling Garden", "India", "India", "Fashion jewellery (verify)", "", "", "Verify", "No", "", "Verify on profile", "Public profile exists", "Instagram handle resolves", "fashion", "Potential IG-first seller", "Ecommerce", "", "5", "Sparse ops detail; verify."),
]


def format_lead(idx: int, row: tuple[str, ...]) -> str:
    (
        handle,
        business,
        city,
        state,
        btype,
        wa,
        email,
        ordering,
        website_present,
        website_url,
        recent,
        engagement,
        bio,
        keywords,
        reason,
        services,
        maps,
        score,
        notes,
    ) = row

    ig = f"@{handle}"
    url = f"https://www.instagram.com/{handle}/"

    lines = [
        f"{'=' * 50}",
        f"LEAD #{idx}",
        f"{'=' * 50}",
        f"Business Name: {business}",
        f"Instagram Handle: {ig}",
        f"Instagram URL: {url}",
        "Followers Count: Not available from public index (verify in-app)",
        f"City: {city}",
        f"State: {state}",
        f"Business Type: {btype}",
        f"WhatsApp Number: {wa}",
        f"Email: {email}",
        f"Ordering Method: {ordering}",
        f"Website Present: {website_present}",
        f"Website URL: {website_url}",
        f"Recent Activity Date: {recent}",
        f"Average Engagement: {engagement}",
        f"Bio Text: {bio}",
        f"Keywords: {keywords}",
        f"Reason Qualified: {reason}",
        f"Potential Services Needed: {services}",
        f"Google Maps Link: {maps}",
        f"Lead Quality Score: {score}/10",
        f"Notes: {notes}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    handles = [row[0] for row in LEADS]
    if len(handles) != len(set(handles)):
        dupes = sorted({h for h in handles if handles.count(h) > 1})
        raise SystemExit(f"Duplicate handles: {dupes}")

    if len(LEADS) != 100:
        raise SystemExit(f"Expected 100 leads, got {len(LEADS)}")

    header = textwrap.dedent(
        f"""\
        ================================================================================
        INDIA JEWELLERY - INSTAGRAM / WHATSAPP / DM LEADS (PUBLIC WEB SNIPPETS)
        ================================================================================
        Generated: 2026-05-23
        Source method: Public web search snippets + limited Instagram HTML fetches
        IMPORTANT:
        - Treat phone numbers, websites, and activity dates as UNVERIFIED until checked on Instagram.
        - Several entries include 'verify' notes where the public index was sparse.
        - This file is meant as a starter prospecting list, not a fully audited CRM export.
        ================================================================================

        """
    )

    body = "".join(format_lead(i + 1, row) for i, row in enumerate(LEADS))
    Path("/workspace/india_jewellery_instagram_leads.txt").write_text(header + body, encoding="utf-8")


if __name__ == "__main__":
    main()
