#!/usr/bin/env python3
"""Generate india_jewellery_instagram_leads.txt from curated public-source snapshots."""
from __future__ import annotations

from pathlib import Path

# Each entry: unique Instagram handle; phone numbers normalized where known; no duplicate phones.
LEADS: list[dict[str, str]] = [
    {
        "business": "Biswakarma Jewellery Shilpaya",
        "handle": "bjs2k",
        "followers": "Verify on profile",
        "city": "Kolkata",
        "state": "West Bengal",
        "type": "Diamond / fine jewellery (earrings, nose pins)",
        "whatsapp": "+919874085669",
        "email": "Not listed in public posts",
        "ordering": "WhatsApp; captions promote WhatsApp for details/orders",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed posts reference WhatsApp-led sales (verify recency on profile)",
        "engagement": "Not extracted from SERP",
        "bio": "Kolkata-area jeweller; posts emphasise WhatsApp contact for collections",
        "keywords": "WhatsApp, diamond earrings, nose pin, Kolkata",
        "qualified": "Strong WhatsApp CTA; SMB Instagram storefront pattern",
        "services": "WhatsApp automation, lightweight catalog site, CRM for orders",
        "maps": "https://www.google.com/maps/search/Biswakarma+Jewellery+Shilpaya+Kolkata",
        "score": "8",
        "notes": "Public Instagram captions repeatedly list WhatsApp ordering.",
    },
    {
        "business": "Beautiful Creations (Indian Kundan / Moissanite)",
        "handle": "beautiful_creations0365",
        "followers": "Verify on profile",
        "city": "India (pan-India shipping; HQ not explicit in snippet)",
        "state": "—",
        "type": "Kundan / moissanite imitation & bridal sets",
        "whatsapp": "+919911283949",
        "email": "Not listed in public posts",
        "ordering": "DM or WhatsApp with product picture; online prepay",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reels/posts show booking flow (verify recency)",
        "engagement": "Posts cite large repeat client base (marketing claim)",
        "bio": "DM/WhatsApp booking; moissanite/kundan focus",
        "keywords": "DM to order, moissanite, kundan, bridal",
        "qualified": "Classic DM+WhatsApp order flow; no dedicated site in snippets",
        "services": "Ecommerce checkout, order management, WhatsApp API",
        "maps": "",
        "score": "9",
        "notes": "Caption pattern: send picture on WhatsApp for booking guidance.",
    },
    {
        "business": "Jewellery Palace BJS",
        "handle": "_jewellery_palace_bjs",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Fashion / bridal imitation pieces",
        "whatsapp": "+918440038551",
        "email": "Not listed",
        "ordering": "Order on WhatsApp (per post caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed product post with WhatsApp order line",
        "engagement": "Not extracted",
        "bio": "Product posts include WhatsApp order number",
        "keywords": "Order on WhatsApp, nath, code-based SKUs",
        "qualified": "Explicit WhatsApp ordering language",
        "services": "WhatsApp automation, SKU catalog microsite",
        "maps": "",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Jodhpuri Silver (Khushbu network branch)",
        "handle": "jodhpuri_silver",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Silver payal / traditional silver",
        "whatsapp": "+919358839704",
        "email": "Not listed",
        "ordering": "WhatsApp screenshot-to-order (per posts)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reels with order instructions",
        "engagement": "Not extracted",
        "bio": "Silver fashion jewellery; COD mentioned in some posts",
        "keywords": "Silver payal, COD, WhatsApp screenshot",
        "qualified": "Screenshot-order pattern fits Instagram-led SMB",
        "services": "WhatsApp commerce, payments link flow",
        "maps": "",
        "score": "7",
        "notes": "Distinct WhatsApp number from other Khushbu-line posts using 9929595357.",
    },
    {
        "business": "Jewellery Shopper",
        "handle": "jewellery_shopper_",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Silver / plated fashion jewellery",
        "whatsapp": "+918905291031",
        "email": "Not listed",
        "ordering": "WhatsApp screenshot for order (some posts reference website promos—treat as hybrid)",
        "website_yn": "Unclear",
        "website_url": "Posts mention website-order discounts; verify bio",
        "activity": "Indexed reels",
        "engagement": "Not extracted",
        "bio": "Screenshot WhatsApp ordering; promotional website mentions in captions",
        "keywords": "WhatsApp screenshot, silver, COD mentions",
        "qualified": "Strong WhatsApp-first ordering; verify website presence in bio before outreach",
        "services": "Unify web+WhatsApp funnel, discount messaging automation",
        "maps": "",
        "score": "6",
        "notes": "Primary contact taken from posts using +91 8905291031 to avoid duplicating +91 9929595357 used elsewhere.",
    },
    {
        "business": "Samskruthi Jewellers",
        "handle": "samskruthijewellers",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "925 silver bridal / layered necklaces",
        "whatsapp": "+918790112233",
        "email": "Not listed",
        "ordering": "WhatsApp to place order (caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel with WhatsApp CTA",
        "engagement": "Not extracted",
        "bio": "Silver bridal strings; international shipping references in niche posts",
        "keywords": "925 silver, pearls, WhatsApp order",
        "qualified": "Clear WhatsApp purchase path",
        "services": "Catalog site, international shipping calculator, CRM",
        "maps": "",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Khushbu Jewellers Tinwari",
        "handle": "khushbu_jewellers_tinwari",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Rajwadi silver / gold-polish fashion",
        "whatsapp": "+919929595357",
        "email": "Not listed",
        "ordering": "WhatsApp screenshot ordering; COD mentioned",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reels",
        "engagement": "Not extracted",
        "bio": "Customisation mentioned; WhatsApp-led",
        "keywords": "Custom orders, silver, COD, screenshot order",
        "qualified": "High-intent SMB; heavy WhatsApp ops",
        "services": "WhatsApp automation, returns/COD policy pages",
        "maps": "",
        "score": "9",
        "notes": "Canonical entry for +91 9929595357 (deduped against other pages reusing same number).",
    },
    {
        "business": "Chudiwale Fashion Jewellery",
        "handle": "chudiwale_",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Custom bangles / bridal bangles",
        "whatsapp": "+917972380643",
        "email": "Not listed",
        "ordering": "WhatsApp for booking & details",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed post",
        "engagement": "Not extracted",
        "bio": "Customised bangle sets; WhatsApp booking",
        "keywords": "Custom orders, bangles, bridal",
        "qualified": "Custom + WhatsApp = strong services upsell",
        "services": "Custom order forms, CRM, IG shopping setup",
        "maps": "",
        "score": "8",
        "notes": "",
    },
    {
        "business": "JJ Resin Memo (custom resin accessories)",
        "handle": "jj_resin.memo",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Resin personalised accessories (adjacent gifting)",
        "whatsapp": "+918489166598",
        "email": "Not listed",
        "ordering": "WhatsApp (caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed post",
        "engagement": "Not extracted",
        "bio": "Custom resin name pieces",
        "keywords": "Resin, custom, WhatsApp",
        "qualified": "SMB maker channel; less pure jewellery but strong WhatsApp custom workflow",
        "services": "WhatsApp chatbots for customization intake",
        "maps": "",
        "score": "6",
        "notes": "Include only if targeting adjacent custom-jewellery workflows.",
    },
    {
        "business": "Mahavir Imitation Jewellery",
        "handle": "mahavirimitationjewelle",
        "followers": "Verify on profile",
        "city": "Mumbai",
        "state": "Maharashtra",
        "type": "Imitation / oxidised bangles wholesale-retail",
        "whatsapp": "+918320499102",
        "email": "Not listed",
        "ordering": "Call/WhatsApp per caption",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed Navratri oxidised bangles post",
        "engagement": "Not extracted",
        "bio": "Wholesale-forward imitation jewellery",
        "keywords": "Imitation, oxidised, bangles, Mumbai",
        "qualified": "Phone-led ordering; SMB manufacturer vibe",
        "services": "B2B catalog, WhatsApp broadcast compliance tooling",
        "maps": "https://www.google.com/maps/search/Mahavir+imitation+jewellery+Mumbai",
        "score": "7",
        "notes": "",
    },
    {
        "business": "Lakshmi Creations Imitation Jewellery",
        "handle": "lakshmi_creations_9",
        "followers": "Verify on profile",
        "city": "Mumbai",
        "state": "Maharashtra",
        "type": "Imitation wholesale jhumkas / sets",
        "whatsapp": "+919849567353",
        "email": "Not listed",
        "ordering": "WhatsApp for orders & more collections",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed post",
        "engagement": "Not extracted",
        "bio": "Wholesale pricing language",
        "keywords": "Wholesale, jhumkas, imitation",
        "qualified": "WhatsApp wholesale enquiries",
        "services": "Wholesale portal, line-sheet automation",
        "maps": "",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Oxidised Jewellery Wholesaler",
        "handle": "oxidised_jewellery_wholesaler",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Oxidised / German silver wholesale",
        "whatsapp": "See profile / DM (number not in indexed snippet)",
        "email": "Not listed",
        "ordering": "Likely DM/WhatsApp wholesale pattern",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed catalogue posts",
        "engagement": "Not extracted",
        "bio": "Wholesale oxidised focus",
        "keywords": "Oxidised, wholesaler",
        "qualified": "Needs profile visit to capture WhatsApp; still IG-led distribution",
        "services": "B2B mini-site, WhatsApp catalog",
        "maps": "",
        "score": "6",
        "notes": "WhatsApp not in SERP snippet—verify on profile before outreach.",
    },
    {
        "business": "South Indian Temple Jewellery",
        "handle": "southindian__templejewellery",
        "followers": "Verify on profile",
        "city": "Chennai seller focus (per hashtags)",
        "state": "Tamil Nadu",
        "type": "Temple / matte finish imitation",
        "whatsapp": "+917904076978",
        "email": "Not listed",
        "ordering": "DM or WhatsApp; UPI prepay; WhatsApp group link in posts",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed post",
        "engagement": "Not extracted",
        "bio": "South Indian traditional sets; community group link",
        "keywords": "Temple jewellery, Chennai, DM, WhatsApp group",
        "qualified": "Dual DM+WhatsApp + community = automation opportunity",
        "services": "Community management, WhatsApp CRM, catalog",
        "maps": "",
        "score": "8",
        "notes": "Posts also list a second WhatsApp line +918610765751—confirm which inbox is primary before outreach.",
    },
    {
        "business": "Vari Artificial Jewellery by Ritu Soni",
        "handle": "vari_artificials_jewellery",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Temple bangles / artificial gold-tone",
        "whatsapp": "+918769988299",
        "email": "Not listed",
        "ordering": "DM or call numbers in caption",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed post",
        "engagement": "Not extracted",
        "bio": "Temple jewellery bangles; same-day local delivery language",
        "keywords": "Temple, artificial, DM",
        "qualified": "DM + phone hybrid SMB",
        "services": "WhatsApp routing from DM, local delivery landing page",
        "maps": "",
        "score": "7",
        "notes": "Alternate number sometimes listed—confirm on profile.",
    },
    {
        "business": "Temple Jewellery Hub by Priya",
        "handle": "templejewelleryhub_bypriya",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Temple / Nagas-style sets",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "Likely DM (price-in-caption pattern)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed product-style posts",
        "engagement": "Not extracted",
        "bio": "Temple hub branding",
        "keywords": "Temple, Nagas, budget sets",
        "qualified": "IG-native merchandising",
        "services": "Micro-catalog, WhatsApp order templates",
        "maps": "",
        "score": "6",
        "notes": "Add WhatsApp from bio when verified.",
    },
    {
        "business": "Samsara Jaipur",
        "handle": "samsarajaipur",
        "followers": "Verify on profile",
        "city": "Jaipur",
        "state": "Rajasthan",
        "type": "Rajasthan-inspired statement jewellery",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "Likely DM (heritage collection posts)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed collection post",
        "engagement": "Not extracted",
        "bio": "Jaipur cultural positioning",
        "keywords": "Jaipur, traditional, boutique",
        "qualified": "Boutique IG brand—confirm order channel",
        "services": "Brand site, lookbook, WhatsApp concierge",
        "maps": "https://www.google.com/maps/search/Jaipur+jewellery+boutique",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Rajputi Jewellery (Rajasthan)",
        "handle": "jewellery_rajasthan",
        "followers": "Verify on profile",
        "city": "Jaipur / Rajasthan",
        "state": "Rajasthan",
        "type": "Rajputi earrings / pendal styles",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "DM typical for this niche",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed style posts",
        "engagement": "Not extracted",
        "bio": "Regional Rajputi designs",
        "keywords": "Rajputi, earrings",
        "qualified": "Regional SMB aesthetic",
        "services": "Regional SEO microsite, WhatsApp",
        "maps": "",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Rashi Collection (custom beaded / kalire)",
        "handle": "rashi_collection_",
        "followers": "Verify on profile",
        "city": "Ahmednagar / Jaipur tags (per posts)",
        "state": "Maharashtra / Rajasthan",
        "type": "Handmade bridal floral / kalire",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "DM (manufacturer post references @rashi_collection_)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Cross-posted client features",
        "engagement": "Not extracted",
        "bio": "Custom bridal jewellery",
        "keywords": "Custom, bridal, handmade",
        "qualified": "Custom bridal = high WhatsApp/DM load",
        "services": "Custom order intake forms, CRM",
        "maps": "",
        "score": "7",
        "notes": "",
    },
    {
        "business": "Jewel Indukuri's",
        "handle": "indukurisjewel",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Lab-grown diamond pendants (custom)",
        "whatsapp": "+916302720676",
        "email": "Not listed",
        "ordering": "WhatsApp for details/custom mount",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel",
        "engagement": "Not extracted",
        "bio": "Custom pendant messaging",
        "keywords": "Lab grown, customize, WhatsApp",
        "qualified": "Premium SMB with consultative selling",
        "services": "Appointment booking, CRM, education microsite",
        "maps": "",
        "score": "7",
        "notes": "",
    },
    {
        "business": "Vernika Silver",
        "handle": "vernika.silver.jewellery",
        "followers": "Verify on profile",
        "city": "Bengaluru",
        "state": "Karnataka",
        "type": "92.5 silver retail (Chickpet / Avenue Road)",
        "whatsapp": "+917406810666",
        "email": "Not listed",
        "ordering": "Call / WhatsApp bookings; video call shopping",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel mentions bookings",
        "engagement": "Not extracted",
        "bio": "Local silver with video-call commerce",
        "keywords": "925 silver, Bengaluru, video call",
        "qualified": "Hybrid local+online; no site in snippet",
        "services": "Click-to-call/WhatsApp, inventory microsite",
        "maps": "https://www.google.com/maps/search/Avenue+Road+silver+jewellery+Bengaluru",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Jewels of Karnataka",
        "handle": "jewelsofkarnataka",
        "followers": "Verify on profile",
        "city": "Bengaluru / Karnataka",
        "state": "Karnataka",
        "type": "One-gram gold plated / mangalsutra chains",
        "whatsapp": "+919740234813",
        "email": "Not listed",
        "ordering": "WhatsApp on collection posts",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed SKU posts",
        "engagement": "Not extracted",
        "bio": "JK collection branding",
        "keywords": "One gram gold, Karnataka, WhatsApp",
        "qualified": "Volume SKU model on WhatsApp",
        "services": "SKU sheets, WhatsApp quick replies",
        "maps": "",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Chezhiyan Velli Maaligai",
        "handle": "chezian_velli_maaligai",
        "followers": "Verify on profile",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "type": "925 silver customised wedding rings",
        "whatsapp": "+917010078402",
        "email": "Not listed",
        "ordering": "DM or WhatsApp (caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel",
        "engagement": "Not extracted",
        "bio": "Silver custom name laser",
        "keywords": "Silver 92.5, custom, Chennai",
        "qualified": "Custom silver + dual channel",
        "services": "Product configurator, WhatsApp automation",
        "maps": "https://www.google.com/maps/search/Chennai+silver+jewellery",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Shree Silver Pune (SHREE SILVER)",
        "handle": "silver_jewels_pune",
        "followers": "Verify on profile",
        "city": "Pune",
        "state": "Maharashtra",
        "type": "925 hallmarked silver rings / daily wear",
        "whatsapp": "Verify on profile (shop + online ordering referenced)",
        "email": "Not listed",
        "ordering": "Visit shop or order online (caption); capture WA from bio",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel",
        "engagement": "Not extracted",
        "bio": "Raviwar Peth shop location in captions",
        "keywords": "925 silver, Pune, hallmarked",
        "qualified": "Local retail SMB expanding online",
        "services": "Local pickup scheduling page, WhatsApp",
        "maps": "https://www.google.com/maps/search/Sonya+Maruti+Chowk+silver+Pune",
        "score": "7",
        "notes": "Confirm WhatsApp from bio—SERP snippet emphasised shop/online.",
    },
    {
        "business": "Shri Silver Jewellery",
        "handle": "shrisilverjewellery_28",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "925 silver studs / small items",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "DM typical",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed SKU posts",
        "engagement": "Not extracted",
        "bio": "Code-based SKU posts (SS:##)",
        "keywords": "925 silver, studs",
        "qualified": "SKU-heavy IG retail",
        "services": "Automated SKU PDF catalog",
        "maps": "",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Omkar Jewels Surat",
        "handle": "omkar_jewels_surat",
        "followers": "Verify on profile",
        "city": "Surat",
        "state": "Gujarat",
        "type": "Custom gold / bespoke jewellery",
        "whatsapp": "+918141248248",
        "email": "Not listed",
        "ordering": "Phone/WhatsApp + showroom visit",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel with address",
        "engagement": "Not extracted",
        "bio": "Custom jewellery in Surat",
        "keywords": "Custom, Surat, bespoke",
        "qualified": "Consultative jeweller SMB",
        "services": "3D render microsite, CRM, WhatsApp",
        "maps": "https://www.google.com/maps/search/Angel+Square+Uttran+Surat+jewellery",
        "score": "7",
        "notes": "",
    },
    {
        "business": "Sujatha Gold Covering Works",
        "handle": "sujatha_gold_covering_works",
        "followers": "Verify on profile",
        "city": "Machilipatnam area (per hashtags)",
        "state": "Andhra Pradesh",
        "type": "Micro-plated / one-gram gold imitation wholesale",
        "whatsapp": "+917036132171",
        "email": "Not listed",
        "ordering": "WhatsApp for bookings; bulk line",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed wholesale reel",
        "engagement": "Not extracted",
        "bio": "COD & video call for bulk buyers",
        "keywords": "Wholesale, micro plated, COD",
        "qualified": "High-throughput WhatsApp wholesale",
        "services": "B2B ordering portal, inventory sync",
        "maps": "",
        "score": "8",
        "notes": "Multiple numbers in some posts—confirm active bulk line on profile.",
    },
    {
        "business": "Varudi Jewellers Surat",
        "handle": "varudijewellers",
        "followers": "Verify on profile",
        "city": "Surat",
        "state": "Gujarat",
        "type": "Certified gold jewellery (DM instant buy positioning)",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "DM for instant buy messaging in reel title",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel",
        "engagement": "Not extracted",
        "bio": "DM-led purchase framing",
        "keywords": "DM, Surat, certified gold",
        "qualified": "DM commerce pattern",
        "services": "Trust landing pages, secure payment links",
        "maps": "https://www.google.com/maps/search/Varudi+jewellers+Surat",
        "score": "6",
        "notes": "Validate SMB vs larger retailer from bio.",
    },
    {
        "business": "Poddar Jewels",
        "handle": "poddarjewels",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Kundan/polki artificial & bridal sets",
        "whatsapp": "+919899134124",
        "email": "Not listed",
        "ordering": "WhatsApp for wholesale/retail enquiries",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed post",
        "engagement": "Not extracted",
        "bio": "Hand crafted kundan/polki sets",
        "keywords": "Wholesale, retail, kundan",
        "qualified": "Explicit B2B/B2C WhatsApp",
        "services": "Wholesale line sheets, CRM",
        "maps": "",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Stylika (Ahmedabad oxidised feature reel)",
        "handle": "stylika_",
        "followers": "Verify on profile",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "type": "Oxidised / fashion discovery content (verify seller vs blogger)",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "Unclear—may be creator; verify before prospecting",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed Navratri oxidised reel",
        "engagement": "Not extracted",
        "bio": "Fashion discovery positioning",
        "keywords": "Ahmedabad, oxidised, Navratri",
        "qualified": "Low confidence—use for partnerships if creator",
        "services": "Influencer collabs, affiliate storefront",
        "maps": "",
        "score": "4",
        "notes": "Flagged as verify account type (seller vs influencer).",
    },
    {
        "business": "Mughal Jeweller",
        "handle": "mughal.jeweller",
        "followers": "Verify on profile",
        "city": "Delhi NCR (typical for handle theme)",
        "state": "Delhi",
        "type": "Italian silver / chandi nose rings etc.",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "Likely DM/phone in highlights",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed deal posts",
        "engagement": "Not extracted",
        "bio": "Deal-style IG promos",
        "keywords": "Chandi, nose ring, deals",
        "qualified": "Promo-led SMB",
        "services": "Offer automation, WhatsApp broadcasts (opt-in)",
        "maps": "",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Begum Bazar Wholesale Jewelry",
        "handle": "begumbazar_wholesale_jewelry",
        "followers": "Verify on profile",
        "city": "Hyderabad",
        "state": "Telangana",
        "type": "Wholesale guttapusalu / pearl haram sets",
        "whatsapp": "+919618136342",
        "email": "Not listed",
        "ordering": "DM or WhatsApp with screenshot SKU flow",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed posts (numbers vary slightly—verify latest)",
        "engagement": "Not extracted",
        "bio": "Begum Bazar wholesale idiom",
        "keywords": "Begum Bazar, wholesale, screenshot order",
        "qualified": "Classic wholesale IG pattern",
        "services": "B2B portal, ERP-light integrations",
        "maps": "https://www.google.com/maps/search/Begum+Bazar+jewellery+Hyderabad",
        "score": "8",
        "notes": "Some posts show alternate last digits—confirm canonical business number.",
    },
    {
        "business": "Janvish One Gram Gold & Boutique",
        "handle": "janvish_onegramgold_and_boutiq",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "One-gram gold forming jewellery",
        "whatsapp": "+918121769801",
        "email": "Not listed",
        "ordering": "Screenshot + WhatsApp; WA groups for updates",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel",
        "engagement": "Not extracted",
        "bio": "One gram gold combos",
        "keywords": "One gram gold, WhatsApp group",
        "qualified": "Community + WhatsApp commerce",
        "services": "Group migration to broadcast lists (opt-in), catalog",
        "maps": "",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Harshita Jewellery (1 gram gold)",
        "handle": "harshita_jewellery23",
        "followers": "Verify on profile",
        "city": "Balasore",
        "state": "Odisha",
        "type": "One-gram gold plated jewellery",
        "whatsapp": "+918637232187",
        "email": "Not listed",
        "ordering": "WhatsApp in reel caption",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel with local landmark",
        "engagement": "Not extracted",
        "bio": "Local Odisha SMB with nationwide delivery language",
        "keywords": "One gram gold, Odisha, warranty claims in caption",
        "qualified": "Regional SMB with shipping",
        "services": "Warranty page, tracking automation",
        "maps": "https://www.google.com/maps/search/Balasore+FM+College+near+jewellery",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Roshi Collections",
        "handle": "roshi.collections",
        "followers": "Verify on profile",
        "city": "Tamil Nadu shipping emphasis",
        "state": "Tamil Nadu",
        "type": "One-gram gold forming chains & temple sets",
        "whatsapp": "+919092327836",
        "email": "Not listed",
        "ordering": "WhatsApp with product screenshot; online payment only",
        "website_yn": "No",
        "website_url": "",
        "activity": "Multiple indexed SKUs",
        "engagement": "Not extracted",
        "bio": "Trusted page messaging; south Indian bridal keywords",
        "keywords": "One gram gold, temple, Tamil Nadu",
        "qualified": "High-trust WhatsApp-only checkout pattern",
        "services": "Payment links, order tracking portal",
        "maps": "",
        "score": "9",
        "notes": "",
    },
    {
        "business": "Lakshmi Jewells (Sree Wholesale Jewellery)",
        "handle": "lakshmijewells",
        "followers": "Verify on profile",
        "city": "South India",
        "state": "—",
        "type": "Matte / rose gold finish imitation wholesale",
        "whatsapp": "+919390483697",
        "email": "Not listed",
        "ordering": "Order & enquiry via WhatsApp (caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel",
        "engagement": "Not extracted",
        "bio": "Strict policies (opening video, no COD)",
        "keywords": "Wholesale, choker, black beads",
        "qualified": "Policy-heavy WhatsApp ops = automation candidate",
        "services": "Policy microsite, ticketing",
        "maps": "",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Asha Bangles Official (Punjabi bridal chura)",
        "handle": "ashabanglesofficial",
        "followers": "Verify on profile",
        "city": "Patiala / North India service area",
        "state": "Punjab",
        "type": "Bridal chura / bangles custom",
        "whatsapp": "+917014592741",
        "email": "Not listed",
        "ordering": "WhatsApp; partial COD; customisation",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed post",
        "engagement": "Not extracted",
        "bio": "Long-running chura specialist claims in captions",
        "keywords": "Bridal chura, custom, partial COD",
        "qualified": "Custom bridal + WhatsApp = high touch",
        "services": "Customizer web app, CRM, IG ads",
        "maps": "",
        "score": "8",
        "notes": "",
    },
    {
        "business": "SGT House of German Silver (Hyderabad)",
        "handle": "sgthouseofgermansilver.hyd",
        "followers": "Verify on profile",
        "city": "Hyderabad",
        "state": "Telangana",
        "type": "German silver pooja idols / sets",
        "whatsapp": "+918522919996",
        "email": "Not listed",
        "ordering": "WhatsApp booking for online orders; video shopping",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel with map short link",
        "engagement": "Not extracted",
        "bio": "Kukatpally branch focus",
        "keywords": "German silver, video call shopping",
        "qualified": "Hybrid showroom + WhatsApp commerce",
        "services": "Appointment booking, hybrid inventory",
        "maps": "https://g.co/kgs/hCWGba",
        "score": "7",
        "notes": "Also lists second number in some posts.",
    },
    {
        "business": "Because It's Silver (bcos_its_silver)",
        "handle": "bcos_its_silver",
        "followers": "Verify on profile",
        "city": "Hyderabad",
        "state": "Telangana",
        "type": "Pure silver guttapusalu / oxidised silver",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "Likely DM / phone in bio",
        "website_yn": "No",
        "website_url": "",
        "activity": "Older indexed posts still surface",
        "engagement": "Not extracted",
        "bio": "Hyderabad pearls niche hashtags",
        "keywords": "Silver, guttapusalu, Hyderabad",
        "qualified": "Heritage silver SMB",
        "services": "Lookbook microsite",
        "maps": "https://www.google.com/maps/search/Hyderabad+silver+jewellery",
        "score": "6",
        "notes": "Confirm active status and WhatsApp from bio.",
    },
    {
        "business": "Trend Jewelryys",
        "handle": "trend_jewelryys",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Trend-led fashion jewellery",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "Likely DM",
        "website_yn": "No",
        "website_url": "",
        "activity": "SERP surfaced posts",
        "engagement": "Low in sample comments",
        "bio": "Trending SKU posts",
        "keywords": "Trending, fashion",
        "qualified": "Needs verification of activity",
        "services": "Content calendar, reels ads",
        "maps": "",
        "score": "5",
        "notes": "Prioritize only if recent posting confirmed.",
    },
    {
        "business": "Wear and Shine Jewelry",
        "handle": "wear_nd_shine_jewelry",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Fashion jewellery",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "DM",
        "website_yn": "No",
        "website_url": "",
        "activity": "Low comment posts in SERP",
        "engagement": "Low in sample",
        "bio": "Fashion jewellery posts",
        "keywords": "Fashion jewellery",
        "qualified": "Weak signal—verify activity",
        "services": "Growth, creative testing",
        "maps": "",
        "score": "5",
        "notes": "",
    },
    {
        "business": "Lucknow Artificial Jewellery",
        "handle": "lucknow_artificial_jewellery_",
        "followers": "Verify on profile",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "type": "Artificial / one-gram polish earrings",
        "whatsapp": "+918957754721",
        "email": "Not listed",
        "ordering": "Booking number in reel caption; COD mentioned",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel",
        "engagement": "Not extracted",
        "bio": "City-tagged artificial jewellery",
        "keywords": "Lucknow, imitation, COD",
        "qualified": "Geo-tagged SMB with COD",
        "services": "COD policy page, WhatsApp automation",
        "maps": "https://www.google.com/maps/search/Lucknow+artificial+jewellery",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Silver Shine Jewellery (Vadodara)",
        "handle": "silvershine_jewelery",
        "followers": "Verify on profile",
        "city": "Vadodara",
        "state": "Gujarat",
        "type": "925 hallmark silver",
        "whatsapp": "+917572962224",
        "email": "Not listed",
        "ordering": "DM or WhatsApp (caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel",
        "engagement": "Not extracted",
        "bio": "Vadodara/Baroda tags",
        "keywords": "925, Vadodara, DM/WhatsApp",
        "qualified": "Dual-channel SMB silver",
        "services": "WhatsApp catalog, local SEO page",
        "maps": "https://www.google.com/maps/search/Vadodara+925+silver+jewellery",
        "score": "8",
        "notes": "",
    },
    {
        "business": "Silver Palace 45",
        "handle": "silver_palace45",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "925 silver studs SKUs",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "DM",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed SKU post",
        "engagement": "Not extracted",
        "bio": "Code-based listings",
        "keywords": "925 silver, studs",
        "qualified": "SKU IG retail",
        "services": "Automated invoice from DM",
        "maps": "",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Sai Jewellers Rajat Ujjain",
        "handle": "sai_jewellers_rajat_ujjain",
        "followers": "Verify on profile",
        "city": "Ujjain",
        "state": "Madhya Pradesh",
        "type": "Gold-plated fashion necklaces",
        "whatsapp": "+917024274632",
        "email": "Not listed",
        "ordering": "DM / WhatsApp (caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed post referencing MP",
        "engagement": "Not extracted",
        "bio": "Temple-adjacent captions",
        "keywords": "Ujjain, gold plated, WhatsApp",
        "qualified": "Regional SMB with WA/DM",
        "services": "WhatsApp commerce, trust badges",
        "maps": "https://www.google.com/maps/search/Ujjain+jewellery+shop",
        "score": "7",
        "notes": "",
    },
    {
        "business": "Rajputii Jewellery",
        "handle": "rajputii_jewellery_",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Rajputi / traditional silver-gold tone fashion",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "DM",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed posts",
        "engagement": "Some engagement in SERP snippet",
        "bio": "Traditional niche",
        "keywords": "Rajputi, traditional",
        "qualified": "Niche SMB",
        "services": "UGC campaigns, collabs",
        "maps": "",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Jewellery Junction Nagpur",
        "handle": "jewellryjunction",
        "followers": "Verify on profile",
        "city": "Nagpur",
        "state": "Maharashtra",
        "type": "Imitation jewellery retail",
        "whatsapp": "+919730162779",
        "email": "Not listed",
        "ordering": "Phone / in-store; DMs likely",
        "website_yn": "No",
        "website_url": "",
        "activity": "Influencer collab posts surface shop",
        "engagement": "Not extracted",
        "bio": "Teen Nal Chowk location",
        "keywords": "Imitation, Nagpur, retail",
        "qualified": "Physical retail with IG discovery",
        "services": "Click-to-WhatsApp ads, inventory highlights",
        "maps": "https://www.google.com/maps/search/Teen+Nal+Chowk+Nagpur+jewellery",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Aashu's Pearl Creation",
        "handle": "aashus_pearl_creation",
        "followers": "Verify on profile",
        "city": "Maharashtra",
        "state": "Maharashtra",
        "type": "Handmade traditional chokers / Maharashtrian bridal",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "DM to order (caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel",
        "engagement": "Not extracted",
        "bio": "Customisation available",
        "keywords": "Handmade, DM, bridal",
        "qualified": "DM-only maker SMB",
        "services": "DM automation (Meta), lead forms",
        "maps": "",
        "score": "7",
        "notes": "",
    },
    {
        "business": "Aakanksha Jewellery",
        "handle": "aakanksha_jewellery",
        "followers": "Verify on profile",
        "city": "Maharashtra",
        "state": "Maharashtra",
        "type": "Pearl chinchpeti / traditional necklaces",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "DM to own piece (caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed post",
        "engagement": "Not extracted",
        "bio": "Maharashtrian bride positioning",
        "keywords": "Chinchpeti, DM, pearls",
        "qualified": "DM-led premium traditional",
        "services": "Lookbook PDF, WhatsApp follow-up",
        "maps": "",
        "score": "7",
        "notes": "",
    },
    {
        "business": "MRK Zevar Bangalore",
        "handle": "mrkzevar",
        "followers": "Verify on profile",
        "city": "Bengaluru",
        "state": "Karnataka",
        "type": "Chains / MRK group jewellery",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "Likely showroom + DMs",
        "website_yn": "No",
        "website_url": "",
        "activity": "Brand posts indexed",
        "engagement": "Not extracted",
        "bio": "Group brand tone",
        "keywords": "Chains, Bengaluru",
        "qualified": "Potential mid-market—verify SMB fit",
        "services": "B2C ecommerce, omnichannel",
        "maps": "https://www.google.com/maps/search/MRK+Zevar+Bengaluru",
        "score": "5",
        "notes": "Could be larger group; validate before outreach.",
    },
    {
        "business": "The Amethyst Store (Jayanagar Silver)",
        "handle": "theamethyststore",
        "followers": "Verify on profile",
        "city": "Bengaluru",
        "state": "Karnataka",
        "type": "92.5 luxury silver retail",
        "whatsapp": "+918925967592",
        "email": "Not listed",
        "ordering": "Phone/WhatsApp contact pair in reel",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed opening/location reel",
        "engagement": "Not extracted",
        "bio": "Jayanagar boutique silver",
        "keywords": "925, Jayanagar, boutique",
        "qualified": "Boutique silver with hybrid retail",
        "services": "Appointment booking, CRM",
        "maps": "https://www.google.com/maps/search/Jayanagar+4th+block+silver+jewellery",
        "score": "7",
        "notes": "Alternate number appears in caption pair.",
    },
    {
        "business": "Khushbu Jewellers (Instagram handle khushbujewellers.com_)",
        "handle": "khushbujewellers.com_",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "High-volume silver SKUs (rajputi / sindoor / hathful)",
        "whatsapp": "+919875791031",
        "email": "Not listed",
        "ordering": "WhatsApp screenshot ordering; captions sometimes promote website-order discounts",
        "website_yn": "Unclear",
        "website_url": "Verify whether a standalone ecommerce site exists vs IG-only promos",
        "activity": "Frequently indexed reels/posts",
        "engagement": "Not extracted",
        "bio": "Screenshot-to-order pattern across many SKUs",
        "keywords": "Silver, COD, website promos, screenshot order",
        "qualified": "Ops-heavy WhatsApp-first retailer (merge multi-lines in CRM)",
        "services": "WhatsApp API, ERP, unified catalog",
        "maps": "",
        "score": "7",
        "notes": "Additional WhatsApp line observed on posts: +918233445357 (example: sindoor box reel).",
    },
    {
        "business": "Pooja Jewels (silver payal seller)",
        "handle": "poojajewels_",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "925 silver fashion / payal",
        "whatsapp": "+917597344552",
        "email": "Not listed",
        "ordering": "WhatsApp; COD available per reel caption",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel (author resolved via Instagram oembed)",
        "engagement": "Not extracted",
        "bio": "Small-business hashtags in captions",
        "keywords": "Silver payal, COD, WhatsApp",
        "qualified": "Explicit WhatsApp + COD SMB pattern",
        "services": "WhatsApp commerce, payments links, CRM",
        "maps": "",
        "score": "8",
        "notes": "Handle confirmed via public oembed metadata for reel URL.",
    },
    {
        "business": "Kundan Creations by Jinal",
        "handle": "kundancreations_",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Moissanite / polki plated necklaces",
        "whatsapp": "+917359147370",
        "email": "Not listed",
        "ordering": "WhatsApp for pricing/orders (caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel",
        "engagement": "Not extracted",
        "bio": "Premium imitation bridal positioning",
        "keywords": "Polki, moissanite, WhatsApp",
        "qualified": "WhatsApp-led consultative selling",
        "services": "Catalog PDF automation, CRM",
        "maps": "",
        "score": "8",
        "notes": "",
    },
    {
        "business": "JUST KUNDAN India",
        "handle": "just_kundan",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Moissanite polki carved sets",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "DM / comment-to-order pattern common in niche (verify)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed catalogue-style post",
        "engagement": "Not extracted",
        "bio": "PR-coded SKUs with INR+shipping language",
        "keywords": "Polki, moissanite, bridal",
        "qualified": "IG-native merchandising",
        "services": "WhatsApp order desk, checkout links",
        "maps": "",
        "score": "6",
        "notes": "Confirm WhatsApp/DM channel from bio.",
    },
    {
        "business": "Radhe Jewellers Anand",
        "handle": "radhe_jewellers",
        "followers": "Verify on profile",
        "city": "Anand",
        "state": "Gujarat",
        "type": "Gold / diamond / silver ornaments (showroom-led)",
        "whatsapp": "+917046489990",
        "email": "Not listed",
        "ordering": "Call/WhatsApp per caption",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed bridal collection post",
        "engagement": "Not extracted",
        "bio": "Charotar region jewellery store tone",
        "keywords": "Bridal, showroom, Gujarat",
        "qualified": "Hybrid retail + phone/WhatsApp",
        "services": "Local SEO, WhatsApp appointments",
        "maps": "https://www.google.com/maps/search/Radhe+Jewellers+Anand",
        "score": "6",
        "notes": "Showroom-first; still useful for omnichannel upgrades.",
    },
    {
        "business": "Sai Brindavan Jewellers",
        "handle": "saibrindavan_jewellers",
        "followers": "Verify on profile",
        "city": "Hyderabad",
        "state": "Telangana",
        "type": "Begum Bazar wholesale/retail jewellery",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "Likely in-market + DM (verify)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel about Begum Bazar positioning",
        "engagement": "Not extracted",
        "bio": "Wholesale/retail market language",
        "keywords": "Begum Bazar, wholesale",
        "qualified": "Market stall SMB modernization candidate",
        "services": "Inventory digitization, WhatsApp catalog",
        "maps": "https://www.google.com/maps/search/Begum+Bazar+jewellery+Hyderabad",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Pooja Shree Jewellery One Gram",
        "handle": "pooja_shree_jewellary_onegram",
        "followers": "Verify on profile",
        "city": "Chhatrapati Sambhajinagar (Aurangabad)",
        "state": "Maharashtra",
        "type": "One-gram gold / temple mangalsutra",
        "whatsapp": "+919503080030",
        "email": "Not listed",
        "ordering": "DM numbers listed in reel caption",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel",
        "engagement": "Not extracted",
        "bio": "Maharashtra geo tags",
        "keywords": "One gram gold, temple, DM",
        "qualified": "DM-first regional SMB",
        "services": "WhatsApp migration, automated sizing FAQ",
        "maps": "https://www.google.com/maps/search/Sambhajinagar+jewellery",
        "score": "7",
        "notes": "Second number sometimes listed: +919156535485 (verify active).",
    },
    {
        "business": "Lavanya Jewellers (Gold)",
        "handle": "lavanyajewellers_slj",
        "followers": "Verify on profile",
        "city": "Vijayawada / Kanuru (per posts)",
        "state": "Andhra Pradesh",
        "type": "916/22ct gold & diamond pendants (custom)",
        "whatsapp": "+919441176530",
        "email": "Not listed",
        "ordering": "DM or WhatsApp; worldwide shipping language",
        "website_yn": "No",
        "website_url": "",
        "activity": "Multiple indexed reels",
        "engagement": "Not extracted",
        "bio": "In-store + customised orders",
        "keywords": "Gold, diamond, custom, WhatsApp",
        "qualified": "Consultative jeweller with strong WhatsApp",
        "services": "Appointment booking, CRM, payments",
        "maps": "https://www.google.com/maps/search/Lavanya+Jewellers+Vijayawada",
        "score": "7",
        "notes": "Higher ticket items—still SMB-style Instagram distribution.",
    },
    {
        "business": "Yuvraj Nosepins (Chandni Chowk)",
        "handle": "yuvraj_nosepins",
        "followers": "Verify on profile",
        "city": "New Delhi",
        "state": "Delhi",
        "type": "Lightweight gold earrings / nosepins",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "Showroom-first (Kucha Mahajani); DMs likely",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel",
        "engagement": "Not extracted",
        "bio": "Chandni Chowk shopping positioning",
        "keywords": "Gold earrings, Chandni Chowk",
        "qualified": "Iconic market SMB; digital uplift opportunity",
        "services": "WhatsApp catalog, local delivery landing pages",
        "maps": "https://www.google.com/maps/search/Kucha+Mahajani+Chandni+Chowk+jewellery",
        "score": "6",
        "notes": "Pvt Ltd label appears in some posts—validate enterprise fit before outreach.",
    },
    {
        "business": "S. Swarnakar & Son",
        "handle": "s.swarnakarandson",
        "followers": "Verify on profile",
        "city": "Kolkata (Chetla)",
        "state": "West Bengal",
        "type": "Traditional gold/silver wedding jewellery",
        "whatsapp": "+918981948452",
        "email": "Not listed",
        "ordering": "Booking number in captions",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed silver collection post",
        "engagement": "Not extracted",
        "bio": "Kolkata hashtags; hallmarked pieces",
        "keywords": "Kolkata, wedding jewellery, silver",
        "qualified": "Phone-led bookings from Instagram discovery",
        "services": "WhatsApp automation, ecommerce for repeat SKUs",
        "maps": "https://www.google.com/maps/search/Chetla+jewellery+Kolkata",
        "score": "7",
        "notes": "",
    },
    {
        "business": "Gobind Jewellers Durgapur",
        "handle": "gobindjewellers",
        "followers": "Verify on profile",
        "city": "Durgapur",
        "state": "West Bengal",
        "type": "Gold bridal sets / traditional jewellery",
        "whatsapp": "+919593222111",
        "email": "Not listed",
        "ordering": "Phone contact in posts; showroom pickup",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed collection posts",
        "engagement": "Not extracted",
        "bio": "Durgapur market jeweller tone",
        "keywords": "Bridal, gold, Durgapur",
        "qualified": "Regional showroom using IG for awareness",
        "services": "WhatsApp commerce layer, CRM",
        "maps": "https://www.google.com/maps/search/Chandidas+Market+Durgapur+jewellery",
        "score": "6",
        "notes": "",
    },
    {
        "business": "Silpa Silvers",
        "handle": "silpa.silvers",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "925 antique silver pooja pieces / decor-jewellery crossover",
        "whatsapp": "+919581875223",
        "email": "Not listed",
        "ordering": "WhatsApp inquiries (caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed product post",
        "engagement": "Not extracted",
        "bio": "Artisanal silver tone",
        "keywords": "Antique silver, WhatsApp",
        "qualified": "WhatsApp-led premium craft brand",
        "services": "Catalog microsite, CRM",
        "maps": "",
        "score": "7",
        "notes": "Alternate number sometimes listed: +917301616666.",
    },
    {
        "business": "Ahilya Fine Silver Jewels",
        "handle": "ahilyafinesilverjewels",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "925 silver / Thushi-inspired collections (verify assortment)",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "Likely DM (classic silver IG pattern)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed collection post surfaced via oembed discovery",
        "engagement": "Not extracted",
        "bio": "Fine silver positioning",
        "keywords": "925 silver, traditional",
        "qualified": "Silver IG brand without site in snippet",
        "services": "Shopify-lite, WhatsApp catalog",
        "maps": "",
        "score": "6",
        "notes": "Handle confirmed via oembed for a tagged post URL.",
    },
    {
        "business": "Elegant Fashion by Rupika",
        "handle": "elegant_fashion6095",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Handmade terracotta / fashion earrings",
        "whatsapp": "+919087319846",
        "email": "Not listed",
        "ordering": "DM or WhatsApp (caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed older post still discoverable",
        "engagement": "Not extracted",
        "bio": "Custom colours for handmade earrings",
        "keywords": "Handmade, terracotta, DM",
        "qualified": "Maker SMB with dual-channel ordering",
        "services": "Customizer widget, WhatsApp automation",
        "maps": "",
        "score": "7",
        "notes": "Adjacent to core jewellery but strong IG commerce pattern.",
    },
    {
        "business": "The Madras Art Studio",
        "handle": "themadras_artstudio",
        "followers": "Verify on profile",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "type": "Resin preserved-flower pendants & jewellery",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "DM to order (caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed post; handle via oembed",
        "engagement": "Not extracted",
        "bio": "Custom resin jewellery studio",
        "keywords": "Resin, DM to order, custom",
        "qualified": "DM-heavy custom workflow",
        "services": "Intake forms, CRM, WhatsApp follow-ups",
        "maps": "https://www.google.com/maps/search/Chennai+resin+jewellery",
        "score": "7",
        "notes": "Handle confirmed via public oembed metadata.",
    },
    {
        "business": "Talk With Art by Rach",
        "handle": "talkwithart_byrach",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Resin pendants / charms",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "DM for orders & prices (caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed post; handle via oembed",
        "engagement": "Not extracted",
        "bio": "Custom resin pieces",
        "keywords": "Resin, DM for price",
        "qualified": "Maker channel; automation-friendly intake",
        "services": "WhatsApp/DM routing, invoice bots",
        "maps": "",
        "score": "7",
        "notes": "Handle confirmed via public oembed metadata.",
    },
    {
        "business": "Mamta Arts & Artifacts",
        "handle": "mamta_arts_and_artifacts",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Handmade resin / gifting (bridal-adjacent)",
        "whatsapp": "+917758922201",
        "email": "Not listed",
        "ordering": "DM or WhatsApp (caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed long-caption gift post",
        "engagement": "Not extracted",
        "bio": "Return gifts / wedding gifting",
        "keywords": "Resin thali, wedding gifts, WhatsApp",
        "qualified": "High-touch gifting SMB",
        "services": "CRM, brochure site, WhatsApp automation",
        "maps": "",
        "score": "6",
        "notes": "Crossover gifting vs core jewellery—still relevant services stack.",
    },
    {
        "business": "Dreams Jewellery (one gram gold)",
        "handle": "dreams.jewellery2023",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "One-gram gold plated men's bracelets / chains",
        "whatsapp": "+919099003670",
        "email": "Not listed",
        "ordering": "WhatsApp for price details (caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed post; handle via oembed",
        "engagement": "Not extracted",
        "bio": "One gram gold keywords",
        "keywords": "One gram gold, mens bracelet, WhatsApp",
        "qualified": "Volume WhatsApp pricing model",
        "services": "SKU sheets, WhatsApp quick replies",
        "maps": "",
        "score": "8",
        "notes": "Some posts list a second number (+91 9106503944)—verify canonical line.",
    },
    {
        "business": "Pooja Jewellers (silver moti ring)",
        "handle": "pooja_jewellerpj",
        "followers": "Verify on profile",
        "city": "India",
        "state": "—",
        "type": "Silver moti / fashion rings",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "Likely DM/WhatsApp (verify)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed reel title",
        "engagement": "Not extracted",
        "bio": "Silver moti SKU posts",
        "keywords": "Silver, ring",
        "qualified": "SMB SKU IG retailer",
        "services": "WhatsApp catalog",
        "maps": "",
        "score": "6",
        "notes": "Different handle from @poojajewels_; keep separate in CRM.",
    },
    {
        "business": "Aarti Jewellers Surat",
        "handle": "aartijewellers.surat",
        "followers": "Verify on profile",
        "city": "Surat",
        "state": "Gujarat",
        "type": "Gold / lightweight gold fashion sets",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "Showroom-first promotions on reels (add WhatsApp from bio)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed Surat promotional reels",
        "engagement": "Not extracted",
        "bio": "Surat jewellery store tone",
        "keywords": "Surat, gold, offers",
        "qualified": "Regional retailer using IG for promos",
        "services": "WhatsApp offers automation, appointment booking",
        "maps": "https://www.google.com/maps/search/Aarti+Jewellers+Surat",
        "score": "5",
        "notes": "Validate SMB fit vs larger showroom.",
    },
    {
        "business": "SS Nagarkar Jewellers Pune",
        "handle": "ssnagarkarjewellers",
        "followers": "Verify on profile",
        "city": "Pune",
        "state": "Maharashtra",
        "type": "Traditional gold bridal sets",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "Visit store language in posts; likely phone/DM",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed bridal combo post",
        "engagement": "Not extracted",
        "bio": "South Indian gold bridal combos",
        "keywords": "Gold, bridal, Pune",
        "qualified": "Showroom-led brand with IG presence",
        "services": "Omnichannel catalogue, WhatsApp concierge",
        "maps": "https://www.google.com/maps/search/SS+Nagarkar+Jewellers+Pune",
        "score": "5",
        "notes": "Handle confirmed via oembed for a public post URL.",
    },
    {
        "business": "Dilip Jewellers Nagpur",
        "handle": "dilipjewellersnagpur",
        "followers": "Verify on profile",
        "city": "Nagpur",
        "state": "Maharashtra",
        "type": "22k gold long necklaces / rani haar",
        "whatsapp": "Verify on profile",
        "email": "Not listed",
        "ordering": "Showroom visit emphasis; DMs likely",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed Hansapuri gold reel",
        "engagement": "Not extracted",
        "bio": "Nagpur gold shopping hashtags",
        "keywords": "Gold, Nagpur, showroom",
        "qualified": "Traditional jeweller using reels for discovery",
        "services": "Video commerce, WhatsApp follow-ups",
        "maps": "https://www.google.com/maps/search/Dilip+Jewellers+Hansapuri+Nagpur",
        "score": "5",
        "notes": "",
    },
    {
        "business": "Emmadi Silver Jewellery",
        "handle": "emmadi_silver_jewellery",
        "followers": "Verify on profile",
        "city": "Hyderabad",
        "state": "Telangana",
        "type": "Silver / wedding-focused jewellery (showroom + WhatsApp video)",
        "whatsapp": "+916302112233",
        "email": "Not listed",
        "ordering": "WhatsApp video appointments (reel caption)",
        "website_yn": "No",
        "website_url": "",
        "activity": "Indexed expo / showroom reels",
        "engagement": "Not extracted",
        "bio": "Kukatpally / Punjagutta references",
        "keywords": "Silver, Hyderabad, video call",
        "qualified": "Strong WhatsApp + showroom hybrid (may be mid-size—validate)",
        "services": "Appointment scheduling, CRM, ads",
        "maps": "https://www.google.com/maps/search/Emmadi+Silver+Jewellery+Kukatpally",
        "score": "5",
        "notes": "Also lists Punjagutta WhatsApp line in some posts—confirm scale before SMB pitch.",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Cenora Jewels",
        "handle": "cenorajewels",
        "city": "Mumbai",
        "state": "Maharashtra",
        "type": "Fashion / promotional jewellery",
        "whatsapp": "+917021923226",
        "ordering": "DM to order and WhatsApp in indexed reel caption",
        "activity": "Indexed reel with DM/WhatsApp CTA",
        "bio": "Reel text: Buy 1 get 1 free; DM to order / WhatsApp contact",
        "keywords": "DM to order, WhatsApp, Mumbai, reels",
        "qualified": "Explicit DM + WhatsApp dual-channel ordering; SMB-style promo post",
        "services": "WhatsApp automation, Instagram shop integration, lightweight catalog site",
        "score": "8",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Rajputi Jewellery Wholesaler (S.C.)",
        "handle": "rajputi_jewelery_wholsaler_s.c",
        "city": "India",
        "state": "—",
        "type": "Rajputi / traditional imitation sets",
        "whatsapp": "+917877634674",
        "ordering": "WhatsApp for price and orders; group link mentioned in some posts",
        "activity": "Indexed reel with WhatsApp order line",
        "bio": "Wholesale-oriented rajputi jewellery captions",
        "keywords": "Rajputi, wholesale, WhatsApp",
        "qualified": "Screenshot-style wholesale flow typical of IG-first sellers",
        "services": "B2B catalog, WhatsApp broadcast compliance, inventory microsite",
        "score": "7",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "https://www.google.com/maps/search/Sukh+Vilas+Bombay+Market+Surat",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Sukh Vilas Surat",
        "handle": "sukh_vilas_surat",
        "city": "Surat",
        "state": "Gujarat",
        "type": "Fashion / wedding wear shop (Bombay Market) with jewellery reels",
        "whatsapp": "+919909686288",
        "ordering": "WhatsApp screenshot to book price/order (caption lists two store lines)",
        "activity": "Indexed Surat wholesale reel with timings and address",
        "bio": "Bombay Market Umarvada; screenshot-to-WhatsApp booking pattern",
        "keywords": "Surat, screenshot order, wholesale",
        "qualified": "Strong WhatsApp screenshot workflow; physical Surat address",
        "services": "WhatsApp commerce, COD/prepay policy pages, bilingual catalog",
        "score": "8",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Swarnam Varnam",
        "handle": "swarnam_varnam",
        "city": "Hyderabad",
        "state": "Telangana",
        "type": "Temple / traditional imitation jewellery tone (verify assortment)",
        "whatsapp": "Verify on profile",
        "ordering": "Likely DM/WhatsApp typical for similar Hyderabad sellers—confirm on profile",
        "activity": "Indexed post surfaced in jewellery SERP",
        "bio": "Handle surfaced via public post metadata; confirm niche on profile",
        "keywords": "Hyderabad, temple jewellery, traditional",
        "qualified": "Good candidate for recursive discovery from similar followers",
        "services": "Instagram growth, Reels ads, WhatsApp concierge",
        "score": "6",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Wedding Answers (bridal accessories)",
        "handle": "weddinganswers",
        "city": "Delhi NCR (pan-India shipping)",
        "state": "Delhi",
        "type": "Bridal kalire, chooda boxes, veils, wedding accessories",
        "whatsapp": "+918368213149",
        "ordering": "WhatsApp or DM; advance payment; screenshot product to enquire",
        "activity": "Indexed bridal accessory posts with strict payment policy text",
        "bio": "Wedding ideas / bridal add-ons; heavy WhatsApp + DM language",
        "keywords": "Kalire, chooda box, DM, WhatsApp",
        "qualified": "Accessory seller adjacent to jewellery with mature WhatsApp ops",
        "services": "CRM for custom orders, payment link automation, IG DM automation",
        "score": "8",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Jewelz by Aayushi",
        "handle": "jewelz_by_aayushi",
        "city": "India",
        "state": "—",
        "type": "Fashion / artificial jewellery (verify category on profile)",
        "whatsapp": "Verify on profile",
        "ordering": "Indexed post surfaced without captured number—check bio",
        "activity": "Indexed Instagram post in jewellery SERP",
        "bio": "Confirm product focus and contact line on live profile",
        "keywords": "Fashion jewellery, Instagram discovery",
        "qualified": "Handle confirmed via oEmbed; needs quick profile pass for WA",
        "services": "Bio optimisation, WhatsApp deep link, catalog landing page",
        "score": "6",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "https://www.google.com/maps/search/Lakshmi+Srinivasa+Jewelleries+Khammam",
        "notes": "Alternate line cited in posts: +91 7416388396—confirm active branch.",
        "business": "Lakshmi Srinivasa Jewelleries",
        "handle": "lakshmi_srinivasa_jewelleries",
        "city": "Khammam",
        "state": "Telangana",
        "type": "925 silver / antique-style silver",
        "whatsapp": "+917416588396",
        "ordering": "Video call shopping; dual numbers in indexed reel caption",
        "activity": "Indexed reel promoting video-call viewing",
        "bio": "Khammam-tagged silver reels",
        "keywords": "Silver 925, video call, Khammam",
        "qualified": "Hybrid remote selling fits WhatsApp-first tooling pitch",
        "services": "Appointment scheduling, WhatsApp video catalog, CRM",
        "score": "7",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Jewellery by Lalitha (imitation)",
        "handle": "jewellery_by_lalitha",
        "city": "India",
        "state": "—",
        "type": "Lalitha imitation jewellery",
        "whatsapp": "+917672044475",
        "ordering": "DM or WhatsApp; screenshot product; online payment only (no COD per indexed caption)",
        "activity": "Indexed post with stepwise order instructions",
        "bio": "Strict no-COD policy and parcel video requirement",
        "keywords": "DM order, WhatsApp, imitation",
        "qualified": "Very clear DM+WhatsApp SOP—ideal services automation prospect",
        "services": "Payment links, order tracking portal, policy microsite",
        "score": "9",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Khushbu Jewellers Official",
        "handle": "khushbu_jewellers_official",
        "city": "India",
        "state": "—",
        "type": "Silver lightweight fashion pieces",
        "whatsapp": "+918829911024",
        "ordering": "WhatsApp order line in indexed post caption",
        "activity": "Indexed silver evil-eye pendant style post",
        "bio": "Distinct handle from tinwari line; WhatsApp order number in caption",
        "keywords": "Silver, evil eye, WhatsApp order",
        "qualified": "Separate handle with explicit WhatsApp order path",
        "services": "SKU tagging in WhatsApp, CRM tags by campaign",
        "score": "7",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "https://www.google.com/maps/search/Grace+Silver+Studio+Kanpur",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Grace Silver Studio",
        "handle": "gracesilverstudio",
        "city": "Kanpur",
        "state": "Uttar Pradesh",
        "type": "925 sterling wired nose pins / silver fashion",
        "whatsapp": "+918009327101",
        "ordering": "DM or WhatsApp per indexed reel; India shipping mentioned",
        "activity": "Indexed celebrity-style nose pin reel",
        "bio": "Hallmarked 925; store reference in Harsh Nagar Kanpur in caption",
        "keywords": "925, nose pin, DM, WhatsApp, Kanpur",
        "qualified": "DM + WhatsApp dual CTA; local store + remote selling",
        "services": "WhatsApp catalog, local SEO page, reviews capture",
        "score": "8",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Those Little Blings",
        "handle": "thoselittleblingss",
        "city": "India",
        "state": "—",
        "type": "Moissanite / fashion studs (oxidised keywords in caption)",
        "whatsapp": "Verify on profile",
        "ordering": "Indexed caption: free shipping; DM to order (confirm WhatsApp in bio)",
        "activity": "Indexed product post in moissanite/oxidised SERP",
        "bio": "Small-business positioning in hashtags",
        "keywords": "Moissanite, DM to order, oxidised",
        "qualified": "DM-first microbrand pattern",
        "services": "Instagram shop, DM automation, checkout links",
        "score": "7",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "https://www.google.com/maps/search/Babu+Churi+Wala+Greater+Kailash+Delhi",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Babu Churi Wala GK",
        "handle": "babuchuriwalagk",
        "city": "Delhi",
        "state": "Delhi",
        "type": "Customised bridal glass/acrylic bangles (churi)",
        "whatsapp": "Verify on profile",
        "ordering": "Custom bridal bangle sets; contact likely via DM/phone (verify bio)",
        "activity": "Indexed reel for customised bridal churi",
        "bio": "GK / Delhi heritage churi seller tone in snippet",
        "keywords": "Bridal bangles, customised chura, Delhi",
        "qualified": "High-touch custom orders—fits CRM and WhatsApp workflows",
        "services": "Custom order forms, WhatsApp templates, appointment booking",
        "score": "7",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "https://www.google.com/maps/search/Chaudhary+Jewellers+Sangrur",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Chaudhary Jewellers Sangrur",
        "handle": "chaudhary.jewellers",
        "city": "Sangrur",
        "state": "Punjab",
        "type": "Gold / silver fashion rings and Sikh-style jewellery posts",
        "whatsapp": "+919578000011",
        "ordering": "Phone/WhatsApp in indexed reel caption",
        "activity": "Indexed reel with market address near bus stand",
        "bio": "Sangrur market location; WhatsApp-friendly SMB jeweller tone",
        "keywords": "Khanda ring, Sangrur, WhatsApp",
        "qualified": "Geo-tagged SMB with on-caption phone contact",
        "services": "Google Business Profile optimisation, click-to-WhatsApp ads",
        "score": "6",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Flabel Creations",
        "handle": "flabelcreations",
        "city": "India",
        "state": "—",
        "type": "Antique Lakshmi jhumkas / imitation bridal earrings",
        "whatsapp": "+917711990044",
        "ordering": "WhatsApp (link in bio referenced) + DM for details in indexed caption",
        "activity": "Indexed jhumka offer post",
        "bio": "Imitation bridal earring promos with flat price + free shipping",
        "keywords": "Jhumka, WhatsApp, imitation",
        "qualified": "Classic SMB combo: flat price + WhatsApp + DM",
        "services": "WhatsApp deep link, UPI payment links, repeat-buyer CRM",
        "score": "8",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "SamAsha Jewellery",
        "handle": "samashajewellery",
        "city": "India",
        "state": "—",
        "type": "Oxidised / German silver earrings and jhumkas",
        "whatsapp": "+919711107695",
        "ordering": "DM or WhatsApp; unboxing video policy in indexed caption",
        "activity": "Indexed BUY NOW style oxidised reel",
        "bio": "German silver / oxidised assortment hashtags",
        "keywords": "Oxidised, DM, WhatsApp, jhumka",
        "qualified": "Explicit DM+WhatsApp ordering with policy text",
        "services": "Returns workflow automation, WhatsApp order bots, catalog PDF",
        "score": "8",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "https://www.google.com/maps/search/Hisar+bridal+chura",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Bridals Chura by Deepali Saluja",
        "handle": "bridals_chura",
        "city": "Hisar",
        "state": "Haryana",
        "type": "American diamond / custom bridal chura",
        "whatsapp": "+918607355159",
        "ordering": "DM or WhatsApp; COD mentioned in indexed caption",
        "activity": "Indexed chura customization post",
        "bio": "Custom colors and sizing; worldwide delivery claim in caption",
        "keywords": "Chura, AD chura, COD, WhatsApp",
        "qualified": "Strong WhatsApp + DM hybrid for high-ticket bridal SKU",
        "services": "3D lookbook, WhatsApp broadcast lists, bridal CRM",
        "score": "8",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "https://www.google.com/maps/search/Muvattupuzha+silver+jewellery",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Elara (Thottathil) Silver",
        "handle": "elara_muvattupuzha",
        "city": "Muvattupuzha",
        "state": "Kerala",
        "type": "92.5 hallmarked silver bracelets / chains",
        "whatsapp": "Verify on profile",
        "ordering": "Likely DM/WhatsApp typical for Kerala silver SMBs—confirm on profile",
        "activity": "Indexed silver bracelet product post (oEmbed author elara_muvattupuzha)",
        "bio": "Kerala silver SMB; hallmarked 925 focus in indexed caption",
        "keywords": "925, Kerala, silver bracelet",
        "qualified": "Hallmarked silver microbrand pattern",
        "services": "Hallmark trust badges on site, WhatsApp catalog, inventory sync",
        "score": "7",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Fashion Mantra Official",
        "handle": "fashion_mantra_official",
        "city": "India",
        "state": "—",
        "type": "Wholesale + single-piece fashion imitation jewellery",
        "whatsapp": "+919316331344",
        "ordering": "Screenshot booking to WhatsApp number in indexed caption",
        "activity": "Indexed price-on-picture wholesale post",
        "bio": "Screenshot-to-book SMB wholesale tone",
        "keywords": "Screenshot booking, wholesale, fashion jewellery",
        "qualified": "Screenshot order flow is textbook WhatsApp-commerce SMB",
        "services": "WhatsApp cart bots, wholesale tier pricing portal",
        "score": "8",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "https://www.google.com/maps/search/KP+Jewellers+Gandhi+Road+Khurja",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "KP Jeweller Khurja",
        "handle": "kp_jeweller",
        "city": "Khurja",
        "state": "Uttar Pradesh",
        "type": "Handmade pendants / gemstone fashion jewellery",
        "whatsapp": "+918279764265",
        "ordering": "Mobile number in indexed reel caption for Khurja shop",
        "activity": "Indexed reel with Gandhi Road address snippet",
        "bio": "KP Jewellers Khurja; gemstone pendant focus",
        "keywords": "Khurja, pendant, WhatsApp",
        "qualified": "SMB jeweller with on-caption phone contact",
        "services": "Google Maps optimisation, WhatsApp Business profile, product QR codes",
        "score": "6",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "https://www.google.com/maps/search/KPR+Jewellery+Hyderabad",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "KPR Jewellery",
        "handle": "kpr_jewellery",
        "city": "Hyderabad",
        "state": "Telangana",
        "type": "Pearl / gold fashion (Hyderabad pearl-house cluster—validate scale)",
        "whatsapp": "Verify on profile",
        "ordering": "Likely showroom + DM; confirm WhatsApp lines on profile",
        "activity": "Indexed post surfaced under Hyderabad jewellery SERP",
        "bio": "Hyderabad-focused jewellery content—validate enterprise vs SMB before pitch",
        "keywords": "Hyderabad, pearls, jewellery",
        "qualified": "Strong local brand signal; verify SMB fit on profile",
        "services": "Omnichannel inventory, appointment booking, ads",
        "score": "5",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "https://www.google.com/maps/search/Rajaji+Road+Kochi+jewellery",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Naksh Jewels Kochi",
        "handle": "_nakshjewels_",
        "city": "Kochi",
        "state": "Kerala",
        "type": "Silver diamond-style / bridal jewellery (Portuguese cut promos in local press reel)",
        "whatsapp": "Verify on profile",
        "ordering": "Discover via tagged Kochi retail collab reel—confirm order path",
        "activity": "Indexed Oh Kochi / local discovery reel",
        "bio": "Near Ambedkar Stadium Rajaji Road per indexed caption context",
        "keywords": "Kochi, silver, bridal",
        "qualified": "Local SMB discovery candidate from city lifestyle collab",
        "services": "Local influencer kits, WhatsApp concierge, micro-landing page",
        "score": "6",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "https://www.google.com/maps/search/Kolhapur+jewellery",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Kolhapuri Thushi (Rishabh Gold)",
        "handle": "kolhapurithushi",
        "city": "Kolhapur",
        "state": "Maharashtra",
        "type": "1 gram mangalsutra chains and vati pendants",
        "whatsapp": "+919403830260",
        "ordering": "WhatsApp in indexed caption; link-in-bio purchase mention",
        "activity": "Indexed mangalsutra product post",
        "bio": "1gm mangalsutra niche hashtags",
        "keywords": "Mangalsutra, 1 gram gold, WhatsApp",
        "qualified": "WhatsApp-led niche SKU seller",
        "services": "WhatsApp catalog, EMI/UPI flows, SEO for mangalsutra",
        "score": "8",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "https://www.google.com/maps/search/Palghar+bhaji+market+jewellery",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Jewellery of World (Mangalmurti Art)",
        "handle": "jewellery_of_world",
        "city": "Palghar",
        "state": "Maharashtra",
        "type": "Maharashtrian bridal jewellery (nath, thushi, mangalsutra)",
        "whatsapp": "+918446200337",
        "ordering": "WhatsApp number in indexed caption; rent/purchase options mentioned",
        "activity": "Indexed Maharashtrian jewellery post",
        "bio": "Palghar west market location in caption",
        "keywords": "Maharashtrian jewellery, Palghar, WhatsApp",
        "qualified": "Geo-tagged ethnic bridal SMB with explicit WhatsApp",
        "services": "Bilingual catalog, rental inventory tracker, WhatsApp automation",
        "score": "8",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "https://www.google.com/maps/search/Patiala+jewellery",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Kaurz Crown Jewellery",
        "handle": "kaurzcrownjewellery",
        "city": "Patiala",
        "state": "Punjab",
        "type": "925 silver with 22k gold plating heirloom-style sets",
        "whatsapp": "+919888298050",
        "ordering": "WhatsApp or DM per indexed fashion editorial style post",
        "activity": "Indexed Punjabi heritage jewellery post",
        "bio": "Handcrafted silver + gold plate; worldwide shipping claims",
        "keywords": "Punjab, 925 silver, DM, WhatsApp",
        "qualified": "Premium SMB with DM+WhatsApp dual channel",
        "services": "International checkout, CRM for custom orders, loyalty program",
        "score": "8",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "https://www.google.com/maps/search/Rohit+Bhai+Jewellers+Chandni+Chowk",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Rohit Bhai Jewellers",
        "handle": "rohitbhaijewellers",
        "city": "Delhi",
        "state": "Delhi",
        "type": "22k antique bridal gold sets (Chandni Chowk)",
        "whatsapp": "+919953916916",
        "ordering": "WhatsApp numbers in indexed reel caption; showroom visit emphasis",
        "activity": "Indexed bridal gold reel with address",
        "bio": "Kucha Mahajani showroom address in caption",
        "keywords": "Chandni Chowk, bridal gold, WhatsApp",
        "qualified": "Traditional jeweller using IG reels; still benefits from WhatsApp CRM",
        "services": "Video commerce, WhatsApp broadcast for new arrivals, appointment slots",
        "score": "6",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "https://www.google.com/maps/search/Jai+Guru+Jewellers+Thiruvallur",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Jai Guru Jewellers Tiruvallur",
        "handle": "jaigurujewellers_tiruvallur",
        "city": "Thiruvallur",
        "state": "Tamil Nadu",
        "type": "Gold chains / wedding haram (real gold retailer)",
        "whatsapp": "+919600972227",
        "ordering": "Call or WhatsApp in indexed collaboration caption",
        "activity": "Indexed gold chain promo via lifestyle collab reel",
        "bio": "Kakkalur area address referenced in indexed content",
        "keywords": "Gold chains, Tamil Nadu, WhatsApp",
        "qualified": "Hybrid physical + phone/WhatsApp discovery",
        "services": "Click-to-WhatsApp ads, inventory reels pipeline, CRM",
        "score": "5",
    },
    {
        "followers": "Verify on profile",
        "email": "Not listed",
        "website_yn": "No",
        "website_url": "",
        "engagement": "Not extracted from SERP",
        "maps": "",
        "notes": "Sourced from indexed public Instagram captions/SERP snippets; verify bio and recency before outreach.",
        "business": "Maharashtrian Jewelry",
        "handle": "maharashtrian_jewelry",
        "city": "Maharashtra",
        "state": "Maharashtra",
        "type": "Mangalsutra and Maharashtrian necklace reels",
        "whatsapp": "Verify on profile",
        "ordering": "Caption in snippet focused on lengths/prices—confirm WhatsApp on profile",
        "activity": "Indexed mangalsutra length post",
        "bio": "Maharashtrian jewellery assortment hashtags",
        "keywords": "Mangalsutra, Maharashtra, reels",
        "qualified": "Niche ethnic handle worth profile pass for WA capture",
        "services": "WhatsApp-first catalog, Marathi/English bilingual flows",
        "score": "6",
    },
]

def render_txt(leads: list[dict[str, str]]) -> str:
    blocks: list[str] = []
    for i, lead in enumerate(leads, start=1):
        h = lead["handle"]
        handle_clean = h.strip().lstrip("@")
        url = f"https://www.instagram.com/{handle_clean}/"
        lines = [
            "",
            "=" * 50,
            f"LEAD #{i}",
            "=" * 50,
            f"Business Name: {lead['business']}",
            f"Instagram Handle: @{handle_clean}",
            f"Instagram URL: {url}",
            f"Followers Count: {lead['followers']}",
            f"City: {lead['city']}",
            f"State: {lead['state']}",
            f"Business Type: {lead['type']}",
            f"WhatsApp Number: {lead['whatsapp']}",
            f"Email: {lead['email']}",
            f"Ordering Method: {lead['ordering']}",
            f"Website Present: {lead['website_yn']}",
            f"Website URL: {lead['website_url']}",
            f"Recent Activity Date: {lead['activity']}",
            f"Average Engagement: {lead['engagement']}",
            f"Bio Text: {lead['bio']}",
            f"Keywords: {lead['keywords']}",
            f"Reason Qualified: {lead['qualified']}",
            f"Potential Services Needed: {lead['services']}",
            f"Google Maps Link: {lead['maps']}",
            f"Lead Quality Score: {lead['score']}",
            f"Notes: {lead['notes']}",
        ]
        blocks.append("\n".join(lines))
    return "\n".join(blocks).lstrip("\n") + "\n"


def main() -> None:
    out = Path(__file__).resolve().parents[1] / "india_jewellery_instagram_leads.txt"
    out.write_text(render_txt(LEADS), encoding="utf-8")
    print(f"Wrote {out} ({len(LEADS)} leads)")


if __name__ == "__main__":
    main()
