#!/usr/bin/env python3
"""Render india_jewellery_instagram_leads.txt with 100 unique handles.

Priority: (1) caption-verified WhatsApp/DM signals from indexed posts,
(2) prior research handoff SMB handles, (3) public search-index scrape handles
(DuckDuckGo html, May 2026) for additional unique accounts. Follower counts and
engagement are generally not public; marked Unknown unless evidenced.
"""
from __future__ import annotations

from pathlib import Path

VERIFIED: list[dict[str, str]] = [
    {"business": "Khushbu Jewellers (Tinwari)", "handle": "khushbu_jewellers_tinwari", "city": "Tinwari", "state": "Madhya Pradesh", "type": "Silver / gold-polish fashion jewellery", "wa": "+919929595357", "email": "Unknown", "order": "WhatsApp screenshot for order; COD mentioned in indexed posts", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "silver, rajputi, COD, WhatsApp screenshot", "why": "Indexed Instagram posts show WhatsApp ordering and customization language.", "svc": "Website, WhatsApp automation, catalog microsite, CRM", "maps": "Unknown", "score": "8", "notes": "instagram.com/khushbu_jewellers_tinwari reels/posts."},
    {"business": "Jewels of Karnataka", "handle": "jewelsofkarnataka", "city": "Bengaluru", "state": "Karnataka", "type": "One-gram gold / fashion sets", "wa": "+919740234813", "email": "Unknown", "order": "WhatsApp (caption)", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "one gram gold, JK collection", "why": "Indexed post text references WhatsApp contact for orders.", "svc": "WhatsApp API, lightweight checkout", "maps": "Unknown", "score": "8", "notes": "instagram.com/jewelsofkarnataka post."},
    {"business": "Jewellery Palace BJS", "handle": "_jewellery_palace_bjs", "city": "Unknown", "state": "India", "type": "Imitation / fashion jewellery", "wa": "+918440038551", "email": "Unknown", "order": "Order on WhatsApp (caption)", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "nath, choti, SKU codes", "why": "Explicit WhatsApp order line in indexed caption.", "svc": "WhatsApp flows, inventory codes", "maps": "Unknown", "score": "7", "notes": "instagram.com/_jewellery_palace_bjs post."},
    {"business": "Jewellery Shopper", "handle": "jewellery_shopper_", "city": "Unknown", "state": "India", "type": "Silver / plated pieces", "wa": "+918905291031", "email": "Unknown", "order": "WhatsApp screenshot for order (earliest indexed number)", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "silver, COD, reels", "why": "Indexed reels show WhatsApp screenshot ordering; some posts may show alternate numbers.", "svc": "WhatsApp automation, payment links", "maps": "Unknown", "score": "7", "notes": "Use earliest indexed WA; reconcile duplicates in CRM."},
    {"business": "Lakshmi Creations (Imitation)", "handle": "lakshmi_creations_9", "city": "Hyderabad", "state": "Telangana", "type": "Imitation wholesale", "wa": "+919849567353", "email": "Unknown", "order": "WhatsApp for orders/collections", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "wholesale, jhumkas", "why": "Wholesale pricing + WhatsApp contact in indexed caption.", "svc": "B2B catalog, WA broadcast compliance", "maps": "Unknown", "score": "8", "notes": "instagram.com/lakshmi_creations_9 post."},
    {"business": "Chudiwale Fashion Jewellery", "handle": "chudiwale_", "city": "Unknown", "state": "India", "type": "Bangles / bridal fashion", "wa": "+917972380643", "email": "Unknown", "order": "WhatsApp booking (caption)", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "customized bangles, bridal", "why": "WhatsApp booking called out in indexed post.", "svc": "WA booking bot, IG ads", "maps": "Unknown", "score": "8", "notes": "instagram.com/chudiwale_ post."},
    {"business": "Janvish One Gram Gold & Boutique", "handle": "janvish_onegramgold_and_boutiq", "city": "Hyderabad", "state": "Telangana", "type": "One-gram gold boutique", "wa": "+918121769801", "email": "Unknown", "order": "WhatsApp screenshot + WhatsApp group updates", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "one gram gold, free ship", "why": "Strong WhatsApp-first ordering language in indexed reel.", "svc": "Community migration, payments, micro-store", "maps": "Unknown", "score": "9", "notes": "instagram.com/janvish_onegramgold_and_boutiq reel."},
    {"business": "Begum Bazar Wholesale Jewelry", "handle": "begumbazar_wholesale_jewelry", "city": "Hyderabad", "state": "Telangana", "type": "One-gram / guttapusalu sets", "wa": "+919618136342", "email": "Unknown", "order": "DM or WhatsApp; screenshot flow", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "Begum Bazar, one gram gold, UPI", "why": "Explicit DM/WhatsApp instructions in indexed post.", "svc": "Wholesale CRM, UPI receipts", "maps": "Unknown", "score": "8", "notes": "instagram.com/begumbazar_wholesale_jewelry post."},
    {"business": "Rajputi Jewellery Wholesaler", "handle": "rajputi_jewelery_wholsaler_s.c", "city": "Unknown", "state": "Rajasthan", "type": "Rajputi imitation sets", "wa": "+917877634674", "email": "Unknown", "order": "WhatsApp + group link mentions", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "rajputi, wholesale", "why": "Wholesale-forward WhatsApp + group join pattern.", "svc": "WA automation for groups", "maps": "Unknown", "score": "7", "notes": "instagram.com/rajputi_jewelery_wholsaler_s.c reel."},
    {"business": "Wholesale Pearls Jewells Onkar", "handle": "wholesalepearlsjewells.onkar", "city": "Unknown", "state": "India", "type": "Pearl / fashion wholesale", "wa": "+919996698633", "email": "Unknown", "order": "DM for full catalog (caption)", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "pearls, manufacturers, DM catalog", "why": "DM-for-catalog manufacturer pattern.", "svc": "PDF catalog site, CRM", "maps": "Unknown", "score": "7", "notes": "instagram.com/wholesalepearlsjewells.onkar reel."},
    {"business": "Sujatha Gold Covering Works", "handle": "sujatha_gold_covering_works", "city": "Machilipatnam", "state": "Andhra Pradesh", "type": "Micro-plated / one-gram gold", "wa": "+917382222208", "email": "Unknown", "order": "WhatsApp bookings; bulk line +917036132171", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "one gram gold, COD, video call", "why": "Multiple WhatsApp lines + COD + video call in indexed caption.", "svc": "Multi-agent WA, order routing", "maps": "Unknown", "score": "8", "notes": "instagram.com/sujatha_gold_covering_works reel."},
    {"business": "Biswakarma Jewellery Shilpalaya", "handle": "bjs2k", "city": "Kolkata", "state": "West Bengal", "type": "Diamond-look / nosepin / earrings", "wa": "+919874085669", "email": "Unknown", "order": "WhatsApp inquiries (caption)", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "WhatsApp details, diamond look", "why": "Indexed posts push WhatsApp contact for orders.", "svc": "Lead tracking, click-to-WA ads", "maps": "Unknown", "score": "8", "notes": "instagram.com/bjs2k posts."},
    {"business": "Lucknow Artificial Jewellery", "handle": "lucknow_artificial_jewellery_", "city": "Lucknow", "state": "Uttar Pradesh", "type": "Artificial / one-gram polish", "wa": "+918957754721", "email": "Unknown", "order": "Phone booking / WhatsApp (caption)", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "COD, shipping India, Lucknow", "why": "Booking number published in indexed reel caption.", "svc": "Logistics messaging, WA bot", "maps": "Unknown", "score": "8", "notes": "instagram.com/lucknow_artificial_jewellery_ reel."},
    {"business": "Flabel Creations", "handle": "flabelcreations", "city": "Unknown", "state": "India", "type": "Fashion / diamond-look sets", "wa": "+917711990044", "email": "Unknown", "order": "DM + WhatsApp (indexed post snippet)", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "same day dispatch, DM details", "why": "Indexed post snippet shows DM + WhatsApp ordering.", "svc": "IG inbox + WA bridge", "maps": "Unknown", "score": "7", "notes": "instagram.com/p/DIneGuzT9wb (More posts from flabelcreations)."},
    {"business": "Jewellery by Rohika", "handle": "jewellery_by_rohika", "city": "Unknown", "state": "India", "type": "Polki / kundan bridal sets", "wa": "+916280926290", "email": "Unknown", "order": "DM or WhatsApp; website checkout also", "web": "Yes", "url": "https://www.rohikastore.com/", "recent": "Unknown", "engage": "Unknown", "kw": "kundan bridal, worldwide ship", "why": "DM + WA ordering; still SMB positioning in caption.", "svc": "Migrate to cleaner checkout, CRM", "maps": "Unknown", "score": "5", "notes": "Has standalone ecommerce site; lower fit for no-website stack."},
    {"business": "Divanka.in", "handle": "divanka.in", "city": "Unknown", "state": "India", "type": "Fashion jhumkas / sets", "wa": "+919207376139", "email": "Unknown", "order": "WhatsApp or website shop", "web": "Yes", "url": "https://www.divanka.in/", "recent": "Unknown", "engage": "Unknown", "kw": "jhumka, shop link", "why": "WhatsApp path exists; professional site reduces no-website fit.", "svc": "Ads + retention", "maps": "Unknown", "score": "4", "notes": "Search snippet shows divanka.in + WhatsApp."},
]

HANDOFF: list[dict[str, str]] = [
    {"business": "Trend Jewelryys", "handle": "trend_jewelryys", "city": "Unknown", "state": "India", "type": "Fashion jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM / comments (typical IG commerce)", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "trending reels", "why": "Indexed via search; confirm ordering path in profile.", "svc": "IG DM tooling", "maps": "Unknown", "score": "5", "notes": "Search index."},
    {"business": "Oxidised Jewellery Wholesaler", "handle": "oxidised_jewellery_wholesaler", "city": "Unknown", "state": "India", "type": "Oxidised wholesale", "wa": "Unknown", "email": "Unknown", "order": "Likely WA/DM wholesale", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "oxidised, wholesale", "why": "Wholesale-oriented handle; verify contact in bio.", "svc": "B2B catalog", "maps": "Unknown", "score": "6", "notes": "Search index."},
    {"business": "Gohar Jewels Official", "handle": "goharjewelsofficial", "city": "Unknown", "state": "India", "type": "Handmade resin jhumkas", "wa": "Unknown", "email": "Unknown", "order": "DM/custom orders (typical niche)", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "resin, pressed flowers", "why": "Indexed product post highlights handmade resin jhumkas.", "svc": "Micro-store", "maps": "Unknown", "score": "7", "notes": "instagram.com/goharjewelsofficial post."},
    {"business": "The Madras Art Studio", "handle": "themadras_artstudio", "city": "Chennai", "state": "Tamil Nadu", "type": "Resin jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM to order; customization (indexed caption)", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "resin, customize", "why": "Explicit DM-to-order language in indexed content.", "svc": "Order forms", "maps": "Unknown", "score": "8", "notes": "Public caption: DM to order."},
    {"business": "Aashu's Pearl Creation", "handle": "aashus_pearl_creation", "city": "Unknown", "state": "Maharashtra", "type": "Handmade pearl / traditional", "wa": "Unknown", "email": "Unknown", "order": "DM for order (caption)", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "handmade, Maharashtrian", "why": "DM ordering in indexed reel.", "svc": "Ecommerce for custom SKUs", "maps": "Unknown", "score": "7", "notes": "instagram.com/aashus_pearl_creation reel."},
    {"business": "Samskruthi Jewellers", "handle": "samskruthijewellers", "city": "Unknown", "state": "India", "type": "Fashion / temple style", "wa": "Unknown", "email": "Unknown", "order": "Comments/DM price asks", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "customer comments", "why": "High comment interaction pattern in search snippet.", "svc": "IG inbox tooling", "maps": "Unknown", "score": "6", "notes": "Search snippet."},
    {"business": "Varudi Jewellers", "handle": "varudijewellers", "city": "Surat", "state": "Gujarat", "type": "Gold jewellery (DM instant buy)", "wa": "Unknown", "email": "Unknown", "order": "DM for instant buy (indexed reel title)", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "Surat, DM, delivery", "why": "Reel framing emphasizes DM-based buying.", "svc": "Trust pages, chatbot", "maps": "Unknown", "score": "6", "notes": "instagram.com/varudijewellers reel."},
    {"business": "BJ Imitation Ahmedabad", "handle": "bj_imitation_ahmedabad", "city": "Ahmedabad", "state": "Gujarat", "type": "Brass / imitation rings", "wa": "Unknown", "email": "Unknown", "order": "Likely DM/WhatsApp", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "Ahmedabad, brass", "why": "Imitation retailer style content in index.", "svc": "Catalog microsite", "maps": "Unknown", "score": "6", "notes": "instagram.com/bj_imitation_ahmedabad reel."},
    {"business": "Chennai Jazz (Jazz Collections)", "handle": "chennai_jazz", "city": "Chennai", "state": "Tamil Nadu", "type": "Bridal / temple rental & sale", "wa": "+919841229944", "email": "Unknown", "order": "Call/WhatsApp + video call booking", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "temple jewellery, rental", "why": "Indexed caption shows WhatsApp and video call booking.", "svc": "Booking CRM", "maps": "Unknown", "score": "7", "notes": "instagram.com/chennai_jazz post."},
    {"business": "Luxe Tashion Jewellery", "handle": "luxetashion_jewellery", "city": "Chennai", "state": "Tamil Nadu", "type": "Fashion / bridal", "wa": "+919841229944", "email": "Unknown", "order": "Cross-promoted with chennai_jazz", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "bridal", "why": "Tagged cluster with chennai_jazz.", "svc": "WA automation", "maps": "Unknown", "score": "6", "notes": "Tagged in chennai_jazz caption."},
    {"business": "Jazz Bangle Store", "handle": "jazz_banglestore", "city": "Chennai", "state": "Tamil Nadu", "type": "Bangles / fashion", "wa": "+919841229944", "email": "Unknown", "order": "Same cluster as chennai_jazz", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "bangles", "why": "Tagged cluster; likely shared operations.", "svc": "WA automation", "maps": "Unknown", "score": "6", "notes": "Tagged in chennai_jazz caption."},
    {"business": "Chettinad Creations", "handle": "chettinad_creations", "city": "Unknown", "state": "Tamil Nadu", "type": "Temple / offer posts", "wa": "Unknown", "email": "Unknown", "order": "DM/comment commerce", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "Chettinad, offers", "why": "Snippet shows engagement on offer posts.", "svc": "Checkout", "maps": "Unknown", "score": "6", "notes": "Search index."},
    {"business": "Wear N Shine Jewelry", "handle": "wear_nd_shine_jewelry", "city": "Unknown", "state": "India", "type": "Fashion jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM-first", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "fashion jewelry", "why": "Indexed via search.", "svc": "IG growth", "maps": "Unknown", "score": "5", "notes": "Search index."},
    {"business": "Kalyani Jewellers (Fashion)", "handle": "kalyani_jewellers_", "city": "Unknown", "state": "India", "type": "Gold-plated fashion sets", "wa": "Unknown", "email": "Unknown", "order": "Link in bio + DM (caption)", "web": "Unknown", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "link in bio, DM", "why": "Mix of bio link + DM; verify storefront type.", "svc": "Owned checkout strategy", "maps": "Unknown", "score": "6", "notes": "instagram.com/kalyani_jewellers_ post."},
    {"business": "Gobind Jewellers", "handle": "gobindjewellers", "city": "Durgapur", "state": "West Bengal", "type": "Gold / lightweight gold", "wa": "+919593222111", "email": "Unknown", "order": "Phone contact; showroom-led", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "Durgapur, hallmarked", "why": "Local jeweller IG with published phone.", "svc": "Local SEO + WA business profile", "maps": "Unknown", "score": "5", "notes": "instagram.com/gobindjewellers post."},
    {"business": "DM Jewellers", "handle": "dm_jewellers", "city": "Pune", "state": "Maharashtra", "type": "Diamond jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM for details", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "diamond, bridal", "why": "Explicit DM CTA in indexed reel.", "svc": "Appointment CRM", "maps": "Unknown", "score": "6", "notes": "instagram.com/dm_jewellers reel."},
    {"business": "Pooja Jewels", "handle": "poojajewels_", "city": "Unknown", "state": "India", "type": "Fashion jewellery reels", "wa": "Unknown", "email": "Unknown", "order": "DM commerce", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "reels", "why": "Search snippet ties reels to handle.", "svc": "IG sales ops", "maps": "Unknown", "score": "6", "notes": "Search index."},
    {"business": "Oberoi Jewellery (Wholesale)", "handle": "oberoi_jewellery", "city": "Unknown", "state": "India", "type": "Artificial gold wholesale", "wa": "+919530775152", "email": "Unknown", "order": "Bulk contact via phone in caption", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "wholesale, worldwide shipping", "why": "Wholesale-forward caption; confirm SMB scale.", "svc": "B2B portal", "maps": "Unknown", "score": "5", "notes": "Indexed post DJO9wcUz26p."},
    {"business": "Rajshree Jewellers Hyderabad", "handle": "rajshreejewellershyderabad", "city": "Hyderabad", "state": "Telangana", "type": "Showroom-led gold", "wa": "Unknown", "email": "Unknown", "order": "DM/call typical", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "Hyderabad showroom", "why": "Hyderabad jeweller content chain.", "svc": "Local ads + WA", "maps": "Unknown", "score": "5", "notes": "Research handoff / search chain."},
    {"business": "Silver N Glamour", "handle": "silverndglamour", "city": "Unknown", "state": "India", "type": "Silver / custom", "wa": "Unknown", "email": "Unknown", "order": "DM/custom (research pool)", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "silver, custom", "why": "Handoff research pool handle.", "svc": "Custom order webform", "maps": "Unknown", "score": "6", "notes": "Handoff list; verify contacts."},
    {"business": "Beautiful Creations", "handle": "beautiful_creations0365", "city": "Unknown", "state": "India", "type": "Artificial / fashion", "wa": "Unknown", "email": "Unknown", "order": "Likely WA/DM", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "creations", "why": "Handoff pool.", "svc": "IG + WA", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "S Swarnakar And Son", "handle": "s.swarnakarandson", "city": "Kolkata", "state": "West Bengal", "type": "Traditional gold SMB", "wa": "Unknown", "email": "Unknown", "order": "Showroom + IG", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "Kolkata", "why": "Handoff pool.", "svc": "Hybrid booking", "maps": "Unknown", "score": "4", "notes": "Handoff list."},
    {"business": "Hira Panna Jewels", "handle": "hirapannajewels", "city": "Mumbai", "state": "Maharashtra", "type": "Fashion / gold SMB", "wa": "Unknown", "email": "Unknown", "order": "DM/phone typical", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "Mumbai", "why": "Handoff pool.", "svc": "WA business profile", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Rohit Bhai Jewellers", "handle": "rohitbhaijewellers", "city": "Unknown", "state": "India", "type": "Gold SMB", "wa": "Unknown", "email": "Unknown", "order": "Phone/DM", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "traditional", "why": "Handoff pool.", "svc": "Lead capture", "maps": "Unknown", "score": "4", "notes": "Handoff list."},
    {"business": "Radha Rani Imitation", "handle": "radha_rani_imitation_7", "city": "Unknown", "state": "India", "type": "Imitation sets", "wa": "Unknown", "email": "Unknown", "order": "WA/DM typical niche", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "imitation", "why": "Handoff pool.", "svc": "Catalog", "maps": "Unknown", "score": "6", "notes": "Handoff list."},
    {"business": "Hyderabadi Jewellery", "handle": "hyderabadijewllery", "city": "Hyderabad", "state": "Telangana", "type": "Local fashion jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM/WA typical", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "Hyderabad", "why": "Handoff pool.", "svc": "Localization ads", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Gahane Jewellery", "handle": "gahanejewellery", "city": "Unknown", "state": "India", "type": "Designer fashion", "wa": "Unknown", "email": "Unknown", "order": "DM commerce", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "designer", "why": "Handoff pool.", "svc": "Lookbook site", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Silver Store Chennai", "handle": "silver_store_chennai", "city": "Chennai", "state": "Tamil Nadu", "type": "Silver retail", "wa": "Unknown", "email": "Unknown", "order": "Store + IG", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "silver", "why": "Handoff pool.", "svc": "POS + IG", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Chezian Velli Maaligai", "handle": "chezian_velli_maaligai", "city": "Chennai", "state": "Tamil Nadu", "type": "Silver (Tamil retail)", "wa": "Unknown", "email": "Unknown", "order": "Traditional retail + IG", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "Tamil, silver", "why": "Handoff pool.", "svc": "Bilingual site", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Rashi Collection", "handle": "rashi_collection_", "city": "Unknown", "state": "India", "type": "Imitation collections", "wa": "Unknown", "email": "Unknown", "order": "DM/WA", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "collection", "why": "Handoff pool.", "svc": "WA", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Rajaveer Imitation Ahmedabad", "handle": "rajaveer_imitation_ahemadabad", "city": "Ahmedabad", "state": "Gujarat", "type": "Imitation wholesale/retail", "wa": "Unknown", "email": "Unknown", "order": "WA common niche", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "Ahmedabad imitation", "why": "Handoff pool.", "svc": "Wholesale IG", "maps": "Unknown", "score": "6", "notes": "Handoff list."},
    {"business": "Sai Raj Immitation", "handle": "sairajimmitation_01", "city": "Unknown", "state": "India", "type": "Imitation jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM/WA", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "imitation", "why": "Handoff pool.", "svc": "Catalog", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Just Kundan", "handle": "just_kundan", "city": "Unknown", "state": "India", "type": "Kundan fashion sets", "wa": "Unknown", "email": "Unknown", "order": "DM commerce", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "kundan", "why": "Handoff pool.", "svc": "Lookbook", "maps": "Unknown", "score": "6", "notes": "Handoff list."},
    {"business": "Kundan Art Jewellers", "handle": "kundan_art_jewellers", "city": "Unknown", "state": "India", "type": "Kundan / bridal", "wa": "Unknown", "email": "Unknown", "order": "DM/WA", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "bridal", "why": "Handoff pool.", "svc": "Landing pages", "maps": "Unknown", "score": "6", "notes": "Handoff list."},
    {"business": "Vari Artificials Jewellery", "handle": "vari_artificials_jewellery", "city": "Unknown", "state": "India", "type": "Artificial jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM/WA", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "artificial", "why": "Handoff pool.", "svc": "WA", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Sakhi One Gram Gold Jewellery", "handle": "sakhi_1_gram_gold_jewellery", "city": "Unknown", "state": "India", "type": "One-gram gold", "wa": "Unknown", "email": "Unknown", "order": "WA groups common", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "one gram gold", "why": "Handoff pool.", "svc": "Group tooling", "maps": "Unknown", "score": "7", "notes": "Handoff list."},
    {"business": "Roshi Collections", "handle": "roshi.collections", "city": "Unknown", "state": "India", "type": "Fashion jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM commerce", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "collections", "why": "Handoff pool.", "svc": "IG shop", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "SD Beads", "handle": "sd_beads", "city": "Unknown", "state": "India", "type": "Beads / components", "wa": "Unknown", "email": "Unknown", "order": "B2B DM", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "beads", "why": "Handoff pool.", "svc": "B2B portal", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "South Indian Temple Jewellery", "handle": "southindian__templejewellery", "city": "Unknown", "state": "South India", "type": "Temple jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM/WA", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "temple", "why": "Handoff pool.", "svc": "SEO + WA", "maps": "Unknown", "score": "7", "notes": "Handoff list."},
    {"business": "JJ Resin Memo", "handle": "jj_resin.memo", "city": "Unknown", "state": "India", "type": "Resin accessories", "wa": "Unknown", "email": "Unknown", "order": "DM orders", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "resin", "why": "Handoff pool.", "svc": "Etsy-like checkout", "maps": "Unknown", "score": "6", "notes": "Handoff list."},
    {"business": "Farbfleck Resin Art", "handle": "farbfleck_resinart", "city": "Unknown", "state": "India", "type": "Resin art jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM custom", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "resin art", "why": "Handoff pool.", "svc": "Portfolio site", "maps": "Unknown", "score": "6", "notes": "Handoff list."},
    {"business": "Sampati Official", "handle": "sampati_official", "city": "Unknown", "state": "India", "type": "Fashion jewellery brandlet", "wa": "Unknown", "email": "Unknown", "order": "DM/WA", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "official", "why": "Handoff pool.", "svc": "Brand site", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Sumatiara Creation", "handle": "sumatiara_creation", "city": "Unknown", "state": "India", "type": "Handmade / boutique", "wa": "Unknown", "email": "Unknown", "order": "DM orders", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "handmade", "why": "Handoff pool.", "svc": "Checkout", "maps": "Unknown", "score": "6", "notes": "Handoff list."},
    {"business": "Mahi Jewelry", "handle": "mahijewelry", "city": "Unknown", "state": "India", "type": "Fashion jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM commerce", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "fashion", "why": "Handoff pool.", "svc": "Reels ads", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Lakshmi Jewells", "handle": "lakshmijewells", "city": "Unknown", "state": "India", "type": "Imitation / fashion", "wa": "Unknown", "email": "Unknown", "order": "DM/WA", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "imitation", "why": "Handoff pool.", "svc": "WA", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Jodhpuri Silver", "handle": "jodhpuri_silver", "city": "Jodhpur", "state": "Rajasthan", "type": "Silver tribal / jodhpuri", "wa": "Unknown", "email": "Unknown", "order": "DM typical", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "silver, jodhpuri", "why": "Handoff pool.", "svc": "Artisan ecommerce", "maps": "Unknown", "score": "7", "notes": "Handoff list."},
    {"business": "Lavanya Jewellers SLJ", "handle": "lavanyajewellers_slj", "city": "Unknown", "state": "India", "type": "Fashion jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM/WA", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "lavanya", "why": "Handoff pool.", "svc": "CRM", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Omkar Jewels Surat", "handle": "omkar_jewels_surat", "city": "Surat", "state": "Gujarat", "type": "Fashion / gold jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM/WA", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "Surat", "why": "Handoff pool.", "svc": "B2C site", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Eye of Shakti", "handle": "eyeofshakti", "city": "Unknown", "state": "India", "type": "Statement / spiritual", "wa": "Unknown", "email": "Unknown", "order": "DM niche brand", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "spiritual", "why": "Handoff pool.", "svc": "Storytelling site", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Asha Bangles Official", "handle": "ashabanglesofficial", "city": "Unknown", "state": "India", "type": "Bangles specialist", "wa": "Unknown", "email": "Unknown", "order": "DM/WA", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "bangles", "why": "Handoff pool.", "svc": "Configurator", "maps": "Unknown", "score": "6", "notes": "Handoff list."},
    {"business": "Dreams Jewellery 2023", "handle": "dreams.jewellery2023", "city": "Unknown", "state": "India", "type": "Fashion jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM commerce", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "new seller", "why": "Handoff pool.", "svc": "Starter stack", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Omaira and Binish", "handle": "omaira_and_binish", "city": "Unknown", "state": "India", "type": "Boutique jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "boutique", "why": "Handoff pool.", "svc": "Duo brand site", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Amita Jewellery", "handle": "amita_jewellery", "city": "Unknown", "state": "India", "type": "Fashion jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM/WA", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "fashion", "why": "Handoff pool.", "svc": "CRM", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Harshi Anbu Jewellery", "handle": "harshianbujewellery", "city": "Unknown", "state": "India", "type": "Fashion jewellery", "wa": "Unknown", "email": "Unknown", "order": "DM", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "Tamil/India mix", "why": "Handoff pool.", "svc": "Localization", "maps": "Unknown", "score": "5", "notes": "Handoff list."},
    {"business": "Amora Arts and Jewels", "handle": "amoraartsandjewels", "city": "Unknown", "state": "India", "type": "Jewellery + art", "wa": "Unknown", "email": "Unknown", "order": "DM", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "pricing comments", "why": "Search snippet shows high engagement price inquiries.", "svc": "IG inbox", "maps": "Unknown", "score": "6", "notes": "instagram.com/amoraartsandjewels."},
    {"business": "Nikhil Jewellery Hyderabad", "handle": "nikhiljewelleryhyderabad", "city": "Hyderabad", "state": "Telangana", "type": "916 gold showroom content", "wa": "Unknown", "email": "Unknown", "order": "Showroom-first", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "916 gold, LB Nagar", "why": "Traditional gold jeweller; weaker IG-only fit.", "svc": "Appointment booking", "maps": "Unknown", "score": "3", "notes": "Showroom-heavy; lower priority for IG-only thesis."},
    {"business": "Yuvraj Nosepins", "handle": "yuvraj_nosepins", "city": "Delhi", "state": "Delhi", "type": "Gold nosepins (Chandni Chowk)", "wa": "Unknown", "email": "Unknown", "order": "Store-first", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "Chandni Chowk, gold", "why": "Pvt Ltd style retail; physical-first.", "svc": "Inventory + IG", "maps": "Unknown", "score": "3", "notes": "instagram.com/yuvraj_nosepins reel."},
    {"business": "Vir Kanya Jewels Chennai", "handle": "virkanyajewels_chennai", "city": "Chennai", "state": "Tamil Nadu", "type": "Fine gold jewellery", "wa": "Unknown", "email": "Unknown", "order": "Luxury retail", "web": "Unknown", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "fine gold", "why": "Luxury positioning; not core imitation SMB.", "svc": "N/A", "maps": "Unknown", "score": "2", "notes": "Luxury fine jewellery; low fit for IG-DM SMB stack."},
    {"business": "Aarti Jewellers Surat", "handle": "aartijewellers.surat", "city": "Surat", "state": "Gujarat", "type": "Gold jewellery showroom offers", "wa": "Unknown", "email": "Unknown", "order": "Store visits + IG promos", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "Surat, making charges offers", "why": "Indexed reel promotes in-store offers.", "svc": "Local IG ads", "maps": "Unknown", "score": "4", "notes": "instagram.com/aartijewellers.surat reel."},
    {"business": "Mahavir Imitation Jewelle", "handle": "mahavirimitationjewelle", "city": "Surat", "state": "Gujarat", "type": "Imitation jewellery", "wa": "Unknown", "email": "Unknown", "order": "Likely WA/DM (niche)", "web": "No", "url": "Unknown", "recent": "Unknown", "engage": "Unknown", "kw": "imitation, Surat", "why": "Imitation handle surfaced in Surat wholesale search index.", "svc": "Catalog + WA", "maps": "Unknown", "score": "6", "notes": "instagram.com/mahavirimitationjewelle."},
    {"business": "D9 Creation Jewellery", "handle": "d9creation_jewellery", "city": "Jaipur", "state": "Rajasthan", "type": "Oxidised german silver", "wa": "Unknown", "email": "Unknown", "order": "Website checkout linked in posts", "web": "Yes", "url": "https://d9creation.com/", "recent": "Unknown", "engage": "Unknown", "kw": "oxidised, german silver", "why": "Has ecommerce domain in caption; still SMB manufacturer vibe.", "svc": "Ads + retention", "maps": "Unknown", "score": "3", "notes": "Has standalone ecommerce site."},
]

SCRAPED_HANDLES = [
    "3ijsdelhi","DeviJewellery_","_jewellery_vizag","_vizag_jewellery_","bhopal_art_jewelry","bhopal_jewelry04","bhopal_jewelry_04","challani_jewellery","coimbatore_jewellery_show","coimbatore_onegramjewellery","coimbatorejewellers","darjewellery_","delhiartificialjewellery","dkcreations_jewellery","emblishcoimbatore","girlsfashion.pune","gold_jewellery_lucknow","grishaasvizag","hrievajewels","imitation_jewellary_delhi","imitation_jewellery.delhi","imitationjewellery.delhi","imitationjewellery__","jaipur_kundan","jaipur_kundan_jewelers","jaipur_kundan_jewellery","jewellerskolkata","jewellery._kolkata","jewellery.kolkata","jewellery.wholesaler_pune","jewellery_kolkata","jewellery_kolkata__","jewellery_wholesale_surat","jewellss_by_sukritiii","kolkata_jewellery","kundan.jewellery.jaipur","ladlajewellers","mk_jewellers_kolkata","mypunefashion","one_gram_gold_hyderabad_1","one_gram_gold_jewellery","pune_jewellery","radhekrishna8613","starjewellery.coimbatore","sumanjewellery_coimbatore","surat.wholesale","surat_jewelry","temple.jewellery.in","temple__jewellery_","temple_jewellery","temple_jewellerycollection","vasodharijewellers","viaarafinejewels","vijayasrentaljewellery","vizag_jewellery_rental","vjewellerymart","vrajjewellers.vadodara","vysyarajujewellers",
    "artifyindiaaa","indian_kundan_jewelry","kattam.in","nakshatra_jewellery_3","nakshatra_jewels","niranjanam_jewellery","traditional_south_indian_jewel","wholesale_jewellery_09","marwari_silver_store","rajesh_silver_jewellery","silver_jewellery_indian","silverjewellery.india","siri_silver_jewellery","southindianjewelleryonline","bridal_jewellery._","bridal_jewellery_by_gjint","bridaljewelleryshop",
]

EXCLUDE = {"templeneedlenthread","jewellery_pages","usa.jewelry.usa","weddinganswers","popular"}


def row_from_handle(handle: str) -> dict[str, str]:
    pretty = handle.replace("_", " ").replace(".", " ").strip().title()
    return {
        "business": pretty + " (IG)",
        "handle": handle,
        "city": "Unknown",
        "state": "India",
        "type": "Fashion / imitation / silver / temple jewellery (verify)",
        "wa": "Unknown",
        "email": "Unknown",
        "order": "Likely DM/WhatsApp (verify in bio/captions)",
        "web": "Unknown",
        "url": "Unknown",
        "recent": "Unknown",
        "engage": "Unknown",
        "kw": "city/niche keywords from search index",
        "why": "Handle surfaced via public search index scrape (DuckDuckGo html) for Indian jewellery queries.",
        "svc": "Website, WhatsApp automation, IG growth, CRM",
        "maps": "Unknown",
        "score": "5",
        "notes": "Automated discovery — confirm niche, location, and ordering path before outreach.",
    }


def main() -> None:
    out: list[dict[str, str]] = []
    seen_h: set[str] = set()
    seen_p: set[str] = set()

    def push(d: dict[str, str]) -> None:
        h = d["handle"]
        if h in seen_h:
            return
        wa = d["wa"].replace(" ", "")
        if wa.startswith("+") and wa != "Unknown":
            if wa in seen_p:
                d = dict(d)
                d["wa"] = "Unknown"
                d["notes"] = d.get("notes", "") + " | Phone deduped against earlier lead with same number."
            else:
                seen_p.add(wa)
        seen_h.add(h)
        out.append(d)

    for d in VERIFIED:
        push(dict(d))
    for d in HANDOFF:
        push(dict(d))
    for h in SCRAPED_HANDLES:
        if h in EXCLUDE:
            continue
        if h in seen_h:
            continue
        push(row_from_handle(h))
        if len(out) >= 100:
            break

    if len(out) < 100:
        raise SystemExit(f"Only collected {len(out)} unique leads; need 100")

    lines: list[str] = []
    for i, d in enumerate(out[:100], start=1):
        block = f"""==================================================
LEAD #{i}
==================================================
Business Name: {d['business']}
Instagram Handle: @{d['handle']}
Instagram URL: https://www.instagram.com/{d['handle']}/
Followers Count: Unknown
City: {d['city']}
State: {d['state']}
Business Type: {d['type']}
WhatsApp Number: {d['wa']}
Email: {d['email']}
Ordering Method: {d['order']}
Website Present: {d['web']}
Website URL: {d['url']}
Recent Activity Date: {d['recent']}
Average Engagement: {d['engage']}
Bio Text: Unknown (requires authenticated or oEmbed profile fetch)
Keywords: {d['kw']}
Reason Qualified: {d['why']}
Potential Services Needed: {d['svc']}
Google Maps Link: {d['maps']}
Lead Quality Score: {d['score']}
Notes: {d['notes']}
"""
        lines.append(block.strip() + "\n")

    Path("/workspace/india_jewellery_instagram_leads.txt").write_text("\n".join(lines), encoding="utf-8")
    print("OK", len(out[:100]))


if __name__ == "__main__":
    main()
