#!/usr/bin/env python3
"""Emit tools/leads.compact.jsonl (100 rows). Run: python3 tools/emit_leads_jsonl.py"""
from __future__ import annotations

import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from tools.extra_lead_rows import EXTRA  # noqa: E402

# Short keys: h handle, n business name, c city, s state, t type, w whatsapp, e email,
# o ordering, y website yes/no, u website url, f followers, a recent activity, g engagement,
# b bio, k keywords, r reason, p services, m gmaps, q score, x notes

ROWS: list[dict[str, str]] = [
    {"h": "wear_nd_shine_jewelry", "n": "Wear nd Shine Jewelry", "c": "Coimbatore", "s": "Tamil Nadu", "t": "Bridal & temple fashion jewellery", "w": "+917981803973", "e": "", "o": "WhatsApp + Instagram DM", "y": "No", "u": "", "f": "Not verifiable (IG login wall)", "a": "2026-01 (third-party blog reference)", "g": "Not verifiable", "b": "DM for price; DM/WhatsApp to order; ships across India (per public blog snippet)", "k": "bridal,kundan,DM,WhatsApp,south indian", "r": "Instagram-native selling with WA published on partner blog; no standalone ecommerce site in crawl", "p": "WhatsApp automation; lightweight ecommerce; CRM; Instagram ads", "m": "", "q": "8", "x": "WA +91 7981803973 cited on blog.southindiajewels.com; verify on live IG bio."},
    {"h": "chudiwale_", "n": "Chudiwale Fashion Jewellery", "c": "India", "s": "India", "t": "Custom bridal bangles / chura", "w": "+917972380643", "e": "", "o": "WhatsApp + DM", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Customised bangle sets; WhatsApp for booking (caption snippet)", "k": "bangles,chura,bridal,custom", "r": "Strong WhatsApp CTA in post copy; SMB positioning", "p": "WhatsApp automation; catalog site; CRM", "m": "", "q": "8", "x": "City inferred as India-wide shipping; refine via IG highlights."},
    {"h": "lakshmi_creations_9", "n": "Lakshmi Creations Imitation Jewellery", "c": "Chennai", "s": "Tamil Nadu", "t": "Imitation / wholesale jhumkas", "w": "+919849567353", "e": "", "o": "WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Wholesale prices; order via WhatsApp for more collections", "k": "imitation,wholesale,jhumkas", "r": "Classic IG + WhatsApp wholesale motion", "p": "B2B portal; WhatsApp catalog automation; inventory CRM", "m": "", "q": "7", "x": "Exact city from handle not explicit; Tamil-style assortment."},
    {"h": "_jewellery_palace_bjs", "n": "Jewellery Palace (BJS)", "c": "India", "s": "India", "t": "Bridal nath / pech", "w": "+918440038551", "e": "", "o": "WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Order on WhatsApp with product code", "k": "nath,bridal,WhatsApp order", "r": "Explicit WhatsApp ordering line in captions", "p": "WhatsApp flows; product codification; mini-site", "m": "", "q": "7", "x": "Geo not stated in snippet."},
    {"h": "southindian__templejewellery", "n": "South Indian Temple Jewellery", "c": "Chennai", "s": "Tamil Nadu", "t": "Temple / matt finish jewellery", "w": "+917904076978", "e": "", "o": "DM + WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "DM or WhatsApp; UPI payments; WhatsApp group link in posts", "k": "temple,south indian,WhatsApp group", "r": "Dual DM + WA; temple assortment; Chennai seller hashtag", "p": "WhatsApp Commerce API; UPI receipts automation; ecommerce", "m": "", "q": "8", "x": "Second number +919010765751 appears in some posts; keep one canonical WA per dedupe policy."},
    {"h": "jewelsofkarnataka", "n": "Jewels of Karnataka", "c": "Bangalore", "s": "Karnataka", "t": "One-gram gold plated", "w": "+919740234813", "e": "", "o": "WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "JK collection; contact on WhatsApp for orders", "k": "one gram gold,karnataka,WhatsApp", "r": "Pan-India micro seller pattern on IG", "p": "Shopify-lite; WA automation; IG checkout education", "m": "", "q": "8", "x": "City assumed Bangalore-centric brand; confirm via bio."},
    {"h": "vernika.silver.jewellery", "n": "Vernika Silver (Sri Lakshmi Venkateshwara)", "c": "Bangalore", "s": "Karnataka", "t": "92.5 silver retail", "w": "+917406810666", "e": "", "o": "Call / WhatsApp / video call", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Chickpet / Avenue Road locations; video call bookings", "k": "925 silver,chickpet,bengaluru", "r": "Physical + IG hybrid; strong call-to-action for remote orders", "p": "Local SEO; WA booking bot; reviews CRM", "m": "https://www.google.com/maps/search/?api=1&query=Vernika+Silver+Avenue+Road+Bengaluru", "q": "6", "x": "Has showroom; still IG-led discovery."},
    {"h": "mahalaxmi_gold99", "n": "Mahalaxmi Jwellers", "c": "Mysuru", "s": "Karnataka", "t": "916 hallmark casting chains", "w": "+919880820391", "e": "", "o": "DM + WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "DM for details; WhatsApp numbers listed in reel copy", "k": "916,gold chain,WhatsApp", "r": "Multi-city hashtags; SMB jeweller tone", "p": "WA automation; payments reconciliation; ecommerce", "m": "", "q": "7", "x": "Second WA 7348921999 omitted to satisfy unique phone rule."},
    {"h": "unique_jewelryys", "n": "Pooja Jewels / Unique Jewelryys", "c": "India", "s": "India", "t": "925 silver with COD", "w": "+917597344552", "e": "", "o": "WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "For order WhatsApp; COD India; 925 silver catalogue", "k": "925,COD,silver", "r": "Pure IG + WA fulfilment; no brand site surfaced in crawl", "p": "Shopify; WA commerce; CRM", "m": "", "q": "8", "x": "Do not duplicate same WA under another handle."},
    {"h": "samashajewellery", "n": "SamAsha Jewellery", "c": "Delhi", "s": "Delhi", "t": "Oxidised / German silver jhumkas", "w": "+919711107695", "e": "", "o": "DM + WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "BUY NOW; DM or WhatsApp; oxidised catalogue", "k": "oxidised,jhumka,WhatsApp", "r": "Explicit omnichannel ordering in reel", "p": "WA automation; performance ads; returns workflow", "m": "", "q": "8", "x": "City inferred from oxidised wholesale cluster; verify."},
    {"h": "prabhajewelry", "n": "Prabha Silver & Gold Jewellery", "c": "Hyderabad", "s": "Telangana", "t": "925 silver + gold polish", "w": "+917708234442", "e": "", "o": "WhatsApp enquiries", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Nakshi sets; fish-hook chains; WA for enquiries", "k": "925,nakshi,WhatsApp", "r": "Product + WA CTA without standalone storefront in crawl", "p": "Ecommerce; CRM; payments", "m": "", "q": "8", "x": "Hyderabad implied by similar seller cluster; confirm via bio."},
    {"h": "bcos_its_silver", "n": "BCOS Its Silver", "c": "Hyderabad", "s": "Telangana", "t": "925 silver + custom bridal", "w": "+919094138036", "e": "", "o": "WhatsApp (customisation line on site)", "y": "Yes", "u": "https://www.bcositssilver.com/", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Showrooms Hyderabad & Bengaluru; IG-led launches", "k": "925,showroom,WhatsApp", "r": "Still heavy IG + WA servicing; site exists (not mission-pure)", "p": "Headless commerce; WA bots; loyalty CRM", "m": "https://www.google.com/maps/search/?api=1&query=BCOS+Its+Silver+Jubilee+Hills", "q": "5", "x": "Downscore for owned ecommerce site; keep only if hybrid outreach matters."},
    {"h": "goharjewelsofficial", "n": "Gohar Jewels Official", "c": "India", "s": "India", "t": "Handmade resin / preserved flower jhumkas", "w": "", "e": "", "o": "Instagram DM (custom)", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Handmade resin jhumkas; customised dried flowers", "k": "resin,custom,DM", "r": "Niche handmade; DM-first custom orders", "p": "Ecommerce; IG automation; CRM", "m": "", "q": "7", "x": "Add WA if visible in bio after manual check."},
    {"h": "indukurisjewel", "n": "Jewel Indukuri's", "c": "Hyderabad", "s": "Telangana", "t": "Lab-grown diamond pendants", "w": "+916302720676", "e": "", "o": "WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Customise pendent; WhatsApp for details", "k": "lab grown,custom,WhatsApp", "r": "SMB custom jeweller using WA for specs", "p": "3D configurator; CRM; WhatsApp flows", "m": "", "q": "7", "x": "Fine jewellery but SMB IG motion."},
    {"h": "indranibiswas_", "n": "Indrani's Collection", "c": "Kolkata", "s": "West Bengal", "t": "Clay / black polish / resin fashion jewellery", "w": "", "e": "", "o": "Instagram DM", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Dm to buy; clay chokers; resin pendants; Kolkata small business tags", "k": "kolkata,handmade,DM", "r": "Hyper-local creator commerce; no site in crawl", "p": "Website; payments; IG shop integration", "m": "https://www.google.com/maps/search/?api=1&query=Kolkata+fashion+jewellery", "q": "8", "x": "Ideal services lead for web + checkout."},
    {"h": "d9creation_jewellery", "n": "D9creation Oxidised Jewellery", "c": "Jaipur", "s": "Rajasthan", "t": "German silver oxidised bangles", "w": "", "e": "", "o": "Website checkout + IG discovery", "y": "Yes", "u": "https://d9creation.com/", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Manufacturer vibe; Jaipur hashtags; purchase link copy", "k": "oxidised,jaipur,manufacturer", "r": "IG as top-of-funnel to owned site", "p": "Attribution; IG ads; WA retargeting", "m": "", "q": "5", "x": "Website present; still oxidised niche."},
    {"h": "lavanyajewellers_slj", "n": "Lavanya Jewellers (Gold)", "c": "Hyderabad", "s": "Telangana", "t": "Gold temple / kasulaperu custom", "w": "+919441176530", "e": "", "o": "DM + WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Customised orders; DM or WhatsApp; ships India & USA", "k": "kasulaperu,temple,bridal", "r": "High-ticket custom via DM/WA", "p": "CRM; clienteling automation; website for repeats", "m": "", "q": "7", "x": "Showroom-scale possible; still IG servicing."},
    {"h": "nikhiljewelleryhyderabad", "n": "Nikhil and Brothers Jewellery", "c": "Hyderabad", "s": "Telangana", "t": "916 gold lockets / chains", "w": "", "e": "", "o": "DM / store", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Hyderabad LB Nagar area tags; gold jewellery reels", "k": "916,gold,hyderabad", "r": "Regional gold SMB using IG catalogue", "p": "Ecommerce; appointment WA; CRM", "m": "https://www.google.com/maps/search/?api=1&query=LB+Nagar+gold+jewellery", "q": "6", "x": "Add WA from bio manually."},
    {"h": "pukhraj.jewellers1", "n": "Pukhraj Jewellers", "c": "Ahmedabad", "s": "Gujarat", "t": "Antique 22kt gold rings", "w": "+919409151772", "e": "", "o": "DM + WhatsApp + call", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "DM your order; WhatsApp/call; customisation; Satellite address in caption", "k": "antique gold,DM,WhatsApp", "r": "Strong DM + WA CTAs with geo address", "p": "Local landing pages; WA automation; CRM", "m": "https://www.google.com/maps/search/?api=1&query=Vaibhav+Tower+Satellite+Ahmedabad+jewellery", "q": "8", "x": "Investment plans mentioned; qualify carefully."},
    {"h": "varudijewellers", "n": "Varudi Jeweller", "c": "Surat", "s": "Gujarat", "t": "Gold retail / DM instant buy", "w": "", "e": "", "o": "Instagram DM", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Instant buy; DM us; safe delivery India", "k": "surat,gold,DM", "r": "DM-first jewellery shop positioning", "p": "WhatsApp commerce backup; reviews; ads", "m": "https://www.google.com/maps/search/?api=1&query=Varudi+Jeweller+Surat", "q": "7", "x": "Add phone from Google Maps cross-check."},
    {"h": "bridals_chura", "n": "Deepali Saluja Bridals Chura", "c": "Hisar", "s": "Haryana", "t": "AD / custom bridal chura", "w": "+918607355159", "e": "", "o": "DM + WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "COD available; customise colours; DM or WhatsApp", "k": "chura,bridal,custom", "r": "Classic SMB bridal accessory IG motion", "p": "WhatsApp automation; CRM; UGC", "m": "", "q": "8", "x": "Chura is jewellery-adjacent bridal accessory lead."},
    {"h": "roshi.collections", "n": "Roshi Collections", "c": "Tamil Nadu", "s": "Tamil Nadu", "t": "One-gram gold forming chains", "w": "+919092327836", "e": "", "o": "WhatsApp (online payment)", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "TN shipping; WhatsApp order; screenshot booking", "k": "one gram gold,forming,WhatsApp", "r": "IG-native price+WA flow", "p": "Checkout links; WA templates; CRM", "m": "", "q": "8", "x": "No COD per post; qualify buyers."},
    {"h": "s.swarnakarandson", "n": "S Swarnakar & Son", "c": "Kolkata", "s": "West Bengal", "t": "Gold / silver wedding jewellery", "w": "+918981948452", "e": "", "o": "Call / WhatsApp booking", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Chetla Kolkata; booking number in captions", "k": "kolkata,gold,booking", "r": "Local heritage jeweller using IG promos", "p": "Online catalogue; WA automation; CRM", "m": "https://www.google.com/maps/search/?api=1&query=Chetla+Kolkata+jewellery", "q": "6", "x": "Physical store; IG for campaigns."},
    {"h": "jewelzbyaayushi", "n": "Jewelz by Aayushi", "c": "India", "s": "India", "t": "Fashion / dream jewel store", "w": "", "e": "", "o": "Instagram DM", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Dm for order positioning in posts", "k": "fashion jewellery,DM", "r": "DM-first SMB", "p": "WhatsApp; Shopify starter; IG shopping", "m": "", "q": "7", "x": "Add WA from bio manually."},
    {"h": "silverjewelleryramala", "n": "Ramala Collections Silver", "c": "India", "s": "India", "t": "92.5 silver long harams", "w": "+919398255253", "e": "", "o": "WhatsApp / possible site link in some posts", "y": "Unknown", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "To order via WhatsApp; heavy silver sets", "k": "925,silver,haram", "r": "WA-led fulfilment", "p": "Ecommerce; CRM; payments", "m": "", "q": "7", "x": "Some posts mention website text—verify before pitching no-site stack."},
    {"h": "rajputi_jewelery_wholsaler_s.c", "n": "Rajputi Jewellery Manufacturer", "c": "Jodhpur", "s": "Rajasthan", "t": "Rajputi wholesale sets", "w": "+917877634674", "e": "", "o": "WhatsApp + groups", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Join WhatsApp group; wholesale pricing", "k": "rajputi,wholesale,WhatsApp", "r": "Manufacturer using IG for funnel", "p": "B2B portal; WA group automation", "m": "", "q": "7", "x": "Hindi-heavy captions; great WA automation candidate."},
    {"h": "rajputijewellerybhilwara00", "n": "Rajputi Jewellery Bhilwara", "c": "Bhilwara", "s": "Rajasthan", "t": "Rajputi AD sets", "w": "+919829900459", "e": "", "o": "WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Order on WhatsApp; gold-look handmade positioning", "k": "rajputi,bhilwara,WhatsApp", "r": "Different WA from other Rajputi lead", "p": "Catalogue web; CRM; ads", "m": "", "q": "7", "x": "Verify uniqueness vs other Rajputi accounts."},
    {"h": "sujatha_gold_covering_works", "n": "Sujatha Gold Covering Works", "c": "Machilipatnam", "s": "Andhra Pradesh", "t": "One-gram micro gold plated", "w": "+917382222208", "e": "", "o": "WhatsApp (multiple lines in wholesale posts)", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "COD; bulk video call; WhatsApp for bookings", "k": "one gram gold,andhra,wholesale", "r": "Wholesale IG + WA heavy operations", "p": "ERP; WA commerce; CRM", "m": "", "q": "8", "x": "Additional numbers in posts for bulk—keep single canonical line here."},
    {"h": "just_kundan", "n": "JUST_KUNDAN India", "c": "India", "s": "India", "t": "Bollywood-inspired kundan", "w": "", "e": "", "o": "WhatsApp (per caption)", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Please WhatsApp for products without price; bookings", "k": "kundan,bollywood,WhatsApp", "r": "Celebrity-inspired catalogue seller", "p": "WA catalog; ecommerce; CRM", "m": "", "q": "7", "x": "Add phone from bio manually."},
    {"h": "sudheer_kt_one_gram_gold", "n": "Sudheer KT One Gram Gold", "c": "Telangana", "s": "Telangana", "t": "One-gram gold flexible necklaces", "w": "+919646191111", "e": "", "o": "WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "WhatsApp numbers in reel for orders", "k": "one gram gold,necklace,WhatsApp", "r": "Strong WA CTA", "p": "Checkout; CRM; ads", "m": "", "q": "8", "x": "Alternate WA 8179278811 appears—verify active line."},
    {"h": "rk_pearls_and_jewellers", "n": "RK Pearls & Jewellers", "c": "Kakinada", "s": "Andhra Pradesh", "t": "German silver / one-gram / pearls", "w": "", "e": "", "o": "Instagram DM", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "DM for more details; local complex address", "k": "kakinada,pearls,DM", "r": "Local store using IG", "p": "WA; Google Business Profile; web", "m": "https://www.google.com/maps/search/?api=1&query=Mothi+Complex+Rajaji+Street+Kakinada+jewellery", "q": "6", "x": "Add phone from GBP."},
    {"h": "rudrakshjeweller", "n": "Rudraksh Jeweller Dombivli", "c": "Dombivli", "s": "Maharashtra", "t": "Fashion / gold jewellery", "w": "+917304421201", "e": "", "o": "Call / WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Store address; contact for details", "k": "dombivli,jewellery,WhatsApp", "r": "Local jeweller IG presence", "p": "GBP; WA automation; web", "m": "https://www.google.com/maps/search/?api=1&query=Rudraksh+Jeweller+Dombivli", "q": "6", "x": "Clarify inventory focus via IG highlights."},
    {"h": "silvershine_jewelery", "n": "Silver Shine Jewellery", "c": "Vadodara", "s": "Gujarat", "t": "925 silver", "w": "+917572962224", "e": "", "o": "DM + WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Order on DM/WhatsApp; hallmark silver", "k": "925,vadodara,WhatsApp", "r": "SMB silver with WA", "p": "Ecommerce; CRM", "m": "", "q": "8", "x": "Typos in caption ('gor')—still valid signal."},
    {"h": "bjs2k", "n": "Biswakarma Jewellery Shilpaya", "c": "Kolkata", "s": "West Bengal", "t": "Diamond nosepins / jewellery", "w": "+919874085669", "e": "", "o": "WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "WhatsApp for orders; diamond nosepin promos", "k": "diamond,nosepin,WhatsApp", "r": "Kolkata-area SMB using WA heavily", "p": "CRM; automation; landing pages", "m": "", "q": "7", "x": "Diamond category—still qualifies as jewellery."},
    {"h": "r.k_wedding_shop_", "n": "R.K Wedding Shop", "c": "India", "s": "India", "t": "Bridal chura / gold-plated sets", "w": "+918626949088", "e": "", "o": "DM + WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "COD; worldwide shipping; DM or WhatsApp", "k": "chura,bridal,WhatsApp", "r": "Strong SMB D2C signals", "p": "WhatsApp automation; ecommerce", "m": "", "q": "8", "x": "Name includes wedding shop beyond jewellery."},
    {"h": "rcpkjewellers", "n": "RCPK Jewellers", "c": "India", "s": "India", "t": "22kt wax-filled gold bangles", "w": "", "e": "", "o": "Instagram DM", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "DM for pricing queries", "k": "gold bangles,DM", "r": "DM-led pricing for hallmark pieces", "p": "WA; quote automation; web", "m": "", "q": "6", "x": "Geo unclear from snippet."},
    {"h": "rk.jewellers_offical", "n": "R.K Jewellers", "c": "India", "s": "India", "t": "Gold lightweight chains", "w": "", "e": "", "o": "DM / store", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Short MS reels; hallmark gold", "k": "gold,chains", "r": "SMB jeweller IG", "p": "WA; ecommerce", "m": "", "q": "5", "x": "Handle typo 'offical'; verify legitimacy."},
    {"h": "shrisilverjewellery_28", "n": "Shri Silver Jewellery", "c": "India", "s": "India", "t": "925 silver krishna earrings", "w": "", "e": "", "o": "DM", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Silver krishna earring codes in reels", "k": "925,krishna,silver", "r": "Catalog style posts", "p": "WA; Shopify", "m": "", "q": "6", "x": "Add WA from bio manually."},
    {"h": "srishsilvers", "n": "Srishsilvers", "c": "Chennai", "s": "Tamil Nadu", "t": "925 silver articles & kada", "w": "+918903838989", "e": "", "o": "DM + WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "DM for orders; WhatsApp on silver kada post", "k": "silver,kada,Chennai", "r": "Dual-channel ordering", "p": "Ecommerce; CRM", "m": "", "q": "8", "x": "Tamil Nadu focus from product context."},
    {"h": "silver_store_chennai", "n": "Silver Store Chennai", "c": "Chennai", "s": "Tamil Nadu", "t": "925 silver retail", "w": "", "e": "", "o": "DM / store visit", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Silver retail Chennai branding", "k": "silver,Chennai,retail", "r": "Local IG retail discovery", "p": "GBP; WA; ecommerce", "m": "https://www.google.com/maps/search/?api=1&query=Silver+Store+Chennai", "q": "6", "x": "Add phone from GBP/bio."},
    {"h": "silversiddhi", "n": "Siddhi Silver", "c": "Kolhapur", "s": "Maharashtra", "t": "Traditional Maharashtrian silver", "w": "+919403830260", "e": "sales@siddhisilver.in", "o": "WhatsApp + link-in-bio shop", "y": "Yes", "u": "https://siddhisilver.in/", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Buy now link in bio + WhatsApp lines", "k": "kolhapuri saaj,925,WhatsApp", "r": "Hybrid IG + ecommerce; still WA-heavy", "p": "WhatsApp Commerce integration; retention CRM", "m": "https://www.google.com/maps/search/?api=1&query=Siddhi+Silver+Kolhapur", "q": "6", "x": "Website exists—pitch integrations not greenfield site."},
    {"h": "simplysilverbyneha", "n": "Simply Silver by Neha", "c": "New Delhi", "s": "Delhi", "t": "Handcrafted 925 silver", "w": "+919810087990", "e": "contact@simplysilver.in", "o": "WhatsApp + website shop", "y": "Yes", "u": "https://simplysilver.in/", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "HQ Sainik Farm; handmade positioning", "k": "925,delhi,handmade", "r": "Premium SMB with IG + owned store", "p": "CRM; automation; subscriptions", "m": "https://www.google.com/maps/search/?api=1&query=Simply+Silver+Sainik+Farm", "q": "5", "x": "Website exists; still WA contact path."},
    {"h": "vyra_gold", "n": "Vyra Gold (Vijayakrishna)", "c": "Kollam", "s": "Kerala", "t": "22k temple nagas necklaces", "w": "+919995901152", "e": "", "o": "WhatsApp", "y": "Unknown", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "916 hallmark; WhatsApp for details; Vyra branding", "k": "temple gold,kerala,WhatsApp", "r": "Regional jeweller with IG + WA", "p": "Clienteling; web; automation", "m": "https://www.google.com/maps/search/?api=1&query=Vyra+Gold+Kollam", "q": "6", "x": "MSME-scale possible; qualify before outreach."},
    {"h": "sri_krishnagold", "n": "Sri Krishna Gold Mysore", "c": "Mysuru", "s": "Karnataka", "t": "Gold mangalya chains", "w": "+919741119406", "e": "", "o": "WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Whatsapp on chain offers; Mysore address tags", "k": "gold chain,mysuru,WhatsApp", "r": "Classic SMB IG + WA", "p": "Web; CRM; ads", "m": "https://www.google.com/maps/search/?api=1&query=Krishna+Gold+Ashoka+Road+Mysore", "q": "7", "x": "Physical store; IG promos."},
    {"h": "onegramgold", "n": "One Gram Gold Jewellery", "c": "Hyderabad", "s": "Telangana", "t": "One-gram gold plated temple chains", "w": "+919491762486", "e": "", "o": "WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Bookings WhatsApp; no COD stated", "k": "one gram gold,WhatsApp,temple", "r": "IG + WA for bookings", "p": "Checkout; CRM; COD policy UX", "m": "", "q": "8", "x": "Clarify payment rules before prospecting."},
    {"h": "ashabanglesofficial", "n": "Asha Bangles Official", "c": "Patiala", "s": "Punjab", "t": "Punjabi bridal chura", "w": "+917014592741", "e": "", "o": "WhatsApp", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "22 years designing; partial COD; customisation", "k": "punjabi chura,WhatsApp,bridal", "r": "Strong WhatsApp ordering CTA", "p": "WA automation; CRM; UGC", "m": "", "q": "8", "x": "Also referenced as Asha Bangles network."},
    {"h": "jodhpuri_silver", "n": "Jodhpuri Silver (Khushbu network posts)", "c": "Jodhpur", "s": "Rajasthan", "t": "925 silver payals / bridal silver", "w": "+918233445357", "e": "", "o": "WhatsApp screenshot orders", "y": "Unknown", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "COD; WhatsApp screenshot ordering; silver payal promos", "k": "silver,payal,jodhpur", "r": "High-intent WhatsApp commerce posts", "p": "Headless checkout; fraud checks; CRM", "m": "", "q": "7", "x": "Posts also reference website discounts—verify site presence before no-site pitch."},
    {"h": "khushbujewellers.com_", "n": "Khushbu Jewellers (Shopify-style handle)", "c": "Jodhpur", "s": "Rajasthan", "t": "Silver hathphool / lightweight silver", "w": "+919875791031", "e": "", "o": "WhatsApp screenshot + website order mentions", "y": "Yes", "u": "https://khushbujewellers.com/", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Heavy discount + COD + website upsell mentions", "k": "silver,COD,website", "r": "Large D2C motion; still IG acquisition", "p": "Attribution; CRM; retention", "m": "", "q": "4", "x": "Enterprise-adjacent; use for integration upsell not 'no website'."},
    {"h": "jewelsbynitin", "n": "Jewels By Nitin", "c": "India", "s": "India", "t": "Punjabi groom kantha jewellery", "w": "", "e": "", "o": "Instagram DM", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Traditional Punjabi groom jewellery posts", "k": "punjabi,groom,jewellery", "r": "Niche cultural jewellery IG", "p": "Web; WA; international shipping stack", "m": "", "q": "6", "x": "Add WA from bio manually."},
    {"h": "gahanejewellery", "n": "Gahane Jewellery", "c": "Kolkata", "s": "West Bengal", "t": "916 hallmark kon-kon bangles", "w": "", "e": "", "o": "DM / store", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Handcrafted gold bangles; Bengali bride tags", "k": "gold bangles,bengali,bridal", "r": "Heritage craft positioning", "p": "Ecommerce; appointment booking", "m": "", "q": "6", "x": "Add contact from bio."},
    {"h": "pooja._.jamnagar", "n": "The Jhumka Store (Pooja Jamnagar)", "c": "Jamnagar", "s": "Gujarat", "t": "Diamond / jhumka focus", "w": "", "e": "", "o": "DM / home delivery text", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Home delivery available messaging", "k": "jhumka,jamnagar", "r": "Local IG retail", "p": "WA; GBP; web", "m": "https://www.google.com/maps/search/?api=1&query=Jamnagar+jhumka+store", "q": "6", "x": "Confirm business phone via DM autoresponder."},
    {"h": "maharashtrian_jewelry", "n": "Maharashtrian Jewellery", "c": "Pune", "s": "Maharashtra", "t": "Traditional Maharashtrian sets", "w": "", "e": "", "o": "Instagram DM", "y": "No", "u": "", "f": "Not verifiable", "a": "Not verifiable", "g": "Not verifiable", "b": "Chinchpeti; nath; tanmani; free shipping lines", "k": "marathi,bridal,traditional", "r": "Catalog seller with price-in-caption pattern", "p": "WhatsApp; ecommerce; inventory", "m": "", "q": "7", "x": "Add phone from pinned post if any."},
]


def _merged_rows() -> list[dict[str, str]]:
    """Base ROWS + EXTRA, deduped by handle then unique non-empty WhatsApp."""
    base = [r for r in ROWS if (r.get("h") or "").strip() and (r.get("n") or "").strip()]
    merged = base + list(EXTRA)
    seen_h: set[str] = set()
    seen_w: set[str] = set()
    out: list[dict[str, str]] = []
    for r in merged:
        h = (r.get("h") or "").strip().lower()
        if not h or h in seen_h:
            continue
        w = (r.get("w") or "").strip()
        if w and w in seen_w:
            continue
        if w:
            seen_w.add(w)
        seen_h.add(h)
        out.append(r)
    return out


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    out = root / "tools" / "leads.compact.jsonl"
    clean = _merged_rows()
    if len(clean) != 100:
        raise SystemExit(f"Expected 100 rows after merge/dedupe, got {len(clean)}")
    out.write_text("\n".join(json.dumps(r, ensure_ascii=False) for r in clean) + "\n", encoding="utf-8")
    print("wrote", out)


if __name__ == "__main__":
    main()
